/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 03 (Modules 51–75)
 *  "Social Life & Unforeseen Events" — 5 sub-blocks:
 *    3.1 Making Friends      (51–55)  pubs, banter, invitations
 *    3.2 Medical Emergency   (56–60)  999, A&E, describing pain
 *    3.3 Transport Errors    (61–65)  wrong train, strikes, penalty fare
 *    3.4 Bank Fraud Scare    (66–70)  frozen card, scam calls, disputes
 *    3.5 Conflict & Belonging(71–75)  complaints, apologies, BONUS
 *  Module 75 = "London Local" milestone selfie.
 * ============================================================ */

export const BLOCK03_MODULES = [
  /* 3.1 — MAKING FRIENDS */
  { sequence: 51, blockId: 3, indexInBlock: 1, phase: 3, subBlock: "3.1", threshold: 80,
    sceneTitle: { en: "Fancy a Pint?", "pt-BR": "Bora uma Pint?" },
    contextDescription: { en: "A noisy pub after work. A colleague leans over the din: “Fancy a pint?” Saying no the wrong way ends the friendship before it starts.", "pt-BR": "Um pub barulhento depois do trabalho. Um colega grita por cima do barulho: “Fancy a pint?” Recusar do jeito errado encerra a amizade antes de começar." },
    objective: { en: "Accept a social invitation naturally.", "pt-BR": "Aceitar um convite social com naturalidade." },
    culturalNote: { en: "‘Fancy a…?’ = do you want…? Saying yes to the pub is how friendships form here.", "pt-BR": "‘Fancy a…?’ = você quer…? Aceitar o pub é como nascem as amizades aqui." },
    environment: { mood: "pleased", baseNoise: 54 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "CO" },
    drills: [{ word: "go on then", say: "GÔU ón dén", note: { en: "= sure, why not.", "pt-BR": "= claro, por que não." } }],
    dialogueSteps: [ { text: "Fancy a pint? We're all heading to the pub.", tr: { en: "Want a beer? We're going to the pub.", "pt-BR": "Quer uma cerveja? Vamos ao pub." }, ear: { en: "<b>“FÉN-si a páint”</b>", "pt-BR": "<b>“FÉN-si a páint”</b>" }, audioPrompt: "Colleague, shouting over pub noise: “Fancy a pint? We're all heading to the pub.”", basic: "Yeah, go on then.", fluent: "Go on then — I'd love one." } ] },
  { sequence: 52, blockId: 3, indexInBlock: 2, phase: 3, subBlock: "3.1", threshold: 80,
    sceneTitle: { en: "So, What Do You Do?", "pt-BR": "E Aí, Trabalha com Quê?" },
    contextDescription: { en: "Pint in hand, the classic opener lands: “So, what do you do?” In Britain, your answer sets your whole social footing.", "pt-BR": "Pint na mão, chega a pergunta clássica: “So, what do you do?” Na Grã-Bretanha, sua resposta define toda a sua posição social." },
    objective: { en: "Introduce your job and return the question.", "pt-BR": "Apresentar seu trabalho e devolver a pergunta." },
    environment: { mood: "pleased", baseNoise: 52 },
    npc: { name: { en: "New Acquaintance", "pt-BR": "Conhecido(a)" }, initials: "NA" },
    drills: [{ word: "what about you?", say: "uât a-BÁUT iú", note: { en: "Return the question.", "pt-BR": "Devolva a pergunta." } }],
    dialogueSteps: [ { text: "So, what do you do?", tr: { en: "What's your job?", "pt-BR": "Qual é o seu trabalho?" }, ear: { en: "<b>“uât du iú dú”</b>", "pt-BR": "<b>“uât du iú dú”</b>" }, audioPrompt: "Acquaintance, friendly: “So, what do you do?”", basic: "I'm a designer. You?", fluent: "I'm a designer — what about you?" } ] },
  { sequence: 53, blockId: 3, indexInBlock: 3, phase: 3, subBlock: "3.1", threshold: 80,
    sceneTitle: { en: "Reading the Banter", "pt-BR": "Entendendo a Zoeira" },
    contextDescription: { en: "Someone insults you with a grin — and everyone laughs. It's ‘banter’: friendly mockery. Take it well or you're an outsider.", "pt-BR": "Alguém te insulta sorrindo — e todos riem. É ‘banter’: zoeira amigável. Leve numa boa ou você é de fora." },
    objective: { en: "Respond to friendly teasing without offence.", "pt-BR": "Responder à zoeira amigável sem se ofender." },
    culturalNote: { en: "Banter = affectionate insults. Smiling and firing back = you belong.", "pt-BR": "Banter = insultos afetuosos. Sorrir e revidar = você pertence." },
    environment: { mood: "pleased", baseNoise: 55 },
    npc: { name: { en: "New Mate", "pt-BR": "Novo Amigo" }, initials: "NM" },
    drills: [{ word: "cheeky", say: "TCHÍ-ki", note: { en: "= playfully rude.", "pt-BR": "= atrevido, de brincadeira." } }],
    dialogueSteps: [ { text: "You're not from round here, are ya? Bless.", tr: { en: "Teasing you for being foreign — play along.", "pt-BR": "Te zoando por ser estrangeiro — entre na brincadeira." }, ear: { en: "<b>“round ria, a-ia”</b>", "pt-BR": "<b>“round ria, a-ia”</b>" }, audioPrompt: "New mate, grinning, teasing: “You're not from round here, are ya? Bless.”", basic: "Cheeky! No, I'm not.", fluent: "Cheeky! No — but I'm learning fast." } ] },
  { sequence: 54, blockId: 3, indexInBlock: 4, phase: 3, subBlock: "3.1", threshold: 80,
    sceneTitle: { en: "Your Round", "pt-BR": "Sua Rodada" },
    contextDescription: { en: "“It's your round, mate.” The sacred pub law: everyone buys a round in turn. Skip yours and you're marked forever.", "pt-BR": "“It's your round, mate.” A lei sagrada do pub: cada um paga uma rodada na sua vez. Pule a sua e você é marcado para sempre." },
    objective: { en: "Offer to buy a round and take the order.", "pt-BR": "Oferecer-se para pagar uma rodada e anotar o pedido." },
    culturalNote: { en: "‘Rounds’ are a social contract. Always buy yours — it's about fairness, not money.", "pt-BR": "As ‘rodadas’ são um contrato social. Sempre pague a sua — é sobre justiça, não dinheiro." },
    environment: { mood: "pleased", baseNoise: 56 },
    npc: { name: { en: "New Mate", "pt-BR": "Novo Amigo" }, initials: "NM" },
    drills: [{ word: "same again?", say: "SÊIM a-GÉN", note: { en: "= the same drinks?", "pt-BR": "= as mesmas bebidas?" } }],
    dialogueSteps: [ { text: "It's your round, mate.", tr: { en: "It's your turn to buy drinks.", "pt-BR": "É sua vez de pagar as bebidas." }, ear: { en: "<b>“iór ráund”</b>", "pt-BR": "<b>“iór ráund”</b>" }, audioPrompt: "Mate, nudging you: “It's your round, mate.”", basic: "Right! Same again?", fluent: "Right, my round — same again, everyone?" } ] },
  { sequence: 55, blockId: 3, indexInBlock: 5, phase: 3, subBlock: "3.1", threshold: 80,
    sceneTitle: { en: "Swapping Numbers", "pt-BR": "Trocando Números" },
    contextDescription: { en: "Night winding down, a real connection made. “We should do this again — give us your number.” Seal the new friendship.", "pt-BR": "A noite acabando, uma conexão de verdade. “We should do this again — give us your number.” Sele a nova amizade." },
    objective: { en: "Exchange contact details warmly.", "pt-BR": "Trocar contatos de forma calorosa." },
    environment: { mood: "pleased", baseNoise: 48 },
    npc: { name: { en: "New Mate", "pt-BR": "Novo Amigo" }, initials: "NM" },
    drills: [{ word: "give us your number", say: "guív âs iór NÂM-bâr", note: { en: "'us' = me (London slang).", "pt-BR": "'us' = eu (gíria de Londres)." } }],
    dialogueSteps: [ { text: "We should do this again. Give us your number?", tr: { en: "Let's meet again — your number?", "pt-BR": "Vamos repetir — seu número?" }, ear: { en: "<b>“guív âs”</b> = give me", "pt-BR": "<b>“guív âs”</b> = me dá" }, audioPrompt: "Mate, sincere: “We should do this again. Give us your number?”", basic: "Yeah, definitely!", fluent: "Definitely — here, I'll text you." } ] },

  /* 3.2 — MEDICAL EMERGENCY */
  { sequence: 56, blockId: 3, indexInBlock: 6, phase: 3, subBlock: "3.2", threshold: 80,
    sceneTitle: { en: "Someone Collapses", "pt-BR": "Alguém Desmaia" },
    contextDescription: { en: "On the street, a man crumples to the pavement. People freeze. You're nearest. You must call 999 and speak clearly under adrenaline.", "pt-BR": "Na rua, um homem desaba na calçada. As pessoas congelam. Você está mais perto. Precisa ligar 999 e falar claro sob adrenalina." },
    objective: { en: "Call 999 and request the right service.", "pt-BR": "Ligar 999 e pedir o serviço certo." },
    culturalNote: { en: "UK emergency = 999 (or 112). The operator asks: “which service?”", "pt-BR": "Emergência no Reino Unido = 999 (ou 112). O operador pergunta: “which service?”" },
    environment: { mood: "hostile", baseNoise: 50 },
    npc: { name: { en: "999 Operator", "pt-BR": "Operador 999" }, initials: "99" },
    drills: [{ word: "ambulance, now!", say: "ÉM-biu-lâns, náu", note: { en: "Name the service fast.", "pt-BR": "Diga o serviço rápido." } }],
    dialogueSteps: [ { text: "Emergency, which service?", tr: { en: "Which service do you need?", "pt-BR": "De qual serviço você precisa?" }, ear: { en: "<b>“UÍTCH SÂR-vis”</b>", "pt-BR": "<b>“UÍTCH SÂR-vis”</b>" }, audioPrompt: "Operator, calm and fast: “Emergency, which service?”", basic: "Ambulance, now!", fluent: "Ambulance — a man's collapsed!" } ] },
  { sequence: 57, blockId: 3, indexInBlock: 7, phase: 3, subBlock: "3.2", threshold: 80,
    sceneTitle: { en: "Where Are You?", "pt-BR": "Onde Você Está?" },
    contextDescription: { en: "“Stay calm. What's your location?” You barely know — you must read a street sign and a landmark, fast, while your hands shake.", "pt-BR": "“Stay calm. What's your location?” Você mal sabe — precisa ler uma placa e um ponto de referência, rápido, com as mãos tremendo." },
    objective: { en: "Give your location under pressure.", "pt-BR": "Informar sua localização sob pressão." },
    environment: { mood: "hostile", baseNoise: 48 },
    npc: { name: { en: "999 Operator", "pt-BR": "Operador 999" }, initials: "99" },
    drills: [{ word: "I'm on…", say: "aim ón", note: { en: "State the street.", "pt-BR": "Diga a rua." } }],
    dialogueSteps: [ { text: "Stay calm. What's your exact location?", tr: { en: "Where exactly are you?", "pt-BR": "Onde exatamente você está?" }, ear: { en: "<b>“lô-KÊI-shân”</b>", "pt-BR": "<b>“lô-KÊI-shân”</b>" }, audioPrompt: "Operator: “Stay calm. What's your exact location?”", basic: "I'm on Brick Lane.", fluent: "I'm on Brick Lane, near the station." } ] },
  { sequence: 58, blockId: 3, indexInBlock: 8, phase: 3, subBlock: "3.2", threshold: 80,
    sceneTitle: { en: "Describe the Patient", "pt-BR": "Descreva o Paciente" },
    contextDescription: { en: "“Is he breathing? Conscious?” Medical triage by phone. Wrong words cost minutes that cost lives.", "pt-BR": "“Is he breathing? Conscious?” Triagem médica por telefone. Palavras erradas custam minutos que custam vidas." },
    objective: { en: "Report breathing/consciousness clearly.", "pt-BR": "Relatar respiração/consciência com clareza." },
    environment: { mood: "hostile", baseNoise: 46 },
    npc: { name: { en: "999 Operator", "pt-BR": "Operador 999" }, initials: "99" },
    drills: [{ word: "he's breathing", say: "ríz BRÍ-thin", note: { en: "Key status word.", "pt-BR": "Palavra-chave de estado." } }],
    dialogueSteps: [ { text: "Is he breathing? Is he conscious?", tr: { en: "Breathing? Awake?", "pt-BR": "Respirando? Consciente?" }, ear: { en: "<b>“KÓN-shâs”</b>", "pt-BR": "<b>“KÓN-shâs”</b>" }, audioPrompt: "Operator, urgent: “Is he breathing? Is he conscious?”", basic: "He's breathing, not awake.", fluent: "He's breathing but he's not conscious." } ] },
  { sequence: 59, blockId: 3, indexInBlock: 9, phase: 2, subBlock: "3.2", threshold: 80,
    sceneTitle: { en: "At A&E", "pt-BR": "No Pronto-Socorro" },
    contextDescription: { en: "Accident & Emergency: harsh lights, a queue of the unwell, a triage nurse with no time. You explain why you came in with him.", "pt-BR": "Pronto-socorro (A&E): luzes duras, uma fila de doentes, uma enfermeira de triagem sem tempo. Você explica por que veio com ele." },
    objective: { en: "Explain the situation to triage.", "pt-BR": "Explicar a situação na triagem." },
    culturalNote: { en: "‘A&E’ = ER. ‘Casualty’ is the old name. Expect a long wait if not critical.", "pt-BR": "‘A&E’ = pronto-socorro. ‘Casualty’ é o nome antigo. Espere fila longa se não for grave." },
    environment: { mood: "neutral", baseNoise: 40 },
    npc: { name: { en: "Triage Nurse", "pt-BR": "Enfermeira de Triagem" }, initials: "TN" },
    drills: [{ word: "he collapsed", say: "ri co-LÉPST", note: { en: "= ele desmaiou.", "pt-BR": "= ele desmaiou." } }],
    dialogueSteps: [ { text: "What happened, and when?", tr: { en: "Explain what happened.", "pt-BR": "Explique o que aconteceu." }, ear: { en: "<b>“uât RÉ-pând”</b>", "pt-BR": "<b>“uât RÉ-pând”</b>" }, audioPrompt: "Nurse, brisk: “What happened, and when?”", basic: "He collapsed outside.", fluent: "He collapsed in the street about ten minutes ago." } ] },
  { sequence: 60, blockId: 3, indexInBlock: 10, phase: 2, subBlock: "3.2", threshold: 80,
    sceneTitle: { en: "An Allergic Reaction", "pt-BR": "Uma Reação Alérgica" },
    contextDescription: { en: "Now it's you: your throat tightens after a sandwich — a nut allergy. You must warn staff before you can't speak at all.", "pt-BR": "Agora é você: sua garganta fecha depois de um sanduíche — alergia a nozes. Precisa avisar antes de não conseguir mais falar." },
    objective: { en: "Declare an allergy as an emergency.", "pt-BR": "Declarar uma alergia como emergência." },
    environment: { mood: "hostile", baseNoise: 44 },
    npc: { name: { en: "Nurse", "pt-BR": "Enfermeira(o)" }, initials: "NU" },
    drills: [{ word: "I'm allergic to nuts", say: "aim a-LÂR-djik tu NÂTS", note: { en: "Life-saving sentence.", "pt-BR": "Frase que salva vidas." } }],
    dialogueSteps: [ { text: "What's wrong? Talk to me.", tr: { en: "Tell me what's happening.", "pt-BR": "Me diga o que está acontecendo." }, ear: { en: "<b>“a-LÂR-djik”</b>", "pt-BR": "<b>“a-LÂR-djik”</b>" }, audioPrompt: "Nurse, alarmed: “What's wrong? Talk to me.”", basic: "I'm allergic to nuts!", fluent: "I'm allergic to nuts — my throat's closing." } ] },

  /* 3.3 — TRANSPORT ERRORS */
  { sequence: 61, blockId: 3, indexInBlock: 11, phase: 3, subBlock: "3.3", threshold: 80,
    sceneTitle: { en: "Wrong Train", "pt-BR": "Trem Errado" },
    contextDescription: { en: "Three stops in, the announcements don't match your plan. Heart sinking, you ask a fellow passenger if you've boarded the wrong train.", "pt-BR": "Três paradas e os avisos não batem com seu plano. Com o coração na mão, você pergunta a um passageiro se pegou o trem errado." },
    objective: { en: "Confirm a mistake and find the fix.", "pt-BR": "Confirmar um erro e achar a solução." },
    environment: { mood: "neutral", baseNoise: 62 },
    npc: { name: { en: "Passenger", "pt-BR": "Passageiro(a)" }, initials: "PA" },
    drills: [{ word: "is this going to…?", say: "iz dis GÔU-in tu", note: { en: "Confirm the destination.", "pt-BR": "Confirme o destino." } }],
    dialogueSteps: [ { text: "This one? Nah, you want the eastbound. Get off next stop.", tr: { en: "Wrong way — get off at the next stop.", "pt-BR": "Sentido errado — desça na próxima." }, ear: { en: "<b>“ÍST-baund”</b>", "pt-BR": "<b>“ÍST-baund”</b>" }, audioPrompt: "Passenger, over train noise: “This one? Nah, you want the eastbound. Get off next stop.”", basic: "Next stop, thanks.", fluent: "Right — I'll get off next stop, cheers." } ] },
  { sequence: 62, blockId: 3, indexInBlock: 12, phase: 2, subBlock: "3.3", threshold: 80,
    sceneTitle: { en: "Rail Replacement Bus", "pt-BR": "Ônibus no Lugar do Trem" },
    contextDescription: { en: "“This line's closed — rail replacement bus service.” The Briton's nightmare. Staff herd confused crowds toward a car park.", "pt-BR": "“This line's closed — rail replacement bus service.” O pesadelo britânico. Funcionários conduzem multidões confusas até um estacionamento." },
    objective: { en: "Understand a closure and find the replacement.", "pt-BR": "Entender o fechamento e achar o substituto." },
    culturalNote: { en: "Weekend ‘engineering works’ + replacement buses are a rite of passage.", "pt-BR": "‘Obras’ de fim de semana + ônibus substituto são um rito de passagem." },
    environment: { mood: "hostile", baseNoise: 58 },
    npc: { name: { en: "Station Staff", "pt-BR": "Funcionário(a)" }, initials: "ST" },
    drills: [{ word: "replacement bus", say: "ri-PLÊIS-mânt bâs", note: { en: "= ônibus substituto.", "pt-BR": "= ônibus substituto." } }],
    dialogueSteps: [ { text: "Line's closed, love. Replacement bus out front.", tr: { en: "Take the replacement bus outside.", "pt-BR": "Pegue o ônibus substituto lá fora." }, ear: { en: "<b>“ri-PLÊIS-mânt”</b>", "pt-BR": "<b>“ri-PLÊIS-mânt”</b>" }, audioPrompt: "Staff, weary: “Line's closed, love. Replacement bus out front.”", basic: "Where's the bus?", fluent: "Out front — got it, thanks." } ] },
  { sequence: 63, blockId: 3, indexInBlock: 13, phase: 3, subBlock: "3.3", threshold: 80,
    sceneTitle: { en: "The Strike", "pt-BR": "A Greve" },
    contextDescription: { en: "Gates shut, boards blank: a Tube strike. A stranded crowd grumbles. You ask how else to get across the city.", "pt-BR": "Catracas fechadas, painéis vazios: greve no metrô. Uma multidão presa resmunga. Você pergunta como atravessar a cidade de outro jeito." },
    objective: { en: "Find an alternative during a strike.", "pt-BR": "Achar uma alternativa durante a greve." },
    environment: { mood: "hostile", baseNoise: 60 },
    npc: { name: { en: "Commuter", "pt-BR": "Passageiro(a)" }, initials: "PC" },
    drills: [{ word: "on strike", say: "ón STRÁIK", note: { en: "= em greve.", "pt-BR": "= em greve." } }],
    dialogueSteps: [ { text: "Tube's on strike, mate. Bus or walk, innit.", tr: { en: "No Tube — take a bus or walk.", "pt-BR": "Sem metrô — ônibus ou a pé." }, ear: { en: "<b>“i-NÍT”</b> = isn't it", "pt-BR": "<b>“i-NÍT”</b> = né" }, audioPrompt: "Commuter, resigned: “Tube's on strike, mate. Bus or walk, innit.”", basic: "Which bus?", fluent: "Right — which bus should I take?" } ] },
  { sequence: 64, blockId: 3, indexInBlock: 14, phase: 3, subBlock: "3.3", threshold: 80,
    sceneTitle: { en: "Penalty Fare", "pt-BR": "Multa de Bilhete" },
    contextDescription: { en: "A ticket inspector blocks the carriage: “Tickets, please.” Your card didn't tap in properly. Now you face a penalty fare — argue calmly.", "pt-BR": "Um fiscal bloqueia o vagão: “Tickets, please.” Seu cartão não registrou direito. Agora você enfrenta uma multa — argumente com calma." },
    objective: { en: "Explain a tap failure to avoid/handle a fine.", "pt-BR": "Explicar a falha do cartão para evitar/lidar com a multa." },
    culturalNote: { en: "‘Penalty fare’ can be £80+. Stay polite; explain the gate was open/broken.", "pt-BR": "A ‘penalty fare’ pode passar de £80. Seja educado; explique que a catraca estava aberta/quebrada." },
    environment: { mood: "hostile", baseNoise: 52 },
    npc: { name: { en: "Ticket Inspector", "pt-BR": "Fiscal" }, initials: "TI" },
    drills: [{ word: "it didn't tap", say: "it DÍ-dânt tép", note: { en: "Explain the failure.", "pt-BR": "Explique a falha." } }],
    dialogueSteps: [ { text: "No valid ticket? That's a penalty fare.", tr: { en: "No ticket = a fine.", "pt-BR": "Sem bilhete = multa." }, ear: { en: "<b>“PÉ-nâl-ti fér”</b>", "pt-BR": "<b>“PÉ-nâl-ti fér”</b>" }, audioPrompt: "Inspector, stern: “No valid ticket? That's a penalty fare.”", basic: "It didn't tap. Sorry.", fluent: "I tapped, but the reader failed — honestly." } ] },
  { sequence: 65, blockId: 3, indexInBlock: 15, phase: 3, subBlock: "3.3", threshold: 80,
    sceneTitle: { en: "Missed the Last Train", "pt-BR": "Perdi o Último Trem" },
    contextDescription: { en: "Midnight. The shutters come down: you've missed the last train. A lone night-bus driver is your only way home.", "pt-BR": "Meia-noite. As grades descem: você perdeu o último trem. Um motorista de ônibus noturno é sua única forma de chegar em casa." },
    objective: { en: "Find a night bus home.", "pt-BR": "Achar um ônibus noturno para casa." },
    environment: { mood: "neutral", baseNoise: 46 },
    npc: { name: { en: "Night Bus Driver", "pt-BR": "Motorista Noturno" }, initials: "NB" },
    drills: [{ word: "does the N25 stop here?", say: "dâz dâ én-TUÉN-ti-fáiv stóp ria", note: { en: "Night buses start with N.", "pt-BR": "Ônibus noturnos começam com N." } }],
    dialogueSteps: [ { text: "Last train's gone. Night bus? Yeah, this is the N25.", tr: { en: "Take the night bus N25.", "pt-BR": "Pegue o ônibus noturno N25." }, ear: { en: "<b>“nait bâs”</b>", "pt-BR": "<b>“nait bâs”</b>" }, audioPrompt: "Driver, tired: “Last train's gone. Night bus? Yeah, this is the N25.”", basic: "Great, thank you.", fluent: "Perfect — the N25, thank you." } ] },

  /* 3.4 — BANK FRAUD SCARE */
  { sequence: 66, blockId: 3, indexInBlock: 16, phase: 3, subBlock: "3.4", threshold: 80,
    sceneTitle: { en: "Card Frozen", "pt-BR": "Cartão Bloqueado" },
    contextDescription: { en: "Your card's declined again — but you have money. A text says it's ‘frozen for suspicious activity’. You ring the bank, tense.", "pt-BR": "Seu cartão é recusado de novo — mas você tem dinheiro. Um SMS diz que foi ‘bloqueado por atividade suspeita’. Você liga para o banco, tenso." },
    objective: { en: "Report a frozen card to the bank.", "pt-BR": "Relatar um cartão bloqueado ao banco." },
    environment: { mood: "hostile", baseNoise: 38 },
    npc: { name: { en: "Bank Line", "pt-BR": "Central do Banco" }, initials: "BL" },
    drills: [{ word: "my card's frozen", say: "mai kards FRÔU-zân", note: { en: "= bloqueado.", "pt-BR": "= bloqueado." } }],
    dialogueSteps: [ { text: "Thanks for calling. How can I help?", tr: { en: "How can I help you?", "pt-BR": "Como posso ajudar?" }, ear: { en: "<b>“FRÔU-zân”</b>", "pt-BR": "<b>“FRÔU-zân”</b>" }, audioPrompt: "Bank agent, scripted: “Thanks for calling. How can I help?”", basic: "My card's frozen.", fluent: "My card's been frozen — I need it unblocked." } ] },
  { sequence: 67, blockId: 3, indexInBlock: 17, phase: 3, subBlock: "3.4", threshold: 80,
    sceneTitle: { en: "Security Questions", "pt-BR": "Perguntas de Segurança" },
    contextDescription: { en: "“I'll need to verify your identity.” A barrage of questions — date of birth, address, last transaction. Get one wrong and you're locked out.", "pt-BR": "“I'll need to verify your identity.” Uma saraivada de perguntas — data de nascimento, endereço, última transação. Erre uma e você fica de fora." },
    objective: { en: "Pass identity verification.", "pt-BR": "Passar na verificação de identidade." },
    environment: { mood: "neutral", baseNoise: 34 },
    npc: { name: { en: "Bank Line", "pt-BR": "Central do Banco" }, initials: "BL" },
    drills: [{ word: "date of birth", say: "dêit âv BÂRTH", note: { en: "Common verification.", "pt-BR": "Verificação comum." } }],
    dialogueSteps: [ { text: "Can you confirm your date of birth?", tr: { en: "What's your date of birth?", "pt-BR": "Qual sua data de nascimento?" }, ear: { en: "<b>“dêit âv bârth”</b>", "pt-BR": "<b>“dêit âv bârth”</b>" }, audioPrompt: "Agent: “Can you confirm your date of birth?”", basic: "The third of May.", fluent: "Yes — the third of May, nineteen ninety-five." } ] },
  { sequence: 68, blockId: 3, indexInBlock: 18, phase: 3, subBlock: "3.4", threshold: 80,
    sceneTitle: { en: "Is This a Scam?", "pt-BR": "Isso é Golpe?" },
    contextDescription: { en: "Later, a call: “This is your bank — confirm your PIN.” Real banks NEVER ask that. A scammer is testing you. Refuse and hang up.", "pt-BR": "Mais tarde, uma ligação: “This is your bank — confirm your PIN.” Bancos reais NUNCA pedem isso. Um golpista está te testando. Recuse e desligue." },
    objective: { en: "Recognise and refuse a phishing call.", "pt-BR": "Reconhecer e recusar uma ligação de golpe." },
    culturalNote: { en: "No real bank asks for your full PIN or password. ‘I'll call the bank myself.’", "pt-BR": "Nenhum banco real pede seu PIN ou senha completos. ‘Eu mesmo ligo para o banco.’" },
    environment: { mood: "hostile", baseNoise: 36 },
    npc: { name: { en: "Caller (Scam)", "pt-BR": "Golpista" }, initials: "??" },
    drills: [{ word: "I won't give you that", say: "ai uôunt guív iú dét", note: { en: "Refuse firmly.", "pt-BR": "Recuse com firmeza." } }],
    dialogueSteps: [ { text: "This is your bank. Confirm your full PIN to secure your account.", tr: { en: "A scammer wants your PIN — refuse!", "pt-BR": "Um golpista quer seu PIN — recuse!" }, ear: { en: "<b>“pín”</b> = senha", "pt-BR": "<b>“pín”</b> = senha" }, audioPrompt: "Caller, smooth and urgent (a scam): “This is your bank. Confirm your full PIN to secure your account.”", basic: "No. I won't give you that.", fluent: "No — banks never ask that. I'm hanging up." } ] },
  { sequence: 69, blockId: 3, indexInBlock: 19, phase: 3, subBlock: "3.4", threshold: 80,
    sceneTitle: { en: "Disputing a Charge", "pt-BR": "Contestando uma Cobrança" },
    contextDescription: { en: "A charge you didn't make appears. You call the real bank to dispute it and request a chargeback. Be precise.", "pt-BR": "Aparece uma cobrança que você não fez. Você liga para o banco de verdade para contestar e pedir o estorno. Seja preciso." },
    objective: { en: "Dispute an unauthorised transaction.", "pt-BR": "Contestar uma transação não autorizada." },
    environment: { mood: "neutral", baseNoise: 34 },
    npc: { name: { en: "Fraud Team", "pt-BR": "Setor Antifraude" }, initials: "FT" },
    drills: [{ word: "I didn't make this", say: "ai DÍ-dânt mêik dis", note: { en: "Deny the charge.", "pt-BR": "Negue a cobrança." } }],
    dialogueSteps: [ { text: "Which transaction are you disputing?", tr: { en: "Which charge is wrong?", "pt-BR": "Qual cobrança está errada?" }, ear: { en: "<b>“dis-PIÚ-tin”</b>", "pt-BR": "<b>“dis-PIÚ-tin”</b>" }, audioPrompt: "Fraud team: “Which transaction are you disputing?”", basic: "I didn't make this one.", fluent: "The £200 one — I didn't make it." } ] },
  { sequence: 70, blockId: 3, indexInBlock: 20, phase: 3, subBlock: "3.4", threshold: 80,
    sceneTitle: { en: "New Card Coming", "pt-BR": "Cartão Novo a Caminho" },
    contextDescription: { en: "Resolved. “We'll cancel the old card and post a new one in 3–5 working days.” Confirm your address and breathe.", "pt-BR": "Resolvido. “We'll cancel the old card and post a new one in 3–5 working days.” Confirme o endereço e respire." },
    objective: { en: "Confirm address for a replacement card.", "pt-BR": "Confirmar o endereço para o cartão novo." },
    environment: { mood: "pleased", baseNoise: 32 },
    npc: { name: { en: "Fraud Team", "pt-BR": "Setor Antifraude" }, initials: "FT" },
    drills: [{ word: "working days", say: "UÂR-kin dêis", note: { en: "= dias úteis.", "pt-BR": "= dias úteis." } }],
    dialogueSteps: [ { text: "New card in 3–5 working days. Same address?", tr: { en: "New card in 3–5 business days — same address?", "pt-BR": "Cartão novo em 3–5 dias úteis — mesmo endereço?" }, ear: { en: "<b>“UÂR-kin dêis”</b>", "pt-BR": "<b>“UÂR-kin dêis”</b>" }, audioPrompt: "Agent, reassuring: “New card in 3–5 working days. Same address?”", basic: "Yes, same address.", fluent: "Yes, same address — thank you." } ] },

  /* 3.5 — CONFLICT & BELONGING */
  { sequence: 71, blockId: 3, indexInBlock: 21, phase: 3, subBlock: "3.5", threshold: 80,
    sceneTitle: { en: "Noise Complaint", "pt-BR": "Reclamação de Barulho" },
    contextDescription: { en: "A knock at 11pm. Your flatmate, frosty and passive-aggressive: “Sorry, but could you keep it down a bit?” (Translation: turn it off NOW.)", "pt-BR": "Batem à porta às 23h. Seu colega de apê, gélido e passivo-agressivo: “Sorry, but could you keep it down a bit?” (Tradução: desligue isso JÁ.)" },
    objective: { en: "Defuse a passive-aggressive complaint.", "pt-BR": "Desarmar uma reclamação passivo-agressiva." },
    culturalNote: { en: "‘Sorry, but…’ + ‘a bit’ = a serious complaint, softened. Apologise sincerely.", "pt-BR": "‘Sorry, but…’ + ‘a bit’ = reclamação séria, suavizada. Peça desculpas de verdade." },
    environment: { mood: "hostile", baseNoise: 36 },
    npc: { name: { en: "Flatmate", "pt-BR": "Colega de Apê" }, initials: "FM" },
    drills: [{ word: "so sorry", say: "sôu SÓ-ri", note: { en: "Apologise sincerely.", "pt-BR": "Peça desculpas com sinceridade." } }],
    dialogueSteps: [ { text: "Sorry, but could you keep it down a bit?", tr: { en: "Please be quiet (it's serious).", "pt-BR": "Por favor, faça silêncio (é sério)." }, ear: { en: "<b>“kíp it dáun”</b>", "pt-BR": "<b>“kíp it dáun”</b>" }, audioPrompt: "Flatmate, tight smile at the door: “Sorry, but could you keep it down a bit?”", basic: "So sorry! Right now.", fluent: "So sorry — I'll turn it down right now." } ] },
  { sequence: 72, blockId: 3, indexInBlock: 22, phase: 3, subBlock: "3.5", threshold: 80,
    sceneTitle: { en: "Returning a Faulty Item", "pt-BR": "Devolvendo um Produto com Defeito" },
    contextDescription: { en: "The kettle you bought is broken. At the shop, a defensive clerk eyes you. You must assert your refund rights — politely but firmly.", "pt-BR": "A chaleira que você comprou quebrou. Na loja, um atendente na defensiva te encara. Você precisa afirmar seu direito ao reembolso — com educação e firmeza." },
    objective: { en: "Request a refund for a faulty product.", "pt-BR": "Pedir reembolso de um produto com defeito." },
    environment: { mood: "hostile", baseNoise: 42 },
    npc: { name: { en: "Shop Clerk", "pt-BR": "Atendente" }, initials: "SC" },
    drills: [{ word: "a refund", say: "a RÍ-fând", note: { en: "= reembolso.", "pt-BR": "= reembolso." } }],
    dialogueSteps: [ { text: "Have you got the receipt?", tr: { en: "Do you have the receipt?", "pt-BR": "Você tem a nota?" }, ear: { en: "<b>“ri-SÍT”</b> (silent P)", "pt-BR": "<b>“ri-SÍT”</b> (P mudo)" }, audioPrompt: "Clerk, defensive: “Have you got the receipt?”", basic: "Yes. It's faulty — a refund, please.", fluent: "Yes — it's faulty, so I'd like a refund." } ] },
  { sequence: 73, blockId: 3, indexInBlock: 23, phase: 3, subBlock: "3.5", threshold: 80,
    sceneTitle: { en: "The Queue Jumper", "pt-BR": "O Fura-Fila" },
    contextDescription: { en: "Someone shoves in front of you in the queue — a cardinal British sin. The crowd bristles silently. You must call it out... the British way.", "pt-BR": "Alguém fura a fila na sua frente — um pecado capital britânico. A multidão se irrita em silêncio. Você precisa reagir... do jeito britânico." },
    objective: { en: "Confront queue-jumping with icy politeness.", "pt-BR": "Confrontar o fura-fila com uma educação gelada." },
    culturalNote: { en: "Queue-jumping is unforgivable here. ‘Excuse me, there's a queue’ is a deadly weapon.", "pt-BR": "Furar fila é imperdoável aqui. ‘Excuse me, there's a queue’ é uma arma mortal." },
    environment: { mood: "hostile", baseNoise: 44 },
    npc: { name: { en: "Queue Jumper", "pt-BR": "Fura-Fila" }, initials: "QJ" },
    drills: [{ word: "there's a queue", say: "dérz a KIÚ", note: { en: "‘queue’ = fila (just 'kiú').", "pt-BR": "‘queue’ = fila (só 'kiú')." } }],
    dialogueSteps: [ { text: "...oh, am I not allowed to stand here?", tr: { en: "He's pretending he didn't jump.", "pt-BR": "Ele finge que não furou." }, ear: { en: "<b>“kiú”</b>", "pt-BR": "<b>“kiú”</b>" }, audioPrompt: "Jumper, feigning innocence: “...oh, am I not allowed to stand here?”", basic: "Excuse me, there's a queue.", fluent: "Excuse me — there's a queue, actually." } ] },
  { sequence: 74, blockId: 3, indexInBlock: 24, phase: 3, subBlock: "3.5", threshold: 80,
    sceneTitle: { en: "The Apology Dance", "pt-BR": "A Dança das Desculpas" },
    contextDescription: { en: "You bump into someone. Both of you say “sorry!” instantly — even though it was their fault. Master the reflexive British apology.", "pt-BR": "Você esbarra em alguém. Os dois dizem “sorry!” na hora — mesmo sendo culpa dele. Domine a desculpa reflexa britânica." },
    objective: { en: "Perform the reflexive ‘sorry’ exchange.", "pt-BR": "Executar a troca reflexa de ‘sorry’." },
    culturalNote: { en: "Brits say ‘sorry’ for everything — it's social lubricant, not guilt.", "pt-BR": "Britânicos dizem ‘sorry’ para tudo — é lubrificante social, não culpa." },
    environment: { mood: "neutral", baseNoise: 46 },
    npc: { name: { en: "Passer-by", "pt-BR": "Pedestre" }, initials: "PB" },
    drills: [{ word: "sorry! / no, sorry!", say: "SÓ-ri! nôu, SÓ-ri!", note: { en: "Both apologise — always.", "pt-BR": "Os dois pedem desculpa — sempre." } }],
    dialogueSteps: [ { text: "Oh — sorry!", tr: { en: "They apologise (even if it's your bump).", "pt-BR": "Eles pedem desculpa (mesmo sendo seu esbarrão)." }, ear: { en: "<b>“SÓ-ri”</b>", "pt-BR": "<b>“SÓ-ri”</b>" }, audioPrompt: "Passer-by, reflexively: “Oh — sorry!”", basic: "No, sorry! My fault.", fluent: "No no, sorry — totally my fault!" } ] },
  { sequence: 75, blockId: 3, indexInBlock: 25, phase: 3, subBlock: "3.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "London Local", tagline: "London Local — Crisis-Proof", shareText: "Medical emergencies, bank scams, Tube strikes, queue-jumpers — survived them all. I'm a London Local now! 🇬🇧" },
    sceneTitle: { en: "Bonus — Sunday Roast", "pt-BR": "Bônus — Almoço de Domingo" },
    contextDescription: { en: "Your new mate invites you to a proper Sunday roast at the local. Warmth, gravy, laughter, belonging. You're not surviving London anymore — you're living it.", "pt-BR": "Seu novo amigo te convida para um verdadeiro almoço de domingo no pub local. Calor humano, molho, risadas, pertencimento. Você não está mais sobrevivendo a Londres — está vivendo." },
    objective: { en: "Accept belonging — toast with new friends.", "pt-BR": "Aceitar o pertencimento — brindar com novos amigos." },
    environment: { mood: "pleased", baseNoise: 44 },
    npc: { name: { en: "New Mate", "pt-BR": "Novo Amigo" }, initials: "NM" },
    drills: [{ word: "cheers, mate!", say: "TCHÍRZ, mêit", note: { en: "The toast of belonging.", "pt-BR": "O brinde do pertencimento." } }],
    dialogueSteps: [
      { text: "Glad you came. You're one of us now. Cheers!", tr: { en: "You belong now — cheers!", "pt-BR": "Você é dos nossos agora — saúde!" }, ear: { en: "<b>“tchírz”</b>", "pt-BR": "<b>“tchírz”</b>" }, audioPrompt: "New mate, raising a glass, warm pub roar: “Glad you came. You're one of us now. Cheers!”", basic: "Cheers, mate!", fluent: "Cheers, mate — to good friends!" },
      { text: "Knew you'd fit right in. Roast's on me.", tr: { en: "You fit in — lunch is on him.", "pt-BR": "Você se encaixou — o almoço é por conta dele." }, ear: { en: "<b>“fit ráit in”</b>", "pt-BR": "<b>“fit ráit in”</b>" }, audioPrompt: "Mate, clapping your shoulder: “Knew you'd fit right in. Roast's on me.”", basic: "You're the best!", fluent: "You legend — thank you!" },
    ] },
];

export const BLOCK03_BY_SEQUENCE = BLOCK03_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
