/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 11 (Modules 251–275)
 *  "The Crisis of Identity" — 5 sub-blocks:
 *    11.1 Homesickness Spiral (251–255) the wave, the longing, the low
 *    11.2 Two Worlds          (256–260) home-self vs London-self, "you've changed"
 *    11.3 ⚡ WILDCARD: 3am Call (261–265) a parent falls ill — drop everything
 *    11.4 Family Pressure     (266–270) "when are you coming home?", guilt
 *    11.5 Choosing Your Path  (271–275) roots AND wings — BONUS milestone
 *  Module 275 = "Two Worlds, One Home" milestone selfie.
 * ============================================================ */

export const BLOCK11_MODULES = [
  /* 11.1 — HOMESICKNESS SPIRAL */
  { sequence: 251, blockId: 11, indexInBlock: 1, phase: 2, subBlock: "11.1", threshold: 80,
    sceneTitle: { en: "The Wave", "pt-BR": "A Onda" },
    contextDescription: { en: "Out of nowhere, a song on the radio in your language, and homesickness hits like a physical blow. A friend sees your face crumple and gently asks what's wrong.", "pt-BR": "Do nada, uma música no rádio no seu idioma, e a saudade bate como um golpe físico. Um amigo vê seu rosto desmoronar e pergunta com cuidado o que houve." },
    objective: { en: "Name a sudden wave of homesickness.", "pt-BR": "Nomear uma onda súbita de saudade." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "it hit me out of nowhere", say: "it RÍT mi áut âv NÔU-uér", note: { en: "= me pegou do nada.", "pt-BR": "= me pegou do nada." } }],
    dialogueSteps: [ { text: "Hey, what's wrong? You went somewhere just then.", tr: { en: "They sense your sadness.", "pt-BR": "Eles sentem sua tristeza." }, ear: { en: "<b>“áut âv NÔU-uér”</b>", "pt-BR": "<b>“áut âv NÔU-uér”</b>" }, audioPrompt: "Friend, gentle and quiet: “Hey, what's wrong? You went somewhere just then.”", basic: "Homesickness hit me out of nowhere.", fluent: "Sorry — homesickness just hit me out of nowhere. That song..." } ] },
  { sequence: 252, blockId: 11, indexInBlock: 2, phase: 3, subBlock: "11.1", threshold: 80,
    sceneTitle: { en: "Chasing the Taste of Home", "pt-BR": "Atrás do Sabor de Casa" },
    contextDescription: { en: "You travel across the city to a tiny shop that sells food from back home. The owner, a fellow countryman, hears your accent and lights up. A moment of belonging in exile.", "pt-BR": "Você atravessa a cidade até uma lojinha que vende comida do seu país. O dono, um conterrâneo, ouve seu sotaque e se ilumina. Um momento de pertencimento no exílio." },
    objective: { en: "Connect with a fellow countryman in your language.", "pt-BR": "Conectar-se com um conterrâneo na sua língua." },
    environment: { mood: "pleased", baseNoise: 34 },
    npc: { name: { en: "Shop Owner", "pt-BR": "Dono da Loja" }, initials: "SO" },
    drills: [{ word: "tastes like home", say: "têists láik RÔUM", note: { en: "= tem gosto de casa.", "pt-BR": "= tem gosto de casa." } }],
    dialogueSteps: [ { text: "You're from back home? It's all here — take your time.", tr: { en: "A taste of home, in your language.", "pt-BR": "Um pedaço de casa, na sua língua." }, ear: { en: "<b>“têists láik rôum”</b>", "pt-BR": "<b>“têists láik rôum”</b>" }, audioPrompt: "Shop owner, warm, recognising your accent: “You're from back home? It's all here — take your time.”", basic: "This all tastes like home.", fluent: "It all tastes like home — I didn't know how much I needed this." } ] },
  { sequence: 253, blockId: 11, indexInBlock: 3, phase: 2, subBlock: "11.1", threshold: 80,
    sceneTitle: { en: "The Lonely Sunday", "pt-BR": "O Domingo Solitário" },
    contextDescription: { en: "A grey Sunday, the flat too quiet, everyone away. The loneliness of a life built far from where you started. You call a friend just to hear a voice — and admit you're low.", "pt-BR": "Um domingo cinzento, o apê quieto demais, todos fora. A solidão de uma vida construída longe de onde você começou. Você liga para um amigo só para ouvir uma voz — e admite que está pra baixo." },
    objective: { en: "Reach out instead of isolating.", "pt-BR": "Buscar contato em vez de se isolar." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "feeling a bit low", say: "FÍ-lin a bit LÔU", note: { en: "= meio pra baixo.", "pt-BR": "= meio pra baixo." } }],
    dialogueSteps: [ { text: "Hiya! Wasn't expecting a call — everything okay?", tr: { en: "They pick up — be honest.", "pt-BR": "Eles atendem — seja honesto." }, ear: { en: "<b>“FÍ-lin lôu”</b>", "pt-BR": "<b>“FÍ-lin lôu”</b>" }, audioPrompt: "Friend, surprised and warm on the phone: “Hiya! Wasn't expecting a call — everything okay?”", basic: "Feeling a bit low, honestly.", fluent: "Honestly, I'm feeling a bit low — just needed to hear a friendly voice." } ] },
  { sequence: 254, blockId: 11, indexInBlock: 4, phase: 2, subBlock: "11.1", threshold: 80,
    sceneTitle: { en: "“Was It Worth It?”", "pt-BR": "“Valeu a Pena?”" },
    contextDescription: { en: "At your lowest, the question that haunts every immigrant surfaces: giving up everything familiar — for this? A close friend asks if you regret coming. You must answer honestly.", "pt-BR": "No seu pior momento, surge a pergunta que assombra todo imigrante: abrir mão de tudo que era familiar — por isto? Um amigo próximo pergunta se você se arrepende de ter vindo. Responda com honestidade." },
    objective: { en: "Confront the doubt of whether it was worth it.", "pt-BR": "Encarar a dúvida se valeu a pena." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Close Friend", "pt-BR": "Amigo Próximo" }, initials: "CF" },
    drills: [{ word: "some days I wonder", say: "sâm dêis ai UÂN-dâr", note: { en: "= tem dias que me pergunto.", "pt-BR": "= tem dias que me pergunto." } }],
    dialogueSteps: [ { text: "Do you ever regret it? Leaving everything behind?", tr: { en: "Do you regret coming?", "pt-BR": "Você se arrepende de ter vindo?" }, ear: { en: "<b>“ri-GRÉT”</b>", "pt-BR": "<b>“ri-GRÉT”</b>" }, audioPrompt: "Close friend, soft and serious: “Do you ever regret it? Leaving everything behind?”", basic: "Some days I wonder. Not today.", fluent: "Some days I wonder — but then I remember how far I've come." } ] },
  { sequence: 255, blockId: 11, indexInBlock: 5, phase: 3, subBlock: "11.1", threshold: 80,
    sceneTitle: { en: "A Small Light", "pt-BR": "Uma Pequena Luz" },
    contextDescription: { en: "The fog lifts a little: a friend turns up unannounced with food from your home country, just because. The kindness of a found family. You let yourself receive it.", "pt-BR": "A névoa se dissipa um pouco: um amigo aparece sem avisar com comida do seu país, só porque sim. A gentileza de uma família encontrada. Você se permite receber." },
    objective: { en: "Accept comfort from a chosen family.", "pt-BR": "Aceitar o conforto de uma família escolhida." },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "you didn't have to", say: "iú DÍ-dânt rév tu", note: { en: "= você não precisava.", "pt-BR": "= você não precisava." } }],
    dialogueSteps: [ { text: "I found your favourite from back home. Thought of you.", tr: { en: "They brought comfort food.", "pt-BR": "Trouxeram comida que conforta." }, ear: { en: "<b>“thôt âv iú”</b>", "pt-BR": "<b>“thôt âv iú”</b>" }, audioPrompt: "Friend, at your door with a bag, smiling: “I found your favourite from back home. Thought of you.”", basic: "You didn't have to. Thank you.", fluent: "You didn't have to do that — honestly, you have no idea what this means." } ] },

  /* 11.2 — TWO WORLDS */
  { sequence: 256, blockId: 11, indexInBlock: 6, phase: 2, subBlock: "11.2", threshold: 80,
    sceneTitle: { en: "“You've Changed”", "pt-BR": "“Você Mudou”" },
    contextDescription: { en: "On a call home, an old friend says it with an edge: “You've changed. You're not the same person who left.” Part accusation, part truth. You must answer it with honesty and love.", "pt-BR": "Numa ligação para casa, um amigo antigo diz com uma ponta de mágoa: “Você mudou. Não é mais a mesma pessoa que foi embora.” Parte acusação, parte verdade. Responda com honestidade e amor." },
    objective: { en: "Respond to ‘you've changed’ without defensiveness.", "pt-BR": "Responder ao ‘você mudou’ sem se defender." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Old Friend", "pt-BR": "Amigo Antigo" }, initials: "OF" },
    drills: [{ word: "maybe I have", say: "MÊI-bi ai rév", note: { en: "Own the change.", "pt-BR": "Assuma a mudança." } }],
    dialogueSteps: [ { text: "You've changed. You're not who you were when you left.", tr: { en: "An old friend says you've changed.", "pt-BR": "Um amigo antigo diz que você mudou." }, ear: { en: "<b>“tchêindjd”</b>", "pt-BR": "<b>“tchêindjd”</b>" }, audioPrompt: "Old friend, a little hurt down the line: “You've changed. You're not who you were when you left.”", basic: "Maybe I have. I've grown.", fluent: "Maybe I have — but I'm still me, just... more of me." } ] },
  { sequence: 257, blockId: 11, indexInBlock: 7, phase: 2, subBlock: "11.2", threshold: 80,
    sceneTitle: { en: "The Accent Slips", "pt-BR": "O Sotaque Escapa" },
    contextDescription: { en: "Speaking your own language now, English words keep slipping in, your accent oddly bent. A relative teases you for ‘sounding foreign’ in your mother tongue. A strange grief.", "pt-BR": "Falando seu próprio idioma agora, palavras em inglês escapam, seu sotaque estranhamente torto. Um parente te zoa por ‘soar estrangeiro’ na sua língua materna. Um luto estranho." },
    objective: { en: "Cope with losing fluency in your own language.", "pt-BR": "Lidar com a perda de fluência na própria língua." },
    culturalNote: { en: "First-language attrition is real — your two selves overwrite each other. It's normal.", "pt-BR": "A perda da língua materna é real — seus dois ‘eus’ se sobrescrevem. É normal." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Relative", "pt-BR": "Parente" }, initials: "RE" },
    drills: [{ word: "I mix them up now", say: "ai míks dém âp náu", note: { en: "= agora eu misturo.", "pt-BR": "= agora eu misturo." } }],
    dialogueSteps: [ { text: "Listen to you — you've got an accent in your OWN language!", tr: { en: "They tease your shifting accent.", "pt-BR": "Zoam seu sotaque mudando." }, ear: { en: "<b>“ÉK-sânt”</b>", "pt-BR": "<b>“ÉK-sânt”</b>" }, audioPrompt: "Relative, teasing affectionately: “Listen to you — you've got an accent in your OWN language!”", basic: "Ha — I mix them up now.", fluent: "I know — I mix them up now, my brain lives in two languages." } ] },
  { sequence: 258, blockId: 11, indexInBlock: 8, phase: 2, subBlock: "11.2", threshold: 80,
    sceneTitle: { en: "Caught Between Values", "pt-BR": "Entre Dois Valores" },
    contextDescription: { en: "A clash: a London friend finds something normal that your home culture finds rude — or vice versa. You're the bridge, belonging fully to neither. You must explain both sides gently.", "pt-BR": "Um choque: um amigo de Londres acha normal algo que sua cultura considera grosseiro — ou o contrário. Você é a ponte, sem pertencer totalmente a nenhum lado. Explique ambos com gentileza." },
    objective: { en: "Bridge a clash between your two cultures.", "pt-BR": "Fazer a ponte entre suas duas culturas." },
    environment: { mood: "neutral", baseNoise: 38 },
    npc: { name: { en: "London Friend", "pt-BR": "Amigo de Londres" }, initials: "LF" },
    drills: [{ word: "where I'm from,", say: "uér aim FRÂM", note: { en: "Frame your culture.", "pt-BR": "Enquadre sua cultura." } }],
    dialogueSteps: [ { text: "Why would that be rude? It's totally normal here.", tr: { en: "Explain your culture's view.", "pt-BR": "Explique a visão da sua cultura." }, ear: { en: "<b>“rúd”</b>", "pt-BR": "<b>“rúd”</b>" }, audioPrompt: "London friend, genuinely puzzled: “Why would that be rude? It's totally normal here.”", basic: "Where I'm from, it's different.", fluent: "Here it's fine — but where I'm from, it'd come across as rude." } ] },
  { sequence: 259, blockId: 11, indexInBlock: 9, phase: 2, subBlock: "11.2", threshold: 80,
    sceneTitle: { en: "Neither Here Nor There", "pt-BR": "Nem Aqui Nem Lá" },
    contextDescription: { en: "The loneliest truth of the immigrant: too foreign for home, too foreign for here. You confess this in-between feeling to someone who's lived it — another long-term expat.", "pt-BR": "A verdade mais solitária do imigrante: estrangeiro demais para casa, estrangeiro demais para aqui. Você confessa esse sentimento de entremeio a quem já viveu isso — outro expat de longa data." },
    objective: { en: "Articulate the ‘in-between’ identity feeling.", "pt-BR": "Expressar o sentimento de identidade ‘no entremeio’." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "Fellow Expat", "pt-BR": "Outro Expat" }, initials: "FE" },
    drills: [{ word: "I belong to both and neither", say: "ai bi-LÓNG tu bôuth ând NÍ-dâr", note: { en: "The in-between truth.", "pt-BR": "A verdade do entremeio." } }],
    dialogueSteps: [ { text: "Do you ever feel like you fit nowhere now?", tr: { en: "They name the in-between feeling.", "pt-BR": "Eles nomeiam o sentimento do entremeio." }, ear: { en: "<b>“fit NÔU-uér”</b>", "pt-BR": "<b>“fit NÔU-uér”</b>" }, audioPrompt: "Fellow expat, knowingly: “Do you ever feel like you fit nowhere now?”", basic: "Yes. Both and neither.", fluent: "All the time — I belong to both places, and to neither." } ] },
  { sequence: 260, blockId: 11, indexInBlock: 10, phase: 2, subBlock: "11.2", threshold: 80,
    sceneTitle: { en: "Two Halves", "pt-BR": "Duas Metades" },
    contextDescription: { en: "A turning thought: maybe you don't have to choose. Maybe being two things is a richness, not a loss. You begin to say it out loud for the first time, testing the idea.", "pt-BR": "Um pensamento que vira a chave: talvez você não precise escolher. Talvez ser duas coisas seja uma riqueza, não uma perda. Você começa a dizer isso em voz alta pela primeira vez, testando a ideia." },
    objective: { en: "Begin reframing dual identity as strength.", "pt-BR": "Começar a ver a dupla identidade como força." },
    environment: { mood: "pleased", baseNoise: 28 },
    npc: { name: { en: "Fellow Expat", "pt-BR": "Outro Expat" }, initials: "FE" },
    drills: [{ word: "it's a strength", say: "its a STRÉNGTH", note: { en: "= é uma força.", "pt-BR": "= é uma força." } }],
    dialogueSteps: [ { text: "So how do you make peace with it?", tr: { en: "How do you reconcile both sides?", "pt-BR": "Como você reconcilia os dois lados?" }, ear: { en: "<b>“strÉngth”</b>", "pt-BR": "<b>“strÉngth”</b>" }, audioPrompt: "Fellow expat, curious: “So how do you make peace with it?”", basic: "Maybe it's a strength, not a loss.", fluent: "I'm starting to think it's a strength — being two things at once." } ] },

  /* 11.3 — ⚡ WILDCARD: THE 3AM CALL ⚡ */
  { sequence: 261, blockId: 11, indexInBlock: 11, phase: 2, subBlock: "11.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ Wildcard: The 3am Call", "pt-BR": "⚡ Curinga: A Ligação das 3h" },
    contextDescription: { en: "The phone screams at 3am — the call every immigrant dreads. Your mother's voice, breaking: your father's been rushed to hospital. The world tilts. You must take in the words through the fear.", "pt-BR": "O celular grita às 3h — a ligação que todo imigrante teme. A voz da sua mãe, embargada: seu pai foi levado às pressas para o hospital. O mundo se inclina. Você precisa absorver as palavras através do medo." },
    objective: { en: "Take in devastating news and stay present.", "pt-BR": "Absorver uma notícia devastadora e manter-se presente." },
    environment: { mood: "hostile", baseNoise: 20 },
    npc: { name: { en: "Mother", "pt-BR": "Mãe" }, initials: "Mã" },
    drills: [{ word: "I'm coming home", say: "aim KÂ-min rôum", note: { en: "= estou indo para casa.", "pt-BR": "= estou indo para casa." } }],
    dialogueSteps: [ { text: "It's your father — he's in hospital. You need to come.", tr: { en: "Your father is in hospital.", "pt-BR": "Seu pai está no hospital." }, ear: { en: "<b>“RÓS-pi-tâl”</b>", "pt-BR": "<b>“RÓS-pi-tâl”</b>" }, audioPrompt: "Mother, voice trembling at 3am, near silence: “It's your father — he's in hospital. You need to come.”", basic: "I'm coming home. Now.", fluent: "I'm coming home — right now. I'll be on the first flight." } ] },
  { sequence: 262, blockId: 11, indexInBlock: 12, phase: 3, subBlock: "11.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ The Emergency Flight", "pt-BR": "⚡ O Voo de Emergência" },
    contextDescription: { en: "4am, the airport, hands shaking, every flight full. At the desk you must beg, fight, and explain through tears for any seat home — tonight, at any price.", "pt-BR": "4h da manhã, o aeroporto, mãos tremendo, todos os voos lotados. No balcão você precisa implorar, lutar e explicar entre lágrimas por qualquer assento para casa — hoje, a qualquer preço." },
    objective: { en: "Secure an emergency flight under pressure.", "pt-BR": "Conseguir um voo de emergência sob pressão." },
    environment: { mood: "hostile", baseNoise: 42 },
    npc: { name: { en: "Airline Desk", "pt-BR": "Balcão da Cia. Aérea" }, initials: "AL" },
    drills: [{ word: "it's a family emergency", say: "its a FÉ-mi-li i-MÂR-djân-si", note: { en: "= é emergência familiar.", "pt-BR": "= é emergência familiar." } }],
    dialogueSteps: [ { text: "I'm sorry, the next flight's fully booked.", tr: { en: "The flight is full — plead your case.", "pt-BR": "O voo está cheio — explique seu caso." }, ear: { en: "<b>“i-MÂR-djân-si”</b>", "pt-BR": "<b>“i-MÂR-djân-si”</b>" }, audioPrompt: "Airline agent, apologetic at a busy desk: “I'm sorry, the next flight's fully booked.”", basic: "Please — it's a family emergency.", fluent: "Please — it's a family emergency, my father's in hospital. Anything at all." } ] },
  { sequence: 263, blockId: 11, indexInBlock: 13, phase: 2, subBlock: "11.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ Telling the Boss", "pt-BR": "⚡ Avisando o Chefe" },
    contextDescription: { en: "From the departure gate, you call your boss. The leader you fought to become must now ask, vulnerably, for the time and space to be a child again, far away.", "pt-BR": "Do portão de embarque, você liga para seu chefe. O líder que você lutou para se tornar precisa agora pedir, vulnerável, o tempo e o espaço para voltar a ser um filho, longe dali." },
    objective: { en: "Tell your boss you must leave indefinitely.", "pt-BR": "Avisar o chefe que precisa ir por tempo indeterminado." },
    environment: { mood: "neutral", baseNoise: 38 },
    npc: { name: { en: "Boss", "pt-BR": "Chefe" }, initials: "BO" },
    drills: [{ word: "I need to be with family", say: "ai níd tu bi uíd FÉ-mi-li", note: { en: "State the need plainly.", "pt-BR": "Diga a necessidade direto." } }],
    dialogueSteps: [ { text: "Of course — family first. Take whatever time you need.", tr: { en: "They understand — accept it.", "pt-BR": "Eles entendem — aceite." }, ear: { en: "<b>“FÉ-mi-li fârst”</b>", "pt-BR": "<b>“FÉ-mi-li fârst”</b>" }, audioPrompt: "Boss, immediately kind on the phone: “Of course — family first. Take whatever time you need.”", basic: "Thank you. I need to be with family.", fluent: "Thank you — I have to be with my family right now, I don't know for how long." } ] },
  { sequence: 264, blockId: 11, indexInBlock: 14, phase: 2, subBlock: "11.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ At the Bedside", "pt-BR": "⚡ À Beira do Leito" },
    contextDescription: { en: "Home at last, in your first language, at your father's hospital bed. He's weak but awake. In the language of your childhood, you tell him what London never let you say enough.", "pt-BR": "Finalmente em casa, no seu primeiro idioma, à beira do leito do seu pai. Ele está fraco mas acordado. Na língua da sua infância, você diz a ele o que Londres nunca te deixou dizer o bastante." },
    objective: { en: "Be fully present with family, in your roots.", "pt-BR": "Estar plenamente presente com a família, nas suas raízes." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Father", "pt-BR": "Pai" }, initials: "Pa" },
    drills: [{ word: "I'm here, Dad", say: "aim RÍR, déd", note: { en: "= estou aqui, pai.", "pt-BR": "= estou aqui, pai." } }],
    dialogueSteps: [ { text: "You came all this way... for your old man?", tr: { en: "He's moved you came.", "pt-BR": "Ele se emociona por você ter vindo." }, ear: { en: "<b>“ól mén”</b> = velho (carinhoso)", "pt-BR": "<b>“ól mén”</b> = coroa (carinhoso)" }, audioPrompt: "Father, weak but smiling from the hospital bed: “You came all this way... for your old man?”", basic: "I'm here, Dad. Always.", fluent: "Of course I came — I'm here, Dad. I'm not going anywhere." } ] },
  { sequence: 265, blockId: 11, indexInBlock: 15, phase: 2, subBlock: "11.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ The Re-evaluation", "pt-BR": "⚡ A Reavaliação" },
    contextDescription: { en: "Your father stabilises. In the quiet after the fear, the huge question returns, heavier than ever: should you give up London and come home for good? You speak the doubt aloud.", "pt-BR": "Seu pai estabiliza. No silêncio depois do medo, a pergunta enorme retorna, mais pesada do que nunca: você deveria largar Londres e voltar para casa de vez? Você diz a dúvida em voz alta." },
    objective: { en: "Voice the question of giving up London.", "pt-BR": "Verbalizar a dúvida de largar Londres." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Mother", "pt-BR": "Mãe" }, initials: "Mã" },
    drills: [{ word: "I don't know what to do", say: "ai dôunt nôu uât tu DÚ", note: { en: "= não sei o que fazer.", "pt-BR": "= não sei o que fazer." } }],
    dialogueSteps: [ { text: "So... will you stay here now? With us?", tr: { en: "Will you give up London?", "pt-BR": "Você vai largar Londres?" }, ear: { en: "<b>“stêi ría”</b>", "pt-BR": "<b>“stêi ría”</b>" }, audioPrompt: "Mother, hopeful and fragile in the quiet hospital corridor: “So... will you stay here now? With us?”", basic: "I honestly don't know.", fluent: "I honestly don't know anymore — my heart's torn in two." } ] },

  /* 11.4 — FAMILY PRESSURE */
  { sequence: 266, blockId: 11, indexInBlock: 16, phase: 2, subBlock: "11.4", threshold: 80,
    sceneTitle: { en: "“When Are You Coming Home?”", "pt-BR": "“Quando Você Volta?”" },
    contextDescription: { en: "Now that you're here, the family closes in with love and expectation: surely you'll stay now? You must hold space for their hope without making a promise you can't keep.", "pt-BR": "Agora que você está aqui, a família te cerca com amor e expectativa: claro que você vai ficar agora, né? Você precisa acolher a esperança deles sem fazer uma promessa que não pode cumprir." },
    objective: { en: "Resist pressure without crushing hope.", "pt-BR": "Resistir à pressão sem esmagar a esperança." },
    environment: { mood: "hostile", baseNoise: 30 },
    npc: { name: { en: "Mother", "pt-BR": "Mãe" }, initials: "Mã" },
    drills: [{ word: "I need to think", say: "ai níd tu THÍNK", note: { en: "Buy yourself space.", "pt-BR": "Ganhe espaço para pensar." } }],
    dialogueSteps: [ { text: "Your room's just as you left it. You'll stay, won't you?", tr: { en: "They assume you'll stay.", "pt-BR": "Eles presumem que você vai ficar." }, ear: { en: "<b>“uôunt iú”</b>", "pt-BR": "<b>“uôunt iú”</b>" }, audioPrompt: "Mother, hopeful, showing you your old room: “Your room's just as you left it. You'll stay, won't you?”", basic: "I love you. I need to think.", fluent: "I love you all so much — but I need time to think, honestly." } ] },
  { sequence: 267, blockId: 11, indexInBlock: 17, phase: 2, subBlock: "11.4", threshold: 80,
    sceneTitle: { en: "The Guilt", "pt-BR": "A Culpa" },
    contextDescription: { en: "A relative lays it on thick: you abandoned the family, chasing a selfish dream while they struggled. The weaponised guilt of those left behind. You must answer with love, not shame.", "pt-BR": "Um parente pesa a mão: você abandonou a família, perseguindo um sonho egoísta enquanto eles sofriam. A culpa usada como arma por quem ficou. Responda com amor, não com vergonha." },
    objective: { en: "Withstand guilt-tripping with compassion.", "pt-BR": "Resistir à chantagem emocional com compaixão." },
    environment: { mood: "hostile", baseNoise: 28 },
    npc: { name: { en: "Relative", "pt-BR": "Parente" }, initials: "RE" },
    drills: [{ word: "that's not fair", say: "déts nót FÉR", note: { en: "Set a gentle boundary.", "pt-BR": "Estabeleça um limite gentil." } }],
    dialogueSteps: [ { text: "You left us behind to chase your own dreams.", tr: { en: "They guilt-trip you — respond with love.", "pt-BR": "Te culpabilizam — responda com amor." }, ear: { en: "<b>“tchêis”</b> = perseguir", "pt-BR": "<b>“tchêis”</b> = perseguir" }, audioPrompt: "Relative, accusatory and emotional: “You left us behind to chase your own dreams.”", basic: "That's not fair. I love you.", fluent: "That's not fair — I left to build a future, and I never stopped loving you." } ] },
  { sequence: 268, blockId: 11, indexInBlock: 18, phase: 2, subBlock: "11.4", threshold: 80,
    sceneTitle: { en: "The Sibling's Resentment", "pt-BR": "O Ressentimento do Irmão" },
    contextDescription: { en: "Your sibling, who stayed and carried the family's weight, finally lets the bitterness out: you got to fly while they were stuck. You must acknowledge their sacrifice honestly.", "pt-BR": "Seu irmão, que ficou e carregou o peso da família, finalmente deixa a mágoa sair: você pôde voar enquanto ele ficou preso. Você precisa reconhecer o sacrifício dele com honestidade." },
    objective: { en: "Acknowledge a sibling's sacrifice and resentment.", "pt-BR": "Reconhecer o sacrifício e a mágoa do irmão." },
    environment: { mood: "hostile", baseNoise: 26 },
    npc: { name: { en: "Sibling", "pt-BR": "Irmão(ã)" }, initials: "Ir" },
    drills: [{ word: "you carried it all", say: "iú KÉ-rid it ól", note: { en: "= você carregou tudo.", "pt-BR": "= você carregou tudo." } }],
    dialogueSteps: [ { text: "It's easy to fly off when someone else holds the family together.", tr: { en: "They resent that you left.", "pt-BR": "Eles te ressentem por ter ido." }, ear: { en: "<b>“flái óf”</b>", "pt-BR": "<b>“flái óf”</b>" }, audioPrompt: "Sibling, years of resentment surfacing: “It's easy to fly off when someone else holds the family together.”", basic: "You carried it all. I'm sorry.", fluent: "You carried it all while I was away — and I'm so sorry, truly." } ] },
  { sequence: 269, blockId: 11, indexInBlock: 19, phase: 2, subBlock: "11.4", threshold: 80,
    sceneTitle: { en: "Defending Your Choice", "pt-BR": "Defendendo Sua Escolha" },
    contextDescription: { en: "Enough. With love but no apology, you must finally explain that leaving wasn't betrayal — it was courage, and the life you built honours them, not abandons them.", "pt-BR": "Chega. Com amor, mas sem pedir desculpas, você precisa enfim explicar que ir embora não foi traição — foi coragem, e a vida que você construiu os honra, não os abandona." },
    objective: { en: "Defend your decision to emigrate, with dignity.", "pt-BR": "Defender sua decisão de emigrar, com dignidade." },
    environment: { mood: "neutral", baseNoise: 26 },
    npc: { name: { en: "Family", "pt-BR": "Família" }, initials: "FA" },
    drills: [{ word: "I'm proud of my life", say: "aim práud âv mai LÁIF", note: { en: "Claim your path.", "pt-BR": "Assuma seu caminho." } }],
    dialogueSteps: [ { text: "We just don't understand why you'd choose to be so far.", tr: { en: "Explain why you left.", "pt-BR": "Explique por que você foi." }, ear: { en: "<b>“tchúz”</b> = escolher", "pt-BR": "<b>“tchúz”</b> = escolher" }, audioPrompt: "A family member, softer now, searching: “We just don't understand why you'd choose to be so far.”", basic: "I'm proud of my life there.", fluent: "I didn't leave to escape you — I'm proud of the life I built, and it's for all of us." } ] },
  { sequence: 270, blockId: 11, indexInBlock: 20, phase: 2, subBlock: "11.4", threshold: 80,
    sceneTitle: { en: "The Blessing", "pt-BR": "A Bênção" },
    contextDescription: { en: "Your father, recovering, takes your hand and says the thing that frees you: go and live your life, fully, wherever it is. The permission you didn't know you needed.", "pt-BR": "Seu pai, se recuperando, segura sua mão e diz o que te liberta: vá e viva sua vida, plenamente, onde quer que seja. A permissão que você não sabia que precisava." },
    objective: { en: "Receive a parent's blessing to live your life.", "pt-BR": "Receber a bênção de um pai para viver sua vida." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Father", "pt-BR": "Pai" }, initials: "Pa" },
    drills: [{ word: "go and live", say: "gôu ând LÍV", note: { en: "= vá e viva.", "pt-BR": "= vá e viva." } }],
    dialogueSteps: [ { text: "Go and live, my child. We're always here. Always.", tr: { en: "He blesses you to go.", "pt-BR": "Ele te abençoa para ir." }, ear: { en: "<b>“gôu ând lív”</b>", "pt-BR": "<b>“gôu ând lív”</b>" }, audioPrompt: "Father, holding your hand, certain and loving: “Go and live, my child. We're always here. Always.”", basic: "I love you. I'll be back often.", fluent: "I love you — and I'll be back, again and again. This isn't goodbye." } ] },

  /* 11.5 — CHOOSING YOUR PATH */
  { sequence: 271, blockId: 11, indexInBlock: 21, phase: 3, subBlock: "11.5", threshold: 80,
    sceneTitle: { en: "The Goodbye at the Airport", "pt-BR": "A Despedida no Aeroporto" },
    contextDescription: { en: "Leaving home again, but everything's different now — chosen, not fled. At the gate you say goodbye without the old guilt, holding both your worlds at once.", "pt-BR": "Partindo de casa de novo, mas tudo está diferente agora — escolhido, não uma fuga. No portão, você se despede sem a velha culpa, segurando seus dois mundos ao mesmo tempo." },
    objective: { en: "Say a peaceful goodbye, carrying both worlds.", "pt-BR": "Despedir-se em paz, carregando os dois mundos." },
    environment: { mood: "pleased", baseNoise: 40 },
    npc: { name: { en: "Mother", "pt-BR": "Mãe" }, initials: "Mã" },
    drills: [{ word: "see you soon, not goodbye", say: "sí iú SÚN, nót gud-BÁI", note: { en: "= até logo, não adeus.", "pt-BR": "= até logo, não adeus." } }],
    dialogueSteps: [ { text: "Promise me this isn't the last time.", tr: { en: "Reassure them you'll return.", "pt-BR": "Garanta que você voltará." }, ear: { en: "<b>“gud-BÁI”</b>", "pt-BR": "<b>“gud-BÁI”</b>" }, audioPrompt: "Mother, holding you tight at the gate: “Promise me this isn't the last time.”", basic: "See you soon — not goodbye.", fluent: "I promise — this is see you soon, never goodbye." } ] },
  { sequence: 272, blockId: 11, indexInBlock: 22, phase: 3, subBlock: "11.5", threshold: 80,
    sceneTitle: { en: "Coming ‘Home’ to London", "pt-BR": "‘Voltando para Casa’ em Londres" },
    contextDescription: { en: "Landing back at Heathrow, the grey sky and the bustle — and to your shock, it feels like coming home. The cabbie says ‘welcome back’ and you realise: this is home too.", "pt-BR": "Pousando de volta em Heathrow, o céu cinza e o corre-corre — e, para seu espanto, parece voltar para casa. O taxista diz ‘welcome back’ e você percebe: aqui também é um lar." },
    objective: { en: "Recognise London as home, too.", "pt-BR": "Reconhecer Londres como um lar, também." },
    environment: { mood: "pleased", baseNoise: 50 },
    npc: { name: { en: "Cabbie", "pt-BR": "Taxista" }, initials: "CB" },
    drills: [{ word: "good to be back", say: "gúd tu bi BÉK", note: { en: "= bom estar de volta.", "pt-BR": "= bom estar de volta." } }],
    dialogueSteps: [ { text: "Welcome back! Good trip? Where to — home?", tr: { en: "‘Home’ — and it's London.", "pt-BR": "‘Casa’ — e é Londres." }, ear: { en: "<b>“UÉL-câm bék”</b>", "pt-BR": "<b>“UÉL-câm bék”</b>" }, audioPrompt: "Cabbie, cheery in the Heathrow rank: “Welcome back! Good trip? Where to — home?”", basic: "Home, yeah. Good to be back.", fluent: "Home — yeah. Funny, it really does feel good to be back." } ] },
  { sequence: 273, blockId: 11, indexInBlock: 23, phase: 3, subBlock: "11.5", threshold: 80,
    sceneTitle: { en: "Roots and Wings", "pt-BR": "Raízes e Asas" },
    contextDescription: { en: "Back with your London friends, you put the whole journey into words: you don't have to choose between where you're from and where you are. You can have roots AND wings.", "pt-BR": "De volta com seus amigos de Londres, você coloca toda a jornada em palavras: você não precisa escolher entre de onde você é e onde você está. Você pode ter raízes E asas." },
    objective: { en: "Articulate a whole, reconciled identity.", "pt-BR": "Expressar uma identidade inteira e reconciliada." },
    environment: { mood: "pleased", baseNoise: 44 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "roots and wings", say: "rúts ând UÍNGS", note: { en: "= raízes e asas.", "pt-BR": "= raízes e asas." } }],
    dialogueSteps: [ { text: "So — how are you feeling, after everything?", tr: { en: "How do you feel now?", "pt-BR": "Como você se sente agora?" }, ear: { en: "<b>“rúts ând uíngs”</b>", "pt-BR": "<b>“rúts ând uíngs”</b>" }, audioPrompt: "Friend, warm, welcoming you back: “So — how are you feeling, after everything?”", basic: "Whole. Roots and wings.", fluent: "Honestly? Whole — I've finally got roots and wings." } ] },
  { sequence: 274, blockId: 11, indexInBlock: 24, phase: 2, subBlock: "11.5", threshold: 80,
    sceneTitle: { en: "Two Languages, One Heart", "pt-BR": "Dois Idiomas, Um Coração" },
    contextDescription: { en: "On a video call you slip fluidly between both languages with your family — translating your two worlds for each other. The bridge you became is no longer a burden, but a gift.", "pt-BR": "Numa chamada de vídeo você desliza fluidamente entre os dois idiomas com a família — traduzindo seus dois mundos um para o outro. A ponte que você virou não é mais um fardo, mas um presente." },
    objective: { en: "Embrace being the bridge between two worlds.", "pt-BR": "Abraçar o papel de ponte entre dois mundos." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Family", "pt-BR": "Família" }, initials: "FA" },
    drills: [{ word: "best of both", say: "bést âv BÔUTH", note: { en: "= o melhor dos dois.", "pt-BR": "= o melhor dos dois." } }],
    dialogueSteps: [ { text: "Listen to you, switching like that — our little citizen of the world.", tr: { en: "They marvel at your two languages.", "pt-BR": "Eles se encantam com seus dois idiomas." }, ear: { en: "<b>“SÍ-ti-zân âv dâ uârld”</b>", "pt-BR": "<b>“SÍ-ti-zân âv dâ uârld”</b>" }, audioPrompt: "Family, delighted on a video call: “Listen to you, switching like that — our little citizen of the world.”", basic: "Best of both worlds!", fluent: "I've got the best of both worlds now — and I owe it to you." } ] },
  { sequence: 275, blockId: 11, indexInBlock: 25, phase: 3, subBlock: "11.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "Two Worlds, One Home", tagline: "Two Worlds, One Home — Roots & Wings", shareText: "I flew home in a crisis and came back knowing the truth: I don't have to choose. I can love where I'm from AND belong here. Two worlds, one home — roots and wings. 🇬🇧🌍❤️ #LinguoBound" },
    sceneTitle: { en: "Bonus — Whole", "pt-BR": "Bônus — Inteiro" },
    contextDescription: { en: "Golden hour on Primrose Hill, the whole London skyline glowing, a photo of your family from back home in one hand and your London friends beside you. Two worlds, finally at peace inside one heart. You're not torn anymore. You're whole. Take the picture.", "pt-BR": "Hora dourada em Primrose Hill, todo o horizonte de Londres brilhando, uma foto da sua família lá de casa numa das mãos e seus amigos de Londres ao seu lado. Dois mundos, enfim em paz dentro de um só coração. Você não está mais dividido. Você está inteiro. Tire a foto." },
    objective: { en: "Embrace a whole, two-world identity.", "pt-BR": "Abraçar uma identidade inteira, de dois mundos." },
    environment: { mood: "pleased", baseNoise: 38 },
    npc: { name: { en: "Best Friend", "pt-BR": "Melhor Amigo" }, initials: "BF" },
    drills: [{ word: "I'm finally whole", say: "aim FÁI-nâl-li RÔUL", note: { en: "The heart of the journey.", "pt-BR": "O coração da jornada." } }],
    dialogueSteps: [
      { text: "You seem different since you got back. Lighter.", tr: { en: "You're at peace now.", "pt-BR": "Você está em paz agora." }, ear: { en: "<b>“LÁI-târ”</b>", "pt-BR": "<b>“LÁI-târ”</b>" }, audioPrompt: "Best friend, gentle, on the hill at golden hour: “You seem different since you got back. Lighter.”", basic: "I'm finally whole.", fluent: "I am — I finally feel whole. Two worlds, one home." },
      { text: "You've got a home here AND there. That's rare, you know.", tr: { en: "You belong in both places.", "pt-BR": "Você pertence aos dois lugares." }, ear: { en: "<b>“rér”</b> = raro", "pt-BR": "<b>“rér”</b> = raro" }, audioPrompt: "Best friend, arm around you, skyline glowing: “You've got a home here AND there. That's rare, you know.”", basic: "Roots and wings.", fluent: "Roots and wings — I wouldn't trade it for anything." },
    ] },
];

export const BLOCK11_BY_SEQUENCE = BLOCK11_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
