/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 13 (Modules 301–325)
 *  "The Professional Crossroads" — 5 sub-blocks:
 *    13.1 Two Roads          (301–305) a second offer, the counter, the choice
 *    13.2 The Grey Area      (306–310) an ethical dilemma at work
 *    13.3 ⚡ WILDCARD: The Whistleblower (311–315) fraud uncovered — job & visa on the line
 *    13.4 The Weight of a Name (316–320) reputation, references, the industry's memory
 *    13.5 The Road Taken     (321–325) integrity over advancement — BONUS milestone (325)
 *  Module 325 = "Person of Integrity" milestone selfie.
 * ============================================================ */

export const BLOCK13_MODULES = [
  /* 13.1 — TWO ROADS */
  { sequence: 301, blockId: 13, indexInBlock: 1, phase: 2, subBlock: "13.1", threshold: 80,
    sceneTitle: { en: "The Headhunter's Call", "pt-BR": "A Ligação do Headhunter" },
    contextDescription: { en: "A recruiter from a rival firm calls: a bigger title, more money, a poached opportunity. Once you couldn't read a menu; now you're being courted. You must field the approach with poise.", "pt-BR": "Um recrutador de uma firma rival liga: um cargo maior, mais dinheiro, uma oportunidade de fisgar você. Um dia você não conseguia ler um cardápio; agora estão te cortejando. Você precisa lidar com a abordagem com classe." },
    objective: { en: "Handle a recruiter's pitch professionally.", "pt-BR": "Lidar com a abordagem de um recrutador com profissionalismo." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "Headhunter", "pt-BR": "Headhunter" }, initials: "HH" },
    drills: [{ word: "I'm open to a conversation", say: "aim ÔU-pân tu a con-vâr-SÊI-shân", note: { en: "= estou aberto a conversar.", "pt-BR": "= estou aberto a conversar." } }, { word: "tell me more", say: "tél mi MÔR", note: { en: "= me conte mais.", "pt-BR": "= me conte mais." } }],
    dialogueSteps: [ { text: "Your name keeps coming up. Would you consider the right move?", tr: { en: "They're courting you.", "pt-BR": "Estão te cortejando." }, ear: { en: "<b>“ÔU-pân tu”</b>", "pt-BR": "<b>“ÔU-pân tu”</b>" }, audioPrompt: "Headhunter, smooth and flattering on the phone: “Your name keeps coming up. Would you consider the right move?”", basic: "I'm open to a conversation. Tell me more.", fluent: "I'm flattered — I'm open to a conversation. Tell me more about the role." } ] },
  { sequence: 302, blockId: 13, indexInBlock: 2, phase: 2, subBlock: "13.1", threshold: 80,
    sceneTitle: { en: "The Rival Interview", "pt-BR": "A Entrevista na Rival" },
    contextDescription: { en: "Across a sleek table, the rival firm's director probes why you'd leave a place you helped build. You must show ambition without bad-mouthing your current employer — a delicate British line.", "pt-BR": "Do outro lado de uma mesa elegante, o diretor da firma rival investiga por que você deixaria um lugar que ajudou a construir. Você precisa mostrar ambição sem falar mal do empregador atual — uma linha britânica delicada." },
    objective: { en: "Express ambition without disloyalty.", "pt-BR": "Expressar ambição sem deslealdade." },
    environment: { mood: "neutral", baseNoise: 26 },
    npc: { name: { en: "Rival Director", "pt-BR": "Diretor Rival" }, initials: "RD" },
    drills: [{ word: "I'm ready for the next challenge", say: "aim RÉ-di fôr dâ nékst TCHÁ-lândj", note: { en: "= estou pronto para o próximo desafio.", "pt-BR": "= estou pronto para o próximo desafio." } }],
    dialogueSteps: [ { text: "So why leave? Things not going well over there?", tr: { en: "Don't badmouth — stay classy.", "pt-BR": "Não fale mal — mantenha a classe." }, ear: { en: "<b>“nékst TCHÁ-lândj”</b>", "pt-BR": "<b>“nékst TCHÁ-lândj”</b>" }, audioPrompt: "Rival director, probing across a glass table: “So why leave? Things not going well over there?”", basic: "They're great. I'm ready for the next challenge.", fluent: "Not at all — I've learned a lot there. I'm simply ready for the next challenge." } ] },
  { sequence: 303, blockId: 13, indexInBlock: 3, phase: 2, subBlock: "13.1", threshold: 80,
    sceneTitle: { en: "The Counter-Offer", "pt-BR": "A Contraproposta" },
    contextDescription: { en: "Your current boss, hearing whispers, calls you in and makes a counter-offer to keep you. The leverage has flipped. You must respond with grace, not greed, and keep your options open.", "pt-BR": "Seu chefe atual, ouvindo os rumores, te chama e faz uma contraproposta para te segurar. O jogo de poder virou. Você precisa responder com classe, não com ganância, e manter as opções abertas." },
    objective: { en: "Respond to a counter-offer without burning bridges.", "pt-BR": "Responder a uma contraproposta sem queimar pontes." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Your Boss", "pt-BR": "Seu Chefe" }, initials: "YB" },
    drills: [{ word: "I need time to think it over", say: "ai níd táim tu THÍNK it ÔU-vâr", note: { en: "= preciso de tempo para pensar.", "pt-BR": "= preciso de tempo para pensar." } }],
    dialogueSteps: [ { text: "Don't go. Whatever they offered, we'll match it. You matter here.", tr: { en: "They want to keep you.", "pt-BR": "Eles querem te manter." }, ear: { en: "<b>“THÍNK it ÔU-vâr”</b>", "pt-BR": "<b>“THÍNK it ÔU-vâr”</b>" }, audioPrompt: "Your boss, suddenly earnest behind a closed door: “Don't go. Whatever they offered, we'll match it. You matter here.”", basic: "Thank you. I need time to think it over.", fluent: "That means a lot — genuinely. I just need a little time to think it over." } ] },
  { sequence: 304, blockId: 13, indexInBlock: 4, phase: 3, subBlock: "13.1", threshold: 80,
    sceneTitle: { en: "Weighing It Out Loud", "pt-BR": "Pesando em Voz Alta" },
    contextDescription: { en: "On a walk along the canal, you talk it through with a trusted mentor: money versus loyalty, ambition versus the team you love. You must articulate a genuine dilemma, not just facts.", "pt-BR": "Num passeio à beira do canal, você conversa com um mentor de confiança: dinheiro versus lealdade, ambição versus o time que você ama. Você precisa articular um dilema genuíno, não só fatos." },
    objective: { en: "Talk through a career dilemma articulately.", "pt-BR": "Conversar sobre um dilema de carreira de forma articulada." },
    environment: { mood: "neutral", baseNoise: 40 },
    npc: { name: { en: "Mentor", "pt-BR": "Mentor" }, initials: "Me" },
    drills: [{ word: "my gut says", say: "mai GÂT séz", note: { en: "= meu instinto diz.", "pt-BR": "= meu instinto diz." } }, { word: "I'm torn", say: "aim TÔRN", note: { en: "= estou dividido.", "pt-BR": "= estou dividido." } }],
    dialogueSteps: [ { text: "Forget the money for a second. Where does your gut point?", tr: { en: "Name what you really feel.", "pt-BR": "Nomeie o que você realmente sente." }, ear: { en: "<b>“mai GÂT séz”</b>", "pt-BR": "<b>“mai GÂT séz”</b>" }, audioPrompt: "Mentor, calm by the canal, ducks and distant traffic: “Forget the money for a second. Where does your gut point?”", basic: "I'm torn. My gut says stay.", fluent: "Honestly, I'm torn — but my gut says the money isn't the whole picture." } ] },
  { sequence: 305, blockId: 13, indexInBlock: 5, phase: 2, subBlock: "13.1", threshold: 80,
    sceneTitle: { en: "Declining with Grace", "pt-BR": "Recusando com Elegância" },
    contextDescription: { en: "You've decided to stay — for now. You must phone the rival firm and turn down their offer warmly enough that the door stays open for the future. Burning no bridges is its own skill.", "pt-BR": "Você decidiu ficar — por enquanto. Você precisa ligar para a firma rival e recusar a proposta de forma calorosa o suficiente para a porta seguir aberta no futuro. Não queimar pontes é uma habilidade em si." },
    objective: { en: "Decline an offer while keeping the relationship warm.", "pt-BR": "Recusar uma proposta mantendo a relação calorosa." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Rival Director", "pt-BR": "Diretor Rival" }, initials: "RD" },
    drills: [{ word: "the timing isn't right", say: "dâ TÁI-min Í-zânt ráit", note: { en: "= o momento não é o certo.", "pt-BR": "= o momento não é o certo." } }, { word: "let's stay in touch", say: "léts stêi in TÂTCH", note: { en: "= vamos manter contato.", "pt-BR": "= vamos manter contato." } }],
    dialogueSteps: [ { text: "I'm sorry to hear that. Is there anything that would change your mind?", tr: { en: "Decline warmly, leave the door open.", "pt-BR": "Recuse com calor, deixe a porta aberta." }, ear: { en: "<b>“stêi in TÂTCH”</b>", "pt-BR": "<b>“stêi in TÂTCH”</b>" }, audioPrompt: "Rival director, gracious but disappointed: “I'm sorry to hear that. Is there anything that would change your mind?”", basic: "The timing isn't right. Let's stay in touch.", fluent: "The timing just isn't right for me now — but I'd love to stay in touch, truly." } ] },

  /* 13.2 — THE GREY AREA */
  { sequence: 306, blockId: 13, indexInBlock: 6, phase: 2, subBlock: "13.2", threshold: 80,
    sceneTitle: { en: "Asked to Bend the Truth", "pt-BR": "Pedido para Distorcer a Verdade" },
    contextDescription: { en: "A manager asks you to ‘massage’ some figures in a client report — nothing illegal, they say, just optimistic. The first small step onto a slippery slope. You must push back diplomatically.", "pt-BR": "Um gerente pede que você ‘maquie’ alguns números num relatório para o cliente — nada ilegal, dizem, só otimista. O primeiro passinho numa ladeira escorregadia. Você precisa recusar com diplomacia." },
    objective: { en: "Diplomatically refuse to misrepresent data.", "pt-BR": "Recusar diplomaticamente distorcer dados." },
    environment: { mood: "hostile", baseNoise: 26 },
    npc: { name: { en: "Manager", "pt-BR": "Gerente" }, initials: "Ma" },
    drills: [{ word: "I'm not comfortable with that", say: "aim nót CÂM-fâr-tâ-bâl uíd dét", note: { en: "= eu não me sinto confortável com isso.", "pt-BR": "= eu não me sinto confortável com isso." } }],
    dialogueSteps: [ { text: "Just round the numbers up a bit. The client wants good news.", tr: { en: "Hold your line politely.", "pt-BR": "Mantenha sua posição com educação." }, ear: { en: "<b>“CÂM-fâr-tâ-bâl”</b>", "pt-BR": "<b>“CÂM-fâr-tâ-bâl”</b>" }, audioPrompt: "Manager, casual but pointed, leaning over your desk: “Just round the numbers up a bit. The client wants good news.”", basic: "I'm not comfortable with that.", fluent: "I'm not comfortable misrepresenting it — can we find an honest way to frame it?" } ] },
  { sequence: 307, blockId: 13, indexInBlock: 7, phase: 2, subBlock: "13.2", threshold: 80,
    sceneTitle: { en: "Covering for a Colleague", "pt-BR": "Cobrindo um Colega" },
    contextDescription: { en: "A struggling colleague and friend begs you to cover for a serious mistake they made. Loyalty pulls one way, integrity the other. You must respond with honesty and compassion at once.", "pt-BR": "Um colega e amigo em apuros implora que você o cubra por um erro grave que cometeu. A lealdade puxa para um lado, a integridade para o outro. Você precisa responder com honestidade e compaixão ao mesmo tempo." },
    objective: { en: "Balance loyalty and honesty under pressure.", "pt-BR": "Equilibrar lealdade e honestidade sob pressão." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "Co" },
    drills: [{ word: "I can't lie for you", say: "ai kânt LÁI fôr iú", note: { en: "= eu não posso mentir por você.", "pt-BR": "= eu não posso mentir por você." } }, { word: "let me help you fix it", say: "lét mi rélp iú FÍKS it", note: { en: "= deixa eu te ajudar a consertar.", "pt-BR": "= deixa eu te ajudar a consertar." } }],
    dialogueSteps: [ { text: "Please, just tell them it was a system error. They'll fire me.", tr: { en: "Be honest but kind.", "pt-BR": "Seja honesto mas gentil." }, ear: { en: "<b>“LÁI fôr iú”</b>", "pt-BR": "<b>“LÁI fôr iú”</b>" }, audioPrompt: "Colleague, panicking, whispering by the lifts: “Please, just tell them it was a system error. They'll fire me.”", basic: "I can't lie for you. Let me help you fix it.", fluent: "I can't lie for you — but I won't abandon you either. Let's go in together and fix it." } ] },
  { sequence: 308, blockId: 13, indexInBlock: 8, phase: 2, subBlock: "13.2", threshold: 80,
    sceneTitle: { en: "The Uncomfortable Meeting", "pt-BR": "A Reunião Desconfortável" },
    contextDescription: { en: "In a tense meeting, leadership presents a decision you believe is wrong for clients. Everyone nods along. You must be the lone voice that respectfully raises the concern no one else will.", "pt-BR": "Numa reunião tensa, a liderança apresenta uma decisão que você acredita ser errada para os clientes. Todos concordam de cabeça. Você precisa ser a única voz que, com respeito, levanta a preocupação que ninguém mais vai." },
    objective: { en: "Voice a dissenting concern respectfully.", "pt-BR": "Levantar uma discordância com respeito." },
    environment: { mood: "hostile", baseNoise: 30 },
    npc: { name: { en: "Senior Director", "pt-BR": "Diretor Sênior" }, initials: "SD" },
    drills: [{ word: "with respect, I disagree", say: "uíd ris-PÉKT, ai dis-â-GRÍ", note: { en: "= com todo respeito, discordo.", "pt-BR": "= com todo respeito, discordo." } }, { word: "have we considered", say: "rév uí cân-SÍ-dârd", note: { en: "= será que consideramos…", "pt-BR": "= será que consideramos…" } }],
    dialogueSteps: [ { text: "Good, we're all agreed then. Moving on—", tr: { en: "Speak up before it's too late.", "pt-BR": "Fale antes que seja tarde." }, ear: { en: "<b>“uíd ris-PÉKT”</b>", "pt-BR": "<b>“uíd ris-PÉKT”</b>" }, audioPrompt: "Senior director, briskly closing the topic in a boardroom: “Good, we're all agreed then. Moving on—”", basic: "With respect, I disagree.", fluent: "Sorry — with respect, I disagree. Have we considered what this does to the client?" } ] },
  { sequence: 309, blockId: 13, indexInBlock: 9, phase: 2, subBlock: "13.2", threshold: 80,
    sceneTitle: { en: "The Tempting Shortcut", "pt-BR": "O Atalho Tentador" },
    contextDescription: { en: "A peer offers you confidential information from a competitor — a shortcut that would make you a star overnight. The temptation is real, the risk enormous. You must turn it down clearly.", "pt-BR": "Um colega te oferece informação confidencial de um concorrente — um atalho que te tornaria um astro da noite para o dia. A tentação é real, o risco enorme. Você precisa recusar com clareza." },
    objective: { en: "Refuse an unethical advantage firmly.", "pt-BR": "Recusar uma vantagem antiética com firmeza." },
    environment: { mood: "hostile", baseNoise: 28 },
    npc: { name: { en: "Peer", "pt-BR": "Colega de Nível" }, initials: "Pe" },
    drills: [{ word: "that's a line I won't cross", say: "déts a láin ai uôunt CRÓS", note: { en: "= essa é uma linha que eu não cruzo.", "pt-BR": "= essa é uma linha que eu não cruzo." } }],
    dialogueSteps: [ { text: "Nobody will ever know. This makes your whole year. Take it.", tr: { en: "Refuse the shortcut.", "pt-BR": "Recuse o atalho." }, ear: { en: "<b>“uôunt CRÓS”</b>", "pt-BR": "<b>“uôunt CRÓS”</b>" }, audioPrompt: "Peer, low and conspiratorial in an empty office: “Nobody will ever know. This makes your whole year. Take it.”", basic: "No. That's a line I won't cross.", fluent: "No — that's a line I won't cross, not for any deal. And you shouldn't either." } ] },
  { sequence: 310, blockId: 13, indexInBlock: 10, phase: 2, subBlock: "13.2", threshold: 80,
    sceneTitle: { en: "Naming Your Values", "pt-BR": "Nomeando Seus Valores" },
    contextDescription: { en: "Your mentor, impressed, asks why you keep choosing the hard, honest path when shortcuts abound. You must articulate the principle you live by — in clear, grown-up English.", "pt-BR": "Seu mentor, impressionado, pergunta por que você sempre escolhe o caminho difícil e honesto quando há tantos atalhos. Você precisa articular o princípio que rege sua vida — num inglês claro e maduro." },
    objective: { en: "Articulate your professional values clearly.", "pt-BR": "Articular seus valores profissionais com clareza." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Mentor", "pt-BR": "Mentor" }, initials: "Me" },
    drills: [{ word: "I'd rather sleep at night", say: "aid RÁ-dâr slíp ét náit", note: { en: "= prefiro dormir tranquilo.", "pt-BR": "= prefiro dormir tranquilo." } }],
    dialogueSteps: [ { text: "You make it harder for yourself, you know. Why?", tr: { en: "Explain your principle.", "pt-BR": "Explique seu princípio." }, ear: { en: "<b>“slíp ét náit”</b>", "pt-BR": "<b>“slíp ét náit”</b>" }, audioPrompt: "Mentor, genuinely curious over coffee: “You make it harder for yourself, you know. Why?”", basic: "I'd rather sleep at night.", fluent: "Maybe — but a name takes years to build and a second to lose. I'd rather sleep at night." } ] },

  /* 13.3 — ⚡ WILDCARD: THE WHISTLEBLOWER ⚡ */
  { sequence: 311, blockId: 13, indexInBlock: 11, phase: 2, subBlock: "13.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ Wildcard: What You Found", "pt-BR": "⚡ Curinga: O Que Você Achou" },
    contextDescription: { en: "Late, alone, reconciling accounts, you stumble onto it: the firm is hiding millions in losses from clients and regulators. Outright fraud. Your hands go cold. A colleague catches you staring at the screen.", "pt-BR": "Tarde, sozinho, fechando contas, você tropeça nisso: a firma está escondendo milhões em perdas de clientes e do regulador. Fraude pura. Suas mãos gelam. Um colega te flagra encarando a tela." },
    objective: { en: "Process discovering serious fraud, stay composed.", "pt-BR": "Processar a descoberta de uma fraude grave, manter a compostura." },
    environment: { mood: "hostile", baseNoise: 18 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "Co" },
    drills: [{ word: "something doesn't add up", say: "SÂM-thing dâzânt éd ÂP", note: { en: "= tem algo que não fecha.", "pt-BR": "= tem algo que não fecha." } }],
    dialogueSteps: [ { text: "You're here late. You alright? You've gone pale.", tr: { en: "Stay composed — don't reveal it yet.", "pt-BR": "Mantenha a calma — não revele ainda." }, ear: { en: "<b>“éd ÂP”</b>", "pt-BR": "<b>“éd ÂP”</b>" }, audioPrompt: "Colleague, concerned, appearing at your desk in a near-empty office: “You're here late. You alright? You've gone pale.”", basic: "I'm fine. Something doesn't add up.", fluent: "I'm fine — just tired. Some numbers here... don't quite add up. It's nothing." } ] },
  { sequence: 312, blockId: 13, indexInBlock: 12, phase: 2, subBlock: "13.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ The Pressure to Stay Quiet", "pt-BR": "⚡ A Pressão para Ficar Calado" },
    contextDescription: { en: "A senior partner closes the door. They know that you know. The threat is silken: forget what you saw, and your career soars; speak, and your job — and your visa sponsorship — vanish. You must not crumble.", "pt-BR": "Um sócio sênior fecha a porta. Eles sabem que você sabe. A ameaça é aveludada: esqueça o que viu, e sua carreira decola; fale, e seu emprego — e seu patrocínio de visto — somem. Você não pode desmoronar." },
    objective: { en: "Withstand intimidation without committing.", "pt-BR": "Resistir à intimidação sem se comprometer." },
    culturalNote: { en: "For many immigrants a work visa is tied to the employer — losing the job can mean losing the right to stay. That makes whistleblowing terrifyingly high-stakes.", "pt-BR": "Para muitos imigrantes o visto de trabalho está atrelado ao empregador — perder o emprego pode significar perder o direito de ficar. Isso torna denunciar algo aterrorizante." },
    environment: { mood: "hostile", baseNoise: 16 },
    npc: { name: { en: "Senior Partner", "pt-BR": "Sócio Sênior" }, initials: "SP" },
    drills: [{ word: "I need to think carefully", say: "ai níd tu THÍNK KÉR-fu-li", note: { en: "= preciso pensar com cuidado.", "pt-BR": "= preciso pensar com cuidado." } }],
    dialogueSteps: [ { text: "People who stay loyal go far here. People who don't... lose everything. We understand each other?", tr: { en: "A veiled threat — don't fold.", "pt-BR": "Uma ameaça velada — não ceda." }, ear: { en: "<b>“lôu-iâl”</b> = leal", "pt-BR": "<b>“lôu-iâl”</b> = leal" }, audioPrompt: "Senior partner, quiet menace behind a closed door: “People who stay loyal go far here. People who don't... lose everything. We understand each other?”", basic: "I hear you. I need to think carefully.", fluent: "I hear you clearly — this is a lot to take in. I need to think very carefully." } ] },
  { sequence: 313, blockId: 13, indexInBlock: 13, phase: 3, subBlock: "13.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ The Sleepless Choice", "pt-BR": "⚡ A Escolha Sem Sono" },
    contextDescription: { en: "3am on a cold bridge over the Thames, your whole London life in the balance: stay silent and safe, or do the right thing and risk losing everything you built. You voice the decision to your closest friend.", "pt-BR": "3h da manhã numa ponte gelada sobre o Tâmisa, toda a sua vida em Londres na balança: ficar calado e seguro, ou fazer o certo e arriscar perder tudo que construiu. Você verbaliza a decisão ao seu amigo mais próximo." },
    objective: { en: "Resolve to do the right thing despite the cost.", "pt-BR": "Decidir fazer o certo apesar do custo." },
    environment: { mood: "neutral", baseNoise: 34 },
    npc: { name: { en: "Best Friend", "pt-BR": "Melhor Amigo" }, initials: "BF" },
    drills: [{ word: "I have to do what's right", say: "ai rév tu du uâts RÁIT", note: { en: "= eu tenho que fazer o que é certo.", "pt-BR": "= eu tenho que fazer o que é certo." } }],
    dialogueSteps: [ { text: "You could lose your job. Your visa. Everything. Are you sure?", tr: { en: "Stand by your choice.", "pt-BR": "Sustente sua escolha." }, ear: { en: "<b>“uâts RÁIT”</b>", "pt-BR": "<b>“uâts RÁIT”</b>" }, audioPrompt: "Best friend, frightened for you, wind and river under a bridge at night: “You could lose your job. Your visa. Everything. Are you sure?”", basic: "I have to do what's right.", fluent: "I know what it could cost me — but I have to do what's right. I couldn't live with myself otherwise." } ] },
  { sequence: 314, blockId: 13, indexInBlock: 14, phase: 2, subBlock: "13.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ Reporting It", "pt-BR": "⚡ Fazendo a Denúncia" },
    contextDescription: { en: "Hands steady at last, you sit before the regulator's investigator and lay out the fraud, clearly and precisely, in your second language. The bravest English you've ever had to speak.", "pt-BR": "Mãos enfim firmes, você se senta diante do investigador do órgão regulador e expõe a fraude, com clareza e precisão, na sua segunda língua. O inglês mais corajoso que você já precisou falar." },
    objective: { en: "Report wrongdoing clearly to an authority.", "pt-BR": "Relatar a irregularidade com clareza a uma autoridade." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Investigator", "pt-BR": "Investigador" }, initials: "In" },
    drills: [{ word: "I'd like to report", say: "aid láik tu ri-PÔRT", note: { en: "= eu gostaria de relatar/denunciar.", "pt-BR": "= eu gostaria de relatar/denunciar." } }, { word: "I have evidence", say: "ai rév É-vi-dâns", note: { en: "= eu tenho provas.", "pt-BR": "= eu tenho provas." } }],
    dialogueSteps: [ { text: "Take your time. Tell me exactly what you found, from the beginning.", tr: { en: "State the facts clearly.", "pt-BR": "Exponha os fatos com clareza." }, ear: { en: "<b>“ri-PÔRT”</b>", "pt-BR": "<b>“ri-PÔRT”</b>" }, audioPrompt: "Investigator, calm and formal in a quiet office: “Take your time. Tell me exactly what you found, from the beginning.”", basic: "I'd like to report fraud. I have evidence.", fluent: "I'd like to report financial fraud at my firm — and I have the evidence to back it up." } ] },
  { sequence: 315, blockId: 13, indexInBlock: 15, phase: 3, subBlock: "13.3", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ The Fallout", "pt-BR": "⚡ As Consequências" },
    contextDescription: { en: "It's done. You may be jobless, your visa uncertain, the industry whispering your name. But for the first time in weeks, you can breathe. You tell your mentor what you did, and why.", "pt-BR": "Está feito. Você pode estar desempregado, seu visto incerto, o setor sussurrando seu nome. Mas, pela primeira vez em semanas, você consegue respirar. Você conta ao seu mentor o que fez, e por quê." },
    objective: { en: "Own a hard, principled decision with peace.", "pt-BR": "Assumir uma decisão difícil e íntegra com paz." },
    environment: { mood: "pleased", baseNoise: 36 },
    npc: { name: { en: "Mentor", "pt-BR": "Mentor" }, initials: "Me" },
    drills: [{ word: "I can live with it", say: "ai kân LÍV uíd it", note: { en: "= eu consigo conviver com isso.", "pt-BR": "= eu consigo conviver com isso." } }],
    dialogueSteps: [ { text: "You may have just ended your career. Was it worth it?", tr: { en: "Stand at peace with your choice.", "pt-BR": "Fique em paz com sua escolha." }, ear: { en: "<b>“LÍV uíd it”</b>", "pt-BR": "<b>“LÍV uíd it”</b>" }, audioPrompt: "Mentor, grave but admiring on a windy street: “You may have just ended your career. Was it worth it?”", basic: "Maybe. But I can live with it.", fluent: "Maybe I have — but I can live with it. That's worth more than any title." } ] },

  /* 13.4 — THE WEIGHT OF A NAME */
  { sequence: 316, blockId: 13, indexInBlock: 16, phase: 2, subBlock: "13.4", threshold: 80,
    sceneTitle: { en: "The Industry Talks", "pt-BR": "O Setor Comenta" },
    contextDescription: { en: "Word has spread. At a networking event, some avoid you as ‘the one who talks’; others quietly respect you. A blunt acquaintance asks if you regret it. You must own your reputation with dignity.", "pt-BR": "A notícia se espalhou. Num evento de networking, alguns te evitam como ‘aquele que abre a boca’; outros, em silêncio, te respeitam. Um conhecido direto pergunta se você se arrepende. Você precisa assumir sua reputação com dignidade." },
    objective: { en: "Own a controversial reputation with composure.", "pt-BR": "Assumir uma reputação controversa com serenidade." },
    environment: { mood: "hostile", baseNoise: 46 },
    npc: { name: { en: "Acquaintance", "pt-BR": "Conhecido" }, initials: "Ac" },
    drills: [{ word: "I stand by what I did", say: "ai sténd bái uât ai DÍD", note: { en: "= eu mantenho o que fiz.", "pt-BR": "= eu mantenho o que fiz." } }],
    dialogueSteps: [ { text: "Bold move, blowing the whistle. Bet you regret it now, eh?", tr: { en: "Own it without apology.", "pt-BR": "Assuma sem se desculpar." }, ear: { en: "<b>“sténd BÁI”</b>", "pt-BR": "<b>“sténd BÁI”</b>" }, audioPrompt: "Acquaintance, testing you over the hubbub of a networking event: “Bold move, blowing the whistle. Bet you regret it now, eh?”", basic: "No. I stand by what I did.", fluent: "Not for a second — I stand by what I did, and I'd do it again." } ] },
  { sequence: 317, blockId: 13, indexInBlock: 17, phase: 2, subBlock: "13.4", threshold: 80,
    sceneTitle: { en: "The Reference Request", "pt-BR": "O Pedido de Referência" },
    contextDescription: { en: "Job-hunting now, you call a former leader to ask for a reference — not knowing whose side they're on. You must ask plainly and handle whatever answer comes with grace.", "pt-BR": "Em busca de emprego agora, você liga para um ex-líder para pedir uma referência — sem saber de que lado ele está. Você precisa pedir com franqueza e lidar com qualquer resposta com classe." },
    objective: { en: "Ask for a professional reference directly.", "pt-BR": "Pedir uma referência profissional com franqueza." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Former Leader", "pt-BR": "Ex-Líder" }, initials: "FL" },
    drills: [{ word: "would you be willing to", say: "wud iú bi UÍ-ling tu", note: { en: "= você estaria disposto a…", "pt-BR": "= você estaria disposto a…" } }, { word: "vouch for me", say: "VÁUTCH fôr mi", note: { en: "= dar referência por mim / me indicar.", "pt-BR": "= dar referência por mim / me indicar." } }],
    dialogueSteps: [ { text: "After everything... you want ME to be your reference?", tr: { en: "Ask sincerely.", "pt-BR": "Peça com sinceridade." }, ear: { en: "<b>“VÁUTCH fôr mi”</b>", "pt-BR": "<b>“VÁUTCH fôr mi”</b>" }, audioPrompt: "Former leader, surprised on the phone: “After everything... you want ME to be your reference?”", basic: "Would you be willing to vouch for me?", fluent: "I know it's a lot to ask — but would you be willing to vouch for my work?" } ] },
  { sequence: 318, blockId: 13, indexInBlock: 18, phase: 2, subBlock: "13.4", threshold: 80,
    sceneTitle: { en: "The Unexpected Ally", "pt-BR": "O Aliado Inesperado" },
    contextDescription: { en: "A respected industry figure you barely know reaches out: they heard what you did and admired the spine it took. They offer to open doors. You must accept help graciously without grovelling.", "pt-BR": "Uma figura respeitada do setor, que você mal conhece, te procura: ouviu o que você fez e admirou a coragem que exigiu. Ela se oferece para abrir portas. Você precisa aceitar a ajuda com classe, sem se rebaixar." },
    objective: { en: "Accept unexpected support with grace.", "pt-BR": "Aceitar apoio inesperado com elegância." },
    environment: { mood: "pleased", baseNoise: 28 },
    npc: { name: { en: "Industry Figure", "pt-BR": "Figura do Setor" }, initials: "IF" },
    drills: [{ word: "that means a great deal", say: "dét mínz a grêit DÍL", note: { en: "= isso significa muito.", "pt-BR": "= isso significa muito." } }],
    dialogueSteps: [ { text: "We need more people with your backbone. Let me make some calls for you.", tr: { en: "Accept the help warmly.", "pt-BR": "Aceite a ajuda com calor." }, ear: { en: "<b>“BÉK-bôun”</b> = coragem/espinha", "pt-BR": "<b>“BÉK-bôun”</b> = coragem/espinha" }, audioPrompt: "Industry figure, warm and respectful at a quiet table: “We need more people with your backbone. Let me make some calls for you.”", basic: "Thank you. That means a great deal.", fluent: "That genuinely means a great deal — thank you. I won't waste the chance." } ] },
  { sequence: 319, blockId: 13, indexInBlock: 19, phase: 2, subBlock: "13.4", threshold: 80,
    sceneTitle: { en: "The New Interview", "pt-BR": "A Nova Entrevista" },
    contextDescription: { en: "A new employer asks, point-blank, to hear ‘your side’ of the scandal. This interview will turn on how you tell it: not as a victim, not as a hero, but as a professional who chose integrity.", "pt-BR": "Um novo empregador pede, sem rodeios, para ouvir ‘a sua versão’ do escândalo. Esta entrevista vai depender de como você conta: não como vítima, não como herói, mas como um profissional que escolheu a integridade." },
    objective: { en: "Frame a controversy as integrity, not drama.", "pt-BR": "Enquadrar uma controvérsia como integridade, não drama." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Interviewer", "pt-BR": "Entrevistador" }, initials: "Iv" },
    drills: [{ word: "I did what I believed was right", say: "ai díd uât ai bi-LÍVD uâz RÁIT", note: { en: "= fiz o que acreditei ser certo.", "pt-BR": "= fiz o que acreditei ser certo." } }],
    dialogueSteps: [ { text: "Be straight with me — what really happened at your last firm?", tr: { en: "Tell it with calm integrity.", "pt-BR": "Conte com integridade serena." }, ear: { en: "<b>“bi-LÍVD uâz RÁIT”</b>", "pt-BR": "<b>“bi-LÍVD uâz RÁIT”</b>" }, audioPrompt: "Interviewer, direct, leaning forward: “Be straight with me — what really happened at your last firm?”", basic: "I found fraud. I did what I believed was right.", fluent: "I discovered fraud and reported it. It cost me — but I did what I believed was right, and I'd do it again." } ] },
  { sequence: 320, blockId: 13, indexInBlock: 20, phase: 2, subBlock: "13.4", threshold: 80,
    sceneTitle: { en: "The Offer Worth Having", "pt-BR": "A Proposta Que Vale a Pena" },
    contextDescription: { en: "A firm that prizes ethics offers you a role precisely because of what you did. Vindication. You must accept on terms that protect your values this time — clearly stated, not assumed.", "pt-BR": "Uma firma que preza pela ética te oferece um cargo justamente por causa do que você fez. A reparação. Você precisa aceitar em termos que protejam seus valores desta vez — declarados com clareza, não presumidos." },
    objective: { en: "Accept a role on value-aligned terms.", "pt-BR": "Aceitar um cargo em termos alinhados aos seus valores." },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "New Employer", "pt-BR": "Novo Empregador" }, initials: "NE" },
    drills: [{ word: "we're aligned on that", say: "uír â-LÁIND on dét", note: { en: "= estamos alinhados nisso.", "pt-BR": "= estamos alinhados nisso." } }],
    dialogueSteps: [ { text: "We want someone who'll tell us the truth, even when it's hard. That's you.", tr: { en: "Accept, values first.", "pt-BR": "Aceite, valores em primeiro lugar." }, ear: { en: "<b>“â-LÁIND”</b>", "pt-BR": "<b>“â-LÁIND”</b>" }, audioPrompt: "New employer, sincere across the desk: “We want someone who'll tell us the truth, even when it's hard. That's you.”", basic: "Then we're aligned on that. I accept.", fluent: "If honesty is what you want, then we're aligned on what matters most — I accept." } ] },

  /* 13.5 — THE ROAD TAKEN (milestone 325) */
  { sequence: 321, blockId: 13, indexInBlock: 21, phase: 2, subBlock: "13.5", threshold: 80,
    sceneTitle: { en: "A Fresh Start", "pt-BR": "Um Recomeço" },
    contextDescription: { en: "First day at the new firm, introducing yourself to a team that already respects your story. You must set the right tone — humble, warm, and quietly sure of who you are.", "pt-BR": "Primeiro dia na nova firma, se apresentando a um time que já respeita sua história. Você precisa dar o tom certo — humilde, caloroso e tranquilamente seguro de quem você é." },
    objective: { en: "Introduce yourself with quiet confidence.", "pt-BR": "Apresentar-se com confiança serena." },
    environment: { mood: "pleased", baseNoise: 34 },
    npc: { name: { en: "New Team", "pt-BR": "Novo Time" }, initials: "NT" },
    drills: [{ word: "glad to be here", say: "gléd tu bi RÍR", note: { en: "= feliz de estar aqui.", "pt-BR": "= feliz de estar aqui." } }],
    dialogueSteps: [ { text: "So you're the famous one! No pressure, eh? Welcome aboard.", tr: { en: "Set a humble, warm tone.", "pt-BR": "Dê um tom humilde e caloroso." }, ear: { en: "<b>“uí-KÂM â-BÔRD”</b>", "pt-BR": "<b>“uí-KÂM â-BÔRD”</b>" }, audioPrompt: "A new colleague, grinning at your welcome desk: “So you're the famous one! No pressure, eh? Welcome aboard.”", basic: "Ha! Just glad to be here.", fluent: "Famous is a strong word — I'm just glad to be here. Let's do good work together." } ] },
  { sequence: 322, blockId: 13, indexInBlock: 22, phase: 2, subBlock: "13.5", threshold: 80,
    sceneTitle: { en: "Setting the Standard", "pt-BR": "Estabelecendo o Padrão" },
    contextDescription: { en: "A nervous junior quietly asks how you handle pressure to cut corners. Your answer will shape who they become. You must pass on the principle that cost you so much.", "pt-BR": "Um júnior nervoso pergunta baixinho como você lida com a pressão para burlar regras. Sua resposta vai moldar quem ele vai se tornar. Você precisa passar adiante o princípio que te custou tão caro." },
    objective: { en: "Pass on a hard-won principle to a junior.", "pt-BR": "Transmitir um princípio duramente conquistado a um júnior." },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "Junior", "pt-BR": "Júnior" }, initials: "Jr" },
    drills: [{ word: "your name is all you've got", say: "iór nêim iz ól iúv GÓT", note: { en: "= seu nome é tudo que você tem.", "pt-BR": "= seu nome é tudo que você tem." } }],
    dialogueSteps: [ { text: "But what if saying no costs you everything?", tr: { en: "Guide them honestly.", "pt-BR": "Oriente com honestidade." }, ear: { en: "<b>“ól iúv GÓT”</b>", "pt-BR": "<b>“ól iúv GÓT”</b>" }, audioPrompt: "Junior, anxious and sincere by your desk: “But what if saying no costs you everything?”", basic: "Your name is all you've got. Protect it.", fluent: "It might cost you a job — but your name is all you've really got. Protect it, always." } ] },
  { sequence: 323, blockId: 13, indexInBlock: 23, phase: 3, subBlock: "13.5", threshold: 80,
    sceneTitle: { en: "The Vindication", "pt-BR": "A Vindicação" },
    contextDescription: { en: "News breaks: the old firm has been fined and exposed; your report was the turning point. A journalist calls for comment. You must respond with grace, no gloating, only quiet truth.", "pt-BR": "A notícia estoura: a antiga firma foi multada e exposta; sua denúncia foi o ponto de virada. Um jornalista liga para um comentário. Você precisa responder com classe, sem comemorar, só com a verdade serena." },
    objective: { en: "Respond to vindication graciously, no gloating.", "pt-BR": "Responder à vindicação com classe, sem comemorar." },
    environment: { mood: "pleased", baseNoise: 38 },
    npc: { name: { en: "Journalist", "pt-BR": "Jornalista" }, initials: "Jo" },
    drills: [{ word: "I take no pleasure in it", say: "ai têik nôu PLÉ-jâr in it", note: { en: "= não sinto prazer nisso.", "pt-BR": "= não sinto prazer nisso." } }],
    dialogueSteps: [ { text: "You were right all along. Any comment now that they've been fined?", tr: { en: "Stay gracious in victory.", "pt-BR": "Mantenha a classe na vitória." }, ear: { en: "<b>“nôu PLÉ-jâr”</b>", "pt-BR": "<b>“nôu PLÉ-jâr”</b>" }, audioPrompt: "Journalist, eager on the phone amid street noise: “You were right all along. Any comment now that they've been fined?”", basic: "I take no pleasure in it. I just hope clients are safe.", fluent: "I take no pleasure in any of this — I only hope the clients are protected now. That's all I ever wanted." } ] },
  { sequence: 324, blockId: 13, indexInBlock: 24, phase: 2, subBlock: "13.5", threshold: 80,
    sceneTitle: { en: "No Regrets", "pt-BR": "Sem Arrependimentos" },
    contextDescription: { en: "Your mentor, over a celebratory drink, asks if, knowing the price you paid, you'd choose the same road again. You answer from a place of hard-earned peace.", "pt-BR": "Seu mentor, num drinque de comemoração, pergunta se, sabendo o preço que pagou, você escolheria o mesmo caminho de novo. Você responde de um lugar de paz duramente conquistada." },
    objective: { en: "Affirm a principled choice without regret.", "pt-BR": "Afirmar uma escolha íntegra sem arrependimento." },
    environment: { mood: "pleased", baseNoise: 40 },
    npc: { name: { en: "Mentor", "pt-BR": "Mentor" }, initials: "Me" },
    drills: [{ word: "I'd do it all again", say: "aid du it ól â-GUÉN", note: { en: "= eu faria tudo de novo.", "pt-BR": "= eu faria tudo de novo." } }],
    dialogueSteps: [ { text: "Knowing what it cost you — same road again?", tr: { en: "Answer with earned peace.", "pt-BR": "Responda com a paz conquistada." }, ear: { en: "<b>“ól â-GUÉN”</b>", "pt-BR": "<b>“ól â-GUÉN”</b>" }, audioPrompt: "Mentor, raising a glass in a warm pub: “Knowing what it cost you — same road again?”", basic: "Yes. I'd do it all again.", fluent: "Without a doubt — I'd do it all again. Some things are worth more than a paycheque." } ] },
  { sequence: 325, blockId: 13, indexInBlock: 25, phase: 3, subBlock: "13.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "Person of Integrity", tagline: "Person of Integrity — I Chose the Hard Right", shareText: "I found fraud at the top and they offered me everything to stay quiet — my career, my visa, all of it on the line. I spoke anyway. Today I sleep at night. The hard right over the easy wrong. 🇬🇧⚖️ #LinguoBound" },
    sceneTitle: { en: "Bonus — The Hard Right", "pt-BR": "Bônus — O Certo Difícil" },
    contextDescription: { en: "Dusk on the Millennium Bridge, St Paul's glowing gold behind you, the city you fought to belong to laid out below. You risked everything — the job, the visa, the life — on a principle, and you're still standing, lighter than ever. Not the richest road, but the one you can walk with your head high. Take the picture.", "pt-BR": "Entardecer na Millennium Bridge, a Catedral de São Paulo brilhando dourada atrás de você, a cidade pela qual você lutou para pertencer estendida lá embaixo. Você arriscou tudo — o emprego, o visto, a vida — por um princípio, e ainda está de pé, mais leve do que nunca. Não o caminho mais rico, mas o que você pode trilhar de cabeça erguida. Tire a foto." },
    objective: { en: "Celebrate choosing integrity over advancement.", "pt-BR": "Celebrar escolher a integridade em vez da ascensão." },
    environment: { mood: "pleased", baseNoise: 42 },
    npc: { name: { en: "Mentor", "pt-BR": "Mentor" }, initials: "Me" },
    drills: [{ word: "I can hold my head high", say: "ai kân rôuld mai réd RÁI", note: { en: "= posso andar de cabeça erguida.", "pt-BR": "= posso andar de cabeça erguida." }, }],
    dialogueSteps: [
      { text: "You lost a lot. But look at you — you've never stood taller.", tr: { en: "You won what matters.", "pt-BR": "Você ganhou o que importa." }, ear: { en: "<b>“stúd TÓ-lâr”</b>", "pt-BR": "<b>“stúd TÓ-lâr”</b>" }, audioPrompt: "Mentor, proud, golden light on the bridge: “You lost a lot. But look at you — you've never stood taller.”", basic: "I can hold my head high.", fluent: "I lost the easy things — but I can hold my head high. That's everything." },
      { text: "Few people would've done what you did. Remember that.", tr: { en: "Own your courage.", "pt-BR": "Assuma sua coragem." }, ear: { en: "<b>“ri-MÉM-bâr dét”</b>", "pt-BR": "<b>“ri-MÉM-bâr dét”</b>" }, audioPrompt: "Mentor, hand on your shoulder, city glowing: “Few people would've done what you did. Remember that.”", basic: "The hard right over the easy wrong.", fluent: "I'll remember — the hard right over the easy wrong, every single time." },
    ] },
];

export const BLOCK13_BY_SEQUENCE = BLOCK13_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
