/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 10 (Modules 226–250)
 *  "The Professional Peak" — 5 sub-blocks:
 *    10.1 Mentoring a Junior (226–230) coaching, confidence, delegation
 *    10.2 The Big Presentation(231–235) the pitch, a live failure, hostile Qs
 *    10.3 Conflict Resolution (236–240) mediating, saying no to the boss
 *    10.4 Imposter Syndrome   (241–245) the inner fraud, the panic, the reframe
 *    10.5 The Peak            (246–250) recognition, a rival offer, BONUS
 *  Module 250 = "London Leader" milestone selfie.
 * ============================================================ */

export const BLOCK10_MODULES = [
  /* 10.1 — MENTORING A JUNIOR */
  { sequence: 226, blockId: 10, indexInBlock: 1, phase: 2, subBlock: "10.1", threshold: 80,
    sceneTitle: { en: "The Nervous Junior", "pt-BR": "O Júnior Nervoso" },
    contextDescription: { en: "The faint hum of open-plan HVAC. A new hire — terrified, exactly as you once were — hovers at your desk, afraid to ask a ‘stupid’ question. You must put them at ease.", "pt-BR": "O leve zumbido do ar-condicionado do escritório aberto. Um novato — apavorado, como você um dia foi — paira na sua mesa, com medo de fazer uma pergunta ‘boba’. Você precisa deixá-lo à vontade." },
    objective: { en: "Reassure a nervous new colleague.", "pt-BR": "Tranquilizar um colega novo e nervoso." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Junior", "pt-BR": "Júnior" }, initials: "JR" },
    drills: [{ word: "no such thing", say: "nôu sâtch THÍNG", note: { en: "= não existe pergunta boba.", "pt-BR": "= não existe pergunta boba." } }],
    dialogueSteps: [ { text: "Sorry, this is probably a really stupid question, but…", tr: { en: "They're scared to ask — reassure them.", "pt-BR": "Têm medo de perguntar — tranquilize." }, ear: { en: "<b>“STIÚ-pid”</b>", "pt-BR": "<b>“STIÚ-pid”</b>" }, audioPrompt: "Junior, timid over the low office hum: “Sorry, this is probably a really stupid question, but…”", basic: "No such thing. Go on.", fluent: "There's no such thing here — honestly, ask away." } ] },
  { sequence: 227, blockId: 10, indexInBlock: 2, phase: 2, subBlock: "10.1", threshold: 80,
    sceneTitle: { en: "Coaching, Not Telling", "pt-BR": "Orientar, Não Mandar" },
    contextDescription: { en: "They want the answer handed over. The better mentor asks the question back, so they find it themselves. You must guide without simply solving it for them.", "pt-BR": "Eles querem a resposta de bandeja. O bom mentor devolve a pergunta, para que eles mesmos a encontrem. Você precisa guiar sem simplesmente resolver por eles." },
    objective: { en: "Guide with a question, not an answer.", "pt-BR": "Guiar com uma pergunta, não uma resposta." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Junior", "pt-BR": "Júnior" }, initials: "JR" },
    drills: [{ word: "what do you reckon?", say: "uât du iú RÉ-kân", note: { en: "Turn it back to them.", "pt-BR": "Devolva para eles." } }],
    dialogueSteps: [ { text: "So... what should I do? Just tell me.", tr: { en: "They want the answer — coach instead.", "pt-BR": "Querem a resposta — oriente." }, ear: { en: "<b>“RÉ-kân”</b>", "pt-BR": "<b>“RÉ-kân”</b>" }, audioPrompt: "Junior, hoping for a shortcut: “So... what should I do? Just tell me.”", basic: "What do you reckon first?", fluent: "Before I answer — what do you reckon you'd try first?" } ] },
  { sequence: 228, blockId: 10, indexInBlock: 3, phase: 2, subBlock: "10.1", threshold: 80,
    sceneTitle: { en: "Building Confidence", "pt-BR": "Construindo Confiança" },
    contextDescription: { en: "They did well but can't see it, drowning in self-doubt. You must give specific, genuine praise that actually lands — the kind that once changed everything for you.", "pt-BR": "Eles foram bem mas não enxergam, afogados em autocrítica. Você precisa dar um elogio específico e genuíno que realmente pegue — do tipo que um dia mudou tudo para você." },
    objective: { en: "Give specific, confidence-building praise.", "pt-BR": "Dar um elogio específico que construa confiança." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Junior", "pt-BR": "Júnior" }, initials: "JR" },
    drills: [{ word: "you nailed it", say: "iú NÊILD it", note: { en: "= você mandou bem.", "pt-BR": "= você mandou bem." } }],
    dialogueSteps: [ { text: "It was probably rubbish though, wasn't it.", tr: { en: "They doubt themselves — reassure with specifics.", "pt-BR": "Duvidam de si — elogie com detalhes." }, ear: { en: "<b>“RÂ-bish”</b> = ruim", "pt-BR": "<b>“RÂ-bish”</b> = ruim" }, audioPrompt: "Junior, fishing, deflated: “It was probably rubbish though, wasn't it.”", basic: "No — you nailed the analysis.", fluent: "Far from it — you nailed the analysis, that took real skill." } ] },
  { sequence: 229, blockId: 10, indexInBlock: 4, phase: 2, subBlock: "10.1", threshold: 80,
    sceneTitle: { en: "Delegating Real Work", "pt-BR": "Delegando de Verdade" },
    contextDescription: { en: "The leap of trust: handing them something that matters, with your name on the line. You must delegate clearly — the outcome and the trust, not the micromanagement.", "pt-BR": "O salto de confiança: entregar a eles algo que importa, com seu nome em jogo. Você precisa delegar com clareza — o resultado e a confiança, não o microgerenciamento." },
    objective: { en: "Delegate a real task with clear trust.", "pt-BR": "Delegar uma tarefa real com confiança clara." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Junior", "pt-BR": "Júnior" }, initials: "JR" },
    drills: [{ word: "I trust you with this", say: "ai trâst iú uíd dis", note: { en: "Empower them.", "pt-BR": "Dê autonomia." } }],
    dialogueSteps: [ { text: "You want ME to present this to the client?!", tr: { en: "You're trusting them with something big.", "pt-BR": "Você confia algo grande a eles." }, ear: { en: "<b>“pri-ZÉNT”</b>", "pt-BR": "<b>“pri-ZÉNT”</b>" }, audioPrompt: "Junior, stunned: “You want ME to present this to the client?!”", basic: "Yes. I trust you with this.", fluent: "Yes — I trust you with this, and I'll be right beside you." } ] },
  { sequence: 230, blockId: 10, indexInBlock: 5, phase: 2, subBlock: "10.1", threshold: 80,
    sceneTitle: { en: "Their First Win", "pt-BR": "A Primeira Vitória Deles" },
    contextDescription: { en: "They pulled it off and rush to you, glowing. You must celebrate their win and quietly hand them the credit — the truest mark of a leader.", "pt-BR": "Eles conseguiram e correm até você, radiantes. Você precisa celebrar a vitória e, discretamente, entregar a eles os créditos — a marca mais verdadeira de um líder." },
    objective: { en: "Give a mentee full credit for their win.", "pt-BR": "Dar ao aprendiz todo o crédito pela vitória." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Junior", "pt-BR": "Júnior" }, initials: "JR" },
    drills: [{ word: "that was all you", say: "dét uâz ól iú", note: { en: "= o mérito é todo seu.", "pt-BR": "= o mérito é todo seu." } }],
    dialogueSteps: [ { text: "They loved it! I can't believe I did that!", tr: { en: "They succeeded — credit them.", "pt-BR": "Eles conseguiram — dê o crédito." }, ear: { en: "<b>“bi-LÍV”</b>", "pt-BR": "<b>“bi-LÍV”</b>" }, audioPrompt: "Junior, buzzing with pride: “They loved it! I can't believe I did that!”", basic: "That was all you.", fluent: "Believe it — that was all you. I just pointed the way." } ] },

  /* 10.2 — THE BIG PRESENTATION */
  { sequence: 231, blockId: 10, indexInBlock: 6, phase: 2, subBlock: "10.2", threshold: 80,
    sceneTitle: { en: "Opening the Pitch", "pt-BR": "Abrindo o Pitch" },
    contextDescription: { en: "A silent boardroom, a wall of senior clients, your slides queued. Your career narrows to the next ten minutes. You must open with command and warmth.", "pt-BR": "Uma sala silenciosa, uma parede de clientes seniores, seus slides prontos. Sua carreira se afunila nos próximos dez minutos. Você precisa abrir com firmeza e calor." },
    objective: { en: "Open a high-stakes pitch with authority.", "pt-BR": "Abrir um pitch de alto risco com autoridade." },
    environment: { mood: "hostile", baseNoise: 20 },
    npc: { name: { en: "Client Lead", "pt-BR": "Cliente Principal" }, initials: "CL" },
    drills: [{ word: "thank you for your time", say: "TÉNK iú for iór táim", note: { en: "Open graciously.", "pt-BR": "Abra com gentileza." } }],
    dialogueSteps: [ { text: "Right. We've got fifteen minutes. Impress us.", tr: { en: "You have 15 minutes — begin.", "pt-BR": "Você tem 15 minutos — comece." }, ear: { en: "<b>“im-PRÉS âs”</b>", "pt-BR": "<b>“im-PRÉS âs”</b>" }, audioPrompt: "Client lead, brisk in the silent boardroom: “Right. We've got fifteen minutes. Impress us.”", basic: "Thank you. Let's begin.", fluent: "Thank you for your time — let's get straight into it." } ] },
  { sequence: 232, blockId: 10, indexInBlock: 7, phase: 2, subBlock: "10.2", threshold: 80,
    sceneTitle: { en: "The Live Failure", "pt-BR": "A Falha ao Vivo" },
    contextDescription: { en: "Mid-pitch, the demo freezes. The screen dies. Twenty eyes on you, a bead of sweat. You must recover with poise — improvise, hold the room, don't apologise into oblivion.", "pt-BR": "No meio do pitch, o demo trava. A tela morre. Vinte olhos em você, uma gota de suor. Você precisa se recuperar com classe — improvisar, dominar a sala, sem se desculpar até sumir." },
    objective: { en: "Recover gracefully from a live tech failure.", "pt-BR": "Recuperar-se com classe de uma falha técnica ao vivo." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Client Lead", "pt-BR": "Cliente Principal" }, initials: "CL" },
    drills: [{ word: "bear with me", say: "BÉR uíd mi", note: { en: "= aguarde um instante.", "pt-BR": "= aguarde um instante." } }],
    dialogueSteps: [ { text: "...is the screen supposed to be doing that?", tr: { en: "The demo broke — stay calm.", "pt-BR": "O demo quebrou — fique calmo." }, ear: { en: "<b>“bér uíd mi”</b>", "pt-BR": "<b>“bér uíd mi”</b>" }, audioPrompt: "Client lead, eyebrow raised: “...is the screen supposed to be doing that?”", basic: "Bear with me — I'll talk you through it.", fluent: "Bear with me — actually, let me just talk you through it live." } ] },
  { sequence: 233, blockId: 10, indexInBlock: 8, phase: 2, subBlock: "10.2", threshold: 80,
    sceneTitle: { en: "The Hostile Question", "pt-BR": "A Pergunta Hostil" },
    contextDescription: { en: "A sceptical client tries to dismantle your numbers in front of everyone. You must defend your work with calm precision — turning an attack into credibility.", "pt-BR": "Um cliente cético tenta desmontar seus números na frente de todos. Você precisa defender seu trabalho com precisão calma — transformando o ataque em credibilidade." },
    objective: { en: "Defend your work under hostile questioning.", "pt-BR": "Defender seu trabalho sob questionamento hostil." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Sceptical Client", "pt-BR": "Cliente Cético" }, initials: "SC" },
    drills: [{ word: "let me show you why", say: "lét mi shôu iú UÁI", note: { en: "Counter with evidence.", "pt-BR": "Rebata com evidência." } }],
    dialogueSteps: [ { text: "Those numbers can't be right. Where's the proof?", tr: { en: "They challenge your data — defend it.", "pt-BR": "Eles contestam seus dados — defenda." }, ear: { en: "<b>“prúf”</b>", "pt-BR": "<b>“prúf”</b>" }, audioPrompt: "Sceptical client, sharp: “Those numbers can't be right. Where's the proof?”", basic: "They are — let me show you why.", fluent: "They're solid — let me show you exactly where they come from." } ] },
  { sequence: 234, blockId: 10, indexInBlock: 9, phase: 2, subBlock: "10.2", threshold: 80,
    sceneTitle: { en: "Landing It", "pt-BR": "Fechando" },
    contextDescription: { en: "You've won them over; you can feel the room turn. The close: ask for the decision, clearly, without flinching at the silence that follows. Go for the yes.", "pt-BR": "Você os conquistou; dá para sentir a sala virar. O fechamento: peça a decisão, com clareza, sem hesitar no silêncio que vem depois. Vá pelo sim." },
    objective: { en: "Close the pitch and ask for the decision.", "pt-BR": "Fechar o pitch e pedir a decisão." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Client Lead", "pt-BR": "Cliente Principal" }, initials: "CL" },
    drills: [{ word: "shall we make it happen?", say: "shâl ui mêik it RÉ-pân", note: { en: "Close confidently.", "pt-BR": "Feche com confiança." } }],
    dialogueSteps: [ { text: "Hm. You've certainly given us a lot to think about.", tr: { en: "They're impressed — go for the close.", "pt-BR": "Eles gostaram — vá para o fechamento." }, ear: { en: "<b>“SÂR-tân-li”</b>", "pt-BR": "<b>“SÂR-tân-li”</b>" }, audioPrompt: "Client lead, warming, nodding: “Hm. You've certainly given us a lot to think about.”", basic: "So — shall we make it happen?", fluent: "I'm glad — so, shall we make it happen?" } ] },
  { sequence: 235, blockId: 10, indexInBlock: 10, phase: 3, subBlock: "10.2", threshold: 80,
    sceneTitle: { en: "The Aftermath", "pt-BR": "Depois da Tempestade" },
    contextDescription: { en: "Outside, adrenaline draining, your boss claps your shoulder: “They signed.” Months ago you froze ordering coffee; today you closed a six-figure deal in English.", "pt-BR": "Lá fora, a adrenalina baixando, seu chefe bate no seu ombro: “They signed.” Meses atrás você travava pedindo café; hoje você fechou um contrato de seis dígitos em inglês." },
    objective: { en: "Receive the win and share the credit.", "pt-BR": "Receber a vitória e dividir o crédito." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Boss", "pt-BR": "Chefe" }, initials: "BO" },
    drills: [{ word: "team effort", say: "tím É-fârt", note: { en: "= esforço de equipe.", "pt-BR": "= esforço de equipe." } }],
    dialogueSteps: [ { text: "They signed. You absolute star — how do you feel?", tr: { en: "You won the deal!", "pt-BR": "Você fechou o contrato!" }, ear: { en: "<b>“stár”</b>", "pt-BR": "<b>“stár”</b>" }, audioPrompt: "Boss, elated, clapping your shoulder: “They signed. You absolute star — how do you feel?”", basic: "Relieved! Team effort.", fluent: "Honestly relieved — but it was a real team effort." } ] },

  /* 10.3 — CONFLICT RESOLUTION */
  { sequence: 236, blockId: 10, indexInBlock: 11, phase: 2, subBlock: "10.3", threshold: 80,
    sceneTitle: { en: "Two at War", "pt-BR": "Dois em Guerra" },
    contextDescription: { en: "Two of your team members can't stand each other and it's poisoning the work. As their lead, you must call it out and open a hard conversation neither wants.", "pt-BR": "Dois membros da sua equipe não se suportam e isso está contaminando o trabalho. Como líder, você precisa abordar a questão e abrir uma conversa difícil que nenhum dos dois quer." },
    objective: { en: "Open a difficult team conflict directly.", "pt-BR": "Abordar diretamente um conflito de equipe." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Team Member", "pt-BR": "Membro da Equipe" }, initials: "TM" },
    drills: [{ word: "let's clear the air", say: "léts clír di ÉR", note: { en: "= vamos resolver isso.", "pt-BR": "= vamos resolver isso." } }],
    dialogueSteps: [ { text: "I'm not apologising. He started it.", tr: { en: "They're defensive — open dialogue.", "pt-BR": "Estão na defensiva — abra o diálogo." }, ear: { en: "<b>“clír di ér”</b>", "pt-BR": "<b>“clír di ér”</b>" }, audioPrompt: "Team member, arms crossed: “I'm not apologising. He started it.”", basic: "Let's clear the air together.", fluent: "Nobody's blaming anyone — let's just clear the air, all three of us." } ] },
  { sequence: 237, blockId: 10, indexInBlock: 12, phase: 2, subBlock: "10.3", threshold: 80,
    sceneTitle: { en: "The Difficult Stakeholder", "pt-BR": "O Stakeholder Difícil" },
    contextDescription: { en: "A senior stakeholder keeps moving the goalposts and blaming your team. You must manage upward — firm, factual, respectful — without losing them or your dignity.", "pt-BR": "Um stakeholder sênior fica mudando as regras e culpando sua equipe. Você precisa gerenciar para cima — firme, factual, respeitoso — sem perdê-lo nem sua dignidade." },
    objective: { en: "Manage a difficult senior stakeholder.", "pt-BR": "Gerenciar um stakeholder sênior difícil." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Stakeholder", "pt-BR": "Stakeholder" }, initials: "SH" },
    drills: [{ word: "let's align on scope", say: "léts a-LÁIN ón skôup", note: { en: "Reset expectations.", "pt-BR": "Realinhe expectativas." } }],
    dialogueSteps: [ { text: "This isn't what I asked for. Your team's dropped the ball.", tr: { en: "They blame your team — manage up.", "pt-BR": "Culpam sua equipe — gerencie para cima." }, ear: { en: "<b>“drópt dâ ból”</b>", "pt-BR": "<b>“drópt dâ ból”</b>" }, audioPrompt: "Stakeholder, accusatory: “This isn't what I asked for. Your team's dropped the ball.”", basic: "Let's align on the scope.", fluent: "I hear you — let's align on scope, because it shifted twice." } ] },
  { sequence: 238, blockId: 10, indexInBlock: 13, phase: 2, subBlock: "10.3", threshold: 80,
    sceneTitle: { en: "Saying No to the Boss", "pt-BR": "Dizendo Não ao Chefe" },
    contextDescription: { en: "Your boss demands an impossible deadline that would burn out your team. The hardest professional sentence: pushing back, upward, with respect and a real alternative.", "pt-BR": "Seu chefe exige um prazo impossível que esgotaria sua equipe. A frase profissional mais difícil: dizer não, para cima, com respeito e uma alternativa real." },
    objective: { en: "Push back on the boss with an alternative.", "pt-BR": "Dizer não ao chefe com uma alternativa." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Boss", "pt-BR": "Chefe" }, initials: "BO" },
    drills: [{ word: "I can't promise that", say: "ai ként PRÓ-mis dét", note: { en: "Decline honestly.", "pt-BR": "Recuse com honestidade." } }],
    dialogueSteps: [ { text: "I need it by Friday. Make it work.", tr: { en: "An impossible ask — push back.", "pt-BR": "Um pedido impossível — diga não." }, ear: { en: "<b>“PRÓ-mis”</b>", "pt-BR": "<b>“PRÓ-mis”</b>" }, audioPrompt: "Boss, pressuring: “I need it by Friday. Make it work.”", basic: "I can't promise Friday — but Monday, yes.", fluent: "I can't promise Friday without burning the team out — but Monday, properly done, yes." } ] },
  { sequence: 239, blockId: 10, indexInBlock: 14, phase: 2, subBlock: "10.3", threshold: 80,
    sceneTitle: { en: "The Client Crisis", "pt-BR": "A Crise com o Cliente" },
    contextDescription: { en: "A live crisis: an angry client threatening to walk, and all eyes turn to you to defuse it. You must absorb the heat, own the problem, and lay out a fix, fast.", "pt-BR": "Uma crise ao vivo: um cliente furioso ameaçando sair, e todos os olhos se voltam para você desarmar. Você precisa absorver o calor, assumir o problema e apresentar uma solução, rápido." },
    objective: { en: "Defuse an angry client and own the fix.", "pt-BR": "Acalmar um cliente furioso e assumir a solução." },
    environment: { mood: "hostile", baseNoise: 26 },
    npc: { name: { en: "Angry Client", "pt-BR": "Cliente Furioso" }, initials: "AC" },
    drills: [{ word: "here's what we'll do", say: "rírz uât uíl dú", note: { en: "Pivot to a solution.", "pt-BR": "Vá para a solução." } }],
    dialogueSteps: [ { text: "This is a disaster! We're seriously considering leaving.", tr: { en: "They threaten to leave — own it.", "pt-BR": "Ameaçam sair — assuma." }, ear: { en: "<b>“di-ZÁS-târ”</b>", "pt-BR": "<b>“di-ZÁS-târ”</b>" }, audioPrompt: "Angry client, furious on the line: “This is a disaster! We're seriously considering leaving.”", basic: "I understand. Here's what we'll do.", fluent: "I completely understand — and here's exactly what we'll do to fix it." } ] },
  { sequence: 240, blockId: 10, indexInBlock: 15, phase: 2, subBlock: "10.3", threshold: 80,
    sceneTitle: { en: "Rebuilding Trust", "pt-BR": "Reconstruindo a Confiança" },
    contextDescription: { en: "Weeks later, you delivered on every promise. The once-furious client calls back — calmer, even warm. You must accept the reconciliation and cement the relationship.", "pt-BR": "Semanas depois, você cumpriu cada promessa. O cliente antes furioso liga de volta — mais calmo, até caloroso. Você precisa aceitar a reconciliação e cimentar a relação." },
    objective: { en: "Rebuild a damaged client relationship.", "pt-BR": "Reconstruir uma relação abalada com o cliente." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Client", "pt-BR": "Cliente" }, initials: "CL" },
    drills: [{ word: "glad we turned it around", say: "glad ui târnd it a-RÁUND", note: { en: "= que bom que viramos o jogo.", "pt-BR": "= que bom que viramos o jogo." } }],
    dialogueSteps: [ { text: "I'll admit it — you've completely won us back.", tr: { en: "You rebuilt the trust.", "pt-BR": "Você reconstruiu a confiança." }, ear: { en: "<b>“uân âs bék”</b>", "pt-BR": "<b>“uân âs bék”</b>" }, audioPrompt: "Client, warmer now: “I'll admit it — you've completely won us back.”", basic: "Glad we turned it around.", fluent: "That means a lot — I'm really glad we turned it around together." } ] },

  /* 10.4 — IMPOSTER SYNDROME */
  { sequence: 241, blockId: 10, indexInBlock: 16, phase: 2, subBlock: "10.4", threshold: 80,
    sceneTitle: { en: "The Fraud Feeling", "pt-BR": "A Sensação de Fraude" },
    contextDescription: { en: "Alone at your desk after a win, a cold thought creeps in: they'll find out you don't really belong here. A trusted colleague notices your faraway stare and asks.", "pt-BR": "Sozinho na mesa após uma vitória, um pensamento gelado surge: vão descobrir que você não pertence aqui de verdade. Uma colega de confiança nota seu olhar distante e pergunta." },
    objective: { en: "Admit feelings of imposter syndrome.", "pt-BR": "Admitir a síndrome do impostor." },
    culturalNote: { en: "Imposter syndrome hits high-achievers hardest — naming it shrinks it.", "pt-BR": "A síndrome do impostor atinge mais quem se destaca — nomeá-la a diminui." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "CO" },
    drills: [{ word: "like a fraud", say: "láik a FRÓD", note: { en: "= como uma fraude.", "pt-BR": "= como uma fraude." } }],
    dialogueSteps: [ { text: "You okay? You've been miles away since the win.", tr: { en: "They sense something's off.", "pt-BR": "Eles percebem que algo está errado." }, ear: { en: "<b>“fród”</b>", "pt-BR": "<b>“fród”</b>" }, audioPrompt: "Colleague, gentle over the office hum: “You okay? You've been miles away since the win.”", basic: "I feel like a fraud, honestly.", fluent: "Honestly? I keep feeling like a fraud who'll be found out." } ] },
  { sequence: 242, blockId: 10, indexInBlock: 17, phase: 2, subBlock: "10.4", threshold: 80,
    sceneTitle: { en: "The Panic Before", "pt-BR": "O Pânico Antes" },
    contextDescription: { en: "Minutes before a huge moment, your chest tightens, breath shortens — a wave of panic. You must ground yourself with words, talk yourself back from the edge.", "pt-BR": "Minutos antes de um grande momento, o peito aperta, a respiração encurta — uma onda de pânico. Você precisa se ancorar com palavras, se trazer de volta da beira." },
    objective: { en: "Talk yourself through a moment of panic.", "pt-BR": "Acalmar-se num momento de pânico." },
    environment: { mood: "hostile", baseNoise: 20 },
    npc: { name: { en: "Inner Voice", "pt-BR": "Voz Interior" }, initials: "··" },
    drills: [{ word: "I've earned this", say: "aiv ârnd dis", note: { en: "= eu mereci isto.", "pt-BR": "= eu mereci isto." } }],
    dialogueSteps: [ { text: "(your heart pounds) — you're going to blow this...", tr: { en: "Self-doubt attacks — answer it.", "pt-BR": "A autocrítica ataca — responda." }, ear: { en: "<b>“ârnd dis”</b>", "pt-BR": "<b>“ârnd dis”</b>" }, audioPrompt: "An anxious inner voice, fast and shallow: “(your heart pounds) — you're going to blow this...”", basic: "No. I've earned this.", fluent: "Breathe. I've earned this — I've done the work." } ] },
  { sequence: 243, blockId: 10, indexInBlock: 18, phase: 2, subBlock: "10.4", threshold: 80,
    sceneTitle: { en: "The Mentor's Words", "pt-BR": "As Palavras do Mentor" },
    contextDescription: { en: "A senior mentor pulls you aside and says the thing you needed to hear: everyone feels this, and it never fully goes — you just learn to act anyway. Take it in.", "pt-BR": "Um mentor sênior te chama de lado e diz o que você precisava ouvir: todo mundo sente isso, e nunca passa de vez — você só aprende a agir mesmo assim. Absorva." },
    objective: { en: "Receive and accept reassurance from a mentor.", "pt-BR": "Receber e aceitar a reassurança de um mentor." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Mentor", "pt-BR": "Mentor(a)" }, initials: "ME" },
    drills: [{ word: "that helps, thank you", say: "dét rélps, ténk iú", note: { en: "Accept the support.", "pt-BR": "Aceite o apoio." } }],
    dialogueSteps: [ { text: "Everyone feels like that. The good ones just act anyway.", tr: { en: "Reassurance — accept it.", "pt-BR": "Reassurança — aceite." }, ear: { en: "<b>“ÉK-shu-â-li”</b>", "pt-BR": "diga claro" }, audioPrompt: "Mentor, calm and certain: “Everyone feels like that. The good ones just act anyway.”", basic: "That helps. Thank you.", fluent: "I really needed to hear that — thank you, truly." } ] },
  { sequence: 244, blockId: 10, indexInBlock: 19, phase: 2, subBlock: "10.4", threshold: 80,
    sceneTitle: { en: "The Reframe", "pt-BR": "A Ressignificação" },
    contextDescription: { en: "A peer asks how you pulled off the impossible quarter. Instead of deflecting on luck, you must — for once — own your competence out loud. The internal shift made external.", "pt-BR": "Um colega pergunta como você tirou de letra o trimestre impossível. Em vez de desviar para a sorte, você precisa — pela primeira vez — assumir sua competência em voz alta. A virada interna feita externa." },
    objective: { en: "Own your competence out loud.", "pt-BR": "Assumir sua competência em voz alta." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Peer", "pt-BR": "Colega" }, initials: "PE" },
    drills: [{ word: "I worked hard for this", say: "ai uârkt rárd for dis", note: { en: "Claim it.", "pt-BR": "Assuma." } }],
    dialogueSteps: [ { text: "How did you even pull that quarter off? Luck?", tr: { en: "Don't credit luck — own it.", "pt-BR": "Não credite à sorte — assuma." }, ear: { en: "<b>“púl it óf”</b>", "pt-BR": "<b>“púl it óf”</b>" }, audioPrompt: "Peer, half-teasing: “How did you even pull that quarter off? Luck?”", basic: "Not luck — I worked hard.", fluent: "Not luck — I worked hard for this, and I'm proud of it." } ] },
  { sequence: 245, blockId: 10, indexInBlock: 20, phase: 2, subBlock: "10.4", threshold: 80,
    sceneTitle: { en: "Helping Someone Else", "pt-BR": "Ajudando Outra Pessoa" },
    contextDescription: { en: "Your junior confesses they feel like a fraud — your exact words from weeks ago. You pass on the mentor's wisdom. Healing yourself by healing someone else.", "pt-BR": "Seu júnior confessa que se sente uma fraude — exatamente as suas palavras de semanas atrás. Você repassa a sabedoria do mentor. Curando a si mesmo ao curar o outro." },
    objective: { en: "Pass on reassurance to someone struggling.", "pt-BR": "Repassar a reassurança a quem está sofrendo." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Junior", "pt-BR": "Júnior" }, initials: "JR" },
    drills: [{ word: "everyone feels that", say: "É-vri-uân fíls dét", note: { en: "Normalise it.", "pt-BR": "Normalize." } }],
    dialogueSteps: [ { text: "I just feel like I don't belong here, you know?", tr: { en: "They feel like a fraud — reassure them.", "pt-BR": "Sentem-se fraude — tranquilize." }, ear: { en: "<b>“bi-LÓNG”</b>", "pt-BR": "<b>“bi-LÓNG”</b>" }, audioPrompt: "Junior, quietly confessing: “I just feel like I don't belong here, you know?”", basic: "Everyone feels that. You belong.", fluent: "Everyone feels that — I did too. Trust me, you belong here." } ] },

  /* 10.5 — THE PEAK */
  { sequence: 246, blockId: 10, indexInBlock: 21, phase: 3, subBlock: "10.5", threshold: 80,
    sceneTitle: { en: "Addressing the Company", "pt-BR": "Falando para a Empresa" },
    contextDescription: { en: "All-hands meeting, the whole company watching, and you're the one on stage. You must speak to a hall of people in your second language and hold them.", "pt-BR": "Reunião geral, a empresa inteira assistindo, e é você no palco. Você precisa falar para um salão de pessoas no seu segundo idioma e prender a atenção." },
    objective: { en: "Address a large audience confidently.", "pt-BR": "Dirigir-se com confiança a uma grande plateia." },
    environment: { mood: "neutral", baseNoise: 36 },
    npc: { name: { en: "Audience", "pt-BR": "Plateia" }, initials: "AU" },
    drills: [{ word: "I want to start by", say: "ai uânt tu stárt bai", note: { en: "Open a speech.", "pt-BR": "Abrir um discurso." } }],
    dialogueSteps: [ { text: "(the hall hushes, every face turned to you)", tr: { en: "The room is yours — begin.", "pt-BR": "A sala é sua — comece." }, ear: { en: "<b>“stárt bai”</b>", "pt-BR": "<b>“stárt bai”</b>" }, audioPrompt: "A large hall falling silent, a faint crowd murmur settling: “(the hall hushes, every face turned to you)”", basic: "I want to start by saying thank you.", fluent: "I want to start by thanking every one of you — this is our win." } ] },
  { sequence: 247, blockId: 10, indexInBlock: 22, phase: 3, subBlock: "10.5", threshold: 80,
    sceneTitle: { en: "Public Recognition", "pt-BR": "Reconhecimento Público" },
    contextDescription: { en: "An industry award night. Your name is called. Lights, applause, a microphone. You must give a gracious acceptance — humble, warm, sharing the moment.", "pt-BR": "Uma noite de premiação do setor. Seu nome é chamado. Luzes, aplausos, um microfone. Você precisa fazer um agradecimento elegante — humilde, caloroso, dividindo o momento." },
    objective: { en: "Give a gracious award acceptance.", "pt-BR": "Fazer um agradecimento de premiação elegante." },
    environment: { mood: "pleased", baseNoise: 48 },
    npc: { name: { en: "Host", "pt-BR": "Apresentador(a)" }, initials: "HO" },
    drills: [{ word: "I'm genuinely humbled", say: "aim DJÉ-niu-in-li RÂM-bâld", note: { en: "= estou genuinamente honrado.", "pt-BR": "= estou genuinamente honrado." } }],
    dialogueSteps: [ { text: "And the winner is... you! Come on up — a few words!", tr: { en: "You won — give a speech!", "pt-BR": "Você ganhou — discurse!" }, ear: { en: "<b>“RÂM-bâld”</b>", "pt-BR": "<b>“RÂM-bâld”</b>" }, audioPrompt: "Host, to roaring applause and music: “And the winner is... you! Come on up — a few words!”", basic: "I'm genuinely humbled. Thank you!", fluent: "Wow — I'm genuinely humbled. Thank you, and thank you to my team!" } ] },
  { sequence: 248, blockId: 10, indexInBlock: 23, phase: 2, subBlock: "10.5", threshold: 80,
    sceneTitle: { en: "The Rival's Offer", "pt-BR": "A Proposta do Concorrente" },
    contextDescription: { en: "A rival firm comes calling with a glittering offer — more money, a bigger title. You must weigh loyalty against ambition and respond like a leader who knows their worth.", "pt-BR": "Uma empresa concorrente aparece com uma proposta reluzente — mais dinheiro, um cargo maior. Você precisa pesar lealdade contra ambição e responder como um líder que conhece seu valor." },
    objective: { en: "Field a competing job offer with poise.", "pt-BR": "Lidar com uma proposta concorrente com classe." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Rival Recruiter", "pt-BR": "Recrutador Rival" }, initials: "RR" },
    drills: [{ word: "I'm flattered, but", say: "aim FLÉ-târd, bât", note: { en: "Decline gracefully.", "pt-BR": "Recuse com elegância." } }],
    dialogueSteps: [ { text: "We'll beat your salary by twenty percent. Interested?", tr: { en: "A tempting rival offer.", "pt-BR": "Uma proposta tentadora do rival." }, ear: { en: "<b>“FLÉ-târd”</b>", "pt-BR": "<b>“FLÉ-târd”</b>" }, audioPrompt: "Rival recruiter, smooth and confident: “We'll beat your salary by twenty percent. Interested?”", basic: "I'm flattered, but I'm happy here.", fluent: "I'm flattered — but I'm building something real where I am." } ] },
  { sequence: 249, blockId: 10, indexInBlock: 24, phase: 2, subBlock: "10.5", threshold: 80,
    sceneTitle: { en: "Leaving a Legacy", "pt-BR": "Deixando um Legado" },
    contextDescription: { en: "Your boss asks you to design the team's future — to shape something that outlasts you. From a frightened newcomer to the person who defines how things are done.", "pt-BR": "Seu chefe te pede para desenhar o futuro da equipe — moldar algo que vai além de você. De recém-chegado assustado à pessoa que define como as coisas são feitas." },
    objective: { en: "Step into a legacy-shaping role.", "pt-BR": "Assumir um papel que molda um legado." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Boss", "pt-BR": "Chefe" }, initials: "BO" },
    drills: [{ word: "I'd be proud to", say: "aid bi práud tu", note: { en: "= teria orgulho de.", "pt-BR": "= teria orgulho de." } }],
    dialogueSteps: [ { text: "I want you to build the team's future. Will you?", tr: { en: "They want you to lead the vision.", "pt-BR": "Querem que você lidere a visão." }, ear: { en: "<b>“práud tu”</b>", "pt-BR": "<b>“práud tu”</b>" }, audioPrompt: "Boss, sincere: “I want you to build the team's future. Will you?”", basic: "I'd be proud to.", fluent: "I'd be proud to — let's build something that lasts." } ] },
  { sequence: 250, blockId: 10, indexInBlock: 25, phase: 3, subBlock: "10.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "London Leader", tagline: "London Leader — Top of My Game", shareText: "A performance warning a year ago — an industry award tonight. I mentor, I lead, I built a team. I'm a London Leader now, at the top of my game. 🇬🇧📈🏆 #LinguoBound" },
    sceneTitle: { en: "Bonus — Top of the World", "pt-BR": "Bônus — No Topo do Mundo" },
    contextDescription: { en: "A rooftop bar at dusk, the City lights glittering below, your award in hand and your team raising glasses to you. A year ago a warning nearly ended this. Tonight, you're the leader they look up to. Capture it.", "pt-BR": "Um bar no terraço ao anoitecer, as luzes da City brilhando lá embaixo, seu prêmio na mão e sua equipe erguendo as taças para você. Um ano atrás, uma advertência quase encerrou isto. Hoje, você é o líder que eles admiram. Registre." },
    objective: { en: "Celebrate reaching the professional peak.", "pt-BR": "Celebrar ter alcançado o pico profissional." },
    environment: { mood: "pleased", baseNoise: 46 },
    npc: { name: { en: "Your Team", "pt-BR": "Sua Equipe" }, initials: "TE" },
    drills: [{ word: "to the whole team", say: "tu dâ rôul tím", note: { en: "Share the glory.", "pt-BR": "Divida a glória." } }],
    dialogueSteps: [
      { text: "Speech, boss! To the leader who made us believe!", tr: { en: "They toast you as their leader.", "pt-BR": "Brindam a você como líder." }, ear: { en: "<b>“bi-LÍV”</b>", "pt-BR": "<b>“bi-LÍV”</b>" }, audioPrompt: "Your team, glasses raised on the rooftop, City lights below: “Speech, boss! To the leader who made us believe!”", basic: "To the whole team!", fluent: "Not to me — to the whole team. You made this. Cheers!" },
      { text: "You came so far. We're proud of you.", tr: { en: "They're proud of your journey.", "pt-BR": "Têm orgulho da sua jornada." }, ear: { en: "<b>“práud âv iú”</b>", "pt-BR": "<b>“práud âv iú”</b>" }, audioPrompt: "A team member, sincere under the celebration: “You came so far. We're proud of you.”", basic: "Couldn't have done it without you.", fluent: "I came far because of all of you — thank you, really." },
    ] },
];

export const BLOCK10_BY_SEQUENCE = BLOCK10_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
