/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 15 (Modules 351–375)
 *  "Legacy & Influence" — 5 sub-blocks:
 *    15.1 The Inheritance    (351–355) a bereavement, cross-border estate & tax
 *    15.2 The Quiet Power     (356–360) influencing local policy, the long game
 *    15.3 Significant, Not Just Successful (361–365) founding something that outlasts you
 *    15.4 The Mentor's Mantle (366–370) shaping the next generation of leaders
 *    15.5 What You Leave Behind (371–375) legacy — BONUS milestone (375)
 *  Module 375 = "A Lasting Legacy" milestone selfie.
 * ============================================================ */

export const BLOCK15_MODULES = [
  /* 15.1 — THE INHERITANCE */
  { sequence: 351, blockId: 15, indexInBlock: 1, phase: 2, subBlock: "15.1", threshold: 80,
    sceneTitle: { en: "The Solicitor's Letter", "pt-BR": "A Carta do Advogado" },
    contextDescription: { en: "A relative back home has passed, leaving you part of an estate that straddles two countries. In a hushed London solicitor's office, you must grasp the cross-border legal terms through a fog of grief.", "pt-BR": "Um parente lá de casa faleceu, deixando você parte de um espólio que cruza dois países. Num escritório de advocacia londrino, silencioso, você precisa entender os termos jurídicos transfronteiriços através de uma névoa de luto." },
    objective: { en: "Understand cross-border estate terms while grieving.", "pt-BR": "Entender termos de espólio transfronteiriço enquanto está de luto." },
    culturalNote: { en: "‘Probate’ is the UK legal process of dealing with a deceased person's estate — a word you'll hear constantly here.", "pt-BR": "‘Probate’ (inventário) é o processo jurídico britânico de lidar com o espólio de um falecido — uma palavra que você vai ouvir o tempo todo aqui." },
    environment: { mood: "neutral", baseNoise: 16 },
    npc: { name: { en: "Solicitor", "pt-BR": "Advogado" }, initials: "So" },
    drills: [{ word: "could you walk me through it?", say: "cud iú UÓK mi thru it", note: { en: "= dá pra me explicar passo a passo?", "pt-BR": "= dá pra me explicar passo a passo?" } }, { word: "I'm still taking it in", say: "aim stíl TÊI-king it in", note: { en: "= ainda estou processando/absorvendo.", "pt-BR": "= ainda estou processando/absorvendo." } }],
    dialogueSteps: [ { text: "My condolences. The estate must go through probate in both jurisdictions, I'm afraid.", tr: { en: "Ask him to slow down.", "pt-BR": "Peça para ele ir devagar." }, ear: { en: "<b>“UÓK mi thru it”</b>", "pt-BR": "<b>“UÓK mi thru it”</b>" }, audioPrompt: "Solicitor, gentle and formal in a hushed wood-panelled office, a clock ticking: “My condolences. The estate must go through probate in both jurisdictions, I'm afraid.”", basic: "Thank you. Could you walk me through it? I'm still taking it in.", fluent: "Thank you — forgive me, I'm still taking it in. Could you walk me through what probate in both countries actually means?" } ] },
  { sequence: 352, blockId: 15, indexInBlock: 2, phase: 2, subBlock: "15.1", threshold: 80,
    sceneTitle: { en: "The Tax Adviser", "pt-BR": "O Consultor Tributário" },
    contextDescription: { en: "Inheritance tax, double-taxation treaties, domicile status — a tax adviser lays out a maze where one wrong assumption costs a fortune. You must ask precise questions and pin down what you owe, where.", "pt-BR": "Imposto sobre herança, tratados de bitributação, status de domicílio — um consultor tributário expõe um labirinto onde uma suposição errada custa uma fortuna. Você precisa fazer perguntas precisas e definir o que deve, e onde." },
    objective: { en: "Clarify complex cross-border tax obligations.", "pt-BR": "Esclarecer obrigações tributárias transfronteiriças complexas." },
    environment: { mood: "neutral", baseNoise: 18 },
    npc: { name: { en: "Tax Adviser", "pt-BR": "Consultor Tributário" }, initials: "TA" },
    drills: [{ word: "what's my liability here?", say: "uâts mai lái-â-BÍ-li-ti rír", note: { en: "= qual é a minha obrigação/responsabilidade aqui?", "pt-BR": "= qual é a minha obrigação/responsabilidade aqui?" } }],
    dialogueSteps: [ { text: "Under the double-taxation treaty, you won't pay twice — but domicile changes everything.", tr: { en: "Pin down the numbers.", "pt-BR": "Defina os números." }, ear: { en: "<b>“lái-â-BÍ-li-ti”</b>", "pt-BR": "<b>“lái-â-BÍ-li-ti”</b>" }, audioPrompt: "Tax adviser, precise and brisk: “Under the double-taxation treaty, you won't pay twice — but domicile changes everything.”", basic: "So what's my liability here, exactly?", fluent: "Understood — so given my domicile, what's my actual liability here, and what can I do to reduce it legally?" } ] },
  { sequence: 353, blockId: 15, indexInBlock: 3, phase: 3, subBlock: "15.1", threshold: 80,
    sceneTitle: { en: "Dividing It Fairly", "pt-BR": "Dividindo com Justiça" },
    contextDescription: { en: "On a tense call, siblings back home assume you — the one who ‘got rich abroad’ — should take less, or sort everything out. You must navigate family money tension across an ocean, firmly and lovingly.", "pt-BR": "Numa ligação tensa, os irmãos lá de casa presumem que você — o que ‘ficou rico no exterior’ — deveria ficar com menos, ou resolver tudo. Você precisa navegar a tensão familiar por causa de dinheiro através de um oceano, com firmeza e amor." },
    objective: { en: "Handle family money tension fairly and kindly.", "pt-BR": "Lidar com a tensão familiar por dinheiro com justiça e carinho." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Sibling", "pt-BR": "Irmão(ã)" }, initials: "Si" },
    drills: [{ word: "let's keep this fair for everyone", say: "léts kíp dis FÉR fôr ÉV-ri-uân", note: { en: "= vamos manter isso justo para todos.", "pt-BR": "= vamos manter isso justo para todos." } }],
    dialogueSteps: [ { text: "You've got plenty over there. You don't need your share like we do.", tr: { en: "Be fair but don't be steamrolled.", "pt-BR": "Seja justo, mas não se deixe atropelar." }, ear: { en: "<b>“FÉR fôr ÉV-ri-uân”</b>", "pt-BR": "<b>“FÉR fôr ÉV-ri-uân”</b>" }, audioPrompt: "Sibling, resentful and pointed on a crackly call: “You've got plenty over there. You don't need your share like we do.”", basic: "I hear you. But let's keep this fair for everyone.", fluent: "I hear you, and I want to help — but let's keep this fair for everyone, and decide it together, not out of guilt." } ] },
  { sequence: 354, blockId: 15, indexInBlock: 4, phase: 2, subBlock: "15.1", threshold: 80,
    sceneTitle: { en: "The Eulogy", "pt-BR": "O Elogio Fúnebre" },
    contextDescription: { en: "You're asked to give part of the eulogy — in English, for the London friends who never met them, honouring someone from a world away. You must bridge two cultures in one act of remembrance.", "pt-BR": "Pedem que você faça parte do elogio fúnebre — em inglês, para os amigos de Londres que nunca o conheceram, homenageando alguém de um mundo distante. Você precisa unir duas culturas num único ato de lembrança." },
    objective: { en: "Honour the deceased movingly in English.", "pt-BR": "Homenagear o falecido de forma comovente em inglês." },
    environment: { mood: "neutral", baseNoise: 20 },
    npc: { name: { en: "Mourners", "pt-BR": "Enlutados" }, initials: "Mo" },
    drills: [{ word: "they taught me everything", say: "dêi tót mi ÉV-ri-thing", note: { en: "= eles me ensinaram tudo.", "pt-BR": "= eles me ensinaram tudo." } }],
    dialogueSteps: [ { text: "(the room falls silent; faces turn to you, waiting for your words)", tr: { en: "Speak from the heart.", "pt-BR": "Fale do coração." }, ear: { en: "<b>“tót mi ÉV-ri-thing”</b>", "pt-BR": "<b>“tót mi ÉV-ri-thing”</b>" }, audioPrompt: "A hushed memorial room, a single cough, the soft rustle of an order of service as everyone waits for you.", basic: "They taught me everything. I carry them with me here.", fluent: "Most of you never met them — but everything good in me, they taught me. I carried them across an ocean, and I carry them still." } ] },
  { sequence: 355, blockId: 15, indexInBlock: 5, phase: 3, subBlock: "15.1", threshold: 80,
    sceneTitle: { en: "What Money Can't Touch", "pt-BR": "O Que o Dinheiro Não Alcança" },
    contextDescription: { en: "After it's settled, you sit with a friend and reflect: the inheritance changed your bank balance, but it's clarified what actually matters. You articulate a hard-won perspective on wealth and loss.", "pt-BR": "Depois de tudo resolvido, você se senta com um amigo e reflete: a herança mudou seu saldo bancário, mas deixou claro o que de fato importa. Você articula uma perspectiva duramente conquistada sobre riqueza e perda." },
    objective: { en: "Reflect maturely on wealth, loss, and meaning.", "pt-BR": "Refletir com maturidade sobre riqueza, perda e sentido." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "it puts things in perspective", say: "it puts thingz in pâr-SPÉK-tiv", note: { en: "= isso coloca as coisas em perspectiva.", "pt-BR": "= isso coloca as coisas em perspectiva." } }],
    dialogueSteps: [ { text: "You're better off now, money-wise. Does it even feel like it?", tr: { en: "Share what you've learned.", "pt-BR": "Compartilhe o que aprendeu." }, ear: { en: "<b>“pâr-SPÉK-tiv”</b>", "pt-BR": "<b>“pâr-SPÉK-tiv”</b>" }, audioPrompt: "Friend, thoughtful over a quiet drink: “You're better off now, money-wise. Does it even feel like it?”", basic: "Honestly? It just puts things in perspective.", fluent: "Strangely, no — losing them put everything in perspective. Money was never the part that mattered." } ] },

  /* 15.2 — THE QUIET POWER */
  { sequence: 356, blockId: 15, indexInBlock: 6, phase: 2, subBlock: "15.2", threshold: 80,
    sceneTitle: { en: "The Council Lobby", "pt-BR": "O Lobby na Prefeitura" },
    contextDescription: { en: "You request a meeting with a local councillor to push for a small but real policy change — safer crossings near the school. You must make a persuasive, evidence-based case to a busy official.", "pt-BR": "Você solicita uma reunião com um vereador local para defender uma mudança de política pequena, mas real — travessias mais seguras perto da escola. Você precisa fazer um argumento persuasivo e baseado em evidências a um funcionário ocupado." },
    objective: { en: "Lobby an official with a clear, evidenced case.", "pt-BR": "Fazer lobby a um funcionário com um argumento claro e embasado." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Councillor", "pt-BR": "Vereador" }, initials: "Cr" },
    drills: [{ word: "the evidence speaks for itself", say: "di É-vi-dâns spíks fôr it-SÉLF", note: { en: "= a evidência fala por si.", "pt-BR": "= a evidência fala por si." } }],
    dialogueSteps: [ { text: "I've five minutes. Why should this be a council priority?", tr: { en: "Make the case fast and hard.", "pt-BR": "Faça o argumento rápido e forte." }, ear: { en: "<b>“É-vi-dâns”</b>", "pt-BR": "<b>“É-vi-dâns”</b>" }, audioPrompt: "Councillor, glancing at a watch in a municipal office: “I've five minutes. Why should this be a council priority?”", basic: "Three accidents this year. The evidence speaks for itself.", fluent: "Three accidents at that crossing this year alone — the evidence speaks for itself. This is preventable, and cheap to fix." } ] },
  { sequence: 357, blockId: 15, indexInBlock: 7, phase: 2, subBlock: "15.2", threshold: 80,
    sceneTitle: { en: "Building the Coalition", "pt-BR": "Montando a Coalizão" },
    contextDescription: { en: "To move the council, you must unite shopkeepers, parents and a rival residents' group who all want different things. You broker an alliance — finding the shared interest beneath the disagreements.", "pt-BR": "Para mover a prefeitura, você precisa unir lojistas, pais e um grupo de moradores rival que querem coisas diferentes. Você costura uma aliança — encontrando o interesse comum por baixo das divergências." },
    objective: { en: "Unite competing groups around a shared goal.", "pt-BR": "Unir grupos rivais em torno de um objetivo comum." },
    environment: { mood: "hostile", baseNoise: 40 },
    npc: { name: { en: "Rival Group Leader", "pt-BR": "Líder do Grupo Rival" }, initials: "RL" },
    drills: [{ word: "we want the same thing", say: "uí uânt dâ sêim THING", note: { en: "= a gente quer a mesma coisa.", "pt-BR": "= a gente quer a mesma coisa." } }, { word: "let's pool our efforts", say: "léts PÚL aur É-fârts", note: { en: "= vamos juntar nossos esforços.", "pt-BR": "= vamos juntar nossos esforços." } }],
    dialogueSteps: [ { text: "Why would we back YOUR campaign? You never supported ours.", tr: { en: "Find the common ground.", "pt-BR": "Ache o ponto comum." }, ear: { en: "<b>“PÚL aur É-fârts”</b>", "pt-BR": "<b>“PÚL aur É-fârts”</b>" }, audioPrompt: "Rival group leader, defensive in a crowded hall: “Why would we back YOUR campaign? You never supported ours.”", basic: "Because we want the same thing. Let's pool our efforts.", fluent: "Honestly? Because deep down we want the same thing — safer streets. Apart we're noise; together we're a force. Let's pool our efforts." } ] },
  { sequence: 358, blockId: 15, indexInBlock: 8, phase: 3, subBlock: "15.2", threshold: 80,
    sceneTitle: { en: "The Local News Interview", "pt-BR": "A Entrevista no Jornal Local" },
    contextDescription: { en: "A TV reporter thrusts a microphone at you on the street for a soundbite on the campaign. You must deliver a sharp, quotable line under the pressure of a live-ish camera and passing traffic.", "pt-BR": "Uma repórter de TV enfia um microfone na sua cara, na rua, para uma frase de efeito sobre a campanha. Você precisa entregar uma fala afiada e citável sob a pressão de uma câmera quase ao vivo e do trânsito passando." },
    objective: { en: "Deliver a sharp, quotable soundbite on camera.", "pt-BR": "Entregar uma frase de efeito afiada e citável diante da câmera." },
    environment: { mood: "neutral", baseNoise: 58 },
    npc: { name: { en: "TV Reporter", "pt-BR": "Repórter de TV" }, initials: "TV" },
    drills: [{ word: "this is about our children's safety", say: "dis iz â-báut aur TCHÍL-drâns SÊIF-ti", note: { en: "= isto é sobre a segurança das nossas crianças.", "pt-BR": "= isto é sobre a segurança das nossas crianças." } }],
    dialogueSteps: [ { text: "In one sentence — what's your message to the council today?", tr: { en: "Give a punchy line.", "pt-BR": "Dê uma frase de impacto." }, ear: { en: "<b>“TCHÍL-drâns SÊIF-ti”</b>", "pt-BR": "<b>“TCHÍL-drâns SÊIF-ti”</b>" }, audioPrompt: "TV reporter, mic out, camera rolling on a noisy street: “In one sentence — what's your message to the council today?”", basic: "This is about our children's safety. Act now.", fluent: "Simple: this is about our children's safety. The evidence is in, the cost is small — there's no excuse left for delay." } ] },
  { sequence: 359, blockId: 15, indexInBlock: 9, phase: 2, subBlock: "15.2", threshold: 80,
    sceneTitle: { en: "Addressing the Chamber", "pt-BR": "Discursando na Câmara" },
    contextDescription: { en: "You're given three minutes at a full council meeting to make the final case before the vote. In a formal chamber, addressing elected members directly, you must be measured, powerful, and unanswerable.", "pt-BR": "Você ganha três minutos numa reunião plenária da câmara para fazer o argumento final antes da votação. Num plenário formal, dirigindo-se diretamente aos eleitos, você precisa ser ponderado, potente e irrefutável." },
    objective: { en: "Make a formal, persuasive address to officials.", "pt-BR": "Fazer um discurso formal e persuasivo a autoridades." },
    environment: { mood: "neutral", baseNoise: 26 },
    npc: { name: { en: "Council Chair", "pt-BR": "Presidente da Câmara" }, initials: "CC" },
    drills: [{ word: "I urge you to act", say: "ai ÂRDJ iú tu ékt", note: { en: "= eu peço/insisto que vocês ajam.", "pt-BR": "= eu peço/insisto que vocês ajam." } }],
    dialogueSteps: [ { text: "You have three minutes to address the chamber. Begin.", tr: { en: "Be measured and powerful.", "pt-BR": "Seja ponderado e potente." }, ear: { en: "<b>“ai ÂRDJ iú”</b>", "pt-BR": "<b>“ai ÂRDJ iú”</b>" }, audioPrompt: "Council chair, formal, gavel-quiet chamber: “You have three minutes to address the chamber. Begin.”", basic: "Members, the evidence is clear. I urge you to act today.", fluent: "Honourable members — the evidence is clear, the community is united, and the cost of inaction is measured in our children. I urge you to act today." } ] },
  { sequence: 360, blockId: 15, indexInBlock: 10, phase: 3, subBlock: "15.2", threshold: 80,
    sceneTitle: { en: "The Motion Passes", "pt-BR": "A Moção é Aprovada" },
    contextDescription: { en: "The council votes yes. A small policy, a real change, born from your words. Outside, your coalition celebrates; a parent thanks you. You receive the win with humility and pass on the credit.", "pt-BR": "A câmara vota sim. Uma política pequena, uma mudança real, nascida das suas palavras. Lá fora, sua coalizão comemora; um pai te agradece. Você recebe a vitória com humildade e divide o mérito." },
    objective: { en: "Receive a civic victory with humility.", "pt-BR": "Receber uma vitória cívica com humildade." },
    environment: { mood: "pleased", baseNoise: 48 },
    npc: { name: { en: "Grateful Parent", "pt-BR": "Pai Agradecido" }, initials: "GP" },
    drills: [{ word: "we did this together", say: "uí díd dis tu-GÉ-dâr", note: { en: "= nós fizemos isso juntos.", "pt-BR": "= nós fizemos isso juntos." } }],
    dialogueSteps: [ { text: "My kids cross there every day. You may have just saved a life.", tr: { en: "Share the credit.", "pt-BR": "Divida o mérito." }, ear: { en: "<b>“tu-GÉ-dâr”</b>", "pt-BR": "<b>“tu-GÉ-dâr”</b>" }, audioPrompt: "Grateful parent, emotional outside the chamber, coalition cheering: “My kids cross there every day. You may have just saved a life.”", basic: "We did this together. All of us.", fluent: "Don't thank just me — we did this together, every one of us. That's how things actually change." } ] },

  /* 15.3 — SIGNIFICANT, NOT JUST SUCCESSFUL */
  { sequence: 361, blockId: 15, indexInBlock: 11, phase: 2, subBlock: "15.3", threshold: 80,
    sceneTitle: { en: "The Idea Bigger Than You", "pt-BR": "A Ideia Maior Que Você" },
    contextDescription: { en: "You decide to found a charity to help new immigrants — the help you never had. You pitch the vision to a potential co-founder, articulating a mission that's about significance, not success.", "pt-BR": "Você decide fundar uma ONG para ajudar novos imigrantes — a ajuda que você nunca teve. Você apresenta a visão a um possível cofundador, articulando uma missão que é sobre significância, não sucesso." },
    objective: { en: "Articulate a mission-driven vision.", "pt-BR": "Articular uma visão movida por propósito." },
    environment: { mood: "pleased", baseNoise: 28 },
    npc: { name: { en: "Potential Co-Founder", "pt-BR": "Possível Cofundador" }, initials: "CF" },
    drills: [{ word: "something bigger than ourselves", say: "SÂM-thing BÍ-gâr dén aur-SÉLVZ", note: { en: "= algo maior do que nós.", "pt-BR": "= algo maior do que nós." } }],
    dialogueSteps: [ { text: "You're successful already. Why take on all this risk and stress?", tr: { en: "Name the deeper why.", "pt-BR": "Nomeie o porquê mais profundo." }, ear: { en: "<b>“BÍ-gâr dén aur-SÉLVZ”</b>", "pt-BR": "<b>“BÍ-gâr dén aur-SÉLVZ”</b>" }, audioPrompt: "Potential co-founder, intrigued but cautious over coffee: “You're successful already. Why take on all this risk and stress?”", basic: "Because I want to build something bigger than ourselves.", fluent: "Because success stopped being enough. I want to build something bigger than ourselves — something that outlasts us." } ] },
  { sequence: 362, blockId: 15, indexInBlock: 12, phase: 2, subBlock: "15.3", threshold: 80,
    sceneTitle: { en: "Courting the Donor", "pt-BR": "Cortejando o Doador" },
    contextDescription: { en: "In a hushed members' club, you make the ask to a wealthy potential patron over single-malt. You must be confident, not grovelling — selling a vision worthy of their money, eye to eye.", "pt-BR": "Num clube de sócios silencioso, você faz o pedido a um possível patrono rico, em torno de um single malt. Você precisa ser confiante, não bajulador — vendendo uma visão digna do dinheiro dele, olho no olho." },
    objective: { en: "Make a confident funding ask to a major donor.", "pt-BR": "Fazer um pedido de financiamento confiante a um grande doador." },
    environment: { mood: "neutral", baseNoise: 18 },
    npc: { name: { en: "Potential Patron", "pt-BR": "Possível Patrono" }, initials: "Pn" },
    drills: [{ word: "I'm not asking for charity", say: "aim nót Á-skin fôr TCHÁ-ri-ti", note: { en: "= não estou pedindo esmola.", "pt-BR": "= não estou pedindo esmola." } }, { word: "I'm offering you a legacy", say: "aim Ó-fâ-rin iú a LÉ-gâ-si", note: { en: "= estou te oferecendo um legado.", "pt-BR": "= estou te oferecendo um legado." } }],
    dialogueSteps: [ { text: "Everyone wants my money. Why should I give it to your cause?", tr: { en: "Sell the vision, not pity.", "pt-BR": "Venda a visão, não a pena." }, ear: { en: "<b>“LÉ-gâ-si”</b>", "pt-BR": "<b>“LÉ-gâ-si”</b>" }, audioPrompt: "Potential patron, sipping whisky in a hushed leather-bound club: “Everyone wants my money. Why should I give it to your cause?”", basic: "I'm not asking for charity. I'm offering you a legacy.", fluent: "I'm not asking for charity — I'm offering you a legacy. Your name on something that changes thousands of lives. That's the real return." } ] },
  { sequence: 363, blockId: 15, indexInBlock: 13, phase: 2, subBlock: "15.3", threshold: 80,
    sceneTitle: { en: "Hiring Your First Team", "pt-BR": "Contratando Sua Primeira Equipe" },
    contextDescription: { en: "Interviewing your charity's first employees, you must judge character and conviction, not just CVs. You ask the question that reveals whether someone truly believes in the mission.", "pt-BR": "Entrevistando os primeiros funcionários da sua ONG, você precisa avaliar caráter e convicção, não só currículos. Você faz a pergunta que revela se alguém acredita de verdade na missão." },
    objective: { en: "Interview for conviction, not just credentials.", "pt-BR": "Entrevistar buscando convicção, não só credenciais." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Candidate", "pt-BR": "Candidato" }, initials: "Ca" },
    drills: [{ word: "why does this matter to you?", say: "uái dâz dis MÉ-târ tu iú", note: { en: "= por que isso importa para você?", "pt-BR": "= por que isso importa para você?" } }],
    dialogueSteps: [ { text: "I have ten years of NGO experience and a first-class degree.", tr: { en: "Look past the CV.", "pt-BR": "Olhe além do currículo." }, ear: { en: "<b>“MÉ-târ tu iú”</b>", "pt-BR": "<b>“MÉ-târ tu iú”</b>" }, audioPrompt: "Candidate, polished and rehearsed across the desk: “I have ten years of NGO experience and a first-class degree.”", basic: "That's impressive. But why does this matter to you?", fluent: "Your CV is impressive — but tell me something it doesn't show: why does helping immigrants actually matter to you?" } ] },
  { sequence: 364, blockId: 15, indexInBlock: 14, phase: 2, subBlock: "15.3", threshold: 80,
    sceneTitle: { en: "The First Family Helped", "pt-BR": "A Primeira Família Ajudada" },
    contextDescription: { en: "Your charity helps its first family — terrified, just arrived, exactly as you once were. They thank you in broken English, and the full weight of what you've built lands. You respond with grace.", "pt-BR": "Sua ONG ajuda sua primeira família — aterrorizada, recém-chegada, exatamente como você um dia esteve. Eles agradecem num inglês quebrado, e todo o peso do que você construiu te atinge. Você responde com elegância." },
    objective: { en: "Receive heartfelt thanks from those you set out to help.", "pt-BR": "Receber agradecimentos sinceros de quem você se propôs a ajudar." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Helped Family", "pt-BR": "Família Ajudada" }, initials: "HF" },
    drills: [{ word: "you're not alone here", say: "iór nót â-LÔUN rír", note: { en: "= você não está sozinho aqui.", "pt-BR": "= você não está sozinho aqui." } }],
    dialogueSteps: [ { text: "Thank you... we have nobody else. You give us hope.", tr: { en: "Reassure them warmly.", "pt-BR": "Tranquilize-os com calor." }, ear: { en: "<b>“â-LÔUN rír”</b>", "pt-BR": "<b>“â-LÔUN rír”</b>" }, audioPrompt: "Helped family, emotional, mother's voice breaking: “Thank you... we have nobody else. You give us hope.”", basic: "You're not alone here. We've got you.", fluent: "You're not alone here anymore — I promise you that. I was once exactly where you are. We've got you now." } ] },
  { sequence: 365, blockId: 15, indexInBlock: 15, phase: 3, subBlock: "15.3", threshold: 80,
    sceneTitle: { en: "Significant, Not Just Successful", "pt-BR": "Significativo, Não Só Bem-Sucedido" },
    contextDescription: { en: "A journalist profiling your charity asks what changed — why you pivoted from chasing success to building significance. You articulate the shift that defines this whole chapter of your life.", "pt-BR": "Uma jornalista, fazendo um perfil da sua ONG, pergunta o que mudou — por que você virou a chave de buscar sucesso para construir significância. Você articula a virada que define todo este capítulo da sua vida." },
    objective: { en: "Articulate the shift from success to significance.", "pt-BR": "Articular a virada do sucesso para a significância." },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "Journalist", "pt-BR": "Jornalista" }, initials: "Jo" },
    drills: [{ word: "success is what you get", say: "sâk-SÉS iz uât iú GUÉT", note: { en: "= sucesso é o que você recebe.", "pt-BR": "= sucesso é o que você recebe." } }, { word: "significance is what you give", say: "sig-NÍ-fi-câns iz uât iú GUÍV", note: { en: "= significância é o que você dá.", "pt-BR": "= significância é o que você dá." } }],
    dialogueSteps: [ { text: "You had it all — the career, the home. Why give so much of it away?", tr: { en: "Define the shift.", "pt-BR": "Defina a virada." }, ear: { en: "<b>“sig-NÍ-fi-câns”</b>", "pt-BR": "<b>“sig-NÍ-fi-câns”</b>" }, audioPrompt: "Journalist, recorder running, genuinely curious: “You had it all — the career, the home. Why give so much of it away?”", basic: "Success is what you get. Significance is what you give.", fluent: "I learned a simple thing: success is what you get — significance is what you give. I'd had enough of just getting." } ] },

  /* 15.4 — THE MENTOR'S MANTLE */
  { sequence: 366, blockId: 15, indexInBlock: 16, phase: 2, subBlock: "15.4", threshold: 80,
    sceneTitle: { en: "The Keynote Invitation", "pt-BR": "O Convite para a Palestra" },
    contextDescription: { en: "A university invites you to give a keynote to graduating students on building a life from nothing in a foreign land. You accept, and discuss with the organiser the message worth leaving them.", "pt-BR": "Uma universidade te convida para dar a palestra principal a formandos sobre construir uma vida do zero em terra estrangeira. Você aceita e discute com o organizador a mensagem que vale a pena deixar para eles." },
    objective: { en: "Shape the core message of a keynote.", "pt-BR": "Moldar a mensagem central de uma palestra." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Event Organiser", "pt-BR": "Organizador do Evento" }, initials: "EO" },
    drills: [{ word: "I want to leave them with", say: "ai uânt tu LÍV dém uíd", note: { en: "= quero deixá-los com (uma ideia).", "pt-BR": "= quero deixá-los com (uma ideia)." } }],
    dialogueSteps: [ { text: "These students are about to face the world. What's the one thing you'll tell them?", tr: { en: "Distil your wisdom.", "pt-BR": "Destile sua sabedoria." }, ear: { en: "<b>“LÍV dém uíd”</b>", "pt-BR": "<b>“LÍV dém uíd”</b>" }, audioPrompt: "Event organiser, warm in a quiet faculty office: “These students are about to face the world. What's the one thing you'll tell them?”", basic: "I want to leave them with this: fear is not a stop sign.", fluent: "If I leave them with one thing, it's this: fear isn't a stop sign — it's just the price of doing something that matters." } ] },
  { sequence: 367, blockId: 15, indexInBlock: 17, phase: 2, subBlock: "15.4", threshold: 80,
    sceneTitle: { en: "The Keynote", "pt-BR": "A Palestra" },
    contextDescription: { en: "A vast, hushed auditorium. Hundreds of faces, a spotlight, your voice the only sound. The newcomer who once couldn't order a coffee now holds a hall in the palm of their hand. Deliver the opening.", "pt-BR": "Um auditório vasto e silencioso. Centenas de rostos, um holofote, sua voz o único som. O recém-chegado que um dia não sabia pedir um café agora segura uma plateia na palma da mão. Entregue a abertura." },
    objective: { en: "Open a major keynote with command and warmth.", "pt-BR": "Abrir uma grande palestra com domínio e calor." },
    environment: { mood: "pleased", baseNoise: 20 },
    npc: { name: { en: "The Audience", "pt-BR": "A Plateia" }, initials: "Au" },
    drills: [{ word: "let me take you back", say: "lét mi têik iú BÉK", note: { en: "= deixem-me levá-los de volta (no tempo).", "pt-BR": "= deixem-me levá-los de volta (no tempo)." } }],
    dialogueSteps: [ { text: "(the spotlight finds you; the auditorium goes utterly silent)", tr: { en: "Open with command.", "pt-BR": "Abra com domínio." }, ear: { en: "<b>“têik iú BÉK”</b>", "pt-BR": "<b>“têik iú BÉK”</b>" }, audioPrompt: "A vast auditorium settling into total silence, a faint mic hum, one distant cough, then nothing — all eyes on you.", basic: "Let me take you back to a man who couldn't say hello.", fluent: "Let me take you back years — to a terrified man in this city who couldn't even say ‘hello’. That man was me. And here we are." } ] },
  { sequence: 368, blockId: 15, indexInBlock: 18, phase: 2, subBlock: "15.4", threshold: 80,
    sceneTitle: { en: "The Hard Question", "pt-BR": "A Pergunta Difícil" },
    contextDescription: { en: "In the Q&A, a sharp student challenges you: isn't your success just luck and privilege dressed up as grit? You must answer honestly — acknowledging luck without erasing the work. No defensiveness.", "pt-BR": "No Q&A, um estudante afiado te desafia: o seu sucesso não é só sorte e privilégio fantasiados de garra? Você precisa responder com honestidade — reconhecendo a sorte sem apagar o trabalho. Sem ficar na defensiva." },
    objective: { en: "Answer a challenging question with honest nuance.", "pt-BR": "Responder a uma pergunta desafiadora com honestidade e nuance." },
    environment: { mood: "hostile", baseNoise: 28 },
    npc: { name: { en: "Sharp Student", "pt-BR": "Estudante Afiado" }, initials: "SS" },
    drills: [{ word: "you're not wrong", say: "iór nót RÓNG", note: { en: "= você não está errado.", "pt-BR": "= você não está errado." } }, { word: "luck and work both matter", say: "lâk ând uârk bôuth MÉ-târ", note: { en: "= sorte e trabalho, ambos importam.", "pt-BR": "= sorte e trabalho, ambos importam." } }],
    dialogueSteps: [ { text: "With respect — isn't this just luck and privilege you're calling hard work?", tr: { en: "Answer with honest nuance.", "pt-BR": "Responda com honestidade e nuance." }, ear: { en: "<b>“iór nót RÓNG”</b>", "pt-BR": "<b>“iór nót RÓNG”</b>" }, audioPrompt: "Sharp student, challenging into a mic from the crowd: “With respect — isn't this just luck and privilege you're calling hard work?”", basic: "You're not wrong. Luck and work both matter.", fluent: "You're not wrong — luck was real, and I'll never pretend otherwise. But luck and work both matter. The trick is being ready when luck finally shows up." } ] },
  { sequence: 369, blockId: 15, indexInBlock: 19, phase: 3, subBlock: "15.4", threshold: 80,
    sceneTitle: { en: "The Student Who Stays Behind", "pt-BR": "O Estudante Que Fica Para Trás" },
    contextDescription: { en: "After the talk, a single nervous student lingers — a new immigrant, on the edge of quitting, who saw their own story in yours. This quiet moment matters more than the whole speech. You give them what they need.", "pt-BR": "Depois da palestra, um único estudante nervoso fica para trás — um novo imigrante, à beira de desistir, que viu a própria história na sua. Este momento silencioso importa mais que a palestra inteira. Você dá a ele o que ele precisa." },
    objective: { en: "Give private encouragement to one struggling soul.", "pt-BR": "Dar incentivo particular a uma alma em apuros." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Nervous Student", "pt-BR": "Estudante Nervoso" }, initials: "NS" },
    drills: [{ word: "your story isn't over", say: "iór STÓ-ri Í-zânt ÔU-vâr", note: { en: "= sua história não acabou.", "pt-BR": "= sua história não acabou." } }],
    dialogueSteps: [ { text: "I was going to drop out tomorrow. I just... I don't think I'm strong enough.", tr: { en: "Lift them, one to one.", "pt-BR": "Levante-o, de um para um." }, ear: { en: "<b>“Í-zânt ÔU-vâr”</b>", "pt-BR": "<b>“Í-zânt ÔU-vâr”</b>" }, audioPrompt: "Nervous student, voice barely audible in an emptying hall: “I was going to drop out tomorrow. I just... I don't think I'm strong enough.”", basic: "Listen to me. Your story isn't over.", fluent: "Hey — look at me. I felt exactly that, more than once. Your story isn't over; it's barely begun. Don't you dare quit tomorrow." } ] },
  { sequence: 370, blockId: 15, indexInBlock: 20, phase: 2, subBlock: "15.4", threshold: 80,
    sceneTitle: { en: "Passing On the Mantle", "pt-BR": "Passando o Manto" },
    contextDescription: { en: "Your own first mentor, now elderly, tells you it's time you became to others what they were to you. A torch-passing conversation between two generations. You accept the mantle with gratitude.", "pt-BR": "Seu próprio primeiro mentor, agora idoso, te diz que chegou a hora de você ser para os outros o que ele foi para você. Uma conversa de passagem de bastão entre duas gerações. Você aceita o manto com gratidão." },
    objective: { en: "Accept the role of mentor-elder with gratitude.", "pt-BR": "Aceitar o papel de mentor-mais-velho com gratidão." },
    environment: { mood: "pleased", baseNoise: 18 },
    npc: { name: { en: "Old Mentor", "pt-BR": "Antigo Mentor" }, initials: "OM" },
    drills: [{ word: "I owe so much of this to you", say: "ai ôu sôu mâtch âv dis tu IÚ", note: { en: "= devo muito disso a você.", "pt-BR": "= devo muito disso a você." } }],
    dialogueSteps: [ { text: "My time guiding people is ending. Yours is just beginning. Carry it well.", tr: { en: "Accept with gratitude.", "pt-BR": "Aceite com gratidão." }, ear: { en: "<b>“ai ôu sôu mâtch”</b>", "pt-BR": "<b>“ai ôu sôu mâtch”</b>" }, audioPrompt: "Old mentor, frail but warm, hand on yours: “My time guiding people is ending. Yours is just beginning. Carry it well.”", basic: "I owe so much of this to you. I'll carry it well.", fluent: "I owe so much of who I am to you — I'll carry it well, I promise. And one day I'll pass it on, just like you did." } ] },

  /* 15.5 — WHAT YOU LEAVE BEHIND (milestone 375) */
  { sequence: 371, blockId: 15, indexInBlock: 21, phase: 2, subBlock: "15.5", threshold: 80,
    sceneTitle: { en: "The Award", "pt-BR": "O Prêmio" },
    contextDescription: { en: "You're given a civic honour for your work — a medal, a citation, applause from a city that once felt like a locked door. At the podium you must accept with grace and turn the spotlight outward.", "pt-BR": "Você recebe uma honraria cívica pelo seu trabalho — uma medalha, uma menção, aplausos de uma cidade que um dia parecia uma porta trancada. No pódio, você precisa aceitar com elegância e voltar o holofote para fora." },
    objective: { en: "Accept a public honour graciously.", "pt-BR": "Aceitar uma honraria pública com elegância." },
    environment: { mood: "pleased", baseNoise: 40 },
    npc: { name: { en: "Presenter", "pt-BR": "Apresentador" }, initials: "Pr" },
    drills: [{ word: "I accept this on behalf of", say: "ai ék-SÉPT dis on bi-RÁF âv", note: { en: "= aceito isto em nome de.", "pt-BR": "= aceito isto em nome de." } }],
    dialogueSteps: [ { text: "For outstanding service to this community — the award goes to you. A few words?", tr: { en: "Turn the light outward.", "pt-BR": "Vire a luz para fora." }, ear: { en: "<b>“on bi-RÁF âv”</b>", "pt-BR": "<b>“on bi-RÁF âv”</b>" }, audioPrompt: "Presenter, grand, to applause in a formal hall: “For outstanding service to this community — the award goes to you. A few words?”", basic: "I accept this on behalf of every newcomer who never gave up.", fluent: "I accept this not for me, but on behalf of every frightened newcomer who refused to give up. This is theirs as much as mine." } ] },
  { sequence: 372, blockId: 15, indexInBlock: 22, phase: 3, subBlock: "15.5", threshold: 80,
    sceneTitle: { en: "The Street With Your Mark", "pt-BR": "A Rua Com Sua Marca" },
    contextDescription: { en: "You walk past the safer crossing you fought for, kids using it daily, and the charity centre with its lights on. Tangible proof your words reshaped a corner of the city. You reflect aloud with a friend.", "pt-BR": "Você passa pela travessia mais segura pela qual lutou, com crianças usando-a todo dia, e o centro da ONG com as luzes acesas. Prova tangível de que suas palavras remodelaram um canto da cidade. Você reflete em voz alta com um amigo." },
    objective: { en: "Reflect on tangible, lasting impact.", "pt-BR": "Refletir sobre um impacto tangível e duradouro." },
    environment: { mood: "pleased", baseNoise: 44 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "it'll outlive me", say: "itl áut-LÍV mi", note: { en: "= isso vai me sobreviver.", "pt-BR": "= isso vai me sobreviver." } }],
    dialogueSteps: [ { text: "That crossing, that centre... none of it existed before you. How does that feel?", tr: { en: "Take in your legacy.", "pt-BR": "Absorva seu legado." }, ear: { en: "<b>“áut-LÍV mi”</b>", "pt-BR": "<b>“áut-LÍV mi”</b>" }, audioPrompt: "Friend, proud, walking past the new crossing in street noise: “That crossing, that centre... none of it existed before you. How does that feel?”", basic: "Strange. It'll outlive me. That's the point.", fluent: "Honestly? Humbling. That crossing, that centre — they'll outlive me. And that's exactly the point." } ] },
  { sequence: 373, blockId: 15, indexInBlock: 23, phase: 2, subBlock: "15.5", threshold: 80,
    sceneTitle: { en: "Teaching Them to Lead", "pt-BR": "Ensinando-os a Liderar" },
    contextDescription: { en: "You're deliberately stepping back so others can lead the charity. A protégé panics at the responsibility. You must empower them to fly — the hardest, most generous act of a true leader.", "pt-BR": "Você está deliberadamente se afastando para que outros liderem a ONG. Um protegido entra em pânico com a responsabilidade. Você precisa empoderá-lo para voar — o ato mais difícil e generoso de um verdadeiro líder." },
    objective: { en: "Empower a successor to lead in your place.", "pt-BR": "Empoderar um sucessor a liderar no seu lugar." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Protégé", "pt-BR": "Protegido" }, initials: "Pg" },
    drills: [{ word: "I trust you completely", say: "ai trâst iú câm-PLÍT-li", note: { en: "= confio em você completamente.", "pt-BR": "= confio em você completamente." } }],
    dialogueSteps: [ { text: "But what if I get it wrong? Everyone's counting on me now.", tr: { en: "Empower them to fly.", "pt-BR": "Empodere-o para voar." }, ear: { en: "<b>“câm-PLÍT-li”</b>", "pt-BR": "<b>“câm-PLÍT-li”</b>" }, audioPrompt: "Protégé, overwhelmed and frightened: “But what if I get it wrong? Everyone's counting on me now.”", basic: "You'll get some things wrong. That's fine. I trust you completely.", fluent: "You'll get things wrong — we all do, that's how you grow. But I trust you completely. It's your turn to lead now." } ] },
  { sequence: 374, blockId: 15, indexInBlock: 24, phase: 3, subBlock: "15.5", threshold: 80,
    sceneTitle: { en: "From Survival to Significance", "pt-BR": "Da Sobrevivência à Significância" },
    contextDescription: { en: "A documentary maker asks you to sum up the whole journey — from a man who couldn't say ‘yes’ on a plane to a force that reshaped a community. You must articulate the full arc with hard-won clarity.", "pt-BR": "Um documentarista pede que você resuma toda a jornada — de um homem que não conseguia dizer ‘sim’ num avião a uma força que remodelou uma comunidade. Você precisa articular o arco completo com clareza duramente conquistada." },
    objective: { en: "Summarise an entire life-arc with clarity.", "pt-BR": "Resumir um arco de vida inteiro com clareza." },
    environment: { mood: "pleased", baseNoise: 20 },
    npc: { name: { en: "Documentary Maker", "pt-BR": "Documentarista" }, initials: "DM" },
    drills: [{ word: "it started with one word: yes", say: "it STÁR-tâd uíd uân uârd: iés", note: { en: "= começou com uma palavra: sim.", "pt-BR": "= começou com uma palavra: sim." } }],
    dialogueSteps: [ { text: "From silent on a plane to all of this. How do you even sum that up?", tr: { en: "Name the whole arc.", "pt-BR": "Nomeie o arco inteiro." }, ear: { en: "<b>“STÁR-tâd uíd uân uârd”</b>", "pt-BR": "<b>“STÁR-tâd uíd uân uârd”</b>" }, audioPrompt: "Documentary maker, camera rolling, quiet studio: “From silent on a plane to all of this. How do you even sum that up?”", basic: "It started with one word: yes. Everything grew from there.", fluent: "Honestly? It started with one terrified word on a plane — ‘yes’. Survival became belonging, belonging became significance. It all grew from one yes." } ] },
  { sequence: 375, blockId: 15, indexInBlock: 25, phase: 3, subBlock: "15.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "A Lasting Legacy", tagline: "A Lasting Legacy — I Reshaped a Corner of London", shareText: "I arrived unable to say ‘yes’. Now there's a safer crossing my words won at the council, a charity I built for newcomers, and a generation I mentor. Not just successful — significant. I leave a mark on this city. 🇬🇧🏛️ #LinguoBound" },
    sceneTitle: { en: "Bonus — The Mark You Leave", "pt-BR": "Bônus — A Marca Que Você Deixa" },
    contextDescription: { en: "Golden hour on the South Bank, the river ablaze, the city you reshaped glowing behind you. A medal in your pocket, a charity bearing your vision, a crossing that keeps children safe, a generation that calls you mentor. You came with nothing and no words — and you leave a mark that will outlast you. Step into the light. Take the picture.", "pt-BR": "Hora dourada no South Bank, o rio em chamas, a cidade que você remodelou brilhando atrás de você. Uma medalha no bolso, uma ONG carregando sua visão, uma travessia que mantém crianças seguras, uma geração que te chama de mentor. Você chegou sem nada e sem palavras — e deixa uma marca que vai te sobreviver. Entre na luz. Tire a foto." },
    objective: { en: "Celebrate building a lasting legacy in the city.", "pt-BR": "Celebrar construir um legado duradouro na cidade." },
    environment: { mood: "pleased", baseNoise: 46 },
    npc: { name: { en: "Old Mentor", "pt-BR": "Antigo Mentor" }, initials: "OM" },
    drills: [{ word: "I gave more than I took", say: "ai guêiv môr dén ai TÚK", note: { en: "The measure of a significant life.", "pt-BR": "A medida de uma vida significativa." }, }],
    dialogueSteps: [
      { text: "You didn't just survive this city. You changed it. Forever.", tr: { en: "Take in the legacy.", "pt-BR": "Absorva o legado." }, ear: { en: "<b>“tchêindjd it”</b>", "pt-BR": "<b>“tchêindjd it”</b>" }, audioPrompt: "Old mentor, proud, golden light off the Thames: “You didn't just survive this city. You changed it. Forever.”", basic: "I gave more than I took. That's enough.", fluent: "I didn't just take from this city — in the end, I gave more than I took. That's all I ever wanted." },
      { text: "What will they remember you for, do you think?", tr: { en: "Name your legacy.", "pt-BR": "Nomeie seu legado." }, ear: { en: "<b>“ri-MÉM-bâr iú fôr”</b>", "pt-BR": "<b>“ri-MÉM-bâr iú fôr”</b>" }, audioPrompt: "Old mentor, gently, river glowing behind: “What will they remember you for, do you think?”", basic: "That I left it better than I found it.", fluent: "Not the titles or the money — just this: that I left this city a little better than I found it." },
    ] },
];

export const BLOCK15_BY_SEQUENCE = BLOCK15_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
