/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 06 (Modules 126–150)
 *  "The Professional Integration" — 5 sub-blocks:
 *    6.1 Office Politics     (126–130) emails, meetings, the tea round
 *    6.2 Networking Dinner   (131–135) small talk, cards, the bill
 *    6.3 The Salary Review   (136–140) feedback, negotiating a raise
 *    6.4 Performance Warning (141–145) the dreaded 1:1, defending yourself
 *    6.5 Leading & Belonging (146–150) running meetings, BONUS milestone
 *  Module 150 = "Office Insider" milestone selfie.
 * ============================================================ */

export const BLOCK06_MODULES = [
  /* 6.1 — OFFICE POLITICS */
  { sequence: 126, blockId: 6, indexInBlock: 1, phase: 2, subBlock: "6.1", threshold: 80,
    sceneTitle: { en: "The Passive-Aggressive Email", "pt-BR": "O E-mail Passivo-Agressivo" },
    contextDescription: { en: "Open-plan silence, only keyboards clicking. An email lands: “Per my last email…” — a polite knife. A colleague swivels to ask if you saw it.", "pt-BR": "Silêncio do escritório aberto, só teclados clicando. Chega um e-mail: “Per my last email…” — uma facada educada. Um colega se vira para perguntar se você viu." },
    objective: { en: "Decode and respond to corporate passive-aggression.", "pt-BR": "Decodificar e responder à passivo-agressividade corporativa." },
    culturalNote: { en: "‘Per my last email’ = you ignored me. ‘As discussed’ = I'm covering myself.", "pt-BR": "‘Per my last email’ = você me ignorou. ‘As discussed’ = estou me resguardando." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "CO" },
    drills: [{ word: "leave it with me", say: "lív it uíd mi", note: { en: "= deixa comigo.", "pt-BR": "= deixa comigo." } }],
    dialogueSteps: [ { text: "Did you see Sara's email? Bit pointed, wasn't it.", tr: { en: "That email was a dig — did you catch it?", "pt-BR": "Aquele e-mail foi uma indireta — você pegou?" }, ear: { en: "<b>“PÓIN-tid”</b> = direto/cortante", "pt-BR": "<b>“PÓIN-tid”</b> = cortante" }, audioPrompt: "Colleague, low, conspiratorial in the quiet office: “Did you see Sara's email? Bit pointed, wasn't it.”", basic: "I saw it. Leave it with me.", fluent: "I saw it — bit much. I'll handle it, leave it with me." } ] },
  { sequence: 127, blockId: 6, indexInBlock: 2, phase: 2, subBlock: "6.1", threshold: 80,
    sceneTitle: { en: "Talked Over in the Meeting", "pt-BR": "Atropelado na Reunião" },
    contextDescription: { en: "You start to speak; a louder colleague rolls right over you and takes your point as theirs. You must reclaim the floor — calmly, firmly, in a second language.", "pt-BR": "Você começa a falar; um colega mais alto te atropela e assume sua ideia como dele. Você precisa retomar a palavra — com calma e firmeza, num segundo idioma." },
    objective: { en: "Reclaim the floor without aggression.", "pt-BR": "Retomar a palavra sem agressividade." },
    environment: { mood: "hostile", baseNoise: 30 },
    npc: { name: { en: "Loud Colleague", "pt-BR": "Colega Falante" }, initials: "LC" },
    drills: [{ word: "if I could just finish", say: "if ai kud djâst FÍ-nish", note: { en: "Reclaim politely.", "pt-BR": "Retome com educação." } }],
    dialogueSteps: [ { text: "—so what I think we should do is—", tr: { en: "He's hijacking your point — cut back in.", "pt-BR": "Ele está roubando sua ideia — retome." }, ear: { en: "<b>“FÍ-nish”</b>", "pt-BR": "<b>“FÍ-nish”</b>" }, audioPrompt: "Loud colleague, steamrolling: “—so what I think we should do is—”", basic: "Sorry, if I could just finish.", fluent: "Sorry to jump in — if I could just finish my point." } ] },
  { sequence: 128, blockId: 6, indexInBlock: 3, phase: 2, subBlock: "6.1", threshold: 80,
    sceneTitle: { en: "The Tea Round", "pt-BR": "A Rodada de Chá" },
    contextDescription: { en: "A colleague stands: “Anyone for a brew?” The office tea round is a sacred ritual of belonging. Get your order right — and offer to do the next one.", "pt-BR": "Um colega levanta: “Anyone for a brew?” A rodada de chá do escritório é um ritual sagrado de pertencimento. Acerte seu pedido — e ofereça-se para a próxima." },
    objective: { en: "Participate in the office tea round.", "pt-BR": "Participar da rodada de chá do escritório." },
    culturalNote: { en: "‘A brew’ = a cup of tea. Knowing everyone's order = belonging. Milk? Sugar?", "pt-BR": "‘A brew’ = uma xícara de chá. Saber o pedido de todos = pertencer. Leite? Açúcar?" },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "CO" },
    drills: [{ word: "milk, no sugar", say: "mílk, nôu SHÚ-gâr", note: { en: "The classic order.", "pt-BR": "O pedido clássico." } }],
    dialogueSteps: [ { text: "Anyone for a brew? How d'you take it?", tr: { en: "Want tea? How do you like it?", "pt-BR": "Quer chá? Como você toma?" }, ear: { en: "<b>“brú”</b> = chá", "pt-BR": "<b>“brú”</b> = chá" }, audioPrompt: "Colleague, mug in hand: “Anyone for a brew? How d'you take it?”", basic: "Milk, no sugar. Cheers.", fluent: "Milk, no sugar, please — and I'll get the next round." } ] },
  { sequence: 129, blockId: 6, indexInBlock: 4, phase: 2, subBlock: "6.1", threshold: 80,
    sceneTitle: { en: "Office Gossip", "pt-BR": "Fofoca de Escritório" },
    contextDescription: { en: "By the kettle, a colleague leans in with gossip about the boss. Join in and you risk it spreading; stay aloof and you stay an outsider. Walk the line.", "pt-BR": "Perto da chaleira, um colega se aproxima com uma fofoca sobre o chefe. Entrar na onda é arriscado; ficar de fora te mantém estrangeiro. Equilibre-se." },
    objective: { en: "Navigate gossip without committing.", "pt-BR": "Navegar a fofoca sem se comprometer." },
    environment: { mood: "neutral", baseNoise: 28 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "CO" },
    drills: [{ word: "I couldn't say", say: "ai KÚ-dânt sêi", note: { en: "Diplomatic non-answer.", "pt-BR": "Não-resposta diplomática." } }],
    dialogueSteps: [ { text: "Have you heard about the boss? Between us…", tr: { en: "Gossip incoming — be careful.", "pt-BR": "Vem fofoca — cuidado." }, ear: { en: "<b>“bi-TUÍN âs”</b>", "pt-BR": "<b>“bi-TUÍN âs”</b>" }, audioPrompt: "Colleague, hushed by the kettle: “Have you heard about the boss? Between us…”", basic: "Ooh, I couldn't say.", fluent: "Ha — I couldn't say, I try to stay out of it." } ] },
  { sequence: 130, blockId: 6, indexInBlock: 5, phase: 2, subBlock: "6.1", threshold: 80,
    sceneTitle: { en: "Covering for Someone", "pt-BR": "Cobrindo um Colega" },
    contextDescription: { en: "A teammate is drowning and quietly asks you to cover a task with the boss. Saying yes builds an ally; saying it wrong exposes you both.", "pt-BR": "Um colega está afundando e discretamente te pede para cobrir uma tarefa com o chefe. Dizer sim cria um aliado; dizer errado expõe os dois." },
    objective: { en: "Offer to help a colleague tactfully.", "pt-BR": "Oferecer ajuda a um colega com tato." },
    environment: { mood: "neutral", baseNoise: 26 },
    npc: { name: { en: "Teammate", "pt-BR": "Colega de Equipe" }, initials: "TM" },
    drills: [{ word: "I've got your back", say: "aiv gót iór BÉK", note: { en: "= te dou cobertura.", "pt-BR": "= te dou cobertura." } }],
    dialogueSteps: [ { text: "I'm swamped. Could you cover the report?", tr: { en: "Can you cover this for me?", "pt-BR": "Você cobre isso para mim?" }, ear: { en: "<b>“suómpt”</b> = atolado", "pt-BR": "<b>“suómpt”</b> = atolado" }, audioPrompt: "Teammate, stressed and quiet: “I'm swamped. Could you cover the report?”", basic: "Sure. I've got your back.", fluent: "Course — I've got your back, send it over." } ] },

  /* 6.2 — NETWORKING DINNER */
  { sequence: 131, blockId: 6, indexInBlock: 6, phase: 3, subBlock: "6.2", threshold: 80,
    sceneTitle: { en: "Working the Room", "pt-BR": "Circulando no Evento" },
    contextDescription: { en: "An industry dinner: clinking glasses, a roar of confident chatter, strangers in blazers. You must break into a circle and introduce yourself smoothly.", "pt-BR": "Um jantar do setor: taças tilintando, um rugido de conversas confiantes, estranhos de blazer. Você precisa entrar num grupo e se apresentar com naturalidade." },
    objective: { en: "Introduce yourself at a networking event.", "pt-BR": "Apresentar-se num evento de networking." },
    environment: { mood: "neutral", baseNoise: 50 },
    npc: { name: { en: "Industry Peer", "pt-BR": "Colega de Setor" }, initials: "IP" },
    drills: [{ word: "mind if I join you?", say: "máind if ai DJÓIN iú", note: { en: "Break into a group.", "pt-BR": "Entrar num grupo." } }],
    dialogueSteps: [ { text: "...and that's when the whole launch went sideways—oh, hello!", tr: { en: "They notice you — introduce yourself.", "pt-BR": "Eles te notam — apresente-se." }, ear: { en: "<b>“SÁID-uêis”</b> = deu errado", "pt-BR": "<b>“SÁID-uêis”</b> = deu errado" }, audioPrompt: "Peer, mid-story, turning to you over the dinner roar: “...and that's when the whole launch went sideways—oh, hello!”", basic: "Hi! Mind if I join you?", fluent: "Hi — sounds dramatic! Mind if I join you?" } ] },
  { sequence: 132, blockId: 6, indexInBlock: 7, phase: 3, subBlock: "6.2", threshold: 80,
    sceneTitle: { en: "The Card Exchange", "pt-BR": "A Troca de Cartões" },
    contextDescription: { en: "“What is it you do, exactly?” The pitch under social pressure — interesting, not boastful. Then the smooth offer to swap details.", "pt-BR": "“What is it you do, exactly?” O pitch sob pressão social — interessante, sem se gabar. Depois, a oferta fluida de trocar contatos." },
    objective: { en: "Pitch your work and exchange contacts.", "pt-BR": "Apresentar seu trabalho e trocar contatos." },
    environment: { mood: "neutral", baseNoise: 48 },
    npc: { name: { en: "Industry Peer", "pt-BR": "Colega de Setor" }, initials: "IP" },
    drills: [{ word: "let's connect", say: "léts cô-NÉKT", note: { en: "= vamos nos conectar.", "pt-BR": "= vamos nos conectar." } }],
    dialogueSteps: [ { text: "So what is it you do, exactly?", tr: { en: "What's your work?", "pt-BR": "Com o que você trabalha?" }, ear: { en: "<b>“ig-ZÉKT-li”</b>", "pt-BR": "<b>“ig-ZÉKT-li”</b>" }, audioPrompt: "Peer, genuinely curious: “So what is it you do, exactly?”", basic: "I design products. Let's connect.", fluent: "I design products — we should connect, here's my card." } ] },
  { sequence: 133, blockId: 6, indexInBlock: 8, phase: 3, subBlock: "6.2", threshold: 80,
    sceneTitle: { en: "Talking Shop", "pt-BR": "Falando de Trabalho" },
    contextDescription: { en: "The conversation deepens into industry talk full of buzzwords and acronyms. You must keep up, contribute a sharp opinion, and not get lost.", "pt-BR": "A conversa aprofunda no jargão do setor, cheio de buzzwords e siglas. Você precisa acompanhar, dar uma opinião afiada e não se perder." },
    objective: { en: "Hold your own in industry shop-talk.", "pt-BR": "Manter-se firme no papo técnico do setor." },
    environment: { mood: "neutral", baseNoise: 47 },
    npc: { name: { en: "Industry Peer", "pt-BR": "Colega de Setor" }, initials: "IP" },
    drills: [{ word: "I'd push back on that", say: "aid PÚSH bék ón dét", note: { en: "Politely disagree.", "pt-BR": "Discordar com educação." } }],
    dialogueSteps: [ { text: "AI will replace half these roles in a year, surely?", tr: { en: "A bold opinion — give yours.", "pt-BR": "Uma opinião ousada — dê a sua." }, ear: { en: "<b>“SHÚR-li”</b>", "pt-BR": "<b>“SHÚR-li”</b>" }, audioPrompt: "Peer, provocative over dinner noise: “AI will replace half these roles in a year, surely?”", basic: "I'd push back on that.", fluent: "I'd push back on that — it'll change roles, not erase them." } ] },
  { sequence: 134, blockId: 6, indexInBlock: 9, phase: 3, subBlock: "6.2", threshold: 80,
    sceneTitle: { en: "Splitting the Bill", "pt-BR": "Dividindo a Conta" },
    contextDescription: { en: "The bill lands and the awkward maths begins. Someone barely ate; someone had wine. You must navigate the British bill-split without seeming stingy.", "pt-BR": "A conta chega e começa a matemática constrangedora. Um mal comeu; outro bebeu vinho. Você navega a divisão sem parecer pão-duro." },
    objective: { en: "Handle splitting a group bill fairly.", "pt-BR": "Lidar com a divisão de uma conta em grupo." },
    culturalNote: { en: "‘Shall we just split it?’ is common — but offer to pay your extra if you had more.", "pt-BR": "‘Shall we just split it?’ é comum — mas ofereça pagar o seu a mais se consumiu mais." },
    environment: { mood: "neutral", baseNoise: 44 },
    npc: { name: { en: "Industry Peer", "pt-BR": "Colega de Setor" }, initials: "IP" },
    drills: [{ word: "shall we split it?", say: "shâl ui SPLÍT it", note: { en: "Propose splitting.", "pt-BR": "Propor dividir." } }],
    dialogueSteps: [ { text: "Right, the bill. How shall we do this?", tr: { en: "How do we split the bill?", "pt-BR": "Como dividimos a conta?" }, ear: { en: "<b>“rau shâl ui dú dis”</b>", "pt-BR": "<b>“rau shâl ui dú dis”</b>" }, audioPrompt: "Peer, eyeing the bill: “Right, the bill. How shall we do this?”", basic: "Shall we split it evenly?", fluent: "Shall we just split it evenly? Easiest, isn't it." } ] },
  { sequence: 135, blockId: 6, indexInBlock: 10, phase: 2, subBlock: "6.2", threshold: 80,
    sceneTitle: { en: "Following Up", "pt-BR": "Dando Retorno" },
    contextDescription: { en: "Next morning, a follow-up message from last night's contact: “Great to meet you — coffee sometime?” Convert a chat into a real connection.", "pt-BR": "Na manhã seguinte, uma mensagem do contato de ontem: “Great to meet you — coffee sometime?” Transforme um papo em uma conexão real." },
    objective: { en: "Reply to a networking follow-up.", "pt-BR": "Responder a um follow-up de networking." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "New Contact", "pt-BR": "Novo Contato" }, initials: "NC" },
    drills: [{ word: "I'd love to", say: "aid LÂV tu", note: { en: "Warm, keen yes.", "pt-BR": "Sim caloroso e interessado." } }],
    dialogueSteps: [ { text: "Great to meet you last night — coffee sometime?", tr: { en: "Let's meet for coffee.", "pt-BR": "Vamos tomar um café." }, ear: { en: "<b>“SÂM-taim”</b>", "pt-BR": "<b>“SÂM-taim”</b>" }, audioPrompt: "New contact, voice note, warm: “Great to meet you last night — coffee sometime?”", basic: "I'd love to. When?", fluent: "I'd love to — how's next week looking for you?" } ] },

  /* 6.3 — THE SALARY REVIEW */
  { sequence: 136, blockId: 6, indexInBlock: 11, phase: 2, subBlock: "6.3", threshold: 80,
    sceneTitle: { en: "The Self-Assessment", "pt-BR": "A Autoavaliação" },
    contextDescription: { en: "Review season. First you must write — and then say aloud — what you've achieved, without the cultural cringe of self-praise. Own your wins.", "pt-BR": "Época de avaliação. Primeiro você precisa escrever — e depois dizer em voz alta — o que conquistou, sem o constrangimento cultural de se elogiar. Assuma suas vitórias." },
    objective: { en: "State your achievements with confidence.", "pt-BR": "Declarar suas conquistas com confiança." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "I delivered", say: "ai di-LÍ-vârd", note: { en: "Own your results.", "pt-BR": "Assuma seus resultados." } }],
    dialogueSteps: [ { text: "Talk me through your highlights this year.", tr: { en: "What were your wins?", "pt-BR": "Quais foram suas vitórias?" }, ear: { en: "<b>“RÁI-laits”</b>", "pt-BR": "<b>“RÁI-laits”</b>" }, audioPrompt: "Manager, pen ready in a quiet room: “Talk me through your highlights this year.”", basic: "I delivered three big projects.", fluent: "I delivered three major projects, two ahead of schedule." } ] },
  { sequence: 137, blockId: 6, indexInBlock: 12, phase: 2, subBlock: "6.3", threshold: 80,
    sceneTitle: { en: "Taking Feedback", "pt-BR": "Recebendo Feedback" },
    contextDescription: { en: "“There's one area to work on…” Criticism, delivered in the British sandwich. You must take it gracefully without crumbling or getting defensive.", "pt-BR": "“There's one area to work on…” Crítica, servida no sanduíche britânico. Receba com elegância, sem desabar nem ficar na defensiva." },
    objective: { en: "Receive criticism gracefully.", "pt-BR": "Receber crítica com elegância." },
    environment: { mood: "hostile", baseNoise: 24 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "that's fair", say: "déts FÉR", note: { en: "Accept feedback maturely.", "pt-BR": "Aceitar feedback com maturidade." } }],
    dialogueSteps: [ { text: "One area to work on is your communication.", tr: { en: "A gentle criticism — accept it.", "pt-BR": "Uma crítica leve — aceite-a." }, ear: { en: "<b>“cô-miu-ni-KÊI-shân”</b>", "pt-BR": "<b>“cô-miu-ni-KÊI-shân”</b>" }, audioPrompt: "Manager, measured: “One area to work on is your communication.”", basic: "That's fair. I'll work on it.", fluent: "That's fair — I'll focus on it, thanks for being direct." } ] },
  { sequence: 138, blockId: 6, indexInBlock: 13, phase: 2, subBlock: "6.3", threshold: 80,
    sceneTitle: { en: "Making the Ask", "pt-BR": "Fazendo o Pedido" },
    contextDescription: { en: "The moment. You must ask for a raise — naming a real number, holding the silence that follows, not flinching. The hardest sentence yet.", "pt-BR": "O momento. Você precisa pedir um aumento — dizendo um número real, sustentando o silêncio que vem depois, sem hesitar. A frase mais difícil até agora." },
    objective: { en: "Ask for a specific raise and hold firm.", "pt-BR": "Pedir um aumento específico e manter-se firme." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "I'd like to discuss", say: "aid láik tu dis-KÂS", note: { en: "Open the negotiation.", "pt-BR": "Abrir a negociação." } }],
    dialogueSteps: [ { text: "Anything else you wanted to raise?", tr: { en: "Your opening to ask for more.", "pt-BR": "Sua deixa para pedir mais." }, ear: { en: "<b>“rêiz”</b> = levantar/aumento", "pt-BR": "<b>“rêiz”</b> = levantar/aumento" }, audioPrompt: "Manager, wrapping up: “Anything else you wanted to raise?”", basic: "Yes — I'd like to discuss my pay.", fluent: "Yes — given my results, I'd like to discuss a raise to fifty." } ] },
  { sequence: 139, blockId: 6, indexInBlock: 14, phase: 2, subBlock: "6.3", threshold: 80,
    sceneTitle: { en: "The Counteroffer", "pt-BR": "A Contraproposta" },
    contextDescription: { en: "“I can't do fifty, but I could stretch to forty-six plus a bonus.” The dance. You must weigh it, push gently once more, or accept with grace.", "pt-BR": "“I can't do fifty, but I could stretch to forty-six plus a bonus.” A dança. Você pesa, empurra uma vez mais com jeito, ou aceita com elegância." },
    objective: { en: "Negotiate a counteroffer.", "pt-BR": "Negociar uma contraproposta." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "could we meet halfway?", say: "kud ui mít RÁF-uêi", note: { en: "Propose a middle ground.", "pt-BR": "Propor um meio-termo." } }],
    dialogueSteps: [ { text: "I could stretch to forty-six plus a bonus.", tr: { en: "Their counteroffer — respond.", "pt-BR": "A contraproposta deles — responda." }, ear: { en: "<b>“strétch tu”</b>", "pt-BR": "<b>“strétch tu”</b>" }, audioPrompt: "Manager: “I could stretch to forty-six plus a bonus.”", basic: "Could we meet at forty-eight?", fluent: "Could we meet halfway at forty-eight? Then we're agreed." } ] },
  { sequence: 140, blockId: 6, indexInBlock: 15, phase: 2, subBlock: "6.3", threshold: 80,
    sceneTitle: { en: "Sealing the Deal", "pt-BR": "Fechando o Acordo" },
    contextDescription: { en: "You got the rise. Close it like a professional: gratitude without grovelling, and a clear note to put it in writing.", "pt-BR": "Você conseguiu o aumento. Encerre como profissional: gratidão sem bajulação e um pedido claro para formalizar por escrito." },
    objective: { en: "Close a negotiation and confirm in writing.", "pt-BR": "Fechar a negociação e confirmar por escrito." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "in writing", say: "in RÁI-tin", note: { en: "= por escrito.", "pt-BR": "= por escrito." } }],
    dialogueSteps: [ { text: "Forty-eight it is. Glad we sorted it.", tr: { en: "Deal agreed at 48.", "pt-BR": "Acordo fechado em 48." }, ear: { en: "<b>“sÓR-tid”</b>", "pt-BR": "<b>“sÓR-tid”</b>" }, audioPrompt: "Manager, satisfied: “Forty-eight it is. Glad we sorted it.”", basic: "Thank you. In writing?", fluent: "Thank you — could you confirm it in writing?" } ] },

  /* 6.4 — PERFORMANCE WARNING */
  { sequence: 141, blockId: 6, indexInBlock: 16, phase: 2, subBlock: "6.4", threshold: 80,
    sceneTitle: { en: "“Have You Got a Minute?”", "pt-BR": "“Tem um Minutinho?”" },
    contextDescription: { en: "The five words that freeze every employee. Your manager, unsmiling, books a side room. Something's wrong. You must stay composed walking in.", "pt-BR": "As cinco palavras que gelam qualquer funcionário. Seu gestor, sério, reserva uma salinha. Algo está errado. Você precisa manter a compostura ao entrar." },
    objective: { en: "Stay composed entering a serious 1:1.", "pt-BR": "Manter a compostura ao entrar numa conversa séria." },
    culturalNote: { en: "‘Have you got a minute?’ + a booked room rarely means good news.", "pt-BR": "‘Have you got a minute?’ + sala reservada raramente é boa notícia." },
    environment: { mood: "hostile", baseNoise: 20 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "of course", say: "âv CÓRS", note: { en: "Composed agreement.", "pt-BR": "Concordância serena." } }],
    dialogueSteps: [ { text: "Have you got a minute? In private.", tr: { en: "We need to talk privately.", "pt-BR": "Precisamos conversar a sós." }, ear: { en: "<b>“in PRÁI-vât”</b>", "pt-BR": "<b>“in PRÁI-vât”</b>" }, audioPrompt: "Manager, grave, in near-silence: “Have you got a minute? In private.”", basic: "Of course.", fluent: "Of course — everything okay?" } ] },
  { sequence: 142, blockId: 6, indexInBlock: 17, phase: 2, subBlock: "6.4", threshold: 80,
    sceneTitle: { en: "The Warning", "pt-BR": "A Advertência" },
    contextDescription: { en: "“We've had some concerns about your performance.” The floor drops. You must listen, not panic, and not over-apologise yourself into deeper trouble.", "pt-BR": "“We've had some concerns about your performance.” O chão some. Você precisa ouvir, não entrar em pânico, e não se desculpar tanto a ponto de piorar." },
    objective: { en: "Absorb a performance warning calmly.", "pt-BR": "Absorver uma advertência com calma." },
    environment: { mood: "hostile", baseNoise: 20 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "I understand", say: "ai ãn-dâr-STÉND", note: { en: "Acknowledge, don't grovel.", "pt-BR": "Reconheça, sem se rebaixar." } }],
    dialogueSteps: [ { text: "We've had concerns about your performance.", tr: { en: "There are concerns about your work.", "pt-BR": "Há preocupações com seu desempenho." }, ear: { en: "<b>“cân-SÂRNS”</b>", "pt-BR": "<b>“cân-SÂRNS”</b>" }, audioPrompt: "Manager, serious and quiet: “We've had concerns about your performance.”", basic: "I understand. Can you explain?", fluent: "I understand — could you tell me specifically what's concerned you?" } ] },
  { sequence: 143, blockId: 6, indexInBlock: 18, phase: 2, subBlock: "6.4", threshold: 80,
    sceneTitle: { en: "Standing Your Ground", "pt-BR": "Defendendo-se" },
    contextDescription: { en: "Some of it isn't fair — context was missing. You must defend yourself respectfully, with facts, in a second language, under emotional pressure.", "pt-BR": "Parte disso é injusta — faltou contexto. Você precisa se defender com respeito, com fatos, num segundo idioma, sob pressão emocional." },
    objective: { en: "Defend yourself with facts, respectfully.", "pt-BR": "Defender-se com fatos, respeitosamente." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "with respect,", say: "uíd ris-PÉKT", note: { en: "Disagree professionally.", "pt-BR": "Discordar com profissionalismo." } }],
    dialogueSteps: [ { text: "The deadline was missed, plain and simple.", tr: { en: "They blame you — give context.", "pt-BR": "Eles te culpam — dê o contexto." }, ear: { en: "<b>“DÉD-lain”</b>", "pt-BR": "<b>“DÉD-lain”</b>" }, audioPrompt: "Manager, firm: “The deadline was missed, plain and simple.”", basic: "With respect, the brief changed.", fluent: "With respect, the brief changed twice — I flagged the risk early." } ] },
  { sequence: 144, blockId: 6, indexInBlock: 19, phase: 2, subBlock: "6.4", threshold: 80,
    sceneTitle: { en: "Asking for Support", "pt-BR": "Pedindo Apoio" },
    contextDescription: { en: "The smart move under fire: turn defence into a plan. Ask what success looks like and what support you'll get. Take control of the narrative.", "pt-BR": "A jogada inteligente sob fogo: transformar defesa em plano. Pergunte como é o sucesso e que apoio você terá. Assuma o controle da narrativa." },
    objective: { en: "Request a clear improvement plan and support.", "pt-BR": "Pedir um plano de melhoria claro e apoio." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "what does good look like?", say: "uât dâz gúd lúk láik", note: { en: "Define success.", "pt-BR": "Definir o sucesso." } }],
    dialogueSteps: [ { text: "So, where do we go from here?", tr: { en: "What happens next?", "pt-BR": "E daqui para frente?" }, ear: { en: "<b>“frâm ria”</b>", "pt-BR": "<b>“frâm ria”</b>" }, audioPrompt: "Manager, softening: “So, where do we go from here?”", basic: "What does good look like?", fluent: "What does good look like — and what support can I get?" } ] },
  { sequence: 145, blockId: 6, indexInBlock: 20, phase: 2, subBlock: "6.4", threshold: 80,
    sceneTitle: { en: "The Turnaround", "pt-BR": "A Virada" },
    contextDescription: { en: "Weeks later, the follow-up. You've delivered. The manager, surprised and impressed, acknowledges it. You accept the praise without arrogance.", "pt-BR": "Semanas depois, o retorno. Você entregou. O gestor, surpreso e impressionado, reconhece. Você aceita o elogio sem arrogância." },
    objective: { en: "Accept redemption gracefully.", "pt-BR": "Aceitar a redenção com elegância." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "I appreciate that", say: "ai a-PRÍ-shi-êit dét", note: { en: "Gracious thanks.", "pt-BR": "Agradecimento elegante." } }],
    dialogueSteps: [ { text: "I'll be honest — you've turned it right around.", tr: { en: "You've improved a lot.", "pt-BR": "Você melhorou muito." }, ear: { en: "<b>“târnd it a-RÁUND”</b>", "pt-BR": "<b>“târnd it a-RÁUND”</b>" }, audioPrompt: "Manager, genuinely impressed: “I'll be honest — you've turned it right around.”", basic: "Thank you. I appreciate that.", fluent: "Thank you — I appreciate that, and the support helped." } ] },

  /* 6.5 — LEADING & BELONGING */
  { sequence: 146, blockId: 6, indexInBlock: 21, phase: 2, subBlock: "6.5", threshold: 80,
    sceneTitle: { en: "Chairing Your First Meeting", "pt-BR": "Liderando Sua Primeira Reunião" },
    contextDescription: { en: "You're running the meeting now. Eyes on you, the room waiting. You must open it, set the agenda, and hold the floor in a second language.", "pt-BR": "Agora você comanda a reunião. Olhos em você, a sala esperando. Você precisa abrir, definir a pauta e conduzir num segundo idioma." },
    objective: { en: "Open and lead a meeting.", "pt-BR": "Abrir e conduzir uma reunião." },
    environment: { mood: "neutral", baseNoise: 26 },
    npc: { name: { en: "Team", "pt-BR": "Equipe" }, initials: "TE" },
    drills: [{ word: "let's get started", say: "léts guét STÁR-tid", note: { en: "Open the meeting.", "pt-BR": "Abrir a reunião." } }],
    dialogueSteps: [ { text: "We're all here — over to you.", tr: { en: "It's your meeting to run.", "pt-BR": "A reunião é sua para conduzir." }, ear: { en: "<b>“Ô-vâr tu iú”</b>", "pt-BR": "<b>“Ô-vâr tu iú”</b>" }, audioPrompt: "A colleague, in a hushing room: “We're all here — over to you.”", basic: "Right, let's get started.", fluent: "Thanks everyone — let's get started, three things today." } ] },
  { sequence: 147, blockId: 6, indexInBlock: 22, phase: 2, subBlock: "6.5", threshold: 80,
    sceneTitle: { en: "Giving Feedback", "pt-BR": "Dando Feedback" },
    contextDescription: { en: "Now you're on the other side: a junior's work isn't good enough. You must correct them kindly but clearly — the skill you once needed used on you.", "pt-BR": "Agora você está do outro lado: o trabalho de um júnior não está bom. Você precisa corrigir com gentileza e clareza — a habilidade que um dia usaram com você." },
    objective: { en: "Give constructive feedback kindly.", "pt-BR": "Dar feedback construtivo com gentileza." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Junior", "pt-BR": "Júnior" }, initials: "JR" },
    drills: [{ word: "one thing to tweak", say: "uân thing tu TUÍK", note: { en: "Soften a correction.", "pt-BR": "Suavizar uma correção." } }],
    dialogueSteps: [ { text: "Did I get the report right?", tr: { en: "They want your verdict.", "pt-BR": "Eles querem seu veredito." }, ear: { en: "<b>“tuík”</b> = ajustar", "pt-BR": "<b>“tuík”</b> = ajustar" }, audioPrompt: "Junior, nervous and eager: “Did I get the report right?”", basic: "Good start — one thing to tweak.", fluent: "Strong start — just one thing to tweak, then it's there." } ] },
  { sequence: 148, blockId: 6, indexInBlock: 23, phase: 2, subBlock: "6.5", threshold: 80,
    sceneTitle: { en: "Presenting to Leadership", "pt-BR": "Apresentando à Diretoria" },
    contextDescription: { en: "The boardroom. Senior leaders, arms folded, short on time. You must present your idea crisply and field a sharp, sceptical question.", "pt-BR": "A sala da diretoria. Líderes seniores, braços cruzados, sem tempo. Você precisa apresentar sua ideia com objetividade e responder a uma pergunta afiada e cética." },
    objective: { en: "Pitch to leadership and handle a tough question.", "pt-BR": "Apresentar à diretoria e responder uma pergunta difícil." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Director", "pt-BR": "Diretor(a)" }, initials: "DI" },
    drills: [{ word: "great question", say: "grêit KUÉS-tchân", note: { en: "Buy a beat, stay calm.", "pt-BR": "Ganhe um tempo, mantenha a calma." } }],
    dialogueSteps: [ { text: "And what's the return on this investment?", tr: { en: "Justify the ROI.", "pt-BR": "Justifique o retorno." }, ear: { en: "<b>“ri-TÂRN ón”</b>", "pt-BR": "<b>“ri-TÂRN ón”</b>" }, audioPrompt: "Director, sceptical, arms folded: “And what's the return on this investment?”", basic: "Great question — about thirty percent.", fluent: "Great question — we project a thirty percent return in year one." } ] },
  { sequence: 149, blockId: 6, indexInBlock: 24, phase: 3, subBlock: "6.5", threshold: 80,
    sceneTitle: { en: "The Work Social", "pt-BR": "O Happy Hour do Trabalho" },
    contextDescription: { en: "Friday drinks with the team — but you're senior now. The line between boss and mate blurs over pints. Be human without losing authority.", "pt-BR": "Drinks de sexta com a equipe — mas agora você é sênior. A linha entre chefe e amigo se borra entre as pints. Seja humano sem perder a autoridade." },
    objective: { en: "Balance friendliness and authority socially.", "pt-BR": "Equilibrar simpatia e autoridade no social." },
    environment: { mood: "pleased", baseNoise: 50 },
    npc: { name: { en: "Team", "pt-BR": "Equipe" }, initials: "TE" },
    drills: [{ word: "first round's on me", say: "fârst ráunds ón mi", note: { en: "Generous, leaderly.", "pt-BR": "Generoso, de líder." } }],
    dialogueSteps: [ { text: "You actually came out with us! Legend.", tr: { en: "They're glad you joined.", "pt-BR": "Eles gostaram que você veio." }, ear: { en: "<b>“LÉ-djend”</b> = lenda", "pt-BR": "<b>“LÉ-djend”</b> = lenda" }, audioPrompt: "Team member, delighted over pub noise: “You actually came out with us! Legend.”", basic: "First round's on me!", fluent: "Course I came — first round's on me!" } ] },
  { sequence: 150, blockId: 6, indexInBlock: 25, phase: 2, subBlock: "6.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "Office Insider", tagline: "Office Insider — Workplace Conquered", shareText: "Office politics, a salary negotiation, a performance warning survived and a team that calls me 'legend' — I'm an Office Insider in London now! 🇬🇧💼" },
    sceneTitle: { en: "Bonus — Employee of the Month", "pt-BR": "Bônus — Funcionário do Mês" },
    contextDescription: { en: "From a warning to the top of the wall: your name on the Employee of the Month board, your team clapping. Eight months ago you couldn't order a coffee. Soak it in.", "pt-BR": "De uma advertência ao topo do mural: seu nome no quadro de Funcionário do Mês, sua equipe aplaudindo. Oito meses atrás você não pedia um café. Aproveite o momento." },
    objective: { en: "Accept recognition in front of the team.", "pt-BR": "Aceitar o reconhecimento diante da equipe." },
    environment: { mood: "pleased", baseNoise: 34 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "I'm chuffed", say: "aim TCHÂFT", note: { en: "= estou muito contente (UK).", "pt-BR": "= estou muito contente (UK)." } }],
    dialogueSteps: [
      { text: "Employee of the Month — say a few words!", tr: { en: "You won — give a short speech!", "pt-BR": "Você ganhou — faça um discursinho!" }, ear: { en: "<b>“tchâft”</b> = contente", "pt-BR": "<b>“tchâft”</b> = contente" }, audioPrompt: "Manager, to applause: “Employee of the Month — say a few words!”", basic: "Thanks all — I'm chuffed!", fluent: "Honestly, I'm chuffed — thank you, this team made it happen." },
      { text: "Knew you had it in you. Well deserved.", tr: { en: "You earned it.", "pt-BR": "Você mereceu." }, ear: { en: "<b>“di-ZÂRVD”</b>", "pt-BR": "<b>“di-ZÂRVD”</b>" }, audioPrompt: "Manager, warm, clapping your shoulder: “Knew you had it in you. Well deserved.”", basic: "Means a lot!", fluent: "That means a lot — thank you, really." },
    ] },
];

export const BLOCK06_BY_SEQUENCE = BLOCK06_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
