/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 08 (Modules 176–200)
 *  "Building a Life" — 5 sub-blocks:
 *    8.1 Dating              (176–180) the match, the date, the second-date ask
 *    8.2 Complex Feelings    (181–185) vulnerability, a row, reconciliation
 *    8.3 Permanent Status    (186–190) the Home Office, biometrics, the decision
 *    8.4 Roots & Community    (191–195) volunteering, hosting, becoming a regular
 *    8.5 The Established Life (196–200) a big decision, full circle, BONUS
 *  Module 200 = "Established Londoner — A Life Built" milestone selfie.
 * ============================================================ */

export const BLOCK08_MODULES = [
  /* 8.1 — DATING */
  { sequence: 176, blockId: 8, indexInBlock: 1, phase: 2, subBlock: "8.1", threshold: 80,
    sceneTitle: { en: "The First Message", "pt-BR": "A Primeira Mensagem" },
    contextDescription: { en: "A match on a dating app. The cursor blinks. Flirting in a second language, where one wrong word kills the spark — you must open with charm, not a textbook.", "pt-BR": "Um match num app de namoro. O cursor pisca. Flertar num segundo idioma, onde uma palavra errada mata o clima — você precisa abrir com charme, não com livro didático." },
    objective: { en: "Open a flirty conversation naturally.", "pt-BR": "Abrir uma conversa de paquera com naturalidade." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Match", "pt-BR": "Match" }, initials: "MX" },
    drills: [{ word: "I had to say hi", say: "ai réd tu sêi RÁI", note: { en: "A warm opener.", "pt-BR": "Uma abertura calorosa." } }],
    dialogueSteps: [ { text: "Oh, you actually messaged first. Brave!", tr: { en: "They like that you messaged.", "pt-BR": "Eles gostaram que você chamou." }, ear: { en: "<b>“brêiv”</b> = corajoso", "pt-BR": "<b>“brêiv”</b> = corajoso" }, audioPrompt: "Match, playful voice note: “Oh, you actually messaged first. Brave!”", basic: "I had to say hi.", fluent: "I had to say hi — your taste in music gave me no choice." } ] },
  { sequence: 177, blockId: 8, indexInBlock: 2, phase: 3, subBlock: "8.1", threshold: 80,
    sceneTitle: { en: "The First Date", "pt-BR": "O Primeiro Encontro" },
    contextDescription: { en: "A buzzing wine bar, nerves jangling. They're lovely and quick-witted. You must keep the conversation flowing and not freeze when the banter speeds up.", "pt-BR": "Um bar de vinhos animado, nervos à flor da pele. A pessoa é encantadora e rápida no papo. Você precisa manter a conversa fluindo e não travar quando a zoeira acelera." },
    objective: { en: "Keep a flowing, warm first-date conversation.", "pt-BR": "Manter uma conversa calorosa e fluida no primeiro encontro." },
    environment: { mood: "pleased", baseNoise: 48 },
    npc: { name: { en: "Date", "pt-BR": "Date" }, initials: "DT" },
    drills: [{ word: "tell me about you", say: "tél mi a-BÁUT iú", note: { en: "Turn it back warmly.", "pt-BR": "Devolva com carinho." } }],
    dialogueSteps: [ { text: "So what's your story? How did you end up in London?", tr: { en: "Tell me how you got here.", "pt-BR": "Conte como você veio parar aqui." }, ear: { en: "<b>“énd âp”</b> = parar", "pt-BR": "<b>“énd âp”</b> = parar" }, audioPrompt: "Date, leaning in over the bar buzz: “So what's your story? How did you end up in London?”", basic: "Long story! Tell me about you.", fluent: "Long story — I'll trade it for yours. Tell me about you." } ] },
  { sequence: 178, blockId: 8, indexInBlock: 3, phase: 3, subBlock: "8.1", threshold: 80,
    sceneTitle: { en: "Lost in Translation", "pt-BR": "Perdido na Tradução" },
    contextDescription: { en: "You make a joke that lands flat — a phrase that works back home but not here. Awkward silence. You must recover with humour and turn the slip into charm.", "pt-BR": "Você faz uma piada que não pega — uma frase que funciona no seu país mas não aqui. Silêncio constrangedor. Você precisa se recuperar com humor e transformar o vacilo em charme." },
    objective: { en: "Recover gracefully from a cultural slip.", "pt-BR": "Recuperar-se com graça de um deslize cultural." },
    environment: { mood: "neutral", baseNoise: 46 },
    npc: { name: { en: "Date", "pt-BR": "Date" }, initials: "DT" },
    drills: [{ word: "that didn't translate", say: "dét DÍ-dânt trâns-LÊIT", note: { en: "Laugh at yourself.", "pt-BR": "Ria de si mesmo." } }],
    dialogueSteps: [ { text: "...sorry, I have no idea what that means!", tr: { en: "Your joke didn't land — recover.", "pt-BR": "Sua piada não pegou — recupere-se." }, ear: { en: "<b>“trâns-LÊIT”</b>", "pt-BR": "<b>“trâns-LÊIT”</b>" }, audioPrompt: "Date, laughing, confused: “...sorry, I have no idea what that means!”", basic: "Ha! That didn't translate.", fluent: "Ha — clearly that one didn't translate. Give me a minute!" } ] },
  { sequence: 179, blockId: 8, indexInBlock: 4, phase: 3, subBlock: "8.1", threshold: 80,
    sceneTitle: { en: "The Spark", "pt-BR": "A Faísca" },
    contextDescription: { en: "The conversation deepens; the night feels rare. They go quiet, look at you, and say something genuine. You must respond with real warmth, not a rehearsed line.", "pt-BR": "A conversa aprofunda; a noite parece rara. A pessoa fica quieta, te olha e diz algo sincero. Você precisa responder com carinho de verdade, não com frase ensaiada." },
    objective: { en: "Respond authentically to a sincere moment.", "pt-BR": "Responder com autenticidade a um momento sincero." },
    environment: { mood: "pleased", baseNoise: 38 },
    npc: { name: { en: "Date", "pt-BR": "Date" }, initials: "DT" },
    drills: [{ word: "I feel it too", say: "ai fíl it tú", note: { en: "Honest, simple, warm.", "pt-BR": "Honesto, simples, caloroso." } }],
    dialogueSteps: [ { text: "I really wasn't expecting to like you this much.", tr: { en: "They feel a connection.", "pt-BR": "Eles sentem uma conexão." }, ear: { en: "<b>“ik-SPÉK-tin”</b>", "pt-BR": "<b>“ik-SPÉK-tin”</b>" }, audioPrompt: "Date, softer now, sincere: “I really wasn't expecting to like you this much.”", basic: "I feel it too.", fluent: "Honestly... I feel exactly the same." } ] },
  { sequence: 180, blockId: 8, indexInBlock: 5, phase: 3, subBlock: "8.1", threshold: 80,
    sceneTitle: { en: "Asking for a Second", "pt-BR": "Pedindo o Segundo Encontro" },
    contextDescription: { en: "Outside, goodbye hovering. You must take the risk and ask to see them again — vulnerable, fluent, putting your heart on the line in their language.", "pt-BR": "Lá fora, o adeus pairando. Você precisa arriscar e pedir para vê-los de novo — vulnerável, fluente, colocando o coração em jogo no idioma deles." },
    objective: { en: "Ask for a second date, vulnerably.", "pt-BR": "Pedir um segundo encontro, de forma vulnerável." },
    environment: { mood: "pleased", baseNoise: 36 },
    npc: { name: { en: "Date", "pt-BR": "Date" }, initials: "DT" },
    drills: [{ word: "can I see you again?", say: "kén ai sí iú a-GÉN", note: { en: "The brave ask.", "pt-BR": "O pedido corajoso." } }],
    dialogueSteps: [ { text: "Well... this was lovely.", tr: { en: "Your opening to ask again.", "pt-BR": "Sua deixa para pedir de novo." }, ear: { en: "<b>“a-GÉN”</b>", "pt-BR": "<b>“a-GÉN”</b>" }, audioPrompt: "Date, lingering, smiling on the pavement: “Well... this was lovely.”", basic: "Can I see you again?", fluent: "It really was — can I see you again? Soon?" } ] },

  /* 8.2 — COMPLEX FEELINGS */
  { sequence: 181, blockId: 8, indexInBlock: 6, phase: 2, subBlock: "8.2", threshold: 80,
    sceneTitle: { en: "Opening Up", "pt-BR": "Se Abrindo" },
    contextDescription: { en: "Weeks in, they ask about home — and the homesickness you hide. You must put a complex, tender feeling into a second language, where nuance is hardest of all.", "pt-BR": "Algumas semanas depois, perguntam sobre casa — e a saudade que você esconde. Você precisa colocar um sentimento complexo e delicado num segundo idioma, onde a nuance é o mais difícil." },
    objective: { en: "Express a nuanced emotion (homesickness).", "pt-BR": "Expressar uma emoção sutil (saudade)." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Partner", "pt-BR": "Parceiro(a)" }, initials: "PT" },
    drills: [{ word: "I miss home sometimes", say: "ai mís rôum SÂM-taims", note: { en: "Name the feeling.", "pt-BR": "Nomeie o sentimento." } }],
    dialogueSteps: [ { text: "Do you ever miss home? Really?", tr: { en: "Are you homesick, honestly?", "pt-BR": "Você sente saudade de casa, de verdade?" }, ear: { en: "<b>“rôum-sik”</b> = com saudade", "pt-BR": "<b>“rôum-sik”</b> = com saudade" }, audioPrompt: "Partner, gentle and curious in the quiet: “Do you ever miss home? Really?”", basic: "I miss home sometimes.", fluent: "I do — I miss home sometimes, but my life is here now." } ] },
  { sequence: 182, blockId: 8, indexInBlock: 7, phase: 2, subBlock: "8.2", threshold: 80,
    sceneTitle: { en: "The Misunderstanding", "pt-BR": "O Mal-Entendido" },
    contextDescription: { en: "A phrase you used came out colder than you meant; they're hurt. The cruel trap of a second language. You must clarify what you actually meant, fast.", "pt-BR": "Uma frase que você usou soou mais fria do que pretendia; a pessoa se magoou. A armadilha cruel de um segundo idioma. Você precisa esclarecer o que quis dizer, rápido." },
    objective: { en: "Clarify a hurtful misunderstanding.", "pt-BR": "Esclarecer um mal-entendido que magoou." },
    environment: { mood: "hostile", baseNoise: 24 },
    npc: { name: { en: "Partner", "pt-BR": "Parceiro(a)" }, initials: "PT" },
    drills: [{ word: "that came out wrong", say: "dét kêim áut RÓNG", note: { en: "Repair quickly.", "pt-BR": "Conserte rápido." } }],
    dialogueSteps: [ { text: "That was a horrible thing to say.", tr: { en: "They're hurt — clarify gently.", "pt-BR": "Eles se magoaram — esclareça com cuidado." }, ear: { en: "<b>“RÓ-ri-bâl”</b>", "pt-BR": "<b>“RÓ-ri-bâl”</b>" }, audioPrompt: "Partner, hurt and quiet: “That was a horrible thing to say.”", basic: "Sorry — that came out wrong.", fluent: "I'm so sorry — that came out wrong, it's not what I meant." } ] },
  { sequence: 183, blockId: 8, indexInBlock: 8, phase: 2, subBlock: "8.2", threshold: 80,
    sceneTitle: { en: "Saying What You Need", "pt-BR": "Dizendo o que Você Precisa" },
    contextDescription: { en: "The harder honesty: not apologising, but asking for what you need from them. Assertive vulnerability — the highest level of emotional fluency.", "pt-BR": "A honestidade mais difícil: não pedir desculpas, mas pedir o que você precisa deles. Vulnerabilidade assertiva — o nível mais alto de fluência emocional." },
    objective: { en: "State an emotional need clearly.", "pt-BR": "Expressar uma necessidade emocional com clareza." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Partner", "pt-BR": "Parceiro(a)" }, initials: "PT" },
    drills: [{ word: "I need you to", say: "ai níd iú tu", note: { en: "State the need.", "pt-BR": "Diga a necessidade." } }],
    dialogueSteps: [ { text: "So what do you need from me?", tr: { en: "What do you need?", "pt-BR": "Do que você precisa?" }, ear: { en: "<b>“níd frâm mi”</b>", "pt-BR": "<b>“níd frâm mi”</b>" }, audioPrompt: "Partner, softening, willing to listen: “So what do you need from me?”", basic: "I need you to be patient.", fluent: "I need you to be patient with me when my words come out wrong." } ] },
  { sequence: 184, blockId: 8, indexInBlock: 9, phase: 2, subBlock: "8.2", threshold: 80,
    sceneTitle: { en: "Making Up", "pt-BR": "A Reconciliação" },
    contextDescription: { en: "The air clears. They reach out. You must accept the repair warmly — closing the loop on your first real argument navigated entirely in a foreign tongue.", "pt-BR": "O ar se limpa. A pessoa estende a mão. Você precisa aceitar a reconciliação com carinho — fechando o ciclo da sua primeira briga de verdade conduzida inteiramente num idioma estrangeiro." },
    objective: { en: "Accept reconciliation warmly.", "pt-BR": "Aceitar a reconciliação com carinho." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Partner", "pt-BR": "Parceiro(a)" }, initials: "PT" },
    drills: [{ word: "we're okay", say: "uír ô-KÊI", note: { en: "Reassure together.", "pt-BR": "Tranquilizem-se juntos." } }],
    dialogueSteps: [ { text: "Come here. We're okay, yeah?", tr: { en: "Are we good?", "pt-BR": "Estamos bem?" }, ear: { en: "<b>“uír ô-KÊI”</b>", "pt-BR": "<b>“uír ô-KÊI”</b>" }, audioPrompt: "Partner, warm, arms open: “Come here. We're okay, yeah?”", basic: "We're okay. I promise.", fluent: "We're more than okay — I promise. Thank you for listening." } ] },
  { sequence: 185, blockId: 8, indexInBlock: 10, phase: 2, subBlock: "8.2", threshold: 80,
    sceneTitle: { en: "Meeting the Friends", "pt-BR": "Conhecendo os Amigos" },
    contextDescription: { en: "They bring you to meet their closest friends — a fast, in-jokey group who'll decide if you fit. You must hold your own in rapid, layered British humour.", "pt-BR": "Eles te levam para conhecer os amigos mais próximos — um grupo rápido e cheio de piadas internas que vai decidir se você se encaixa. Você precisa se manter firme no humor britânico veloz e em camadas." },
    objective: { en: "Win over the partner's friends.", "pt-BR": "Conquistar os amigos do parceiro." },
    environment: { mood: "pleased", baseNoise: 50 },
    npc: { name: { en: "Their Friend", "pt-BR": "Amigo(a) Deles" }, initials: "TF" },
    drills: [{ word: "I've heard all about you", say: "aiv rârd ol a-BÁUT iú", note: { en: "Friendly opener.", "pt-BR": "Abertura amigável." } }],
    dialogueSteps: [ { text: "So you're the one we've heard SO much about.", tr: { en: "They've heard about you — charm them.", "pt-BR": "Eles ouviram falar de você — encante-os." }, ear: { en: "<b>“sôu mâtch”</b>", "pt-BR": "<b>“sôu mâtch”</b>" }, audioPrompt: "Their friend, grinning over party noise: “So you're the one we've heard SO much about.”", basic: "All good, I hope!", fluent: "All good things, I hope — I've heard all about you too!" } ] },

  /* 8.3 — PERMANENT STATUS */
  { sequence: 186, blockId: 8, indexInBlock: 11, phase: 2, subBlock: "8.3", threshold: 80,
    sceneTitle: { en: "The Home Office", "pt-BR": "A Imigração (Home Office)" },
    contextDescription: { en: "A cold government waiting room, a ticket number, the weight of your whole future in a folder of documents. Your number is called. Everything rides on the next words.", "pt-BR": "Uma sala de espera fria do governo, um número de senha, o peso de todo o seu futuro numa pasta de documentos. Seu número é chamado. Tudo depende das próximas palavras." },
    objective: { en: "Open a high-stakes immigration appointment.", "pt-BR": "Abrir uma entrevista de imigração de alto risco." },
    culturalNote: { en: "Settled status / ILR = the right to stay permanently. Bring every document.", "pt-BR": "Settled status / ILR = direito de permanecer definitivamente. Leve todos os documentos." },
    environment: { mood: "hostile", baseNoise: 24 },
    npc: { name: { en: "Caseworker", "pt-BR": "Atendente" }, initials: "CW" },
    drills: [{ word: "settled status", say: "SÉ-tâld STÊI-tâs", note: { en: "= residência permanente.", "pt-BR": "= residência permanente." } }],
    dialogueSteps: [ { text: "You're applying for settled status. Documents?", tr: { en: "Show your documents.", "pt-BR": "Mostre seus documentos." }, ear: { en: "<b>“SÉ-tâld”</b>", "pt-BR": "<b>“SÉ-tâld”</b>" }, audioPrompt: "Caseworker, brisk in a quiet office: “You're applying for settled status. Documents?”", basic: "Yes. Here they are.", fluent: "Yes — here's everything, organised by year." } ] },
  { sequence: 187, blockId: 8, indexInBlock: 12, phase: 2, subBlock: "8.3", threshold: 80,
    sceneTitle: { en: "Proving Your Years", "pt-BR": "Comprovando os Anos" },
    contextDescription: { en: "“Prove you've lived here continuously.” Payslips, tenancies, bills — your whole life as a paper trail. A gap in the record could sink the application. Explain it.", "pt-BR": "“Prove que você morou aqui continuamente.” Holerites, contratos, contas — sua vida inteira como rastro de papel. Uma lacuna pode afundar o pedido. Explique-a." },
    objective: { en: "Account for your residence history.", "pt-BR": "Justificar seu histórico de residência." },
    environment: { mood: "hostile", baseNoise: 24 },
    npc: { name: { en: "Caseworker", "pt-BR": "Atendente" }, initials: "CW" },
    drills: [{ word: "continuously", say: "cân-TÍ-niu-âs-li", note: { en: "= continuamente.", "pt-BR": "= continuamente." } }],
    dialogueSteps: [ { text: "There's a gap here, in the spring. Explain it.", tr: { en: "Explain the gap in your records.", "pt-BR": "Explique a lacuna nos registros." }, ear: { en: "<b>“guép”</b> = lacuna", "pt-BR": "<b>“guép”</b> = lacuna" }, audioPrompt: "Caseworker, suspicious: “There's a gap here, in the spring. Explain it.”", basic: "I changed jobs then.", fluent: "I changed jobs that spring — here's the P45 covering it." } ] },
  { sequence: 188, blockId: 8, indexInBlock: 13, phase: 2, subBlock: "8.3", threshold: 80,
    sceneTitle: { en: "Biometrics", "pt-BR": "Biometria" },
    contextDescription: { en: "Fingerprints, photo, signature. A machine, a curt instruction, a flash. The bureaucratic ritual that turns a person into a record. Follow each command precisely.", "pt-BR": "Digitais, foto, assinatura. Uma máquina, uma instrução seca, um flash. O ritual burocrático que transforma uma pessoa num registro. Siga cada comando com precisão." },
    objective: { en: "Follow precise biometric instructions.", "pt-BR": "Seguir instruções biométricas precisas." },
    environment: { mood: "neutral", baseNoise: 26 },
    npc: { name: { en: "Officer", "pt-BR": "Oficial" }, initials: "OF" },
    drills: [{ word: "four fingers, flat", say: "fór FÍN-gârs, flét", note: { en: "Follow the command.", "pt-BR": "Siga o comando." } }],
    dialogueSteps: [ { text: "Right hand — four fingers flat on the glass.", tr: { en: "Put four fingers on the scanner.", "pt-BR": "Quatro dedos no leitor." }, ear: { en: "<b>“flét ón dâ glás”</b>", "pt-BR": "<b>“flét ón dâ glás”</b>" }, audioPrompt: "Officer, clipped: “Right hand — four fingers flat on the glass.”", basic: "Like this?", fluent: "Like this — four fingers, flat?" } ] },
  { sequence: 189, blockId: 8, indexInBlock: 14, phase: 2, subBlock: "8.3", threshold: 80,
    sceneTitle: { en: "The Hard Question", "pt-BR": "A Pergunta Difícil" },
    contextDescription: { en: "Eyes up, the test: “Why should you be allowed to stay?” Your whole journey compressed into one sincere answer. This is the soul of the reality-shock.", "pt-BR": "Olhos para cima, o teste: “Why should you be allowed to stay?” Toda a sua jornada comprimida numa resposta sincera. Esta é a alma do reality-shock." },
    objective: { en: "Make the case for your life here.", "pt-BR": "Defender a sua vida aqui." },
    environment: { mood: "hostile", baseNoise: 22 },
    npc: { name: { en: "Caseworker", "pt-BR": "Atendente" }, initials: "CW" },
    drills: [{ word: "I've built a life here", say: "aiv bilt a láif ria", note: { en: "Your truth, fluent.", "pt-BR": "Sua verdade, fluente." } }],
    dialogueSteps: [ { text: "In your own words — why should you stay?", tr: { en: "Why should you be allowed to stay?", "pt-BR": "Por que você deveria poder ficar?" }, ear: { en: "<b>“bilt a láif”</b>", "pt-BR": "<b>“bilt a láif”</b>" }, audioPrompt: "Caseworker, direct, eyes up: “In your own words — why should you stay?”", basic: "I've built a life here.", fluent: "I've built a life here — work, friends, a home. This is where I belong." } ] },
  { sequence: 190, blockId: 8, indexInBlock: 15, phase: 2, subBlock: "8.3", threshold: 80,
    sceneTitle: { en: "The Decision", "pt-BR": "A Decisão" },
    contextDescription: { en: "A pause that lasts a lifetime. Then a stamp, a printout, a flat “that's approved.” The right to stay — permanently. You must hold it together as the room blurs.", "pt-BR": "Uma pausa que dura uma vida. Então um carimbo, uma impressão, um seco “that's approved.” O direito de ficar — para sempre. Você precisa se segurar enquanto a sala embaça." },
    objective: { en: "Receive a life-changing decision.", "pt-BR": "Receber uma decisão que muda a vida." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Caseworker", "pt-BR": "Atendente" }, initials: "CW" },
    drills: [{ word: "thank you, truly", say: "TÉNK iú, TRÚ-li", note: { en: "Heartfelt thanks.", "pt-BR": "Agradecimento sincero." } }],
    dialogueSteps: [ { text: "...that's approved. Welcome — you can stay.", tr: { en: "You've been granted status!", "pt-BR": "Você foi aprovado!" }, ear: { en: "<b>“a-PRÚVD”</b>", "pt-BR": "<b>“a-PRÚVD”</b>" }, audioPrompt: "Caseworker, the faintest smile: “...that's approved. Welcome — you can stay.”", basic: "Thank you, truly.", fluent: "Thank you — truly. You have no idea what this means." } ] },

  /* 8.4 — ROOTS & COMMUNITY */
  { sequence: 191, blockId: 8, indexInBlock: 16, phase: 3, subBlock: "8.4", threshold: 80,
    sceneTitle: { en: "Giving Back", "pt-BR": "Retribuindo" },
    contextDescription: { en: "You join a local volunteering group — a community garden, a food bank. The organiser welcomes you and asks what you'd like to help with. You're putting down roots.", "pt-BR": "Você entra num grupo de voluntariado local — uma horta comunitária, um banco de alimentos. A organizadora te acolhe e pergunta com o que você quer ajudar. Você está criando raízes." },
    objective: { en: "Volunteer and offer your skills.", "pt-BR": "Voluntariar-se e oferecer suas habilidades." },
    environment: { mood: "pleased", baseNoise: 42 },
    npc: { name: { en: "Organiser", "pt-BR": "Organizador(a)" }, initials: "OR" },
    drills: [{ word: "I'd like to help", say: "aid láik tu RÉLP", note: { en: "Offer yourself.", "pt-BR": "Ofereça-se." } }],
    dialogueSteps: [ { text: "Lovely to have you! What are you good at?", tr: { en: "What can you help with?", "pt-BR": "Com o que você pode ajudar?" }, ear: { en: "<b>“gúd at”</b>", "pt-BR": "<b>“gúd at”</b>" }, audioPrompt: "Organiser, warm and busy: “Lovely to have you! What are you good at?”", basic: "I'd like to help anywhere.", fluent: "Happy to help anywhere — I'm good with people and design." } ] },
  { sequence: 192, blockId: 8, indexInBlock: 17, phase: 3, subBlock: "8.4", threshold: 80,
    sceneTitle: { en: "The Neighbour Dispute", "pt-BR": "A Briga de Vizinhos" },
    contextDescription: { en: "Two neighbours are rowing over a shared bin and a fence. As the calm, settled local you now are, they turn to YOU to mediate. The newcomer has become the peacemaker.", "pt-BR": "Dois vizinhos brigam por uma lixeira compartilhada e uma cerca. Como o local calmo e estabelecido que você agora é, eles se voltam para VOCÊ para mediar. O recém-chegado virou o pacificador." },
    objective: { en: "Mediate a neighbourly dispute calmly.", "pt-BR": "Mediar uma briga de vizinhos com calma." },
    environment: { mood: "hostile", baseNoise: 44 },
    npc: { name: { en: "Neighbour", "pt-BR": "Vizinho(a)" }, initials: "NB" },
    drills: [{ word: "let's find a compromise", say: "léts fáind a CÓM-prô-maiz", note: { en: "= achar um meio-termo.", "pt-BR": "= achar um meio-termo." } }],
    dialogueSteps: [ { text: "You're sensible — tell him he's in the wrong!", tr: { en: "They want you to take sides.", "pt-BR": "Eles querem que você tome partido." }, ear: { en: "<b>“SÉN-si-bâl”</b> = sensato", "pt-BR": "<b>“SÉN-si-bâl”</b> = sensato" }, audioPrompt: "Neighbour, heated, appealing to you: “You're sensible — tell him he's in the wrong!”", basic: "Let's find a compromise.", fluent: "Let's all calm down and find a compromise that works." } ] },
  { sequence: 193, blockId: 8, indexInBlock: 18, phase: 3, subBlock: "8.4", threshold: 80,
    sceneTitle: { en: "Hosting a Dinner", "pt-BR": "Recebendo para Jantar" },
    contextDescription: { en: "Your flat, your friends, your cooking — you're hosting for the first time. A guest arrives; you must welcome them with the easy warmth of someone who belongs.", "pt-BR": "Seu apê, seus amigos, sua comida — você recebe pela primeira vez. Um convidado chega; você precisa acolhê-lo com o calor tranquilo de quem pertence." },
    objective: { en: "Host guests with natural warmth.", "pt-BR": "Receber convidados com calor natural." },
    environment: { mood: "pleased", baseNoise: 40 },
    npc: { name: { en: "Guest", "pt-BR": "Convidado(a)" }, initials: "GU" },
    drills: [{ word: "make yourself at home", say: "mêik iór-SÉLF at RÔUM", note: { en: "Welcome them in.", "pt-BR": "Acolha-os." } }],
    dialogueSteps: [ { text: "Something smells amazing! What can I bring next time?", tr: { en: "They love it — welcome them.", "pt-BR": "Eles adoraram — acolha-os." }, ear: { en: "<b>“a-MÊI-zin”</b>", "pt-BR": "<b>“a-MÊI-zin”</b>" }, audioPrompt: "Guest, arriving, delighted: “Something smells amazing! What can I bring next time?”", basic: "Just you! Make yourself at home.", fluent: "Just bring yourself! Come in, make yourself at home." } ] },
  { sequence: 194, blockId: 8, indexInBlock: 19, phase: 3, subBlock: "8.4", threshold: 80,
    sceneTitle: { en: "The Local's Recommendation", "pt-BR": "A Dica do Local" },
    contextDescription: { en: "A tourist on your street asks where's good to eat. Once that was you, lost and afraid. Now you reel off insider tips like a born-and-bred Londoner.", "pt-BR": "Um turista na sua rua pergunta onde se come bem. Um dia esse foi você, perdido e com medo. Agora você dispara dicas de quem é da terra, como um londrino nato." },
    objective: { en: "Give confident local recommendations.", "pt-BR": "Dar recomendações locais com confiança." },
    environment: { mood: "pleased", baseNoise: 46 },
    npc: { name: { en: "Tourist", "pt-BR": "Turista" }, initials: "TO" },
    drills: [{ word: "you've got to try", say: "iúv gót tu trái", note: { en: "Recommend confidently.", "pt-BR": "Recomende com confiança." } }],
    dialogueSteps: [ { text: "Excuse me — where's good to eat around here?", tr: { en: "Recommend somewhere local.", "pt-BR": "Recomende um lugar local." }, ear: { en: "<b>“a-RÁUND ria”</b>", "pt-BR": "<b>“a-RÁUND ria”</b>" }, audioPrompt: "Tourist, hopeful: “Excuse me — where's good to eat around here?”", basic: "You've got to try the pie shop.", fluent: "Skip the chains — you've got to try the little pie shop on the corner." } ] },
  { sequence: 195, blockId: 8, indexInBlock: 20, phase: 3, subBlock: "8.4", threshold: 80,
    sceneTitle: { en: "Part of the Furniture", "pt-BR": "Parte da Mobília" },
    contextDescription: { en: "At your local pub, the landlord greets you by name and waves you to ‘your’ stool. You're no longer a customer — you're part of the place. Settle in.", "pt-BR": "No seu pub, o dono te cumprimenta pelo nome e te aponta o ‘seu’ banco. Você não é mais um cliente — você é parte do lugar. Acomode-se." },
    objective: { en: "Enjoy being a true local regular.", "pt-BR": "Curtir ser um cliente fiel de verdade." },
    culturalNote: { en: "‘Part of the furniture’ = so familiar you belong there. The highest pub honour.", "pt-BR": "‘Part of the furniture’ = tão familiar que você pertence ali. A maior honra do pub." },
    environment: { mood: "pleased", baseNoise: 48 },
    npc: { name: { en: "Landlord", "pt-BR": "Dono do Pub" }, initials: "PL" },
    drills: [{ word: "the usual spot", say: "dâ IÚ-jiu-âl spót", note: { en: "= o lugar de sempre.", "pt-BR": "= o lugar de sempre." } }],
    dialogueSteps: [ { text: "Evening! Your stool's free — usual, is it?", tr: { en: "They know you — the regular.", "pt-BR": "Eles te conhecem — o cliente fiel." }, ear: { en: "<b>“iór STÚL”</b>", "pt-BR": "<b>“iór STÚL”</b>" }, audioPrompt: "Landlord, warm over pub chatter: “Evening! Your stool's free — usual, is it?”", basic: "The usual, cheers!", fluent: "Evening! The usual, please — good to be back." } ] },

  /* 8.5 — THE ESTABLISHED LIFE */
  { sequence: 196, blockId: 8, indexInBlock: 21, phase: 2, subBlock: "8.5", threshold: 80,
    sceneTitle: { en: "The Big Decision", "pt-BR": "A Grande Decisão" },
    contextDescription: { en: "An estate agent slides a long lease — or even a mortgage — across the desk. Putting down permanent roots in pounds and signatures. You must commit, clear-eyed.", "pt-BR": "Um corretor empurra um contrato longo — ou até um financiamento — sobre a mesa. Criar raízes permanentes em libras e assinaturas. Você precisa se comprometer, de olhos abertos." },
    objective: { en: "Commit to a long-term lease/mortgage.", "pt-BR": "Comprometer-se com um contrato/financiamento de longo prazo." },
    environment: { mood: "neutral", baseNoise: 26 },
    npc: { name: { en: "Estate Agent", "pt-BR": "Corretor(a)" }, initials: "EA" },
    drills: [{ word: "I'm ready to commit", say: "aim RÉ-di tu cô-MÍT", note: { en: "= pronto para assumir.", "pt-BR": "= pronto para assumir." } }],
    dialogueSteps: [ { text: "It's a big commitment. Are you sure?", tr: { en: "Are you ready for this?", "pt-BR": "Você está pronto para isso?" }, ear: { en: "<b>“cô-MÍT-mânt”</b>", "pt-BR": "<b>“cô-MÍT-mânt”</b>" }, audioPrompt: "Estate agent, pen offered: “It's a big commitment. Are you sure?”", basic: "I'm ready to commit.", fluent: "I've never been more sure — I'm ready to commit." } ] },
  { sequence: 197, blockId: 8, indexInBlock: 22, phase: 2, subBlock: "8.5", threshold: 80,
    sceneTitle: { en: "The Promotion", "pt-BR": "A Promoção" },
    contextDescription: { en: "Your boss calls you in — not a warning this time, but an offer to lead the team. From struggling newcomer to leader. You accept, then advocate for your people.", "pt-BR": "Seu chefe te chama — não uma advertência desta vez, mas a oferta de liderar a equipe. De recém-chegado em dificuldade a líder. Você aceita e então defende sua equipe." },
    objective: { en: "Accept a leadership promotion gracefully.", "pt-BR": "Aceitar uma promoção a líder com elegância." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Boss", "pt-BR": "Chefe" }, initials: "BO" },
    drills: [{ word: "I'd be honoured", say: "aid bi Ó-nârd", note: { en: "= seria uma honra.", "pt-BR": "= seria uma honra." } }],
    dialogueSteps: [ { text: "We want you to lead the team. What do you say?", tr: { en: "They offer you leadership.", "pt-BR": "Eles te oferecem a liderança." }, ear: { en: "<b>“Ó-nârd”</b> (silent H)", "pt-BR": "<b>“Ó-nârd”</b> (H mudo)" }, audioPrompt: "Boss, sincere: “We want you to lead the team. What do you say?”", basic: "I'd be honoured.", fluent: "I'd be honoured — and I'll take good care of the team." } ] },
  { sequence: 198, blockId: 8, indexInBlock: 23, phase: 3, subBlock: "8.5", threshold: 80,
    sceneTitle: { en: "Full Circle", "pt-BR": "Ciclo Completo" },
    contextDescription: { en: "The newcomer you once comforted (Module 123) is thriving now, and thanks you for everything. The chain of kindness you received, passed on. Receive their gratitude.", "pt-BR": "O recém-chegado que você acolheu (Módulo 123) agora prospera e te agradece por tudo. A corrente de gentileza que você recebeu, repassada. Receba a gratidão dele." },
    objective: { en: "Accept the gratitude of someone you mentored.", "pt-BR": "Aceitar a gratidão de alguém que você orientou." },
    environment: { mood: "pleased", baseNoise: 38 },
    npc: { name: { en: "Former Newcomer", "pt-BR": "Ex-Recém-chegado" }, initials: "FN" },
    drills: [{ word: "you did the hard part", say: "iú díd dâ rárd párt", note: { en: "Deflect with grace.", "pt-BR": "Desvie com graça." } }],
    dialogueSteps: [ { text: "I made it — because of you. Thank you.", tr: { en: "They credit you for their success.", "pt-BR": "Eles te creditam pelo sucesso." }, ear: { en: "<b>“bi-CÓZ âv iú”</b>", "pt-BR": "<b>“bi-CÓZ âv iú”</b>" }, audioPrompt: "Former newcomer, emotional: “I made it — because of you. Thank you.”", basic: "You did the hard part.", fluent: "You did the hard part — I just remembered how it felt." } ] },
  { sequence: 199, blockId: 8, indexInBlock: 24, phase: 3, subBlock: "8.5", threshold: 80,
    sceneTitle: { en: "Home", "pt-BR": "Lar" },
    contextDescription: { en: "Standing in your own kitchen, keys to your name, a life that's truly yours. A friend asks the simple, enormous question: does it feel like home now? Answer from the heart.", "pt-BR": "Em pé na sua própria cozinha, chaves no seu nome, uma vida que é de verdade sua. Um amigo faz a pergunta simples e enorme: agora parece um lar? Responda do coração." },
    objective: { en: "Affirm that London is home now.", "pt-BR": "Afirmar que Londres agora é seu lar." },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "it feels like home", say: "it fíls láik RÔUM", note: { en: "The whole journey, in five words.", "pt-BR": "Toda a jornada, em cinco palavras." } }],
    dialogueSteps: [ { text: "So... does it finally feel like home?", tr: { en: "Does London feel like home now?", "pt-BR": "Londres parece um lar agora?" }, ear: { en: "<b>“fíls láik rôum”</b>", "pt-BR": "<b>“fíls láik rôum”</b>" }, audioPrompt: "Friend, gentle, in your own kitchen: “So... does it finally feel like home?”", basic: "Yeah. It feels like home.", fluent: "Yeah — it really does. It feels like home now." } ] },
  { sequence: 200, blockId: 8, indexInBlock: 25, phase: 3, subBlock: "8.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "Established Londoner", tagline: "Established Londoner — A Life Built", shareText: "200 modules ago I couldn't order a glass of water. Today I have love, settled status, a job I lead, and a city that's home. I didn't survive London — I built a life here. 🇬🇧🏡 #LinguoBound" },
    sceneTitle: { en: "Bonus — A Life Built", "pt-BR": "Bônus — Uma Vida Construída" },
    contextDescription: { en: "A rooftop at golden hour, the whole skyline laid out — the Shard, the river, the city that once terrified you. Friends, partner, your people around you, glasses raised to YOU. Two hundred modules ago you couldn't ask for water. Now London is yours. Take the photo. This one's forever.", "pt-BR": "Um terraço na hora dourada, todo o horizonte à vista — o Shard, o rio, a cidade que um dia te aterrorizou. Amigos, parceiro, a sua gente ao redor, taças erguidas para VOCÊ. Duzentos módulos atrás você não sabia pedir água. Agora Londres é sua. Tire a foto. Esta é para sempre." },
    objective: { en: "Celebrate the life you've built. City 01: conquered.", "pt-BR": "Celebrar a vida que você construiu. Cidade 01: conquistada." },
    environment: { mood: "pleased", baseNoise: 44 },
    npc: { name: { en: "Your People", "pt-BR": "A Sua Gente" }, initials: "♥" },
    drills: [{ word: "to a life built here", say: "tu a láif bilt ria", note: { en: "The final toast.", "pt-BR": "O brinde final." } }],
    dialogueSteps: [
      { text: "Look how far you've come. A toast — to you!", tr: { en: "They toast your whole journey.", "pt-BR": "Eles brindam toda a sua jornada." }, ear: { en: "<b>“rau fár”</b>", "pt-BR": "<b>“rau fár”</b>" }, audioPrompt: "Your people, glasses raised on a golden rooftop: “Look how far you've come. A toast — to you!”", basic: "To a life built here!", fluent: "To all of you — and to a life built right here. Cheers!" },
      { text: "London's yours now. You earned every bit of it.", tr: { en: "You earned this city.", "pt-BR": "Você conquistou esta cidade." }, ear: { en: "<b>“iú ârnd it”</b>", "pt-BR": "<b>“iú ârnd it”</b>" }, audioPrompt: "Best friend, proud, arm around you: “London's yours now. You earned every bit of it.”", basic: "Every bit of it.", fluent: "Every single bit of it — and this is only the beginning." },
    ] },
];

export const BLOCK08_BY_SEQUENCE = BLOCK08_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
