/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 05 (Modules 101–125)
 *  "Deep Immersion" — a resident settling in. 5 sub-blocks:
 *    5.1 Running a Home      (101–105) broadband, flat-pack, the boiler dies
 *    5.2 Money & Admin       (106–110) payslip, bills, parking-ticket appeal
 *    5.3 Healthcare Deep     (111–115) the 8am GP scramble, dentist, therapy
 *    5.4 Cultural Fluency    (116–120) sarcasm, pub quiz, football, "it's fine"
 *    5.5 Test of Belonging   (121–125) standing up, mentoring, BONUS role-reversal
 *  Module 125 = "True Londoner — City Conquered" (you help a lost tourist).
 * ============================================================ */

export const BLOCK05_MODULES = [
  /* 5.1 — RUNNING A HOME */
  { sequence: 101, blockId: 5, indexInBlock: 1, phase: 3, subBlock: "5.1", threshold: 80,
    sceneTitle: { en: "The Broadband No-Show", "pt-BR": "O Técnico que Não Veio" },
    contextDescription: { en: "You took a day off for the broadband install. The 8am–1pm ‘window’ passed; no one came. You ring the provider, simmering.", "pt-BR": "Você tirou o dia para a instalação da internet. A ‘janela’ das 8h–13h passou; ninguém veio. Você liga para a operadora, fervendo." },
    objective: { en: "Complain about a missed appointment.", "pt-BR": "Reclamar de um atendimento não realizado." },
    culturalNote: { en: "‘An engineer’ does installs; complain calmly, ask for compensation.", "pt-BR": "‘An engineer’ faz a instalação; reclame com calma e peça compensação." },
    environment: { mood: "hostile", baseNoise: 36 },
    npc: { name: { en: "Provider Line", "pt-BR": "Central da Operadora" }, initials: "PL" },
    drills: [{ word: "nobody came", say: "NÔU-bâ-di kêim", note: { en: "= ninguém veio.", "pt-BR": "= ninguém veio." } }],
    dialogueSteps: [ { text: "How can I help today?", tr: { en: "How can I help?", "pt-BR": "Como posso ajudar?" }, ear: { en: "<b>“É-rep ai É-rep”</b>", "pt-BR": "diga claro e firme" }, audioPrompt: "Provider line, scripted: “How can I help today?”", basic: "Nobody came to install it.", fluent: "I waited all day and nobody came to install it." } ] },
  { sequence: 102, blockId: 5, indexInBlock: 2, phase: 3, subBlock: "5.1", threshold: 80,
    sceneTitle: { en: "Flat-Pack Hell", "pt-BR": "O Inferno do Móvel de Montar" },
    contextDescription: { en: "A wardrobe in forty pieces, instructions in pictures, one screw left over. You call a handy neighbour for rescue before it collapses.", "pt-BR": "Um guarda-roupa em quarenta peças, manual só com desenhos, um parafuso sobrando. Você liga para um vizinho habilidoso pedindo socorro antes que desabe." },
    objective: { en: "Ask a neighbour for practical help.", "pt-BR": "Pedir ajuda prática a um vizinho." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "Neighbour", "pt-BR": "Vizinho(a)" }, initials: "NB" },
    drills: [{ word: "give me a hand", say: "guív mi a RÉND", note: { en: "= me dar uma mão.", "pt-BR": "= me dar uma mão." } }],
    dialogueSteps: [ { text: "Alright? You knocked?", tr: { en: "Hi — you knocked?", "pt-BR": "Oi — você bateu?" }, ear: { en: "<b>“ol-RÁIT”</b>", "pt-BR": "<b>“ol-RÁIT”</b>" }, audioPrompt: "Neighbour, friendly at the door: “Alright? You knocked?”", basic: "Could you give me a hand?", fluent: "Sorry to bother you — could you give me a hand?" } ] },
  { sequence: 103, blockId: 5, indexInBlock: 3, phase: 3, subBlock: "5.1", threshold: 80,
    sceneTitle: { en: "The Boiler's Died", "pt-BR": "A Caldeira Pifou" },
    contextDescription: { en: "Mid-winter. No hot water, no heating — the boiler's dead. You call the landlord to demand an emergency repair before you freeze.", "pt-BR": "Pleno inverno. Sem água quente, sem aquecimento — a caldeira morreu. Você liga para o locador exigindo reparo de emergência antes de congelar." },
    objective: { en: "Report a no-heating emergency to the landlord.", "pt-BR": "Relatar emergência sem aquecimento ao locador." },
    culturalNote: { en: "No heating/hot water = an urgent repair the landlord must fix fast.", "pt-BR": "Sem aquecimento/água quente = reparo urgente que o locador deve resolver rápido." },
    environment: { mood: "hostile", baseNoise: 32 },
    npc: { name: { en: "Landlord", "pt-BR": "Locador(a)" }, initials: "LL" },
    drills: [{ word: "no hot water", say: "nôu RÓT UÓ-târ", note: { en: "= sem água quente.", "pt-BR": "= sem água quente." } }],
    dialogueSteps: [ { text: "Hiya, everything okay at the flat?", tr: { en: "Is everything okay there?", "pt-BR": "Está tudo bem no apê?" }, ear: { en: "<b>“BÓI-lâr”</b>", "pt-BR": "<b>“BÓI-lâr”</b>" }, audioPrompt: "Landlord, breezy: “Hiya, everything okay at the flat?”", basic: "No. No hot water — the boiler's dead.", fluent: "No — the boiler's died, there's no heating at all." } ] },
  { sequence: 104, blockId: 5, indexInBlock: 4, phase: 3, subBlock: "5.1", threshold: 80,
    sceneTitle: { en: "A Parcel Next Door", "pt-BR": "Encomenda na Casa do Vizinho" },
    contextDescription: { en: "A ‘Sorry we missed you’ card: your parcel was left with a neighbour you've never met. You knock to retrieve it, awkwardly.", "pt-BR": "Um cartão ‘Sorry we missed you’: sua encomenda ficou com um vizinho que você nunca viu. Você bate na porta para buscá-la, sem graça." },
    objective: { en: "Politely collect a parcel from a neighbour.", "pt-BR": "Buscar educadamente uma encomenda com o vizinho." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "Neighbour", "pt-BR": "Vizinho(a)" }, initials: "NB" },
    drills: [{ word: "a parcel", say: "a PÁR-sâl", note: { en: "= encomenda.", "pt-BR": "= encomenda." } }],
    dialogueSteps: [ { text: "Oh, the parcel? Hang on, I'll grab it.", tr: { en: "They have your parcel — wait a sec.", "pt-BR": "Eles têm sua encomenda — um segundo." }, ear: { en: "<b>“rang ón”</b> = espere", "pt-BR": "<b>“rang ón”</b> = espere" }, audioPrompt: "Neighbour, friendly: “Oh, the parcel? Hang on, I'll grab it.”", basic: "Thank you so much.", fluent: "Thanks so much — sorry for the trouble." } ] },
  { sequence: 105, blockId: 5, indexInBlock: 5, phase: 3, subBlock: "5.1", threshold: 80,
    sceneTitle: { en: "Bin Day Confusion", "pt-BR": "A Confusão da Coleta de Lixo" },
    contextDescription: { en: "Three coloured bins, alternating weeks, baffling rules. You missed collection. A neighbour explains the sacred local recycling law.", "pt-BR": "Três lixeiras coloridas, semanas alternadas, regras confusas. Você perdeu a coleta. Um vizinho explica a sagrada lei local da reciclagem." },
    objective: { en: "Understand the bin/recycling schedule.", "pt-BR": "Entender o calendário de lixo/reciclagem." },
    culturalNote: { en: "Bin day is serious. Wrong bin = a sticker of shame and no collection.", "pt-BR": "Dia do lixo é sério. Lixeira errada = adesivo de vergonha e sem coleta." },
    environment: { mood: "neutral", baseNoise: 38 },
    npc: { name: { en: "Neighbour", "pt-BR": "Vizinho(a)" }, initials: "NB" },
    drills: [{ word: "which bin?", say: "UÍTCH BÍN", note: { en: "= qual lixeira.", "pt-BR": "= qual lixeira." } }],
    dialogueSteps: [ { text: "Recycling's the green one, every other Tuesday.", tr: { en: "Green bin = recycling, alternate Tuesdays.", "pt-BR": "Lixeira verde = reciclagem, terças alternadas." }, ear: { en: "<b>“É-vri â-dâr”</b> = alternada", "pt-BR": "<b>“É-vri â-dâr”</b> = alternada" }, audioPrompt: "Neighbour, pointing at the bins: “Recycling's the green one, every other Tuesday.”", basic: "Green one, Tuesdays. Thanks!", fluent: "Got it — green bin, alternate Tuesdays. Cheers!" } ] },

  /* 5.2 — MONEY & ADMIN */
  { sequence: 106, blockId: 5, indexInBlock: 6, phase: 2, subBlock: "5.2", threshold: 80,
    sceneTitle: { en: "Decoding the Payslip", "pt-BR": "Decifrando o Holerite" },
    contextDescription: { en: "Your first payslip: gross, net, PAYE, NI, pension, ‘tax code’ gibberish — and less money than expected. You ask HR to explain the deductions.", "pt-BR": "Seu primeiro holerite: bruto, líquido, PAYE, NI, pensão, ‘tax code’ — e menos dinheiro que o esperado. Você pede ao RH para explicar os descontos." },
    objective: { en: "Ask HR to explain pay deductions.", "pt-BR": "Pedir ao RH que explique os descontos." },
    culturalNote: { en: "PAYE = tax at source, NI = social security. A wrong ‘tax code’ overcharges you.", "pt-BR": "PAYE = imposto na fonte, NI = seguridade. Um ‘tax code’ errado te cobra a mais." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "HR", "pt-BR": "RH" }, initials: "HR" },
    drills: [{ word: "the deductions", say: "dâ di-DÂK-shâns", note: { en: "= os descontos.", "pt-BR": "= os descontos." } }],
    dialogueSteps: [ { text: "What did you want to ask about your pay?", tr: { en: "What's your pay question?", "pt-BR": "Qual sua dúvida sobre o salário?" }, ear: { en: "<b>“di-DÂK-shâns”</b>", "pt-BR": "<b>“di-DÂK-shâns”</b>" }, audioPrompt: "HR, helpful: “What did you want to ask about your pay?”", basic: "Can you explain the deductions?", fluent: "Could you explain these deductions on my payslip?" } ] },
  { sequence: 107, blockId: 5, indexInBlock: 7, phase: 3, subBlock: "5.2", threshold: 80,
    sceneTitle: { en: "Splitting the Bills", "pt-BR": "Dividindo as Contas" },
    contextDescription: { en: "Flatmate meeting at the kitchen table. Who owes what for gas, electric, council tax, that one expensive month. You must negotiate a fair split.", "pt-BR": "Reunião de colegas na mesa da cozinha. Quem deve o quê de gás, luz, imposto, aquele mês caro. Você precisa negociar uma divisão justa." },
    objective: { en: "Negotiate a fair share of the bills.", "pt-BR": "Negociar uma divisão justa das contas." },
    environment: { mood: "neutral", baseNoise: 34 },
    npc: { name: { en: "Flatmate", "pt-BR": "Colega de Apê" }, initials: "FM" },
    drills: [{ word: "split it evenly", say: "splít it Í-vân-li", note: { en: "= dividir igualmente.", "pt-BR": "= dividir igualmente." } }],
    dialogueSteps: [ { text: "So how do we split this month's bills?", tr: { en: "How do we divide the bills?", "pt-BR": "Como dividimos as contas?" }, ear: { en: "<b>“splít”</b>", "pt-BR": "<b>“splít”</b>" }, audioPrompt: "Flatmate, at the table: “So how do we split this month's bills?”", basic: "Split it evenly?", fluent: "Let's split it evenly — that's fairest." } ] },
  { sequence: 108, blockId: 5, indexInBlock: 8, phase: 3, subBlock: "5.2", threshold: 80,
    sceneTitle: { en: "Appealing a Parking Ticket", "pt-BR": "Recorrendo de uma Multa" },
    contextDescription: { en: "A yellow penalty notice slapped on a friend's car you'd parked. The signage was hidden. You phone the council to contest the fine.", "pt-BR": "Uma notificação amarela colada no carro do amigo que você estacionou. A placa estava escondida. Você liga para a prefeitura para contestar a multa." },
    objective: { en: "Contest a parking fine with a reason.", "pt-BR": "Contestar uma multa de estacionamento com motivo." },
    environment: { mood: "hostile", baseNoise: 36 },
    npc: { name: { en: "Council Office", "pt-BR": "Prefeitura" }, initials: "CO" },
    drills: [{ word: "I'd like to appeal", say: "aid láik tu a-PÍL", note: { en: "= quero recorrer.", "pt-BR": "= quero recorrer." } }],
    dialogueSteps: [ { text: "You're contesting a penalty notice?", tr: { en: "Are you appealing the fine?", "pt-BR": "Você vai contestar a multa?" }, ear: { en: "<b>“a-PÍL”</b>", "pt-BR": "<b>“a-PÍL”</b>" }, audioPrompt: "Council office, bureaucratic: “You're contesting a penalty notice?”", basic: "Yes, I'd like to appeal.", fluent: "Yes — the sign was hidden, so I'd like to appeal." } ] },
  { sequence: 109, blockId: 5, indexInBlock: 9, phase: 3, subBlock: "5.2", threshold: 80,
    sceneTitle: { en: "Switching Energy Provider", "pt-BR": "Trocando de Operadora de Energia" },
    contextDescription: { en: "Your energy bill doubled overnight. You call to switch to a cheaper tariff — and must survive the ‘retention’ agent's counter-offers.", "pt-BR": "Sua conta de energia dobrou da noite para o dia. Você liga para mudar para uma tarifa mais barata — e precisa resistir às contraofertas do agente de ‘retenção’." },
    objective: { en: "Switch to a cheaper energy tariff.", "pt-BR": "Mudar para uma tarifa de energia mais barata." },
    environment: { mood: "hostile", baseNoise: 32 },
    npc: { name: { en: "Energy Agent", "pt-BR": "Atendente de Energia" }, initials: "EN" },
    drills: [{ word: "a cheaper tariff", say: "a TCHÍ-pâr TÉ-rif", note: { en: "= tarifa mais barata.", "pt-BR": "= tarifa mais barata." } }],
    dialogueSteps: [ { text: "Sorry to hear you're leaving. Can I change your mind?", tr: { en: "They'll try to keep you.", "pt-BR": "Vão tentar te segurar." }, ear: { en: "<b>“TÉ-rif”</b>", "pt-BR": "<b>“TÉ-rif”</b>" }, audioPrompt: "Retention agent, persuasive: “Sorry to hear you're leaving. Can I change your mind?”", basic: "No, I want a cheaper tariff.", fluent: "No thanks — I've found a cheaper tariff elsewhere." } ] },
  { sequence: 110, blockId: 5, indexInBlock: 10, phase: 3, subBlock: "5.2", threshold: 80,
    sceneTitle: { en: "The Overdraft Shock", "pt-BR": "O Susto do Cheque Especial" },
    contextDescription: { en: "A text: you've gone into your overdraft and fees are stacking. You call the bank to understand the charges and ask for a buffer.", "pt-BR": "Um SMS: você entrou no cheque especial e as taxas se acumulam. Você liga para o banco para entender as cobranças e pedir um limite de tolerância." },
    objective: { en: "Query overdraft fees and request help.", "pt-BR": "Questionar taxas de cheque especial e pedir ajuda." },
    environment: { mood: "hostile", baseNoise: 34 },
    npc: { name: { en: "Bank Line", "pt-BR": "Central do Banco" }, initials: "BL" },
    drills: [{ word: "overdraft fees", say: "Ô-vâr-draft fíz", note: { en: "= taxas do cheque especial.", "pt-BR": "= taxas do cheque especial." } }],
    dialogueSteps: [ { text: "You're calling about your account charges?", tr: { en: "About the fees?", "pt-BR": "Sobre as taxas?" }, ear: { en: "<b>“Ô-vâr-draft”</b>", "pt-BR": "<b>“Ô-vâr-draft”</b>" }, audioPrompt: "Bank line: “You're calling about your account charges?”", basic: "Yes, the overdraft fees.", fluent: "Yes — can you explain these overdraft fees?" } ] },

  /* 5.3 — HEALTHCARE DEEP */
  { sequence: 111, blockId: 5, indexInBlock: 11, phase: 3, subBlock: "5.3", threshold: 80,
    sceneTitle: { en: "The 8am Scramble", "pt-BR": "A Corrida das 8h" },
    contextDescription: { en: "To see a GP you must call at 8am sharp and fight through an engaged tone for the day's released slots. You finally get through — be fast and clear.", "pt-BR": "Para ver o médico (GP) você liga às 8h em ponto e luta contra o sinal de ocupado pelas vagas do dia. Você finalmente consegue — seja rápido e claro." },
    objective: { en: "Book a same-day GP appointment fast.", "pt-BR": "Agendar consulta no mesmo dia, rápido." },
    culturalNote: { en: "Same-day GP slots vanish in minutes. Have your symptom ready in one line.", "pt-BR": "As vagas do dia somem em minutos. Tenha o sintoma pronto em uma frase." },
    environment: { mood: "hostile", baseNoise: 34 },
    npc: { name: { en: "GP Receptionist", "pt-BR": "Recepção do Posto" }, initials: "GR" },
    drills: [{ word: "an appointment today", say: "ãn a-PÓINT-mânt tu-DÊI", note: { en: "= consulta hoje.", "pt-BR": "= consulta hoje." } }],
    dialogueSteps: [ { text: "Surgery. We've a few slots left this morning.", tr: { en: "A few appointments remain — be quick.", "pt-BR": "Restam poucas vagas — seja rápido." }, ear: { en: "<b>“SÂR-djâ-ri”</b> = posto", "pt-BR": "<b>“SÂR-djâ-ri”</b> = posto" }, audioPrompt: "Receptionist, rushed at 8am: “Surgery. We've a few slots left this morning.”", basic: "An appointment today, please.", fluent: "I'd like an appointment today — it's urgent." } ] },
  { sequence: 112, blockId: 5, indexInBlock: 12, phase: 2, subBlock: "5.3", threshold: 80,
    sceneTitle: { en: "At the Dentist", "pt-BR": "No Dentista" },
    contextDescription: { en: "A throbbing tooth. The receptionist asks the loaded question: “NHS or private?” — one means a wait, the other a big bill.", "pt-BR": "Um dente latejando. A recepcionista faz a pergunta capciosa: “NHS or private?” — um significa espera, o outro uma conta alta." },
    objective: { en: "Choose NHS vs private and explain the problem.", "pt-BR": "Escolher NHS ou particular e explicar o problema." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "Dental Receptionist", "pt-BR": "Recepção do Dentista" }, initials: "DR" },
    drills: [{ word: "toothache", say: "TÚTH-êik", note: { en: "= dor de dente.", "pt-BR": "= dor de dente." } }],
    dialogueSteps: [ { text: "NHS or private? And what's the problem?", tr: { en: "Public or private? What's wrong?", "pt-BR": "Público ou particular? Qual o problema?" }, ear: { en: "<b>“PRÁI-vât”</b>", "pt-BR": "<b>“PRÁI-vât”</b>" }, audioPrompt: "Receptionist: “NHS or private? And what's the problem?”", basic: "NHS. I have toothache.", fluent: "NHS, please — I've got bad toothache." } ] },
  { sequence: 113, blockId: 5, indexInBlock: 13, phase: 3, subBlock: "5.3", threshold: 80,
    sceneTitle: { en: "Collecting a Prescription", "pt-BR": "Retirando a Receita" },
    contextDescription: { en: "The GP sent a prescription to the pharmacy. You collect it and must understand the charge and how to take it.", "pt-BR": "O médico enviou a receita para a farmácia. Você a retira e precisa entender a taxa e como tomar." },
    objective: { en: "Collect a prescription and confirm instructions.", "pt-BR": "Retirar a receita e confirmar as instruções." },
    culturalNote: { en: "Prescriptions have a flat charge in England (free in Scotland/Wales).", "pt-BR": "Receitas têm taxa fixa na Inglaterra (grátis na Escócia/País de Gales)." },
    environment: { mood: "neutral", baseNoise: 32 },
    npc: { name: { en: "Pharmacist", "pt-BR": "Farmacêutico(a)" }, initials: "PH" },
    drills: [{ word: "collecting a prescription", say: "co-LÉK-tin a pris-CRÍP-shân", note: { en: "= retirar a receita.", "pt-BR": "= retirar a receita." } }],
    dialogueSteps: [ { text: "Name? Ah yes — that's nine pounds ninety.", tr: { en: "It's ready — £9.90.", "pt-BR": "Está pronta — £9,90." }, ear: { en: "<b>“pris-CRÍP-shân”</b>", "pt-BR": "<b>“pris-CRÍP-shân”</b>" }, audioPrompt: "Pharmacist, checking: “Name? Ah yes — that's nine pounds ninety.”", basic: "Here you are.", fluent: "Here you go — how often do I take it?" } ] },
  { sequence: 114, blockId: 5, indexInBlock: 14, phase: 3, subBlock: "5.3", threshold: 80,
    sceneTitle: { en: "A Cough That Won't Quit", "pt-BR": "Uma Tosse que Não Passa" },
    contextDescription: { en: "Weeks of a chesty cough. The pharmacist probes your symptoms before deciding whether to sell you something or send you to the GP.", "pt-BR": "Semanas de tosse com catarro. O farmacêutico investiga seus sintomas antes de decidir se vende algo ou te manda ao médico." },
    objective: { en: "Describe a persistent symptom in detail.", "pt-BR": "Descrever um sintoma persistente em detalhe." },
    environment: { mood: "neutral", baseNoise: 32 },
    npc: { name: { en: "Pharmacist", "pt-BR": "Farmacêutico(a)" }, initials: "PH" },
    drills: [{ word: "for two weeks", say: "for tú UÍKS", note: { en: "State duration.", "pt-BR": "Diga a duração." } }],
    dialogueSteps: [ { text: "How long have you had this cough?", tr: { en: "How long with the cough?", "pt-BR": "Há quanto tempo com a tosse?" }, ear: { en: "<b>“kóf”</b> = tosse", "pt-BR": "<b>“kóf”</b> = tosse" }, audioPrompt: "Pharmacist, concerned: “How long have you had this cough?”", basic: "For two weeks.", fluent: "About two weeks — it won't go away." } ] },
  { sequence: 115, blockId: 5, indexInBlock: 15, phase: 3, subBlock: "5.3", threshold: 80,
    sceneTitle: { en: "Reaching Out", "pt-BR": "Pedindo Ajuda" },
    contextDescription: { en: "The isolation of a new country has worn you down. You take a brave step and ask the GP about talking to someone — mental health support.", "pt-BR": "O isolamento de um país novo te desgastou. Você dá um passo corajoso e pergunta ao médico sobre conversar com alguém — apoio em saúde mental." },
    objective: { en: "Ask for mental-health support, calmly.", "pt-BR": "Pedir apoio em saúde mental, com calma." },
    culturalNote: { en: "You can self-refer to NHS talking therapies. Asking is strength, not weakness.", "pt-BR": "Você pode se encaminhar às terapias do NHS. Pedir é força, não fraqueza." },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "GP", "pt-BR": "Médico(a)" }, initials: "GP" },
    drills: [{ word: "I've been struggling", say: "aiv bin STRÂ-glin", note: { en: "= tenho me sentido mal.", "pt-BR": "= tenho me sentido mal." } }],
    dialogueSteps: [ { text: "What can I do for you today?", tr: { en: "How can I help you?", "pt-BR": "Como posso te ajudar?" }, ear: { en: "<b>“STRÂ-glin”</b>", "pt-BR": "<b>“STRÂ-glin”</b>" }, audioPrompt: "GP, gentle and unhurried: “What can I do for you today?”", basic: "I've been struggling lately.", fluent: "I've been struggling lately — I'd like to talk to someone." } ] },

  /* 5.4 — CULTURAL FLUENCY */
  { sequence: 116, blockId: 5, indexInBlock: 16, phase: 3, subBlock: "5.4", threshold: 80,
    sceneTitle: { en: "Decoding Sarcasm", "pt-BR": "Decifrando o Sarcasmo" },
    contextDescription: { en: "It's pouring again and your colleague deadpans: “Lovely weather we're having.” They mean the opposite. Catch the irony — and play along.", "pt-BR": "Chove de novo e seu colega solta, impassível: “Lovely weather we're having.” Ele quer dizer o contrário. Capte a ironia — e entre no jogo." },
    objective: { en: "Recognise and return dry British irony.", "pt-BR": "Reconhecer e devolver a ironia britânica seca." },
    culturalNote: { en: "Flat tone + a positive word about something bad = sarcasm. Match it.", "pt-BR": "Tom neutro + palavra positiva sobre algo ruim = sarcasmo. Acompanhe." },
    environment: { mood: "pleased", baseNoise: 40 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "CO" },
    drills: [{ word: "absolutely glorious", say: "ÉB-so-lut-li GLÓ-ri-âs", note: { en: "Sarcastic agreement.", "pt-BR": "Concordância sarcástica." } }],
    dialogueSteps: [ { text: "Lovely weather we're having.", tr: { en: "(Sarcastic) The weather is awful.", "pt-BR": "(Sarcástico) O tempo está horrível." }, ear: { en: "<b>“LÂV-li UÉ-dâr”</b>", "pt-BR": "<b>“LÂV-li UÉ-dâr”</b>" }, audioPrompt: "Colleague, deadpan, staring at the rain: “Lovely weather we're having.”", basic: "Oh, absolutely glorious.", fluent: "Oh, absolutely glorious — my favourite." } ] },
  { sequence: 117, blockId: 5, indexInBlock: 17, phase: 3, subBlock: "5.4", threshold: 80,
    sceneTitle: { en: "Pub Quiz Night", "pt-BR": "Noite de Quiz no Pub" },
    contextDescription: { en: "Your team needs you for the pub quiz. The quizmaster fires a question over the chatter; your team turns to you for the answer. Belonging in real time.", "pt-BR": "Seu time precisa de você no quiz do pub. O apresentador dispara uma pergunta sobre o burburinho; o time se vira para você pela resposta. Pertencimento em tempo real." },
    objective: { en: "Contribute an answer to your quiz team.", "pt-BR": "Contribuir com uma resposta para o time do quiz." },
    environment: { mood: "pleased", baseNoise: 56 },
    npc: { name: { en: "Quizmaster", "pt-BR": "Apresentador" }, initials: "QM" },
    drills: [{ word: "I reckon it's…", say: "ai RÉ-kân its", note: { en: "= acho que é… (UK).", "pt-BR": "= acho que é… (UK)." } }],
    dialogueSteps: [ { text: "Question five: capital of Australia?", tr: { en: "Quiz question — what's the answer?", "pt-BR": "Pergunta do quiz — qual a resposta?" }, ear: { en: "<b>“RÉ-kân”</b> = acho", "pt-BR": "<b>“RÉ-kân”</b> = acho" }, audioPrompt: "Quizmaster, over the pub din: “Question five: capital of Australia?”", basic: "I reckon it's Canberra.", fluent: "I reckon it's Canberra, not Sydney." } ] },
  { sequence: 118, blockId: 5, indexInBlock: 18, phase: 3, subBlock: "5.4", threshold: 80,
    sceneTitle: { en: "Which Team Do You Support?", "pt-BR": "Para Qual Time Você Torce?" },
    contextDescription: { en: "The tribal question that defines you socially: “So, who do you support?” Football allegiance is identity here. Pick a side and commit.", "pt-BR": "A pergunta tribal que te define socialmente: “So, who do you support?” Torcer por futebol é identidade aqui. Escolha um lado e assuma." },
    objective: { en: "Declare a football allegiance.", "pt-BR": "Declarar para qual time você torce." },
    culturalNote: { en: "‘Support’ a team (not ‘cheer for’). It signals your tribe — choose wisely.", "pt-BR": "‘Support’ um time (não ‘cheer for’). Sinaliza sua tribo — escolha com sabedoria." },
    environment: { mood: "pleased", baseNoise: 52 },
    npc: { name: { en: "Mate", "pt-BR": "Amigo" }, initials: "MA" },
    drills: [{ word: "I support…", say: "ai sâ-PÓRT", note: { en: "= eu torço para…", "pt-BR": "= eu torço para…" } }],
    dialogueSteps: [ { text: "So go on — who do you support?", tr: { en: "Which team do you support?", "pt-BR": "Para qual time você torce?" }, ear: { en: "<b>“sâ-PÓRT”</b>", "pt-BR": "<b>“sâ-PÓRT”</b>" }, audioPrompt: "Mate, grinning, testing you: “So go on — who do you support?”", basic: "I support Arsenal.", fluent: "Arsenal — for my sins." } ] },
  { sequence: 119, blockId: 5, indexInBlock: 19, phase: 3, subBlock: "5.4", threshold: 80,
    sceneTitle: { en: "“It's Fine.”", "pt-BR": "“Tá Tudo Bem.”" },
    contextDescription: { en: "Your flatmate says “it's fine” in a flat voice about the mess you left. It is NOT fine. Read the indirectness and apologise before it festers.", "pt-BR": "Seu colega diz “it's fine” num tom seco sobre a bagunça que você deixou. NÃO está tudo bem. Leia a indireta e peça desculpas antes que azede." },
    objective: { en: "Read British indirectness and respond.", "pt-BR": "Ler a indireta britânica e responder." },
    culturalNote: { en: "‘It's fine’ / ‘no worries’ in a flat tone often means it's NOT fine.", "pt-BR": "‘It's fine’ / ‘no worries’ em tom seco geralmente quer dizer que NÃO está." },
    environment: { mood: "hostile", baseNoise: 30 },
    npc: { name: { en: "Flatmate", "pt-BR": "Colega de Apê" }, initials: "FM" },
    drills: [{ word: "I'll sort it", say: "ail SÓRT it", note: { en: "= eu resolvo.", "pt-BR": "= eu resolvo." } }],
    dialogueSteps: [ { text: "The kitchen? No, it's... fine. Honestly.", tr: { en: "(It is NOT fine — apologise.)", "pt-BR": "(NÃO está bem — peça desculpas.)" }, ear: { en: "<b>“Ó-nâst-li”</b>", "pt-BR": "<b>“Ó-nâst-li”</b>" }, audioPrompt: "Flatmate, flat and clipped: “The kitchen? No, it's... fine. Honestly.”", basic: "Sorry — I'll sort it now.", fluent: "I can tell it's not — sorry, I'll sort it right now." } ] },
  { sequence: 120, blockId: 5, indexInBlock: 20, phase: 3, subBlock: "5.4", threshold: 80,
    sceneTitle: { en: "To Tip or Not to Tip", "pt-BR": "Dar ou Não Gorjeta" },
    contextDescription: { en: "The bill arrives with a vague ‘service charge — optional’. Tipping rules here are murky. You must navigate the awkward moment with the waiter.", "pt-BR": "A conta chega com um vago ‘service charge — optional’. As regras de gorjeta aqui são nebulosas. Você precisa navegar o momento constrangedor com o garçom." },
    objective: { en: "Handle the service-charge/tipping question.", "pt-BR": "Lidar com a questão da taxa de serviço/gorjeta." },
    culturalNote: { en: "Pubs: no tip. Restaurants: ~10–12% if service isn't already added.", "pt-BR": "Pubs: sem gorjeta. Restaurantes: ~10–12% se o serviço não vier incluso." },
    environment: { mood: "neutral", baseNoise: 42 },
    npc: { name: { en: "Waiter", "pt-BR": "Garçom" }, initials: "WA" },
    drills: [{ word: "is service included?", say: "iz SÂR-vis in-CLÚ-did", note: { en: "= o serviço está incluso?", "pt-BR": "= o serviço está incluso?" } }],
    dialogueSteps: [ { text: "Any good for you? Service isn't included.", tr: { en: "Service isn't added — tip optional.", "pt-BR": "O serviço não está incluso — gorjeta opcional." }, ear: { en: "<b>“SÂR-vis”</b>", "pt-BR": "<b>“SÂR-vis”</b>" }, audioPrompt: "Waiter, hovering with the card machine: “Any good for you? Service isn't included.”", basic: "I'll add ten percent.", fluent: "It was lovely — I'll add ten percent, thanks." } ] },

  /* 5.5 — TEST OF BELONGING */
  { sequence: 121, blockId: 5, indexInBlock: 21, phase: 3, subBlock: "5.5", threshold: 80,
    sceneTitle: { en: "Standing Up for a Friend", "pt-BR": "Defendendo um Amigo" },
    contextDescription: { en: "Someone's being rude to your friend at the bar. You step in — calm, firm, fluent. The reality-shock of confrontation in a second language, mastered.", "pt-BR": "Alguém está sendo grosseiro com seu amigo no bar. Você intervém — calmo, firme, fluente. O choque de confrontar num segundo idioma, dominado." },
    objective: { en: "Defuse a confrontation, defending a friend.", "pt-BR": "Desarmar um confronto, defendendo um amigo." },
    environment: { mood: "hostile", baseNoise: 54 },
    npc: { name: { en: "Aggressor", "pt-BR": "Provocador" }, initials: "AG" },
    drills: [{ word: "leave it, mate", say: "LÍV it, mêit", note: { en: "= deixa quieto, parceiro.", "pt-BR": "= deixa quieto, parceiro." } }],
    dialogueSteps: [ { text: "What's it got to do with you, eh?", tr: { en: "Why are you getting involved?", "pt-BR": "O que você tem a ver com isso?" }, ear: { en: "<b>“lív it”</b>", "pt-BR": "<b>“lív it”</b>" }, audioPrompt: "Aggressor, squaring up: “What's it got to do with you, eh?”", basic: "Leave it, mate. Walk away.", fluent: "Leave it, mate — let's all just walk away." } ] },
  { sequence: 122, blockId: 5, indexInBlock: 22, phase: 2, subBlock: "5.5", threshold: 80,
    sceneTitle: { en: "The Review at Work", "pt-BR": "A Avaliação no Trabalho" },
    contextDescription: { en: "Three months in, your manager calls you in for a performance review and — finally — a conversation about a pay rise. Advocate for yourself, fluently.", "pt-BR": "Três meses depois, seu gestor te chama para uma avaliação e — enfim — uma conversa sobre aumento. Defenda seu valor, com fluência." },
    objective: { en: "Advocate for a raise in a review.", "pt-BR": "Defender um aumento na avaliação." },
    environment: { mood: "neutral", baseNoise: 28 },
    npc: { name: { en: "Manager", "pt-BR": "Gestor(a)" }, initials: "MG" },
    drills: [{ word: "a pay rise", say: "a PÊI ráiz", note: { en: "= aumento (UK 'rise', US 'raise').", "pt-BR": "= aumento (UK 'rise')." } }],
    dialogueSteps: [ { text: "You've done really well. How are you feeling about the role?", tr: { en: "Praise — your opening to ask.", "pt-BR": "Elogio — sua deixa para pedir." }, ear: { en: "<b>“pêi ráiz”</b>", "pt-BR": "<b>“pêi ráiz”</b>" }, audioPrompt: "Manager, warm: “You've done really well. How are you feeling about the role?”", basic: "Great. Can we discuss a pay rise?", fluent: "Really happy — I'd love to discuss a pay rise." } ] },
  { sequence: 123, blockId: 5, indexInBlock: 23, phase: 3, subBlock: "5.5", threshold: 80,
    sceneTitle: { en: "Comforting a Newcomer", "pt-BR": "Acolhendo um Recém-Chegado" },
    contextDescription: { en: "A new arrival from back home is overwhelmed and homesick — exactly as you once were. You reassure them. The student has become the guide.", "pt-BR": "Um recém-chegado do seu país está perdido e com saudade de casa — exatamente como você esteve. Você o acolhe. O aluno virou o guia." },
    objective: { en: "Reassure and mentor a newcomer.", "pt-BR": "Tranquilizar e orientar um recém-chegado." },
    environment: { mood: "pleased", baseNoise: 34 },
    npc: { name: { en: "Newcomer", "pt-BR": "Recém-chegado(a)" }, initials: "NC" },
    drills: [{ word: "you'll be fine", say: "iúl bi FÁIN", note: { en: "= vai dar tudo certo.", "pt-BR": "= vai dar tudo certo." } }],
    dialogueSteps: [ { text: "I don't know if I can do this. It's so hard.", tr: { en: "They're struggling — reassure them.", "pt-BR": "Eles estão sofrendo — tranquilize-os." }, ear: { en: "<b>“iúl bi fáin”</b>", "pt-BR": "<b>“iúl bi fáin”</b>" }, audioPrompt: "Newcomer, near tears: “I don't know if I can do this. It's so hard.”", basic: "You'll be fine. I'll help you.", fluent: "Hey — you'll be fine. I felt the same. I'll help you." } ] },
  { sequence: 124, blockId: 5, indexInBlock: 24, phase: 3, subBlock: "5.5", threshold: 80,
    sceneTitle: { en: "A Toast to the Journey", "pt-BR": "Um Brinde à Jornada" },
    contextDescription: { en: "Your friends gather to mark how far you've come — from not ordering water to running a London life. Receive the praise; give a small, fluent speech.", "pt-BR": "Seus amigos se reúnem para celebrar o quanto você avançou — de não conseguir pedir água a tocar uma vida em Londres. Receba o elogio; faça um pequeno discurso fluente." },
    objective: { en: "Give a short heartfelt thank-you speech.", "pt-BR": "Fazer um breve discurso de agradecimento." },
    environment: { mood: "pleased", baseNoise: 46 },
    npc: { name: { en: "Best Mate", "pt-BR": "Melhor Amigo" }, initials: "BM" },
    drills: [{ word: "I couldn't have done it without you", say: "ai KÚ-dânt rév dân it ui-DÁUT iú", note: { en: "Gratitude, fluent.", "pt-BR": "Gratidão, fluente." } }],
    dialogueSteps: [ { text: "Look at you now! Say a few words, go on.", tr: { en: "Give a little speech!", "pt-BR": "Faça um discursinho!" }, ear: { en: "<b>“sÊi a fiú uârds”</b>", "pt-BR": "<b>“sÊi a fiú uârds”</b>" }, audioPrompt: "Best mate, raising a glass: “Look at you now! Say a few words, go on.”", basic: "Thank you all. Really.", fluent: "Thank you all — I couldn't have done it without you." } ] },
  { sequence: 125, blockId: 5, indexInBlock: 25, phase: 3, subBlock: "5.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "True Londoner", tagline: "True Londoner — City Conquered", shareText: "125 modules ago I couldn't order a glass of water. Today I gave a lost tourist directions in the rain. London: conquered. 🇬🇧🏆 #LinguoBound" },
    sceneTitle: { en: "Bonus — You Are the Local Now", "pt-BR": "Bônus — Agora o Local é Você" },
    contextDescription: { en: "A rainy street, a soaked tourist squinting at a phone — terrified, exactly as you were on day one. They stop YOU for help. The arc closes: the survivor has become the guide. London is yours.", "pt-BR": "Uma rua chuvosa, um turista encharcado apertando os olhos no celular — apavorado, exatamente como você no primeiro dia. Eles param VOCÊ para pedir ajuda. O ciclo se fecha: o sobrevivente virou o guia. Londres é sua." },
    objective: { en: "Help a lost tourist — the role reversal that crowns City 01.", "pt-BR": "Ajudar um turista perdido — a inversão de papéis que coroa a Cidade 01." },
    environment: { mood: "pleased", baseNoise: 50, rain: true },
    npc: { name: { en: "Lost Tourist", "pt-BR": "Turista Perdido" }, initials: "LT" },
    drills: [{ word: "no worries, I've got you", say: "nôu UÂ-riz, aiv gót iú", note: { en: "Calm, fluent reassurance.", "pt-BR": "Tranquilização calma e fluente." } }],
    dialogueSteps: [
      { text: "Excuse me — sorry — do you know how to get to the Tube?", tr: { en: "A lost tourist needs directions.", "pt-BR": "Um turista perdido precisa de direção." }, ear: { en: "<b>“dâ tiúb”</b>", "pt-BR": "<b>“dâ tiúb”</b>" }, audioPrompt: "Lost tourist, anxious in the rain: “Excuse me — sorry — do you know how to get to the Tube?”", basic: "No worries. It's this way.", fluent: "No worries, I've got you — it's just round the corner, follow me." },
      { text: "Thank you so much. You're a lifesaver!", tr: { en: "They're grateful — you did it.", "pt-BR": "Eles agradecem — você conseguiu." }, ear: { en: "<b>“LÁIF-sêi-vâr”</b>", "pt-BR": "<b>“LÁIF-sêi-vâr”</b>" }, audioPrompt: "Tourist, relieved: “Thank you so much. You're a lifesaver!”", basic: "Welcome to London!", fluent: "Anytime — and hey, welcome to London. You'll be fine." },
    ] },
];

export const BLOCK05_BY_SEQUENCE = BLOCK05_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
