/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 09 (Modules 201–225)
 *  "Advanced Social & Cultural Depth" — 5 sub-blocks:
 *    9.1 The Art of Sarcasm  (201–205) deadpan, understatement, self-deprecation
 *    9.2 The Pub Debate      (206–210) heated-but-friendly disagreement
 *    9.3 Cultural References  (211–215) history, telly, comedy you must catch
 *    9.4 Clique Dynamics     (216–220) in-jokes, hierarchy, caught in a row
 *    9.5 Cultural Insider     (221–225) you GET it now — BONUS milestone
 *  Module 225 = "Honorary Brit" milestone selfie.
 * ============================================================ */

export const BLOCK09_MODULES = [
  /* 9.1 — THE ART OF SARCASM */
  { sequence: 201, blockId: 9, indexInBlock: 1, phase: 3, subBlock: "9.1", threshold: 80,
    sceneTitle: { en: "Understatement", "pt-BR": "O Eufemismo Britânico" },
    contextDescription: { en: "You aced a brutal project. Your colleague's verdict: “Yeah, not bad, that.” In Britain that's high praise — wild enthusiasm is suspicious. Decode it, accept it coolly.", "pt-BR": "Você arrasou num projeto brutal. O veredito do colega: “Yeah, not bad, that.” Na Grã-Bretanha isso é um elogio enorme — entusiasmo demais é suspeito. Decodifique e aceite na boa." },
    objective: { en: "Read British understatement as praise.", "pt-BR": "Ler o eufemismo britânico como elogio." },
    culturalNote: { en: "‘Not bad’ = great. ‘A bit of a nightmare’ = a disaster. Dial everything down.", "pt-BR": "‘Not bad’ = ótimo. ‘A bit of a nightmare’ = um desastre. Diminua tudo." },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "CO" },
    drills: [{ word: "can't complain", say: "ként câm-PLÊIN", note: { en: "Understated ‘I'm great’.", "pt-BR": "‘Estou ótimo’ contido." } }],
    dialogueSteps: [ { text: "Yeah... not bad, that. Not bad at all.", tr: { en: "(That's strong praise.)", "pt-BR": "(Isso é um grande elogio.)" }, ear: { en: "<b>“nót béd”</b>", "pt-BR": "<b>“nót béd”</b>" }, audioPrompt: "Colleague, nodding slowly, deadpan: “Yeah... not bad, that. Not bad at all.”", basic: "Cheers. Can't complain.", fluent: "High praise, that — cheers. Can't complain." } ] },
  { sequence: 202, blockId: 9, indexInBlock: 2, phase: 3, subBlock: "9.1", threshold: 80,
    sceneTitle: { en: "Self-Deprecation", "pt-BR": "A Autodepreciação" },
    contextDescription: { en: "Someone compliments you and the only acceptable response is to playfully put yourself down. Bragging is social death here; cheerful self-mockery wins the room.", "pt-BR": "Alguém te elogia e a única resposta aceitável é se diminuir de brincadeira. Se gabar é morte social aqui; a autoironia bem-humorada conquista a sala." },
    objective: { en: "Deflect a compliment with self-deprecation.", "pt-BR": "Desviar um elogio com autoironia." },
    culturalNote: { en: "Never accept praise straight. ‘Oh, I just got lucky’ keeps you likeable.", "pt-BR": "Nunca aceite o elogio direto. ‘Oh, I just got lucky’ te mantém simpático." },
    environment: { mood: "pleased", baseNoise: 44 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "fluke, honestly", say: "FLÚK, Ó-nâst-li", note: { en: "= pura sorte.", "pt-BR": "= pura sorte." } }],
    dialogueSteps: [ { text: "Mate, you're so talented, it's annoying!", tr: { en: "They praise you — deflect it.", "pt-BR": "Eles te elogiam — desvie." }, ear: { en: "<b>“flúk”</b> = golpe de sorte", "pt-BR": "<b>“flúk”</b> = golpe de sorte" }, audioPrompt: "Friend, admiring over the noise: “Mate, you're so talented, it's annoying!”", basic: "Ha, fluke, honestly.", fluent: "Ha — total fluke, honestly. Don't tell anyone." } ] },
  { sequence: 203, blockId: 9, indexInBlock: 3, phase: 3, subBlock: "9.1", threshold: 80,
    sceneTitle: { en: "Insult as Affection", "pt-BR": "Insulto como Carinho" },
    contextDescription: { en: "Your closest mate greets you with a grinning insult: “Alright, you absolute muppet!” The deeper the friendship, the ruder the hello. Fire one back with love.", "pt-BR": "Seu melhor amigo te cumprimenta com um insulto sorridente: “Alright, you absolute muppet!” Quanto mais profunda a amizade, mais grosseiro o olá. Devolva um com carinho." },
    objective: { en: "Return an affectionate insult.", "pt-BR": "Devolver um insulto afetuoso." },
    environment: { mood: "pleased", baseNoise: 50 },
    npc: { name: { en: "Best Mate", "pt-BR": "Melhor Amigo" }, initials: "BM" },
    drills: [{ word: "alright, you melt", say: "ol-RÁIT, iú MÉLT", note: { en: "Playful comeback ('melt' = softie).", "pt-BR": "Resposta zombeteira ('melt' = molenga)." } }],
    dialogueSteps: [ { text: "Alright, you absolute muppet! Where've you been?", tr: { en: "An affectionate insult — return it.", "pt-BR": "Um insulto carinhoso — devolva." }, ear: { en: "<b>“MÂ-pât”</b> = bobalhão", "pt-BR": "<b>“MÂ-pât”</b> = bobalhão" }, audioPrompt: "Best mate, beaming, arms wide over pub roar: “Alright, you absolute muppet! Where've you been?”", basic: "Alright, you melt!", fluent: "Alright, you melt — missed you too, obviously." } ] },
  { sequence: 204, blockId: 9, indexInBlock: 4, phase: 3, subBlock: "9.1", threshold: 80,
    sceneTitle: { en: "The Deadpan Test", "pt-BR": "O Teste do Deadpan" },
    contextDescription: { en: "A stranger says something outrageous with a totally straight face. Is it serious or a wind-up? You must catch the flicker of deadpan and play along, not panic.", "pt-BR": "Um estranho diz algo absurdo com cara de paisagem total. É sério ou zoeira? Você precisa captar o lampejo do deadpan e entrar na brincadeira, sem se desesperar." },
    objective: { en: "Detect deadpan humour and respond in kind.", "pt-BR": "Detectar o humor deadpan e responder na mesma moeda." },
    environment: { mood: "neutral", baseNoise: 46 },
    npc: { name: { en: "Stranger", "pt-BR": "Estranho(a)" }, initials: "ST" },
    drills: [{ word: "you're winding me up", say: "iór UÁIN-din mi âp", note: { en: "= você está me zoando.", "pt-BR": "= você está me zoando." } }],
    dialogueSteps: [ { text: "Oh yeah, I'm actually the Queen's third cousin. Obviously.", tr: { en: "(Deadpan joke — don't take it literally.)", "pt-BR": "(Piada deadpan — não leve a sério.)" }, ear: { en: "<b>“UÁIN-din âp”</b>", "pt-BR": "<b>“UÁIN-din âp”</b>" }, audioPrompt: "Stranger, utterly straight-faced: “Oh yeah, I'm actually the Queen's third cousin. Obviously.”", basic: "Ha! You're winding me up.", fluent: "Course you are — you're totally winding me up!" } ] },
  { sequence: 205, blockId: 9, indexInBlock: 5, phase: 3, subBlock: "9.1", threshold: 80,
    sceneTitle: { en: "Landing Your Own Joke", "pt-BR": "Acertando a Própria Piada" },
    contextDescription: { en: "The big test: you crack a dry, perfectly-timed joke — in English — and the whole table erupts. The moment your humour finally works in a second language.", "pt-BR": "O grande teste: você solta uma piada seca, no timing perfeito — em inglês — e a mesa inteira explode. O momento em que seu humor finalmente funciona num segundo idioma." },
    objective: { en: "Deliver a joke with British timing.", "pt-BR": "Entregar uma piada com o timing britânico." },
    environment: { mood: "pleased", baseNoise: 52 },
    npc: { name: { en: "The Table", "pt-BR": "A Mesa" }, initials: "TT" },
    drills: [{ word: "I'll get my coat", say: "ail guét mai CÔUT", note: { en: "Self-mocking after a joke.", "pt-BR": "Autozoeira pós-piada." } }],
    dialogueSteps: [ { text: "Go on then, you've gone quiet — say something!", tr: { en: "The table dares you — land a joke.", "pt-BR": "A mesa te desafia — solte uma piada." }, ear: { en: "<b>“guét mai côut”</b>", "pt-BR": "<b>“guét mai côut”</b>" }, audioPrompt: "The table, egging you on over laughter: “Go on then, you've gone quiet — say something!”", basic: "...well, I'll get my coat!", fluent: "...and on that note, I'll get my coat!" } ] },

  /* 9.2 — THE PUB DEBATE */
  { sequence: 206, blockId: 9, indexInBlock: 6, phase: 3, subBlock: "9.2", threshold: 80,
    sceneTitle: { en: "The Hot Take", "pt-BR": "A Opinião Polêmica" },
    contextDescription: { en: "The pub talk turns to politics. Someone lobs a provocative opinion and the table goes quiet, waiting. You must enter the debate without killing the mood.", "pt-BR": "O papo do pub vira política. Alguém lança uma opinião provocativa e a mesa silencia, esperando. Você precisa entrar no debate sem estragar o clima." },
    objective: { en: "Enter a debate with a measured opinion.", "pt-BR": "Entrar num debate com uma opinião ponderada." },
    environment: { mood: "neutral", baseNoise: 50 },
    npc: { name: { en: "Debater", "pt-BR": "Debatedor(a)" }, initials: "DB" },
    drills: [{ word: "I see it differently", say: "ai sí it DÍ-frânt-li", note: { en: "Disagree softly.", "pt-BR": "Discordar com jeito." } }],
    dialogueSteps: [ { text: "Honestly, the whole system's broken. Don't you think?", tr: { en: "A provocative claim — weigh in.", "pt-BR": "Uma afirmação provocativa — opine." }, ear: { en: "<b>“DÍ-frânt-li”</b>", "pt-BR": "<b>“DÍ-frânt-li”</b>" }, audioPrompt: "Debater, leaning in over pints: “Honestly, the whole system's broken. Don't you think?”", basic: "I see it a bit differently.", fluent: "I see it differently — it's flawed, but not broken." } ] },
  { sequence: 207, blockId: 9, indexInBlock: 7, phase: 3, subBlock: "9.2", threshold: 80,
    sceneTitle: { en: "Holding Your Ground", "pt-BR": "Sustentando a Posição" },
    contextDescription: { en: "They push back hard, voice rising. You must defend your point with conviction and evidence — passionate but never personal. This is debate as a sport here.", "pt-BR": "Eles rebatem forte, a voz subindo. Você precisa defender seu ponto com convicção e argumentos — apaixonado, mas nunca pessoal. Aqui, debater é esporte." },
    objective: { en: "Defend a view with conviction, not heat.", "pt-BR": "Defender uma visão com convicção, sem esquentar." },
    environment: { mood: "hostile", baseNoise: 52 },
    npc: { name: { en: "Debater", "pt-BR": "Debatedor(a)" }, initials: "DB" },
    drills: [{ word: "hear me out", say: "RÍR mi áut", note: { en: "= me deixa explicar.", "pt-BR": "= me deixa explicar." } }],
    dialogueSteps: [ { text: "That's naive though, isn't it? Be realistic.", tr: { en: "They call you naive — push back.", "pt-BR": "Eles te chamam de ingênuo — rebata." }, ear: { en: "<b>“nai-ÍV”</b>", "pt-BR": "<b>“nai-ÍV”</b>" }, audioPrompt: "Debater, sharper now: “That's naive though, isn't it? Be realistic.”", basic: "Hear me out — the data says otherwise.", fluent: "Hear me out — it's not naive, the numbers actually back me up." } ] },
  { sequence: 208, blockId: 9, indexInBlock: 8, phase: 3, subBlock: "9.2", threshold: 80,
    sceneTitle: { en: "Playing Devil's Advocate", "pt-BR": "Advogado do Diabo" },
    contextDescription: { en: "To keep it sporting, you flip and argue the opposite side just to test it. The very British game of intellectual fencing for fun. Signal that you're playing.", "pt-BR": "Para manter o esporte, você vira e defende o lado oposto só para testar. O jogo muito britânico da esgrima intelectual por diversão. Sinalize que está brincando." },
    objective: { en: "Play devil's advocate without offence.", "pt-BR": "Bancar o advogado do diabo sem ofender." },
    environment: { mood: "neutral", baseNoise: 50 },
    npc: { name: { en: "Debater", "pt-BR": "Debatedor(a)" }, initials: "DB" },
    drills: [{ word: "devil's advocate", say: "DÉ-vâls ÉD-vâ-kât", note: { en: "= advogado do diabo.", "pt-BR": "= advogado do diabo." } }],
    dialogueSteps: [ { text: "Wait, now you're arguing the other side?!", tr: { en: "They're confused — clarify the game.", "pt-BR": "Eles se confundem — explique o jogo." }, ear: { en: "<b>“ÉD-vâ-kât”</b>", "pt-BR": "<b>“ÉD-vâ-kât”</b>" }, audioPrompt: "Debater, laughing, exasperated: “Wait, now you're arguing the other side?!”", basic: "Just devil's advocate!", fluent: "Just playing devil's advocate — keeps it interesting!" } ] },
  { sequence: 209, blockId: 9, indexInBlock: 9, phase: 3, subBlock: "9.2", threshold: 80,
    sceneTitle: { en: "Agree to Disagree", "pt-BR": "Concordar em Discordar" },
    contextDescription: { en: "Neither side will budge, but no one's actually upset — that's the magic. You must close the debate gracefully, the British way, with respect and a fresh round.", "pt-BR": "Nenhum lado cede, mas ninguém está realmente bravo — essa é a mágica. Você precisa encerrar o debate com elegância, do jeito britânico, com respeito e uma nova rodada." },
    objective: { en: "Close a debate amicably.", "pt-BR": "Encerrar um debate de forma amigável." },
    environment: { mood: "pleased", baseNoise: 48 },
    npc: { name: { en: "Debater", "pt-BR": "Debatedor(a)" }, initials: "DB" },
    drills: [{ word: "agree to disagree", say: "a-GRÍ tu dis-a-GRÍ", note: { en: "= concordar em discordar.", "pt-BR": "= concordar em discordar." } }],
    dialogueSteps: [ { text: "We're never going to agree on this, are we?", tr: { en: "Time to wrap it up amicably.", "pt-BR": "Hora de encerrar amigavelmente." }, ear: { en: "<b>“dis-a-GRÍ”</b>", "pt-BR": "<b>“dis-a-GRÍ”</b>" }, audioPrompt: "Debater, grinning, raising a glass: “We're never going to agree on this, are we?”", basic: "Agree to disagree. Another round?", fluent: "Let's agree to disagree — and you're getting the next round." } ] },
  { sequence: 210, blockId: 9, indexInBlock: 10, phase: 3, subBlock: "9.2", threshold: 80,
    sceneTitle: { en: "The Brexit Minefield", "pt-BR": "O Campo Minado do Brexit" },
    contextDescription: { en: "The most dangerous topic of all surfaces. Strong feelings, family rifts, raw nerves. As a newcomer you must navigate it with tact — listen, acknowledge, don't lecture.", "pt-BR": "O tema mais perigoso de todos surge. Sentimentos fortes, rachaduras familiares, nervos à flor da pele. Como recém-chegado você precisa navegar com tato — ouvir, reconhecer, não dar lição." },
    objective: { en: "Navigate a divisive topic diplomatically.", "pt-BR": "Navegar um tema divisivo com diplomacia." },
    culturalNote: { en: "Brexit still splits families. As a newcomer, listen more than you opine.", "pt-BR": "O Brexit ainda divide famílias. Como recém-chegado, ouça mais do que opine." },
    environment: { mood: "hostile", baseNoise: 48 },
    npc: { name: { en: "Local", "pt-BR": "Local" }, initials: "LO" },
    drills: [{ word: "I can see both sides", say: "ai kén sí bôuth sáids", note: { en: "Stay diplomatic.", "pt-BR": "Mantenha a diplomacia." } }],
    dialogueSteps: [ { text: "Go on — what do YOU make of it all, then?", tr: { en: "They want your take — be careful.", "pt-BR": "Querem sua opinião — cuidado." }, ear: { en: "<b>“méik âv it”</b>", "pt-BR": "<b>“méik âv it”</b>" }, audioPrompt: "Local, testing you, a hush at the table: “Go on — what do YOU make of it all, then?”", basic: "Honestly, I can see both sides.", fluent: "Honestly — I can see both sides, and I'm still learning the history." } ] },

  /* 9.3 — CULTURAL REFERENCES */
  { sequence: 211, blockId: 9, indexInBlock: 11, phase: 3, subBlock: "9.3", threshold: 80,
    sceneTitle: { en: "The Reference You Missed", "pt-BR": "A Referência que Você Não Pegou" },
    contextDescription: { en: "Everyone howls at a quote from a classic sitcom — and you have no idea what it means. Pretending kills you slowly; admitting it, with curiosity, wins you a teacher.", "pt-BR": "Todos gargalham com uma citação de uma sitcom clássica — e você não faz ideia do que significa. Fingir te mata aos poucos; admitir, com curiosidade, te dá um professor." },
    objective: { en: "Admit you missed a reference, with curiosity.", "pt-BR": "Admitir que não pegou a referência, com curiosidade." },
    culturalNote: { en: "Only Fools and Horses, Fawlty Towers, The Office — the shared comedy canon.", "pt-BR": "Only Fools and Horses, Fawlty Towers, The Office — o cânone cômico compartilhado." },
    environment: { mood: "pleased", baseNoise: 46 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "what's that from?", say: "uâts dét frâm", note: { en: "Ask the source.", "pt-BR": "Pergunte a origem." } }],
    dialogueSteps: [ { text: "“He who dares, Rodney!” — classic, eh?", tr: { en: "A sitcom quote you don't know.", "pt-BR": "Uma citação de sitcom que você não conhece." }, ear: { en: "<b>“rí ru DÉRZ”</b>", "pt-BR": "<b>“rí ru DÉRZ”</b>" }, audioPrompt: "Friend, quoting and laughing: “‘He who dares, Rodney!’ — classic, eh?”", basic: "Ha — what's that from?", fluent: "I'm laughing along but — what's that actually from?" } ] },
  { sequence: 212, blockId: 9, indexInBlock: 12, phase: 3, subBlock: "9.3", threshold: 80,
    sceneTitle: { en: "“Don't Mention the War”", "pt-BR": "“Não Fale da Guerra”" },
    contextDescription: { en: "An older Londoner makes a wry WWII joke that carries the whole weight of national memory. You must respond with the right blend of humour and respect.", "pt-BR": "Um londrino mais velho faz uma piada irônica sobre a Segunda Guerra que carrega todo o peso da memória nacional. Você precisa responder com a dose certa de humor e respeito." },
    objective: { en: "Respond to a historical/national reference respectfully.", "pt-BR": "Responder a uma referência histórica/nacional com respeito." },
    culturalNote: { en: "‘The war’, the Blitz, ‘keep calm and carry on’ — deep national identity. Tread kindly.", "pt-BR": "‘A guerra’, a Blitz, ‘keep calm and carry on’ — identidade nacional profunda. Pise com cuidado." },
    environment: { mood: "neutral", baseNoise: 40 },
    npc: { name: { en: "Older Local", "pt-BR": "Senhor(a) Local" }, initials: "OL" },
    drills: [{ word: "the Blitz spirit", say: "dâ BLÍTS SPÍ-rit", note: { en: "Wartime resilience myth.", "pt-BR": "O mito da resiliência da guerra." } }],
    dialogueSteps: [ { text: "We got through the Blitz, we'll get through anything!", tr: { en: "A proud wartime reference.", "pt-BR": "Uma referência orgulhosa à guerra." }, ear: { en: "<b>“blíts”</b>", "pt-BR": "<b>“blíts”</b>" }, audioPrompt: "Older local, wry but proud: “We got through the Blitz, we'll get through anything!”", basic: "That Blitz spirit, eh?", fluent: "That famous Blitz spirit — you don't make 'em like that anymore." } ] },
  { sequence: 213, blockId: 9, indexInBlock: 13, phase: 3, subBlock: "9.3", threshold: 80,
    sceneTitle: { en: "Royal Gossip", "pt-BR": "Fofoca da Realeza" },
    contextDescription: { en: "The nation's favourite soap opera — the Royals — comes up. Some adore them, some can't stand them. You must have a light opinion without stepping on a landmine.", "pt-BR": "A novela favorita da nação — a Realeza — entra na conversa. Uns adoram, outros não suportam. Você precisa ter uma opinião leve sem pisar numa mina." },
    objective: { en: "Hold a light opinion on the monarchy.", "pt-BR": "Ter uma opinião leve sobre a monarquia." },
    environment: { mood: "pleased", baseNoise: 42 },
    npc: { name: { en: "Neighbour", "pt-BR": "Vizinho(a)" }, initials: "NB" },
    drills: [{ word: "I stay out of it", say: "ai stêi áut âv it", note: { en: "Diplomatic neutrality.", "pt-BR": "Neutralidade diplomática." } }],
    dialogueSteps: [ { text: "Did you see the latest royal drama? Scandalous!", tr: { en: "Royal gossip — react lightly.", "pt-BR": "Fofoca real — reaja com leveza." }, ear: { en: "<b>“SKÉN-dâ-lâs”</b>", "pt-BR": "<b>“SKÉN-dâ-lâs”</b>" }, audioPrompt: "Neighbour, gleeful: “Did you see the latest royal drama? Scandalous!”", basic: "Ha, I try to stay out of it!", fluent: "Honestly, it's better than telly — but I stay out of it!" } ] },
  { sequence: 214, blockId: 9, indexInBlock: 14, phase: 3, subBlock: "9.3", threshold: 80,
    sceneTitle: { en: "Rhyming Slang", "pt-BR": "A Gíria que Rima" },
    contextDescription: { en: "An old cabbie hits you with Cockney rhyming slang: “Use your loaf!” (loaf of bread = head). A secret code within the language. You must twig what it means.", "pt-BR": "Um taxista veterano te solta uma gíria cockney que rima: “Use your loaf!” (loaf of bread = head/cabeça). Um código secreto dentro da língua. Você precisa sacar o que significa." },
    objective: { en: "Decode a piece of Cockney rhyming slang.", "pt-BR": "Decodificar uma gíria cockney que rima." },
    culturalNote: { en: "Cockney: ‘plates of meat’=feet, ‘dog and bone’=phone, ‘loaf’=head. London's code.", "pt-BR": "Cockney: ‘plates of meat’=pés, ‘dog and bone’=telefone, ‘loaf’=cabeça. O código de Londres." },
    environment: { mood: "neutral", baseNoise: 48 },
    npc: { name: { en: "Cabbie", "pt-BR": "Taxista" }, initials: "CB" },
    drills: [{ word: "use your loaf", say: "iúz iór LÔUF", note: { en: "= use a cabeça.", "pt-BR": "= use a cabeça." } }],
    dialogueSteps: [ { text: "Quicker on foot, innit — use your loaf!", tr: { en: "‘Use your loaf’ = use your head.", "pt-BR": "‘Use your loaf’ = use a cabeça." }, ear: { en: "<b>“lôuf”</b> = cabeça (gíria)", "pt-BR": "<b>“lôuf”</b> = cabeça (gíria)" }, audioPrompt: "Cabbie, chuckling: “Quicker on foot, innit — use your loaf!”", basic: "Ha — use my head, right?", fluent: "Use my loaf — got it. You're testing me!" } ] },
  { sequence: 215, blockId: 9, indexInBlock: 15, phase: 3, subBlock: "9.3", threshold: 80,
    sceneTitle: { en: "Getting the Joke First", "pt-BR": "Pegando a Piada Primeiro" },
    contextDescription: { en: "A reference drops — and this time YOU get it before anyone explains, and laugh at exactly the right moment. The invisible membrane of culture finally lets you through.", "pt-BR": "Cai uma referência — e desta vez VOCÊ entende antes de qualquer explicação e ri exatamente na hora certa. A membrana invisível da cultura finalmente te deixa passar." },
    objective: { en: "Catch a cultural reference in real time.", "pt-BR": "Pegar uma referência cultural em tempo real." },
    environment: { mood: "pleased", baseNoise: 50 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "lovely jubbly!", say: "LÂV-li DJÂB-li", note: { en: "Classic sitcom catchphrase.", "pt-BR": "Bordão clássico de sitcom." } }],
    dialogueSteps: [ { text: "...and I said the deal was—", tr: { en: "You can finish the famous line!", "pt-BR": "Você consegue completar a frase famosa!" }, ear: { en: "<b>“LÂV-li DJÂB-li”</b>", "pt-BR": "<b>“LÂV-li DJÂB-li”</b>" }, audioPrompt: "Friend, setting up the catchphrase: “...and I said the deal was—”", basic: "—lovely jubbly!", fluent: "—lovely jubbly! See? I'm learning the classics." } ] },

  /* 9.4 — CLIQUE DYNAMICS */
  { sequence: 216, blockId: 9, indexInBlock: 16, phase: 3, subBlock: "9.4", threshold: 80,
    sceneTitle: { en: "The In-Joke Wall", "pt-BR": "O Muro das Piadas Internas" },
    contextDescription: { en: "A tight friend group laughs at a story you weren't there for. You feel the outsider chill. You must ask in — curious, not needy — to be let through the wall.", "pt-BR": "Um grupo unido ri de uma história que você não viveu. Você sente o frio do estranho. Você precisa pedir para entrar — curioso, não carente — para atravessar o muro." },
    objective: { en: "Break into an in-joke gracefully.", "pt-BR": "Entrar numa piada interna com jeito." },
    environment: { mood: "neutral", baseNoise: 48 },
    npc: { name: { en: "Group Member", "pt-BR": "Membro do Grupo" }, initials: "GM" },
    drills: [{ word: "okay, you have to explain", say: "ô-KÊI, iú rév tu iks-PLÊIN", note: { en: "Ask in with a smile.", "pt-BR": "Peça para entrar sorrindo." } }],
    dialogueSteps: [ { text: "—and the goat was STILL on the roof! You had to be there.", tr: { en: "An in-joke you missed — ask in.", "pt-BR": "Uma piada interna que você perdeu — peça para entrar." }, ear: { en: "<b>“rûf”</b> = telhado", "pt-BR": "<b>“rûf”</b> = telhado" }, audioPrompt: "Group member, mid-laugh: “—and the goat was STILL on the roof! You had to be there.”", basic: "Okay, you HAVE to explain!", fluent: "A goat on a roof? Right, someone has to explain this one!" } ] },
  { sequence: 217, blockId: 9, indexInBlock: 17, phase: 3, subBlock: "9.4", threshold: 80,
    sceneTitle: { en: "The Subtle Snub", "pt-BR": "O Desprezo Sutil" },
    contextDescription: { en: "One member of the group clearly doesn't rate you — a cool tone, a pointed exclusion from plans. You must win them over with warmth, not confrontation.", "pt-BR": "Um membro do grupo claramente não vai com a sua cara — um tom frio, uma exclusão proposital dos planos. Você precisa conquistá-lo com simpatia, não confronto." },
    objective: { en: "Win over a frosty group member.", "pt-BR": "Conquistar um membro frio do grupo." },
    environment: { mood: "hostile", baseNoise: 44 },
    npc: { name: { en: "Frosty Member", "pt-BR": "Membro Frio" }, initials: "FM" },
    drills: [{ word: "we should hang out", say: "ui shúd RÉNG áut", note: { en: "Offer to connect.", "pt-BR": "Ofereça-se para se aproximar." } }],
    dialogueSteps: [ { text: "Oh. You're coming on Saturday too, are you.", tr: { en: "A cold welcome — warm them up.", "pt-BR": "Uma recepção fria — aqueça-os." }, ear: { en: "<b>“RÉNG áut”</b>", "pt-BR": "<b>“RÉNG áut”</b>" }, audioPrompt: "Frosty member, flat and unimpressed: “Oh. You're coming on Saturday too, are you.”", basic: "I'd love to. We should hang out.", fluent: "I am — and honestly, we should hang out properly sometime." } ] },
  { sequence: 218, blockId: 9, indexInBlock: 18, phase: 3, subBlock: "9.4", threshold: 80,
    sceneTitle: { en: "Caught in the Middle", "pt-BR": "No Meio do Fogo Cruzado" },
    contextDescription: { en: "Two friends have fallen out and both want you on their side. You must stay loyal to both without picking one — the diplomatic tightrope of belonging to a group.", "pt-BR": "Dois amigos brigaram e os dois te querem do lado deles. Você precisa ser leal a ambos sem escolher um — a corda bamba diplomática de pertencer a um grupo." },
    objective: { en: "Stay neutral between two feuding friends.", "pt-BR": "Manter-se neutro entre dois amigos brigados." },
    environment: { mood: "hostile", baseNoise: 30 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "I'm not taking sides", say: "aim nót têi-kin SÁIDS", note: { en: "= não vou tomar partido.", "pt-BR": "= não vou tomar partido." } }],
    dialogueSteps: [ { text: "You're on my side though, right? Tell me I'm right.", tr: { en: "They want you to pick a side.", "pt-BR": "Querem que você escolha um lado." }, ear: { en: "<b>“têi-kin sáids”</b>", "pt-BR": "<b>“têi-kin sáids”</b>" }, audioPrompt: "Friend, hurt and insistent: “You're on my side though, right? Tell me I'm right.”", basic: "I love you both. No sides.", fluent: "I care about you both — I'm honestly not taking sides on this." } ] },
  { sequence: 219, blockId: 9, indexInBlock: 19, phase: 3, subBlock: "9.4", threshold: 80,
    sceneTitle: { en: "Earning Your Place", "pt-BR": "Conquistando Seu Lugar" },
    contextDescription: { en: "A real moment: you do something thoughtful for the group, and the frosty member finally thaws — “You're actually alright, you.” Quiet acceptance, hard-earned.", "pt-BR": "Um momento real: você faz algo gentil pelo grupo e o membro frio finalmente derrete — “You're actually alright, you.” Aceitação silenciosa, suada." },
    objective: { en: "Accept hard-won acceptance gracefully.", "pt-BR": "Aceitar com graça uma aceitação suada." },
    environment: { mood: "pleased", baseNoise: 42 },
    npc: { name: { en: "Former Frosty", "pt-BR": "Ex-Frio" }, initials: "FF" },
    drills: [{ word: "you're alright too", say: "iór ol-RÁIT tú", note: { en: "Return the warmth, low-key.", "pt-BR": "Devolva o carinho, discreto." } }],
    dialogueSteps: [ { text: "You know what? You're actually alright, you.", tr: { en: "They've accepted you.", "pt-BR": "Eles te aceitaram." }, ear: { en: "<b>“ol-RÁIT, iú”</b>", "pt-BR": "<b>“ol-RÁIT, iú”</b>" }, audioPrompt: "Former frosty member, grudging warmth: “You know what? You're actually alright, you.”", basic: "Ha — you're alright too.", fluent: "Coming from you, that means a lot — you're alright too." } ] },
  { sequence: 220, blockId: 9, indexInBlock: 20, phase: 3, subBlock: "9.4", threshold: 80,
    sceneTitle: { en: "An Inside Joke of Your Own", "pt-BR": "Uma Piada Interna Sua" },
    contextDescription: { en: "Months later: something happens, and now there's a running joke that started with YOU — the group references it, and you're at the centre of the in-crowd. You've arrived.", "pt-BR": "Meses depois: algo acontece e agora há uma piada recorrente que começou com VOCÊ — o grupo a cita, e você está no centro do círculo. Você chegou." },
    objective: { en: "Be the source of the group's in-joke.", "pt-BR": "Ser a origem da piada interna do grupo." },
    environment: { mood: "pleased", baseNoise: 50 },
    npc: { name: { en: "The Group", "pt-BR": "O Grupo" }, initials: "GR" },
    drills: [{ word: "never living that down", say: "NÉ-vâr LÍ-vin dét dáun", note: { en: "= nunca vão me deixar esquecer.", "pt-BR": "= nunca vão me deixar esquecer." } }],
    dialogueSteps: [ { text: "Do the thing! You know — the THING!", tr: { en: "You're the in-joke now.", "pt-BR": "A piada interna agora é você." }, ear: { en: "<b>“dú dâ thíng”</b>", "pt-BR": "<b>“dú dâ thíng”</b>" }, audioPrompt: "The group, chanting and laughing: “Do the thing! You know — the THING!”", basic: "Never living that down!", fluent: "Oh, I'm never living that down, am I — go on then!" } ] },

  /* 9.5 — CULTURAL INSIDER */
  { sequence: 221, blockId: 9, indexInBlock: 21, phase: 3, subBlock: "9.5", threshold: 80,
    sceneTitle: { en: "Explaining Britain", "pt-BR": "Explicando a Grã-Bretanha" },
    contextDescription: { en: "A brand-new expat is baffled by the things that once baffled you — queue rules, ‘you alright?’, the tea hierarchy. You explain it all, fluent and patient. Full circle.", "pt-BR": "Um expat recém-chegado está perdido com as coisas que um dia te confundiram — regras de fila, ‘you alright?’, a hierarquia do chá. Você explica tudo, fluente e paciente. Ciclo completo." },
    objective: { en: "Explain British customs to a newer expat.", "pt-BR": "Explicar os costumes britânicos a um expat mais novo." },
    environment: { mood: "pleased", baseNoise: 40 },
    npc: { name: { en: "New Expat", "pt-BR": "Novo Expat" }, initials: "NE" },
    drills: [{ word: "you'll get used to it", say: "iúl guét IÚST tu it", note: { en: "= você se acostuma.", "pt-BR": "= você se acostuma." } }],
    dialogueSteps: [ { text: "Why does everyone say sorry when I bump THEM?!", tr: { en: "Explain the ‘sorry’ reflex.", "pt-BR": "Explique o reflexo do ‘sorry’." }, ear: { en: "<b>“iúst tu it”</b>", "pt-BR": "<b>“iúst tu it”</b>" }, audioPrompt: "New expat, bewildered: “Why does everyone say sorry when I bump THEM?!”", basic: "Ha! You'll get used to it.", fluent: "It's a reflex here — trust me, you'll be doing it in a month." } ] },
  { sequence: 222, blockId: 9, indexInBlock: 22, phase: 3, subBlock: "9.5", threshold: 80,
    sceneTitle: { en: "“You're Basically British”", "pt-BR": "“Você é Praticamente Britânico”" },
    contextDescription: { en: "After a perfectly-timed sarcastic remark, a local shakes their head in delight: “Honestly, you're basically British now.” The highest compliment they have. Receive it.", "pt-BR": "Depois de um comentário sarcástico no timing perfeito, um local balança a cabeça encantado: “Honestly, you're basically British now.” O maior elogio que eles têm. Receba-o." },
    objective: { en: "Accept being called ‘basically British’.", "pt-BR": "Aceitar ser chamado de ‘praticamente britânico’." },
    environment: { mood: "pleased", baseNoise: 46 },
    npc: { name: { en: "Local Friend", "pt-BR": "Amigo Local" }, initials: "LF" },
    drills: [{ word: "high praise indeed", say: "rai prêiz in-DÍD", note: { en: "Accept with dry wit.", "pt-BR": "Aceite com humor seco." } }],
    dialogueSteps: [ { text: "Honestly? You're basically British now.", tr: { en: "The ultimate compliment.", "pt-BR": "O elogio máximo." }, ear: { en: "<b>“BÊI-sik-li”</b>", "pt-BR": "<b>“BÊI-sik-li”</b>" }, audioPrompt: "Local friend, shaking head, impressed: “Honestly? You're basically British now.”", basic: "High praise indeed!", fluent: "High praise indeed — I'll take that as a knighthood." } ] },
  { sequence: 223, blockId: 9, indexInBlock: 23, phase: 3, subBlock: "9.5", threshold: 80,
    sceneTitle: { en: "Reading the Room", "pt-BR": "Lendo o Ambiente" },
    contextDescription: { en: "A subtle social moment goes tense — someone's upset but pretending not to be. You read the unspoken signals instantly and steer the group kindly past it. Mastery.", "pt-BR": "Um momento social sutil fica tenso — alguém está chateado mas finge que não. Você lê os sinais não ditos na hora e conduz o grupo gentilmente para longe disso. Maestria." },
    objective: { en: "Read and ease an unspoken social tension.", "pt-BR": "Ler e aliviar uma tensão social não dita." },
    environment: { mood: "neutral", baseNoise: 38 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "shall we change the subject?", say: "shâl ui tchêindj dâ SÂB-djekt", note: { en: "Smoothly redirect.", "pt-BR": "Redirecione com suavidade." } }],
    dialogueSteps: [ { text: "No, no, it's fine. Everything's fine.", tr: { en: "(It's clearly NOT fine — ease it.)", "pt-BR": "(Claramente NÃO está bem — alivie.)" }, ear: { en: "<b>“its fáin”</b>", "pt-BR": "<b>“its fáin”</b>" }, audioPrompt: "Friend, tight voice, clearly not fine: “No, no, it's fine. Everything's fine.”", basic: "Shall we change the subject?", fluent: "Let's change the subject — who fancies another drink?" } ] },
  { sequence: 224, blockId: 9, indexInBlock: 24, phase: 3, subBlock: "9.5", threshold: 80,
    sceneTitle: { en: "Dreaming in English", "pt-BR": "Sonhando em Inglês" },
    contextDescription: { en: "A friend asks a quiet, profound question: what language do you think in now? You realise the answer has changed — and what that means about who you've become.", "pt-BR": "Um amigo faz uma pergunta quieta e profunda: em que língua você pensa agora? Você percebe que a resposta mudou — e o que isso significa sobre quem você se tornou." },
    objective: { en: "Reflect on thinking in your second language.", "pt-BR": "Refletir sobre pensar no seu segundo idioma." },
    environment: { mood: "pleased", baseNoise: 28 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "I dreamt in English", say: "ai drémt in ÍN-glish", note: { en: "A milestone of fluency.", "pt-BR": "Um marco da fluência." } }],
    dialogueSteps: [ { text: "Random question — what language do you think in now?", tr: { en: "Which language do you think in?", "pt-BR": "Em que idioma você pensa agora?" }, ear: { en: "<b>“thínk in”</b>", "pt-BR": "<b>“thínk in”</b>" }, audioPrompt: "Friend, thoughtful and quiet: “Random question — what language do you think in now?”", basic: "English, lately. I dreamt in English!", fluent: "English, lately — I even dreamt in English last week. Wild." } ] },
  { sequence: 225, blockId: 9, indexInBlock: 25, phase: 3, subBlock: "9.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "Honorary Brit", tagline: "Honorary Brit — Fluent in the Unspoken", shareText: "I get the sarcasm, win the pub debate, catch the references and read the room — they say I'm basically British now. Fluent in the unspoken. 🇬🇧😏 #LinguoBound" },
    sceneTitle: { en: "Bonus — One of the Locals", "pt-BR": "Bônus — Um dos Locais" },
    contextDescription: { en: "A perfect London evening: your group, your pub, your in-jokes, the banter flowing both ways at full speed — and you're not keeping up, you're leading it. The language isn't a wall anymore. It's home.", "pt-BR": "Uma noite perfeita em Londres: seu grupo, seu pub, suas piadas internas, a zoeira fluindo nos dois sentidos em alta velocidade — e você não está acompanhando, você está liderando. A língua não é mais um muro. É um lar." },
    objective: { en: "Revel in total social fluency.", "pt-BR": "Celebrar a fluência social total." },
    environment: { mood: "pleased", baseNoise: 50 },
    npc: { name: { en: "The Group", "pt-BR": "O Grupo" }, initials: "GR" },
    drills: [{ word: "this round's on me", say: "dis ráunds ón mi", note: { en: "The insider's gesture.", "pt-BR": "O gesto de quem é da casa." } }],
    dialogueSteps: [
      { text: "Mate, when did you get this funny? You're one of us!", tr: { en: "You're truly in the group now.", "pt-BR": "Agora você é do grupo de verdade." }, ear: { en: "<b>“uân âv âs”</b>", "pt-BR": "<b>“uân âv âs”</b>" }, audioPrompt: "The group, roaring with laughter around you: “Mate, when did you get this funny? You're one of us!”", basic: "Always was! This round's on me.", fluent: "Always have been — now shush, this round's on me!" },
      { text: "Honestly couldn't imagine the group without you now.", tr: { en: "You belong completely.", "pt-BR": "Você pertence completamente." }, ear: { en: "<b>“i-MÉ-djin”</b>", "pt-BR": "<b>“i-MÉ-djin”</b>" }, audioPrompt: "Best mate, sincere under the laughter: “Honestly couldn't imagine the group without you now.”", basic: "Couldn't imagine it either.", fluent: "Neither could I — feels like I've always been here." },
    ] },
];

export const BLOCK09_BY_SEQUENCE = BLOCK09_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
