/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 14 (Modules 326–350)
 *  "The Long-Term Resident" — 5 sub-blocks:
 *    14.1 The Body Keeps Score (326–330) long-term health on the NHS
 *    14.2 Building for the Future (331–335) pensions, mortgage, real money talk
 *    14.3 The City of Ghosts   (336–340) watching the city change over years
 *    14.4 Passing the Torch    (341–345) becoming a mentor to a newcomer
 *    14.5 A London Institution (346–350) full circle — BONUS milestone (350)
 *  Module 350 = "A London Institution" milestone selfie.
 * ============================================================ */

export const BLOCK14_MODULES = [
  /* 14.1 — THE BODY KEEPS SCORE */
  { sequence: 326, blockId: 14, indexInBlock: 1, phase: 2, subBlock: "14.1", threshold: 80,
    sceneTitle: { en: "The GP Check-Up", "pt-BR": "A Consulta no Clínico Geral" },
    contextDescription: { en: "Years in, your body sends its first real warning. At the GP surgery you must describe ongoing symptoms precisely — vague English here could cost you a proper diagnosis.", "pt-BR": "Anos depois, seu corpo manda o primeiro aviso de verdade. No consultório do clínico geral (GP) você precisa descrever sintomas contínuos com precisão — um inglês vago aqui pode te custar um diagnóstico correto." },
    objective: { en: "Describe ongoing symptoms precisely to a GP.", "pt-BR": "Descrever sintomas contínuos com precisão ao clínico geral." },
    culturalNote: { en: "In the UK your ‘GP’ (general practitioner) is the gateway to all NHS care — you usually see them before any specialist.", "pt-BR": "No Reino Unido seu ‘GP’ (clínico geral) é a porta de entrada de todo o SUS britânico (NHS) — você costuma vê-lo antes de qualquer especialista." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "GP (Doctor)", "pt-BR": "Clínico Geral" }, initials: "GP" },
    drills: [{ word: "it's been going on for", say: "its bín GÔU-in on fôr", note: { en: "= isso já dura há…", "pt-BR": "= isso já dura há…" } }, { word: "on and off", say: "ón ând ÓF", note: { en: "= de vez em quando / intermitente.", "pt-BR": "= de vez em quando / intermitente." } }],
    dialogueSteps: [ { text: "So, what brings you in today? Take your time.", tr: { en: "Describe it clearly.", "pt-BR": "Descreva com clareza." }, ear: { en: "<b>“ón ând ÓF”</b>", "pt-BR": "<b>“ón ând ÓF”</b>" }, audioPrompt: "GP, calm and unhurried in a quiet surgery: “So, what brings you in today? Take your time.”", basic: "I've had chest pain, on and off, for weeks.", fluent: "I've had a tightness in my chest, on and off — it's been going on for a few weeks now." } ] },
  { sequence: 327, blockId: 14, indexInBlock: 2, phase: 2, subBlock: "14.1", threshold: 80,
    sceneTitle: { en: "The Referral", "pt-BR": "O Encaminhamento" },
    contextDescription: { en: "The GP refers you to a specialist and explains the NHS waiting list. You must ask the right questions about timelines and what to watch for — advocating for yourself politely but firmly.", "pt-BR": "O clínico te encaminha a um especialista e explica a fila de espera do NHS. Você precisa fazer as perguntas certas sobre prazos e sinais de alerta — defendendo a si mesmo com educação, mas firmeza." },
    objective: { en: "Ask informed questions about a referral.", "pt-BR": "Fazer perguntas embasadas sobre um encaminhamento." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "GP (Doctor)", "pt-BR": "Clínico Geral" }, initials: "GP" },
    drills: [{ word: "how long is the wait?", say: "ráu lóng iz dâ UÊIT", note: { en: "= quanto tempo é a espera?", "pt-BR": "= quanto tempo é a espera?" } }, { word: "what should I watch for?", say: "uât shud ai UÓTCH fôr", note: { en: "= a que devo ficar atento?", "pt-BR": "= a que devo ficar atento?" } }],
    dialogueSteps: [ { text: "I'm referring you to cardiology. The wait can be a few months, I'm afraid.", tr: { en: "Advocate for yourself.", "pt-BR": "Defenda a si mesmo." }, ear: { en: "<b>“ráu lóng iz dâ UÊIT”</b>", "pt-BR": "<b>“ráu lóng iz dâ UÊIT”</b>" }, audioPrompt: "GP, writing a referral: “I'm referring you to cardiology. The wait can be a few months, I'm afraid.”", basic: "A few months — what should I watch for meanwhile?", fluent: "I understand the wait — but what symptoms should I watch for, and when should I come straight back?" } ] },
  { sequence: 328, blockId: 14, indexInBlock: 3, phase: 2, subBlock: "14.1", threshold: 80,
    sceneTitle: { en: "Managing It Long-Term", "pt-BR": "Gerenciando a Longo Prazo" },
    contextDescription: { en: "The diagnosis is manageable but chronic — something you'll carry for life. The consultant explains a long-term plan. You must understand medication and lifestyle changes well enough to live by them.", "pt-BR": "O diagnóstico é controlável, mas crônico — algo que você vai carregar pela vida. O especialista explica um plano de longo prazo. Você precisa entender a medicação e as mudanças de estilo de vida bem o bastante para segui-las." },
    objective: { en: "Confirm understanding of a long-term care plan.", "pt-BR": "Confirmar o entendimento de um plano de cuidado de longo prazo." },
    environment: { mood: "neutral", baseNoise: 20 },
    npc: { name: { en: "Consultant", "pt-BR": "Especialista" }, initials: "Cn" },
    drills: [{ word: "just to make sure I've got this right", say: "djâst tu mêik shur aiv gót dis RÁIT", note: { en: "= só para garantir que entendi certo.", "pt-BR": "= só para garantir que entendi certo." } }],
    dialogueSteps: [ { text: "Take this daily, cut the salt, keep active. Manage it, and you'll be fine.", tr: { en: "Confirm you understand.", "pt-BR": "Confirme que entendeu." }, ear: { en: "<b>“gót dis RÁIT”</b>", "pt-BR": "<b>“gót dis RÁIT”</b>" }, audioPrompt: "Consultant, reassuring and clear: “Take this daily, cut the salt, keep active. Manage it, and you'll be fine.”", basic: "Just to make sure I've got this right — daily, every day?", fluent: "Let me check I've got this right: one tablet daily, less salt, stay active — and come back if anything changes?" } ] },
  { sequence: 329, blockId: 14, indexInBlock: 4, phase: 3, subBlock: "14.1", threshold: 80,
    sceneTitle: { en: "At the Pharmacy, Again", "pt-BR": "Na Farmácia, De Novo" },
    contextDescription: { en: "Setting up a repeat prescription, you chat with the pharmacist who's known you for years. A small, ordinary scene that shows how far you've come from the terrified newcomer who couldn't ask for a plaster.", "pt-BR": "Organizando uma receita de uso contínuo, você bate papo com o farmacêutico que te conhece há anos. Uma cena pequena e corriqueira que mostra o quão longe você chegou desde o recém-chegado aterrorizado que não sabia pedir um curativo." },
    objective: { en: "Arrange a repeat prescription with ease.", "pt-BR": "Organizar uma receita de uso contínuo com naturalidade." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Pharmacist", "pt-BR": "Farmacêutico" }, initials: "Ph" },
    drills: [{ word: "set up a repeat prescription", say: "sét âp a ri-PÍT pris-CRÍP-shân", note: { en: "= organizar uma receita de uso contínuo.", "pt-BR": "= organizar uma receita de uso contínuo." } }],
    dialogueSteps: [ { text: "Same as usual? I can set you up on repeats so you don't have to keep asking.", tr: { en: "Handle it like a local.", "pt-BR": "Resolva como um local." }, ear: { en: "<b>“ri-PÍT pris-CRÍP-shân”</b>", "pt-BR": "<b>“ri-PÍT pris-CRÍP-shân”</b>" }, audioPrompt: "Pharmacist, friendly, recognising you: “Same as usual? I can set you up on repeats so you don't have to keep asking.”", basic: "Yes please — set up a repeat prescription.", fluent: "That'd be great — set me up on repeats. Cheers, you've saved me a job!" } ] },
  { sequence: 330, blockId: 14, indexInBlock: 5, phase: 2, subBlock: "14.1", threshold: 80,
    sceneTitle: { en: "Telling Family Back Home", "pt-BR": "Contando à Família Lá de Casa" },
    contextDescription: { en: "You must phone home about your health — without terrifying them across an ocean. You translate medical English into reassurance in your first language, protecting them while being honest.", "pt-BR": "Você precisa ligar para casa sobre sua saúde — sem aterrorizá-los do outro lado do oceano. Você traduz o inglês médico em tranquilidade na sua primeira língua, protegendo-os enquanto é honesto." },
    objective: { en: "Reassure worried family without hiding the truth.", "pt-BR": "Tranquilizar a família preocupada sem esconder a verdade." },
    environment: { mood: "neutral", baseNoise: 22 },
    npc: { name: { en: "Mother", "pt-BR": "Mãe" }, initials: "Mã" },
    drills: [{ word: "it's under control", say: "its ân-dâr cân-TRÔUL", note: { en: "= está sob controle.", "pt-BR": "= está sob controle." } }],
    dialogueSteps: [ { text: "You're so far away and I can't even be there. Is it serious?", tr: { en: "Reassure honestly.", "pt-BR": "Tranquilize com honestidade." }, ear: { en: "<b>“ân-dâr cân-TRÔUL”</b>", "pt-BR": "<b>“ân-dâr cân-TRÔUL”</b>" }, audioPrompt: "Mother, frightened and helpless on the phone: “You're so far away and I can't even be there. Is it serious?”", basic: "It's under control, Mum. Don't worry.", fluent: "It's manageable, Mum — honestly, it's under control. The doctors here are looking after me well." } ] },

  /* 14.2 — BUILDING FOR THE FUTURE */
  { sequence: 331, blockId: 14, indexInBlock: 6, phase: 2, subBlock: "14.2", threshold: 80,
    sceneTitle: { en: "Meeting the Financial Adviser", "pt-BR": "Reunião com o Consultor Financeiro" },
    contextDescription: { en: "You sit with a financial adviser to plan a future you finally believe you'll have here: pension, savings, investments. You must discuss long-term money goals in confident, precise English.", "pt-BR": "Você se senta com um consultor financeiro para planejar um futuro que finalmente acredita que terá aqui: aposentadoria, poupança, investimentos. Você precisa discutir metas financeiras de longo prazo num inglês confiante e preciso." },
    objective: { en: "Discuss long-term financial goals clearly.", "pt-BR": "Discutir metas financeiras de longo prazo com clareza." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Financial Adviser", "pt-BR": "Consultor Financeiro" }, initials: "FA" },
    drills: [{ word: "I want to plan for the long term", say: "ai uânt tu plén fôr dâ lóng TÂRM", note: { en: "= quero planejar a longo prazo.", "pt-BR": "= quero planejar a longo prazo." } }],
    dialogueSteps: [ { text: "Let's start with the big picture. Where do you see yourself in twenty years?", tr: { en: "State your goals.", "pt-BR": "Declare suas metas." }, ear: { en: "<b>“lóng TÂRM”</b>", "pt-BR": "<b>“lóng TÂRM”</b>" }, audioPrompt: "Financial adviser, professional and warm: “Let's start with the big picture. Where do you see yourself in twenty years?”", basic: "Right here. I want to plan for the long term.", fluent: "Honestly? Right here, settled. I want to plan properly for the long term now." } ] },
  { sequence: 332, blockId: 14, indexInBlock: 7, phase: 2, subBlock: "14.2", threshold: 80,
    sceneTitle: { en: "Pensions and Jargon", "pt-BR": "Aposentadoria e Jargão" },
    contextDescription: { en: "The adviser buries you in terms — workplace pension, ISA, compound interest, drawdown. Rather than nod blankly (the old you), you must stop them and ask for plain explanations.", "pt-BR": "O consultor te soterra de termos — pensão da empresa, ISA, juros compostos, saque programado. Em vez de balançar a cabeça sem entender (o antigo você), você precisa interrompê-lo e pedir explicações simples." },
    objective: { en: "Ask for jargon to be explained in plain terms.", "pt-BR": "Pedir que o jargão seja explicado em termos simples." },
    culturalNote: { en: "An ‘ISA’ is a UK tax-free savings/investment account — a staple of British personal finance worth asking about.", "pt-BR": "Uma ‘ISA’ é uma conta de poupança/investimento isenta de imposto no Reino Unido — um pilar das finanças pessoais britânicas que vale a pena conhecer." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Financial Adviser", "pt-BR": "Consultor Financeiro" }, initials: "FA" },
    drills: [{ word: "could you put that in plain English?", say: "cud iú put dét in plêin ÍN-glish", note: { en: "= dá pra explicar em miúdos?", "pt-BR": "= dá pra explicar em miúdos?" } }],
    dialogueSteps: [ { text: "So with drawdown versus an annuity, your decumulation strategy—", tr: { en: "Stop and ask for clarity.", "pt-BR": "Interrompa e peça clareza." }, ear: { en: "<b>“plêin ÍN-glish”</b>", "pt-BR": "<b>“plêin ÍN-glish”</b>" }, audioPrompt: "Financial adviser, rattling off jargon quickly: “So with drawdown versus an annuity, your decumulation strategy—”", basic: "Sorry — could you put that in plain English?", fluent: "Hang on — could you put that in plain English? I want to actually understand what I'm choosing." } ] },
  { sequence: 333, blockId: 14, indexInBlock: 8, phase: 2, subBlock: "14.2", threshold: 80,
    sceneTitle: { en: "The Mortgage Meeting", "pt-BR": "A Reunião do Financiamento" },
    contextDescription: { en: "At the bank, you apply for a mortgage — to buy a home in the city that was once just a stopover. The mortgage adviser probes your finances. You must answer with confidence and ask sharp questions.", "pt-BR": "No banco, você solicita um financiamento imobiliário — para comprar uma casa na cidade que um dia foi só uma escala. O consultor de crédito investiga suas finanças. Você precisa responder com confiança e fazer perguntas afiadas." },
    objective: { en: "Navigate a mortgage application confidently.", "pt-BR": "Conduzir uma solicitação de financiamento com confiança." },
    environment: { mood: "neutral", baseNoise: 26 },
    npc: { name: { en: "Mortgage Adviser", "pt-BR": "Consultor de Crédito" }, initials: "MA" },
    drills: [{ word: "what's the interest rate?", say: "uâts dâ ÍN-trâst rêit", note: { en: "= qual é a taxa de juros?", "pt-BR": "= qual é a taxa de juros?" } }, { word: "fixed or variable?", say: "fíkst ôr VÉ-ri-â-bâl", note: { en: "= prefixada ou pós/variável?", "pt-BR": "= prefixada ou pós/variável?" } }],
    dialogueSteps: [ { text: "Based on your income, we could offer you a mortgage in principle today.", tr: { en: "Ask the sharp questions.", "pt-BR": "Faça as perguntas afiadas." }, ear: { en: "<b>“ÍN-trâst rêit”</b>", "pt-BR": "<b>“ÍN-trâst rêit”</b>" }, audioPrompt: "Mortgage adviser, positive across the desk: “Based on your income, we could offer you a mortgage in principle today.”", basic: "Great. What's the interest rate — fixed or variable?", fluent: "That's great news — what's the interest rate, and would you recommend fixed or variable right now?" } ] },
  { sequence: 334, blockId: 14, indexInBlock: 9, phase: 3, subBlock: "14.2", threshold: 80,
    sceneTitle: { en: "Getting the Keys", "pt-BR": "Pegando as Chaves" },
    contextDescription: { en: "The estate agent hands you the keys to your own London home. The newcomer who once begged for a hostel bed now owns a piece of the city. You're almost too moved to speak — but you must.", "pt-BR": "O corretor te entrega as chaves da sua própria casa em Londres. O recém-chegado que um dia implorou por uma cama em albergue agora é dono de um pedaço da cidade. Você está quase emocionado demais para falar — mas precisa." },
    objective: { en: "Mark a milestone moment with the right words.", "pt-BR": "Marcar um momento decisivo com as palavras certas." },
    environment: { mood: "pleased", baseNoise: 32 },
    npc: { name: { en: "Estate Agent", "pt-BR": "Corretor de Imóveis" }, initials: "EA" },
    drills: [{ word: "I never thought I'd see the day", say: "ai NÉ-vâr thót aid sí dâ DÊI", note: { en: "= nunca pensei que veria esse dia.", "pt-BR": "= nunca pensei que veria esse dia." } }],
    dialogueSteps: [ { text: "Congratulations. They're all yours. Welcome home.", tr: { en: "Let the moment land.", "pt-BR": "Deixe o momento ressoar." }, ear: { en: "<b>“UÉL-câm rôum”</b>", "pt-BR": "<b>“UÉL-câm rôum”</b>" }, audioPrompt: "Estate agent, smiling, jangling keys on a doorstep: “Congratulations. They're all yours. Welcome home.”", basic: "I never thought I'd see the day. Thank you.", fluent: "I never thought I'd see the day — a home of my own, here. Thank you, truly." } ] },
  { sequence: 335, blockId: 14, indexInBlock: 10, phase: 2, subBlock: "14.2", threshold: 80,
    sceneTitle: { en: "A Will and a Future", "pt-BR": "Um Testamento e um Futuro" },
    contextDescription: { en: "With a solicitor, you write a will and put your affairs in order — the most adult, permanent statement that this is where your life now is. A sober, grounding conversation about legacy.", "pt-BR": "Com um advogado, você redige um testamento e organiza suas pendências — a declaração mais adulta e definitiva de que é aqui que sua vida está agora. Uma conversa séria e enraizadora sobre legado." },
    objective: { en: "Discuss long-term legacy and wishes clearly.", "pt-BR": "Discutir legado e desejos de longo prazo com clareza." },
    environment: { mood: "neutral", baseNoise: 20 },
    npc: { name: { en: "Solicitor", "pt-BR": "Advogado" }, initials: "So" },
    drills: [{ word: "I'd like to put my affairs in order", say: "aid láik tu put mai â-FÉRZ in ÔR-dâr", note: { en: "= quero deixar tudo em ordem.", "pt-BR": "= quero deixar tudo em ordem." } }],
    dialogueSteps: [ { text: "And who would you like to be your main beneficiaries?", tr: { en: "State your wishes calmly.", "pt-BR": "Declare seus desejos com calma." }, ear: { en: "<b>“â-FÉRZ in ÔR-dâr”</b>", "pt-BR": "<b>“â-FÉRZ in ÔR-dâr”</b>" }, audioPrompt: "Solicitor, formal and gentle: “And who would you like to be your main beneficiaries?”", basic: "My family, here and back home.", fluent: "I'd like to provide for my family — both the one here and the one back home. They're all mine." } ] },

  /* 14.3 — THE CITY OF GHOSTS */
  { sequence: 336, blockId: 14, indexInBlock: 11, phase: 3, subBlock: "14.3", threshold: 80,
    sceneTitle: { en: "Where the Old Pub Was", "pt-BR": "Onde Era o Pub Antigo" },
    contextDescription: { en: "You walk past the spot where the pub you first made friends in used to be — now luxury flats. You stop a stranger and find yourself, astonishingly, being the one who remembers ‘the old days’.", "pt-BR": "Você passa pelo lugar onde ficava o pub em que fez seus primeiros amigos — agora apartamentos de luxo. Você para um estranho e se vê, surpreendentemente, sendo aquele que lembra ‘dos velhos tempos’." },
    objective: { en: "Reminisce about a vanished local landmark.", "pt-BR": "Relembrar um marco local que desapareceu." },
    environment: { mood: "neutral", baseNoise: 48 },
    npc: { name: { en: "Young Local", "pt-BR": "Jovem Local" }, initials: "YL" },
    drills: [{ word: "there used to be", say: "dér IÚST tu bi", note: { en: "= costumava haver / antes tinha.", "pt-BR": "= costumava haver / antes tinha." } }, { word: "back in the day", say: "bék in dâ DÊI", note: { en: "= naquela época / antigamente.", "pt-BR": "= naquela época / antigamente." } }],
    dialogueSteps: [ { text: "Those flats? They've always been here, haven't they?", tr: { en: "You're the one who remembers.", "pt-BR": "Você é quem lembra." }, ear: { en: "<b>“dér IÚST tu bi”</b>", "pt-BR": "<b>“dér IÚST tu bi”</b>" }, audioPrompt: "Young local, glancing up from their phone, traffic passing: “Those flats? They've always been here, haven't they?”", basic: "No — there used to be a great pub here.", fluent: "Believe it or not, there used to be a brilliant old pub right here. Back in the day, that's where everyone met." } ] },
  { sequence: 337, blockId: 14, indexInBlock: 12, phase: 3, subBlock: "14.3", threshold: 80,
    sceneTitle: { en: "The New Wave of Newcomers", "pt-BR": "A Nova Leva de Recém-Chegados" },
    contextDescription: { en: "On the Tube, a visibly lost newcomer with a suitcase studies a map in panic — a mirror of your first day. You lean over and offer the kindness a stranger once didn't offer you.", "pt-BR": "No metrô, um recém-chegado visivelmente perdido com uma mala estuda um mapa em pânico — um espelho do seu primeiro dia. Você se inclina e oferece a gentileza que um estranho um dia não te ofereceu." },
    objective: { en: "Offer unprompted help to a lost newcomer.", "pt-BR": "Oferecer ajuda espontânea a um recém-chegado perdido." },
    environment: { mood: "pleased", baseNoise: 58 },
    npc: { name: { en: "Lost Newcomer", "pt-BR": "Recém-Chegado Perdido" }, initials: "LN" },
    drills: [{ word: "need a hand?", say: "níd a RÉND", note: { en: "= precisa de uma ajuda?", "pt-BR": "= precisa de uma ajuda?" } }, { word: "you'll get the hang of it", say: "iúl guét dâ RÉNG âv it", note: { en: "= você vai pegar o jeito.", "pt-BR": "= você vai pegar o jeito." } }],
    dialogueSteps: [ { text: "Sorry — sorry, do you know which way is... Camden? My English is bad.", tr: { en: "Help, like you once needed.", "pt-BR": "Ajude, como você um dia precisou." }, ear: { en: "<b>“níd a RÉND”</b>", "pt-BR": "<b>“níd a RÉND”</b>" }, audioPrompt: "Lost newcomer, flustered over rattling Tube noise: “Sorry — sorry, do you know which way is... Camden? My English is bad.”", basic: "Need a hand? You'll get the hang of it.", fluent: "Need a hand? Camden's two stops that way — and don't worry, your English is fine. You'll get the hang of it." } ] },
  { sequence: 338, blockId: 14, indexInBlock: 13, phase: 3, subBlock: "14.3", threshold: 80,
    sceneTitle: { en: "The Reunion of Old Friends", "pt-BR": "O Reencontro de Velhos Amigos" },
    contextDescription: { en: "You gather with the original crew from your early days — scattered now, greyer, changed. You reminisce and reflect on a decade together in this city. Bittersweet, warm, real.", "pt-BR": "Você se reúne com a turma original dos seus primeiros tempos — espalhados agora, mais grisalhos, mudados. Vocês relembram e refletem sobre uma década juntos nesta cidade. Agridoce, caloroso, real." },
    objective: { en: "Reflect warmly on years of shared history.", "pt-BR": "Refletir com carinho sobre anos de história compartilhada." },
    environment: { mood: "pleased", baseNoise: 44 },
    npc: { name: { en: "Old Friend", "pt-BR": "Amigo Antigo" }, initials: "OF" },
    drills: [{ word: "we've come a long way", say: "uív câm a lóng UÊI", note: { en: "= a gente percorreu um longo caminho.", "pt-BR": "= a gente percorreu um longo caminho." } }],
    dialogueSteps: [ { text: "Remember when none of us could afford more than one pint? Look at us now.", tr: { en: "Reflect on the journey.", "pt-BR": "Reflita sobre a jornada." }, ear: { en: "<b>“câm a lóng UÊI”</b>", "pt-BR": "<b>“câm a lóng UÊI”</b>" }, audioPrompt: "Old friend, laughing fondly over pub chatter: “Remember when none of us could afford more than one pint? Look at us now.”", basic: "We've come a long way, haven't we?", fluent: "God, do I — and look at us now. We've come a long way together, all of us." } ] },
  { sequence: 339, blockId: 14, indexInBlock: 14, phase: 2, subBlock: "14.3", threshold: 80,
    sceneTitle: { en: "Defending the City's Soul", "pt-BR": "Defendendo a Alma da Cidade" },
    contextDescription: { en: "At a council consultation about yet another development, you stand as a long-term resident and speak — not against all change, but for protecting what makes the area human. A measured, powerful argument.", "pt-BR": "Numa consulta pública da prefeitura sobre mais um empreendimento, você se levanta como morador antigo e fala — não contra toda mudança, mas pela proteção do que torna o bairro humano. Um argumento ponderado e potente." },
    objective: { en: "Argue thoughtfully at a public consultation.", "pt-BR": "Argumentar com ponderação numa consulta pública." },
    environment: { mood: "neutral", baseNoise: 36 },
    npc: { name: { en: "Council Planner", "pt-BR": "Planejador da Prefeitura" }, initials: "CP" },
    drills: [{ word: "progress shouldn't erase people", say: "PRÓ-gres shu-dânt i-RÊIS PÍ-pâl", note: { en: "= o progresso não deveria apagar as pessoas.", "pt-BR": "= o progresso não deveria apagar as pessoas." } }],
    dialogueSteps: [ { text: "And why should the committee oppose this profitable development?", tr: { en: "Make the human case.", "pt-BR": "Faça o argumento humano." }, ear: { en: "<b>“i-RÊIS PÍ-pâl”</b>", "pt-BR": "<b>“i-RÊIS PÍ-pâl”</b>" }, audioPrompt: "Council planner, formal at a public meeting: “And why should the committee oppose this profitable development?”", basic: "Progress shouldn't erase the people here.", fluent: "I'm not against progress — but progress shouldn't erase the people who make this place a home." } ] },
  { sequence: 340, blockId: 14, indexInBlock: 15, phase: 3, subBlock: "14.3", threshold: 80,
    sceneTitle: { en: "My City, Warts and All", "pt-BR": "Minha Cidade, Com Defeitos e Tudo" },
    contextDescription: { en: "A visiting relative complains about London's grime, cost and grey skies. To your own surprise, you find yourself defending the city — fiercely, lovingly. It has become unmistakably yours.", "pt-BR": "Um parente em visita reclama da sujeira, do custo e do céu cinza de Londres. Para sua própria surpresa, você se vê defendendo a cidade — com ardor, com amor. Ela se tornou, inconfundivelmente, sua." },
    objective: { en: "Defend your adopted city with genuine love.", "pt-BR": "Defender sua cidade adotiva com amor genuíno." },
    environment: { mood: "neutral", baseNoise: 50 },
    npc: { name: { en: "Visiting Relative", "pt-BR": "Parente em Visita" }, initials: "VR" },
    drills: [{ word: "you grow to love it", say: "iú grôu tu LÂV it", note: { en: "= a gente aprende a amar.", "pt-BR": "= a gente aprende a amar." } }],
    dialogueSteps: [ { text: "How do you live here? It's grey, it's dirty, it's so expensive!", tr: { en: "Defend your city.", "pt-BR": "Defenda sua cidade." }, ear: { en: "<b>“grôu tu LÂV it”</b>", "pt-BR": "<b>“grôu tu LÂV it”</b>" }, audioPrompt: "Visiting relative, complaining on a busy street: “How do you live here? It's grey, it's dirty, it's so expensive!”", basic: "It's got a soul. You grow to love it.", fluent: "It's grey and dear, sure — but it's got a soul like nowhere else. You grow to love it, warts and all." } ] },

  /* 14.4 — PASSING THE TORCH */
  { sequence: 341, blockId: 14, indexInBlock: 16, phase: 2, subBlock: "14.4", threshold: 80,
    sceneTitle: { en: "The Newcomer Who Reminds You of You", "pt-BR": "O Recém-Chegado Que Lembra Você" },
    contextDescription: { en: "A terrified new immigrant, fresh off the plane and barely able to speak, is assigned to you to mentor. You see your younger self in their eyes. You must reassure them the way no one reassured you.", "pt-BR": "Um novo imigrante aterrorizado, recém-saído do avião e mal conseguindo falar, é designado para você orientar. Você vê seu eu mais jovem nos olhos dele. Você precisa tranquilizá-lo como ninguém te tranquilizou." },
    objective: { en: "Reassure a frightened newcomer with empathy.", "pt-BR": "Tranquilizar um recém-chegado assustado com empatia." },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "New Immigrant", "pt-BR": "Novo Imigrante" }, initials: "NI" },
    drills: [{ word: "I was exactly where you are", say: "ai uâz ig-ZÉKT-li uér iú ÁR", note: { en: "= eu estive exatamente onde você está.", "pt-BR": "= eu estive exatamente onde você está." } }],
    dialogueSteps: [ { text: "I'm sorry... I can't do this. Everyone speaks so fast. I want to go home.", tr: { en: "Reassure them, as no one did you.", "pt-BR": "Tranquilize-o, como ninguém fez por você." }, ear: { en: "<b>“uér iú ÁR”</b>", "pt-BR": "<b>“uér iú ÁR”</b>" }, audioPrompt: "New immigrant, on the edge of tears, voice shaking: “I'm sorry... I can't do this. Everyone speaks so fast. I want to go home.”", basic: "Hey. I was exactly where you are. It gets better.", fluent: "Listen to me — I was exactly where you are, terrified, ready to quit. It gets better, I promise. We'll do this together." } ] },
  { sequence: 342, blockId: 14, indexInBlock: 17, phase: 3, subBlock: "14.4", threshold: 80,
    sceneTitle: { en: "Teaching the Survival Ropes", "pt-BR": "Ensinando as Manhas de Sobrevivência" },
    contextDescription: { en: "You walk your mentee through the very first survival skills you once fumbled — the Oyster card, ordering a coffee, the polite ‘sorry’. You teach the exact lessons this app first taught you.", "pt-BR": "Você guia seu pupilo pelas primeiras habilidades de sobrevivência que você um dia atrapalhou — o cartão Oyster, pedir um café, o ‘sorry’ educado. Você ensina exatamente as lições que este app te ensinou primeiro." },
    objective: { en: "Coach a beginner through basic survival English.", "pt-BR": "Treinar um iniciante no inglês básico de sobrevivência." },
    environment: { mood: "pleased", baseNoise: 52 },
    npc: { name: { en: "Mentee", "pt-BR": "Pupilo" }, initials: "Mn" },
    drills: [{ word: "just repeat after me", say: "djâst ri-PÍT Á-ftâr mi", note: { en: "= é só repetir depois de mim.", "pt-BR": "= é só repetir depois de mim." } }],
    dialogueSteps: [ { text: "But what if I say it wrong and they laugh at me?", tr: { en: "Coach them gently.", "pt-BR": "Treine-o com gentileza." }, ear: { en: "<b>“ri-PÍT Á-ftâr mi”</b>", "pt-BR": "<b>“ri-PÍT Á-ftâr mi”</b>" }, audioPrompt: "Mentee, nervous beside you at a coffee counter, café noise: “But what if I say it wrong and they laugh at me?”", basic: "Nobody laughs. Just repeat after me.", fluent: "Nobody's going to laugh — and if they do, who cares? Just repeat after me, you've got this." } ] },
  { sequence: 343, blockId: 14, indexInBlock: 18, phase: 2, subBlock: "14.4", threshold: 80,
    sceneTitle: { en: "The Pep Talk", "pt-BR": "A Conversa de Incentivo" },
    contextDescription: { en: "Your mentee fails an interview and crashes, ready to give up. You must lift them out of the pit you once lived in — with honesty about how hard it is, and faith that they'll make it.", "pt-BR": "Seu pupilo se sai mal numa entrevista e desaba, pronto para desistir. Você precisa tirá-lo do buraco em que você um dia viveu — com honestidade sobre o quão difícil é, e fé de que ele vai conseguir." },
    objective: { en: "Motivate someone through a low moment.", "pt-BR": "Motivar alguém num momento de baixa." },
    environment: { mood: "neutral", baseNoise: 24 },
    npc: { name: { en: "Mentee", "pt-BR": "Pupilo" }, initials: "Mn" },
    drills: [{ word: "don't give up now", say: "dôunt guív ÂP náu", note: { en: "= não desista agora.", "pt-BR": "= não desista agora." } }, { word: "look how far you've come", say: "luk ráu FÁR iúv câm", note: { en: "= olha o quanto você já avançou.", "pt-BR": "= olha o quanto você já avançou." } }],
    dialogueSteps: [ { text: "I'm not cut out for this. Maybe I should just go back.", tr: { en: "Lift them up.", "pt-BR": "Levante-o." }, ear: { en: "<b>“guív ÂP”</b>", "pt-BR": "<b>“guív ÂP”</b>" }, audioPrompt: "Mentee, deflated and defeated after a rejection: “I'm not cut out for this. Maybe I should just go back.”", basic: "Don't give up now. Look how far you've come.", fluent: "Don't you dare give up now — look how far you've already come. One ‘no’ isn't the end. I believe in you." } ] },
  { sequence: 344, blockId: 14, indexInBlock: 19, phase: 3, subBlock: "14.4", threshold: 80,
    sceneTitle: { en: "Their First Win", "pt-BR": "A Primeira Vitória Dele" },
    contextDescription: { en: "Your mentee bursts in, glowing — they handled a real conversation in English on their own, no help. You celebrate their breakthrough as proudly as if it were your own. The torch passes.", "pt-BR": "Seu pupilo entra radiante — encarou uma conversa de verdade em inglês sozinho, sem ajuda. Você celebra a conquista dele com tanto orgulho como se fosse sua. A tocha é passada." },
    objective: { en: "Celebrate a mentee's breakthrough genuinely.", "pt-BR": "Celebrar genuinamente a conquista de um pupilo." },
    environment: { mood: "pleased", baseNoise: 34 },
    npc: { name: { en: "Mentee", "pt-BR": "Pupilo" }, initials: "Mn" },
    drills: [{ word: "I'm so proud of you", say: "aim sôu PRÁUD âv iú", note: { en: "= estou tão orgulhoso de você.", "pt-BR": "= estou tão orgulhoso de você." } }],
    dialogueSteps: [ { text: "I did it! I ordered, I joked with him, I understood everything! On my own!", tr: { en: "Celebrate their win.", "pt-BR": "Celebre a vitória dele." }, ear: { en: "<b>“PRÁUD âv iú”</b>", "pt-BR": "<b>“PRÁUD âv iú”</b>" }, audioPrompt: "Mentee, bursting with joy, breathless: “I did it! I ordered, I joked with him, I understood everything! On my own!”", basic: "I'm so proud of you! See? I told you.", fluent: "Look at you! I'm so proud — and you did that all on your own. This is just the beginning." } ] },
  { sequence: 345, blockId: 14, indexInBlock: 20, phase: 2, subBlock: "14.4", threshold: 80,
    sceneTitle: { en: "“How Can I Repay You?”", "pt-BR": "“Como Posso Te Retribuir?”" },
    contextDescription: { en: "Your mentee, now finding their feet, asks how they could ever repay you. You give the only answer that matters: pass it on to the next frightened soul who arrives. The cycle continues.", "pt-BR": "Seu pupilo, agora se firmando, pergunta como poderia um dia te retribuir. Você dá a única resposta que importa: passe adiante para a próxima alma assustada que chegar. O ciclo continua." },
    objective: { en: "Ask only that kindness be passed forward.", "pt-BR": "Pedir apenas que a gentileza seja passada adiante." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Mentee", "pt-BR": "Pupilo" }, initials: "Mn" },
    drills: [{ word: "pass it on", say: "pés it ÓN", note: { en: "= passe adiante.", "pt-BR": "= passe adiante." } }],
    dialogueSteps: [ { text: "You changed my whole life here. How could I ever repay you?", tr: { en: "Tell them to pay it forward.", "pt-BR": "Diga para retribuir adiante." }, ear: { en: "<b>“pés it ÓN”</b>", "pt-BR": "<b>“pés it ÓN”</b>" }, audioPrompt: "Mentee, deeply sincere and grateful: “You changed my whole life here. How could I ever repay you?”", basic: "Just pass it on. Help the next one.", fluent: "You don't repay me — you pass it on. One day, help the next frightened newcomer. That's all I ask." } ] },

  /* 14.5 — A LONDON INSTITUTION (milestone 350) */
  { sequence: 346, blockId: 14, indexInBlock: 21, phase: 3, subBlock: "14.5", threshold: 80,
    sceneTitle: { en: "The Regular", "pt-BR": "O Freguês da Casa" },
    contextDescription: { en: "At your local café, they start your order before you reach the counter and ask after your family by name. You are no longer a customer; you are a fixture. You banter like the local you've become.", "pt-BR": "No seu café de sempre, começam seu pedido antes de você chegar ao balcão e perguntam pela sua família pelo nome. Você não é mais um cliente; é parte do lugar. Você troca zoeira como o local que se tornou." },
    objective: { en: "Banter as a beloved local regular.", "pt-BR": "Trocar zoeira como um freguês querido da casa." },
    environment: { mood: "pleased", baseNoise: 40 },
    npc: { name: { en: "Café Owner", "pt-BR": "Dono do Café" }, initials: "CÓ" },
    drills: [{ word: "you read my mind", say: "iú ríd mai MÁIND", note: { en: "= você leu meus pensamentos.", "pt-BR": "= você leu meus pensamentos." } }],
    dialogueSteps: [ { text: "Your usual's already on. And how's the family keeping?", tr: { en: "You're part of the furniture now.", "pt-BR": "Você já faz parte do lugar." }, ear: { en: "<b>“ríd mai MÁIND”</b>", "pt-BR": "<b>“ríd mai MÁIND”</b>" }, audioPrompt: "Café owner, already making your coffee, warm: “Your usual's already on. And how's the family keeping?”", basic: "You read my mind! They're great, cheers.", fluent: "You read my mind, as always! They're all great, thanks for asking — same to yours." } ] },
  { sequence: 347, blockId: 14, indexInBlock: 22, phase: 2, subBlock: "14.5", threshold: 80,
    sceneTitle: { en: "The Citizenship Decision", "pt-BR": "A Decisão da Cidadania" },
    contextDescription: { en: "You sit with the citizenship application before you — the final, formal acceptance that this is home. You discuss the weight of it with a friend: keeping your roots while claiming a new belonging.", "pt-BR": "Você se senta com o pedido de cidadania à sua frente — a aceitação final e formal de que aqui é um lar. Você conversa sobre o peso disso com um amigo: manter as raízes enquanto reivindica um novo pertencimento." },
    objective: { en: "Express the meaning of claiming citizenship.", "pt-BR": "Expressar o significado de reivindicar a cidadania." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "it doesn't replace where I'm from", say: "it dâzânt ri-PLÊIS uér aim FRÂM", note: { en: "= não substitui de onde eu venho.", "pt-BR": "= não substitui de onde eu venho." } }],
    dialogueSteps: [ { text: "So you're really doing it? Becoming a citizen?", tr: { en: "Speak its full meaning.", "pt-BR": "Diga o significado pleno disso." }, ear: { en: "<b>“ri-PLÊIS”</b>", "pt-BR": "<b>“ri-PLÊIS”</b>" }, audioPrompt: "Friend, moved, over coffee: “So you're really doing it? Becoming a citizen?”", basic: "Yes. It doesn't replace where I'm from. It adds to it.", fluent: "I am — and it doesn't replace where I'm from, it adds to it. I get to be both now." } ] },
  { sequence: 348, blockId: 14, indexInBlock: 23, phase: 2, subBlock: "14.5", threshold: 80,
    sceneTitle: { en: "The Citizenship Ceremony", "pt-BR": "A Cerimônia de Cidadania" },
    contextDescription: { en: "In a council chamber, hand raised, you take the oath alongside others from every corner of the earth. The official invites you to say a few words. You speak from a heart that has travelled so far.", "pt-BR": "Numa câmara da prefeitura, mão erguida, você faz o juramento ao lado de gente de todos os cantos do mundo. O oficial te convida a dizer algumas palavras. Você fala de um coração que viajou tão longe." },
    objective: { en: "Mark the citizenship oath with heartfelt words.", "pt-BR": "Marcar o juramento de cidadania com palavras sentidas." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Registrar", "pt-BR": "Oficial de Registro" }, initials: "Re" },
    drills: [{ word: "I'm proud to call this home", say: "aim práud tu cól dis RÔUM", note: { en: "= tenho orgulho de chamar isto de lar.", "pt-BR": "= tenho orgulho de chamar isto de lar." } }],
    dialogueSteps: [ { text: "Congratulations. Would you like to say a few words to your fellow new citizens?", tr: { en: "Speak from the heart.", "pt-BR": "Fale do coração." }, ear: { en: "<b>“cól dis RÔUM”</b>", "pt-BR": "<b>“cól dis RÔUM”</b>" }, audioPrompt: "Registrar, formal and warm in a council chamber: “Congratulations. Would you like to say a few words to your fellow new citizens?”", basic: "I'm proud to call this home. We made it.", fluent: "I came here with one suitcase and no words — and today I'm proud to call this home. We all made it. Welcome, everyone." } ] },
  { sequence: 349, blockId: 14, indexInBlock: 24, phase: 3, subBlock: "14.5", threshold: 80,
    sceneTitle: { en: "The Full Circle", "pt-BR": "O Ciclo Completo" },
    contextDescription: { en: "Back at the airport arrivals hall where it all began, you wait — not lost and afraid this time, but holding a welcome sign for your own newly-arriving relative. You'll be the steady hand you never had.", "pt-BR": "De volta ao saguão de desembarque do aeroporto onde tudo começou, você espera — não perdido e com medo desta vez, mas segurando uma placa de boas-vindas para um parente seu que está chegando. Você será a mão firme que você nunca teve." },
    objective: { en: "Welcome a loved one to the city as a guide.", "pt-BR": "Receber um ente querido na cidade como um guia." },
    environment: { mood: "pleased", baseNoise: 56 },
    npc: { name: { en: "Arriving Relative", "pt-BR": "Parente Chegando" }, initials: "AR" },
    drills: [{ word: "I've got you", say: "aiv GÓT iú", note: { en: "= pode deixar comigo / estou com você.", "pt-BR": "= pode deixar comigo / estou com você." } }, { word: "welcome to London", say: "UÉL-câm tu LÂN-dân", note: { en: "= bem-vindo a Londres.", "pt-BR": "= bem-vindo a Londres." } }],
    dialogueSteps: [ { text: "I'm here! I'm so scared... I don't know anything about this place.", tr: { en: "Be their steady hand.", "pt-BR": "Seja a mão firme deles." }, ear: { en: "<b>“aiv GÓT iú”</b>", "pt-BR": "<b>“aiv GÓT iú”</b>" }, audioPrompt: "Arriving relative, overwhelmed and emotional in a noisy arrivals hall: “I'm here! I'm so scared... I don't know anything about this place.”", basic: "Welcome to London. I've got you.", fluent: "Welcome to London — breathe, you're not alone. I've got you. I know this city like the back of my hand now." } ] },
  { sequence: 350, blockId: 14, indexInBlock: 25, phase: 3, subBlock: "14.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "A London Institution", tagline: "A London Institution — From One Suitcase to a Whole Life", shareText: "I arrived with one suitcase, no words, and pure fear. Years on: a home with my name on the deeds, a community that calls me family, citizenship, and a newcomer of my own to guide. From lost tourist to a London institution. 🇬🇧🏙️🔑 #LinguoBound" },
    sceneTitle: { en: "Bonus — From One Suitcase", "pt-BR": "Bônus — De Uma Mala Só" },
    contextDescription: { en: "Sunset on Waterloo Bridge — the view that holds the whole city, the river, the Eye, St Paul's, the Houses of Parliament. Beside you, the relative you just collected, eyes wide with the same fear you once had. You remember arriving with one suitcase and not a single word. Now you own a home here, a community calls you family, you carry a new passport, and a frightened newcomer holds your arm. The city didn't just let you in — you became part of its story. Take the picture.", "pt-BR": "Pôr do sol na Ponte de Waterloo — a vista que abraça a cidade inteira, o rio, a London Eye, a Catedral de São Paulo, o Parlamento. Ao seu lado, o parente que você acabou de buscar, olhos arregalados com o mesmo medo que você um dia teve. Você lembra de chegar com uma mala só e nem uma palavra. Agora você tem uma casa aqui, uma comunidade que te chama de família, carrega um novo passaporte, e um recém-chegado assustado segura seu braço. A cidade não só te deixou entrar — você virou parte da história dela. Tire a foto." },
    objective: { en: "Celebrate becoming a true London institution.", "pt-BR": "Celebrar tornar-se uma verdadeira instituição de Londres." },
    environment: { mood: "pleased", baseNoise: 50 },
    npc: { name: { en: "Arriving Relative", "pt-BR": "Parente Chegando" }, initials: "AR" },
    drills: [{ word: "this whole city is yours now too", say: "dis rôul SÍ-ti iz iórz náu tú", note: { en: "The torch, passed on.", "pt-BR": "A tocha, passada adiante." }, }],
    dialogueSteps: [
      { text: "You... you really built a whole life here? All of this?", tr: { en: "You did — all of it.", "pt-BR": "Você construiu — tudo isso." }, ear: { en: "<b>“rôul LÁIF”</b>", "pt-BR": "<b>“rôul LÁIF”</b>" }, audioPrompt: "Arriving relative, awestruck on the bridge at sunset, city humming: “You... you really built a whole life here? All of this?”", basic: "From one suitcase. And so will you.", fluent: "All of it — from one suitcase and no English. And one day, you'll have all this too." },
      { text: "I don't know if I can do what you did.", tr: { en: "Pass them the torch.", "pt-BR": "Passe a tocha a eles." }, ear: { en: "<b>“iórz náu tú”</b>", "pt-BR": "<b>“iórz náu tú”</b>" }, audioPrompt: "Arriving relative, nervous but hopeful, golden light on the Thames: “I don't know if I can do what you did.”", basic: "You can. This whole city is yours now too.", fluent: "You can, and you will — I'll be right beside you. This whole city is yours now too. Welcome home." },
    ] },
];

export const BLOCK14_BY_SEQUENCE = BLOCK14_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
