/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 07 (Modules 151–175)
 *  "Emergency & Resilience" — 5 sub-blocks:
 *    7.1 The Fender Bender   (151–155) a crash, insurance, an angry driver
 *    7.2 Lost Phone, Tube    (156–160) gone in the crowd, lost property, police
 *    7.3 Landlord Dispute    (161–165) a dodgy clause, your rights, escalation
 *    7.4 WILDCARD: Big Freeze (166–170) ❄️ a freak snow paralyses London
 *    7.5 Resilience & Resolve(171–175) burnout, the call home, BONUS
 *  Module 175 = "Unbreakable" milestone selfie.
 * ============================================================ */

export const BLOCK07_MODULES = [
  /* 7.1 — THE FENDER BENDER */
  { sequence: 151, blockId: 7, indexInBlock: 1, phase: 3, subBlock: "7.1", threshold: 80,
    sceneTitle: { en: "The Bump", "pt-BR": "A Batida" },
    contextDescription: { en: "Crossing a wet road, a slow car clips your leg — more shock than injury. Tyres screech, horns blare, the driver leaps out shouting. You must take control.", "pt-BR": "Atravessando a rua molhada, um carro lento pega sua perna — mais susto que lesão. Pneus cantam, buzinas, o motorista salta gritando. Você precisa assumir o controle." },
    objective: { en: "Stay calm and assess after a minor accident.", "pt-BR": "Manter a calma e avaliar após um acidente leve." },
    environment: { mood: "hostile", baseNoise: 58, rain: true },
    npc: { name: { en: "Driver", "pt-BR": "Motorista" }, initials: "DR" },
    drills: [{ word: "I'm okay, I think", say: "aim ô-KÊI, ai thínk", note: { en: "Assess yourself first.", "pt-BR": "Avalie-se primeiro." } }],
    dialogueSteps: [ { text: "Oh my God — are you hurt?! I didn't see you!", tr: { en: "Are you injured?", "pt-BR": "Você se machucou?" }, ear: { en: "<b>“ârt”</b> = ferido", "pt-BR": "<b>“ârt”</b> = ferido" }, audioPrompt: "Driver, panicked, in traffic and rain: “Oh my God — are you hurt?! I didn't see you!”", basic: "I'm okay, I think.", fluent: "I think I'm okay — let's both just stay calm." } ] },
  { sequence: 152, blockId: 7, indexInBlock: 2, phase: 3, subBlock: "7.1", threshold: 80,
    sceneTitle: { en: "Exchanging Details", "pt-BR": "Trocando os Dados" },
    contextDescription: { en: "Adrenaline fading, procedure kicks in. You must calmly request the driver's name, number and insurance — the words that protect you legally.", "pt-BR": "Com a adrenalina baixando, entra o procedimento. Você precisa pedir com calma nome, telefone e seguro do motorista — as palavras que te protegem legalmente." },
    objective: { en: "Request insurance and contact details.", "pt-BR": "Pedir os dados de seguro e contato." },
    environment: { mood: "hostile", baseNoise: 52 },
    npc: { name: { en: "Driver", "pt-BR": "Motorista" }, initials: "DR" },
    drills: [{ word: "your insurance details", say: "iór in-SHÚ-râns DÍ-têils", note: { en: "= seus dados de seguro.", "pt-BR": "= seus dados de seguro." } }],
    dialogueSteps: [ { text: "Look, do we really need to do all this?", tr: { en: "He's trying to avoid it — insist.", "pt-BR": "Ele tenta evitar — insista." }, ear: { en: "<b>“in-SHÚ-râns”</b>", "pt-BR": "<b>“in-SHÚ-râns”</b>" }, audioPrompt: "Driver, reluctant: “Look, do we really need to do all this?”", basic: "Yes. Your insurance details, please.", fluent: "Yes, we do — I need your name and insurance details." } ] },
  { sequence: 153, blockId: 7, indexInBlock: 3, phase: 3, subBlock: "7.1", threshold: 80,
    sceneTitle: { en: "The Angry Driver", "pt-BR": "O Motorista Irritado" },
    contextDescription: { en: "He flips: it was YOUR fault, you came from nowhere, he's late. He's loud, in your face. You must hold your ground without escalating.", "pt-BR": "Ele vira o jogo: a culpa é SUA, você surgiu do nada, ele está atrasado. Alto, na sua cara. Você precisa se impor sem aumentar o conflito." },
    objective: { en: "Hold firm against aggression without escalating.", "pt-BR": "Manter-se firme diante da agressividade sem escalar." },
    environment: { mood: "hostile", baseNoise: 54 },
    npc: { name: { en: "Driver", "pt-BR": "Motorista" }, initials: "DR" },
    drills: [{ word: "there are witnesses", say: "dér ar UÍT-nâ-siz", note: { en: "Calmly assert facts.", "pt-BR": "Afirme os fatos com calma." } }],
    dialogueSteps: [ { text: "You walked out in front of me! This is on you!", tr: { en: "He blames you — stay calm.", "pt-BR": "Ele te culpa — fique calmo." }, ear: { en: "<b>“UÍT-nâ-siz”</b>", "pt-BR": "<b>“UÍT-nâ-siz”</b>" }, audioPrompt: "Driver, shouting, aggressive: “You walked out in front of me! This is on you!”", basic: "Calm down. There are witnesses.", fluent: "Let's stay calm — there are witnesses, and the light was green." } ] },
  { sequence: 154, blockId: 7, indexInBlock: 4, phase: 3, subBlock: "7.1", threshold: 80,
    sceneTitle: { en: "A Witness Steps In", "pt-BR": "Uma Testemunha Intervém" },
    contextDescription: { en: "A passer-by saw it all and offers to back you up. You must thank them and quickly get their contact before they vanish into the crowd.", "pt-BR": "Um pedestre viu tudo e se oferece para confirmar sua versão. Você precisa agradecer e pegar o contato dele rápido, antes que suma na multidão." },
    objective: { en: "Secure a witness's contact details.", "pt-BR": "Garantir o contato de uma testemunha." },
    environment: { mood: "neutral", baseNoise: 48 },
    npc: { name: { en: "Witness", "pt-BR": "Testemunha" }, initials: "WI" },
    drills: [{ word: "could I take your number?", say: "kud ai têik iór NÂM-bâr", note: { en: "Get their contact.", "pt-BR": "Pegue o contato." } }],
    dialogueSteps: [ { text: "I saw the whole thing — that wasn't your fault.", tr: { en: "They're on your side.", "pt-BR": "Eles estão do seu lado." }, ear: { en: "<b>“RÔUL thíng”</b>", "pt-BR": "<b>“RÔUL thíng”</b>" }, audioPrompt: "Witness, stepping forward: “I saw the whole thing — that wasn't your fault.”", basic: "Thank you! Could I take your number?", fluent: "Thank you so much — could I take your number as a witness?" } ] },
  { sequence: 155, blockId: 7, indexInBlock: 5, phase: 3, subBlock: "7.1", threshold: 80,
    sceneTitle: { en: "Calling Insurance", "pt-BR": "Ligando para o Seguro" },
    contextDescription: { en: "Home, shaken. You ring your insurer to open a claim — recounting the incident clearly down a crackly line while they read from a script.", "pt-BR": "Em casa, abalado. Você liga para a seguradora para abrir um sinistro — relatando o incidente com clareza numa linha chiada enquanto eles leem um roteiro." },
    objective: { en: "Open an insurance claim by phone.", "pt-BR": "Abrir um sinistro por telefone." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "Insurer", "pt-BR": "Seguradora" }, initials: "IN" },
    drills: [{ word: "to make a claim", say: "tu mêik a CLÊIM", note: { en: "= abrir um sinistro.", "pt-BR": "= abrir um sinistro." } }],
    dialogueSteps: [ { text: "Claims line. What's happened?", tr: { en: "Tell them what happened.", "pt-BR": "Conte o que aconteceu." }, ear: { en: "<b>“clêim”</b>", "pt-BR": "<b>“clêim”</b>" }, audioPrompt: "Insurer, scripted down a slightly distorted line: “Claims line. What's happened?”", basic: "I want to make a claim.", fluent: "I'd like to make a claim — I was hit by a car today." } ] },

  /* 7.2 — LOST PHONE IN THE TUBE */
  { sequence: 156, blockId: 7, indexInBlock: 6, phase: 3, subBlock: "7.2", threshold: 80,
    sceneTitle: { en: "It's Gone", "pt-BR": "Sumiu" },
    contextDescription: { en: "Rush hour, a packed carriage, bodies pressed close. The doors close — and your pocket is empty. Your phone is gone. You spin to a stranger for help.", "pt-BR": "Hora do rush, vagão lotado, corpos colados. As portas fecham — e seu bolso está vazio. Seu celular sumiu. Você se vira para um estranho pedindo ajuda." },
    objective: { en: "Ask a stranger for urgent help.", "pt-BR": "Pedir ajuda urgente a um estranho." },
    environment: { mood: "hostile", baseNoise: 66 },
    npc: { name: { en: "Passenger", "pt-BR": "Passageiro(a)" }, initials: "PA" },
    drills: [{ word: "my phone's gone", say: "mai fôuns GÓN", note: { en: "= meu celular sumiu.", "pt-BR": "= meu celular sumiu." } }],
    dialogueSteps: [ { text: "You alright? You've gone white as a sheet.", tr: { en: "Are you okay? You look shocked.", "pt-BR": "Você está bem? Parece em choque." }, ear: { en: "<b>“uait az a shít”</b>", "pt-BR": "<b>“uait az a shít”</b>" }, audioPrompt: "Passenger, concerned over roaring train noise: “You alright? You've gone white as a sheet.”", basic: "My phone's gone!", fluent: "My phone's gone — I think it's been nicked!" } ] },
  { sequence: 157, blockId: 7, indexInBlock: 7, phase: 3, subBlock: "7.2", threshold: 80,
    sceneTitle: { en: "Borrowing a Phone", "pt-BR": "Pedindo um Celular Emprestado" },
    contextDescription: { en: "You need to lock your phone NOW, but yours is the gone one. You must ask a wary stranger to borrow theirs — and sound trustworthy in seconds.", "pt-BR": "Você precisa bloquear seu celular AGORA, mas é justo ele que sumiu. Você precisa pedir o de um estranho desconfiado — e parecer confiável em segundos." },
    objective: { en: "Borrow a stranger's phone trustworthily.", "pt-BR": "Pedir o celular de um estranho de forma confiável." },
    environment: { mood: "neutral", baseNoise: 56 },
    npc: { name: { en: "Passenger", "pt-BR": "Passageiro(a)" }, initials: "PA" },
    drills: [{ word: "could I borrow yours?", say: "kud ai BÓ-rou iórs", note: { en: "Ask to borrow.", "pt-BR": "Peça emprestado." } }],
    dialogueSteps: [ { text: "Need to ring someone? Here, but be quick.", tr: { en: "They lend their phone — be fast.", "pt-BR": "Eles emprestam o celular — seja rápido." }, ear: { en: "<b>“BÓ-rou”</b>", "pt-BR": "<b>“BÓ-rou”</b>" }, audioPrompt: "Passenger, cautious but kind: “Need to ring someone? Here, but be quick.”", basic: "Thank you — just one minute.", fluent: "Thank you — I just need to lock my phone, one minute." } ] },
  { sequence: 158, blockId: 7, indexInBlock: 8, phase: 2, subBlock: "7.2", threshold: 80,
    sceneTitle: { en: "TfL Lost Property", "pt-BR": "Achados e Perdidos da TfL" },
    contextDescription: { en: "At the station office you report the loss. The clerk, deadpan, explains the byzantine TfL lost-property process and the days-long wait.", "pt-BR": "No escritório da estação você relata a perda. O atendente, impassível, explica o processo bizantino de achados e perdidos da TfL e a espera de dias." },
    objective: { en: "Report a lost item to station staff.", "pt-BR": "Relatar um item perdido aos funcionários." },
    culturalNote: { en: "TfL lost property is centralised and slow. You'll get a reference and a wait.", "pt-BR": "Os achados e perdidos da TfL são centralizados e lentos. Você ganha um protocolo e espera." },
    environment: { mood: "neutral", baseNoise: 40 },
    npc: { name: { en: "Station Clerk", "pt-BR": "Atendente da Estação" }, initials: "SC" },
    drills: [{ word: "I lost my phone", say: "ai lóst mai FÔUN", note: { en: "Past tense of lose.", "pt-BR": "Passado de lose." } }],
    dialogueSteps: [ { text: "Lost something on the network?", tr: { en: "Did you lose something on the Tube?", "pt-BR": "Perdeu algo no metrô?" }, ear: { en: "<b>“NÉT-uârk”</b>", "pt-BR": "<b>“NÉT-uârk”</b>" }, audioPrompt: "Clerk, deadpan: “Lost something on the network?”", basic: "Yes, I lost my phone.", fluent: "Yes — I lost my phone on the Central line just now." } ] },
  { sequence: 159, blockId: 7, indexInBlock: 9, phase: 2, subBlock: "7.2", threshold: 80,
    sceneTitle: { en: "Police Report for Insurance", "pt-BR": "B.O. para o Seguro" },
    contextDescription: { en: "To claim on insurance you need a crime reference number. Online or by phone to 101, you must report the theft precisely, time and place.", "pt-BR": "Para acionar o seguro você precisa de um número de ocorrência. Online ou pelo 101, relate o furto com precisão, hora e local." },
    objective: { en: "Report a theft to get a crime reference.", "pt-BR": "Registrar o furto para obter o número de ocorrência." },
    culturalNote: { en: "Non-emergency police = 101. You need a ‘crime reference number’ for insurance.", "pt-BR": "Polícia não-emergencial = 101. Você precisa do ‘crime reference number’ para o seguro." },
    environment: { mood: "neutral", baseNoise: 32 },
    npc: { name: { en: "Police (101)", "pt-BR": "Polícia (101)" }, initials: "10" },
    drills: [{ word: "it was stolen", say: "it uâz STÔU-lân", note: { en: "= foi furtado.", "pt-BR": "= foi furtado." } }],
    dialogueSteps: [ { text: "I'll log this. Where and when did it happen?", tr: { en: "Give the place and time.", "pt-BR": "Diga o local e a hora." }, ear: { en: "<b>“uér ând uén”</b>", "pt-BR": "<b>“uér ând uén”</b>" }, audioPrompt: "Police operator on 101, brisk: “I'll log this. Where and when did it happen?”", basic: "On the Tube, an hour ago.", fluent: "On the Central line, about an hour ago — it was stolen." } ] },
  { sequence: 160, blockId: 7, indexInBlock: 10, phase: 3, subBlock: "7.2", threshold: 80,
    sceneTitle: { en: "Replacing the SIM", "pt-BR": "Trocando o Chip" },
    contextDescription: { en: "Back to the phone shop to get a new SIM keeping your number. The clerk recognises you — “Back again?” You explain the saga and reclaim your digital life.", "pt-BR": "De volta à loja para um novo chip mantendo seu número. O atendente te reconhece — “Back again?” Você explica a saga e recupera sua vida digital." },
    objective: { en: "Request a replacement SIM keeping your number.", "pt-BR": "Pedir um chip novo mantendo o número." },
    environment: { mood: "neutral", baseNoise: 44 },
    npc: { name: { en: "Shop Clerk", "pt-BR": "Atendente" }, initials: "SX" },
    drills: [{ word: "keep my number", say: "kíp mai NÂM-bâr", note: { en: "= manter meu número.", "pt-BR": "= manter meu número." } }],
    dialogueSteps: [ { text: "Back again? What happened this time?", tr: { en: "What do you need now?", "pt-BR": "Do que você precisa agora?" }, ear: { en: "<b>“bék a-GÉN”</b>", "pt-BR": "<b>“bék a-GÉN”</b>" }, audioPrompt: "Clerk, half-joking: “Back again? What happened this time?”", basic: "A new SIM — keep my number.", fluent: "Long story — a new SIM, but I need to keep my number." } ] },

  /* 7.3 — LANDLORD DISPUTE */
  { sequence: 161, blockId: 7, indexInBlock: 11, phase: 3, subBlock: "7.3", threshold: 80,
    sceneTitle: { en: "The Suspicious Clause", "pt-BR": "A Cláusula Suspeita" },
    contextDescription: { en: "Moving out, the landlord cites a clause to keep your whole deposit for ‘cleaning and wear’. The flat was spotless. You must challenge it, citing your rights.", "pt-BR": "Na saída, o locador cita uma cláusula para reter todo o seu depósito por ‘limpeza e desgaste’. O apê estava impecável. Você precisa contestar, citando seus direitos." },
    objective: { en: "Challenge an unfair deposit deduction.", "pt-BR": "Contestar uma retenção injusta do depósito." },
    culturalNote: { en: "‘Fair wear and tear’ can't be charged. Deposits must be in a protection scheme.", "pt-BR": "‘Desgaste natural’ não pode ser cobrado. O depósito deve estar num esquema de proteção." },
    environment: { mood: "hostile", baseNoise: 32 },
    npc: { name: { en: "Landlord", "pt-BR": "Locador(a)" }, initials: "LL" },
    drills: [{ word: "fair wear and tear", say: "fér UÉR ând TÉR", note: { en: "= desgaste natural.", "pt-BR": "= desgaste natural." } }],
    dialogueSteps: [ { text: "I'm keeping the deposit for cleaning, it's in the contract.", tr: { en: "He wants your deposit — push back.", "pt-BR": "Ele quer seu depósito — conteste." }, ear: { en: "<b>“di-PÓ-zit”</b>", "pt-BR": "<b>“di-PÓ-zit”</b>" }, audioPrompt: "Landlord, firm on the phone: “I'm keeping the deposit for cleaning, it's in the contract.”", basic: "That's fair wear and tear.", fluent: "That's fair wear and tear — you can't charge for that." } ] },
  { sequence: 162, blockId: 7, indexInBlock: 12, phase: 3, subBlock: "7.3", threshold: 80,
    sceneTitle: { en: "Knowing Your Rights", "pt-BR": "Conhecendo Seus Direitos" },
    contextDescription: { en: "He didn't expect you to know the law. You ask the killer question: which government-backed deposit protection scheme is your money in? The power shifts.", "pt-BR": "Ele não esperava que você conhecesse a lei. Você faz a pergunta decisiva: em qual esquema oficial de proteção de depósito seu dinheiro está? O poder muda de lado." },
    objective: { en: "Cite the deposit protection scheme.", "pt-BR": "Citar o esquema de proteção do depósito." },
    environment: { mood: "hostile", baseNoise: 30 },
    npc: { name: { en: "Landlord", "pt-BR": "Locador(a)" }, initials: "LL" },
    drills: [{ word: "deposit protection scheme", say: "di-PÓ-zit prô-TÉK-shân skím", note: { en: "Your legal lever.", "pt-BR": "Sua alavanca legal." } }],
    dialogueSteps: [ { text: "Well... that's just how it works, alright?", tr: { en: "He's bluffing — name the scheme.", "pt-BR": "Ele está blefando — cite o esquema." }, ear: { en: "<b>“prô-TÉK-shân skím”</b>", "pt-BR": "<b>“prô-TÉK-shân skím”</b>" }, audioPrompt: "Landlord, suddenly defensive: “Well... that's just how it works, alright?”", basic: "Which protection scheme is it in?", fluent: "Which deposit protection scheme is my money in, exactly?" } ] },
  { sequence: 163, blockId: 7, indexInBlock: 13, phase: 3, subBlock: "7.3", threshold: 80,
    sceneTitle: { en: "Threatening (Politely)", "pt-BR": "Ameaçando (com Educação)" },
    contextDescription: { en: "He stalls. You raise the stakes the British way — calm, polite, devastating: you'll raise a formal dispute and contact Citizens Advice. No shouting needed.", "pt-BR": "Ele enrola. Você eleva a aposta do jeito britânico — calmo, educado, devastador: vai abrir uma disputa formal e procurar o Citizens Advice. Sem gritar." },
    objective: { en: "Escalate firmly but politely.", "pt-BR": "Escalar com firmeza, mas com educação." },
    culturalNote: { en: "‘I'll have to escalate this’ + Citizens Advice = a serious, polite threat.", "pt-BR": "‘I'll have to escalate this’ + Citizens Advice = uma ameaça séria e educada." },
    environment: { mood: "hostile", baseNoise: 30 },
    npc: { name: { en: "Landlord", "pt-BR": "Locador(a)" }, initials: "LL" },
    drills: [{ word: "I'll have to escalate this", say: "ail rév tu ÉS-câ-lêit dis", note: { en: "Polite escalation.", "pt-BR": "Escalada educada." } }],
    dialogueSteps: [ { text: "Look, there's no need to make a fuss.", tr: { en: "He wants you to back off — don't.", "pt-BR": "Ele quer que você recue — não recue." }, ear: { en: "<b>“ÉS-câ-lêit”</b>", "pt-BR": "<b>“ÉS-câ-lêit”</b>" }, audioPrompt: "Landlord, wheedling: “Look, there's no need to make a fuss.”", basic: "Then return it, or I'll escalate this.", fluent: "There isn't — just return it, or I'll have to escalate this." } ] },
  { sequence: 164, blockId: 7, indexInBlock: 14, phase: 3, subBlock: "7.3", threshold: 80,
    sceneTitle: { en: "The Resolution", "pt-BR": "A Resolução" },
    contextDescription: { en: "He folds. “Fine — I'll send it back this week.” You confirm the terms clearly so there's no wriggling out. Quiet, hard-won victory.", "pt-BR": "Ele cede. “Fine — I'll send it back this week.” Você confirma os termos com clareza para não ter como ele escapar. Vitória silenciosa e suada." },
    objective: { en: "Confirm a resolution to lock it in.", "pt-BR": "Confirmar a resolução para deixar acertado." },
    environment: { mood: "pleased", baseNoise: 28 },
    npc: { name: { en: "Landlord", "pt-BR": "Locador(a)" }, initials: "LL" },
    drills: [{ word: "in full, by Friday", say: "in FÚL, bai FRÁI-dêi", note: { en: "Pin down the terms.", "pt-BR": "Trave os termos." } }],
    dialogueSteps: [ { text: "Fine, fine — I'll send it back this week.", tr: { en: "He agrees to repay.", "pt-BR": "Ele concorda em devolver." }, ear: { en: "<b>“in fúl”</b> = integral", "pt-BR": "<b>“in fúl”</b> = integral" }, audioPrompt: "Landlord, defeated: “Fine, fine — I'll send it back this week.”", basic: "In full, by Friday?", fluent: "Good — in full, by Friday, and I'd like that in writing." } ] },
  { sequence: 165, blockId: 7, indexInBlock: 15, phase: 3, subBlock: "7.3", threshold: 80,
    sceneTitle: { en: "Citizens Advice", "pt-BR": "Orientação ao Cidadão" },
    contextDescription: { en: "To be sure, you call Citizens Advice — the free service that levels the playing field for everyone in Britain. A kind adviser confirms you were right all along.", "pt-BR": "Para garantir, você liga ao Citizens Advice — o serviço gratuito que equilibra o jogo para todos na Grã-Bretanha. Um orientador gentil confirma que você sempre teve razão." },
    objective: { en: "Seek free advice to confirm your position.", "pt-BR": "Buscar orientação gratuita para confirmar sua posição." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Adviser", "pt-BR": "Orientador(a)" }, initials: "AD" },
    drills: [{ word: "was I in the right?", say: "uâz ai in dâ RÁIT", note: { en: "= eu estava certo?", "pt-BR": "= eu estava certo?" } }],
    dialogueSteps: [ { text: "You were absolutely within your rights.", tr: { en: "You were right to push back.", "pt-BR": "Você estava certo em contestar." }, ear: { en: "<b>“uí-DÍN iór ráits”</b>", "pt-BR": "<b>“uí-DÍN iór ráits”</b>" }, audioPrompt: "Adviser, warm and clear: “You were absolutely within your rights.”", basic: "Thank you. Good to know.", fluent: "Thank you — that's a real relief to hear." } ] },

  /* 7.4 — ❄️ WILDCARD: THE BIG FREEZE ❄️ */
  { sequence: 166, blockId: 7, indexInBlock: 16, phase: 3, subBlock: "7.4", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ Wildcard: It's Snowing", "pt-BR": "⚡ Curinga: Está Nevando" },
    contextDescription: { en: "You wake to an eerie white silence and your phone screaming alerts. Three centimetres of snow has fallen — and the entire city has stopped. A frantic colleague calls.", "pt-BR": "Você acorda num silêncio branco e estranho com o celular gritando alertas. Caíram três centímetros de neve — e a cidade inteira parou. Um colega liga em pânico." },
    objective: { en: "Grasp that a little snow has paralysed London.", "pt-BR": "Entender que um pouco de neve paralisou Londres." },
    culturalNote: { en: "A few cm of snow shuts the UK down: trains, schools, panic. Locals find it both shameful and thrilling.", "pt-BR": "Poucos cm de neve param o Reino Unido: trens, escolas, pânico. Os locais acham isso vergonhoso e empolgante ao mesmo tempo." },
    environment: { mood: "hostile", baseNoise: 38 },
    npc: { name: { en: "Colleague", "pt-BR": "Colega" }, initials: "CO" },
    drills: [{ word: "everything's shut", say: "É-vri-things SHÂT", note: { en: "= tudo fechado.", "pt-BR": "= tudo fechado." } }],
    dialogueSteps: [ { text: "Have you SEEN it out there?! The trains are all cancelled!", tr: { en: "Snow has stopped the trains!", "pt-BR": "A neve parou os trens!" }, ear: { en: "<b>“KÉN-sâld”</b>", "pt-BR": "<b>“KÉN-sâld”</b>" }, audioPrompt: "Colleague, breathless and incredulous: “Have you SEEN it out there?! The trains are all cancelled!”", basic: "Snow? Everything's shut?", fluent: "Wait — all this over a bit of snow? Everything's shut?" } ] },
  { sequence: 167, blockId: 7, indexInBlock: 17, phase: 3, subBlock: "7.4", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ Panic at the Shop", "pt-BR": "⚡ Pânico no Mercado" },
    contextDescription: { en: "You venture out to the corner shop. Chaos: bare shelves, no bread, no milk, people stockpiling as if for a siege. You ask the shopkeeper if anything's left.", "pt-BR": "Você se aventura até o mercadinho. Caos: prateleiras vazias, sem pão, sem leite, gente estocando como para um cerco. Você pergunta ao dono se sobrou algo." },
    objective: { en: "Navigate panic-buying and find essentials.", "pt-BR": "Lidar com o estoque em pânico e achar o essencial." },
    culturalNote: { en: "‘Panic-buying’ bread and milk at the first snowflake is a national tradition.", "pt-BR": "‘Panic-buying’ de pão e leite ao primeiro floco é uma tradição nacional." },
    environment: { mood: "hostile", baseNoise: 50 },
    npc: { name: { en: "Shopkeeper", "pt-BR": "Comerciante" }, initials: "SK" },
    drills: [{ word: "any bread left?", say: "É-ni BRÉD left", note: { en: "= sobrou pão?", "pt-BR": "= sobrou pão?" } }],
    dialogueSteps: [ { text: "Cleared us out, mate — last loaf's gone!", tr: { en: "Everything's sold out.", "pt-BR": "Tudo esgotado." }, ear: { en: "<b>“lôuf”</b> = pão (forma)", "pt-BR": "<b>“lôuf”</b> = pão (de forma)" }, audioPrompt: "Shopkeeper, overwhelmed amid a frantic crowd: “Cleared us out, mate — last loaf's gone!”", basic: "Any milk left?", fluent: "Madness! Any milk left at all?" } ] },
  { sequence: 168, blockId: 7, indexInBlock: 18, phase: 3, subBlock: "7.4", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ The Stranded Neighbour", "pt-BR": "⚡ A Vizinha Presa" },
    contextDescription: { en: "An elderly neighbour is stuck on her icy doorstep, afraid to fall, her carer snowed-out. No one else is around. You step in to help her inside.", "pt-BR": "Uma vizinha idosa está presa na soleira congelada, com medo de cair, sua cuidadora impedida pela neve. Não há mais ninguém. Você intervém para ajudá-la a entrar." },
    objective: { en: "Offer help to a vulnerable neighbour.", "pt-BR": "Oferecer ajuda a uma vizinha vulnerável." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Elderly Neighbour", "pt-BR": "Vizinha Idosa" }, initials: "EN" },
    drills: [{ word: "let me help you", say: "lét mi RÉLP iú", note: { en: "Offer support gently.", "pt-BR": "Ofereça apoio com gentileza." } }],
    dialogueSteps: [ { text: "Oh, I daren't move, dear — it's so slippery.", tr: { en: "She's scared to move on the ice.", "pt-BR": "Ela tem medo de andar no gelo." }, ear: { en: "<b>“SLÍ-pâ-ri”</b>", "pt-BR": "<b>“SLÍ-pâ-ri”</b>" }, audioPrompt: "Elderly neighbour, frightened in the cold: “Oh, I daren't move, dear — it's so slippery.”", basic: "Let me help you. Take my arm.", fluent: "Don't worry — let me help you. Take my arm, slowly." } ] },
  { sequence: 169, blockId: 7, indexInBlock: 19, phase: 3, subBlock: "7.4", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ Snow Day Unity", "pt-BR": "⚡ A União do Dia de Neve" },
    contextDescription: { en: "By afternoon, the panic becomes a party. The whole street is out — sledging on tea trays, building snowmen, strangers laughing together. A neighbour hands you a hot toddy.", "pt-BR": "À tarde, o pânico vira festa. A rua inteira sai — descendo em bandejas de chá, fazendo bonecos de neve, estranhos rindo juntos. Um vizinho te entrega um ponche quente." },
    objective: { en: "Join the spontaneous community celebration.", "pt-BR": "Entrar na celebração espontânea da comunidade." },
    environment: { mood: "pleased", baseNoise: 46 },
    npc: { name: { en: "Neighbour", "pt-BR": "Vizinho(a)" }, initials: "NB" },
    drills: [{ word: "go on then!", say: "GÔU ón dén", note: { en: "Joyful yes.", "pt-BR": "Sim animado." } }],
    dialogueSteps: [ { text: "Come on, grab a tray — we're sledging down the hill!", tr: { en: "Join the snow fun!", "pt-BR": "Venha brincar na neve!" }, ear: { en: "<b>“SLÉ-djin”</b> = descer no trenó", "pt-BR": "<b>“SLÉ-djin”</b> = descer de trenó" }, audioPrompt: "Neighbour, laughing in the snow with the whole street out: “Come on, grab a tray — we're sledging down the hill!”", basic: "Go on then!", fluent: "Go on then — but I've never done this before!" } ] },
  { sequence: 170, blockId: 7, indexInBlock: 20, phase: 3, subBlock: "7.4", threshold: 80, wildcard: true,
    sceneTitle: { en: "⚡ The Thaw", "pt-BR": "⚡ O Degelo" },
    contextDescription: { en: "Next morning it's all slush and the city groans back to life as if nothing happened. At the bus stop a neighbour grins: “Mad, wasn't it?” You share the secret bond of a survived snow day.", "pt-BR": "Na manhã seguinte é tudo lama e a cidade volta à vida como se nada tivesse acontecido. No ponto, um vizinho sorri: “Mad, wasn't it?” Vocês compartilham o laço secreto de um dia de neve sobrevivido." },
    objective: { en: "Bond over the shared absurdity, now a local.", "pt-BR": "Confraternizar pela loucura compartilhada, agora um local." },
    environment: { mood: "pleased", baseNoise: 44 },
    npc: { name: { en: "Neighbour", "pt-BR": "Vizinho(a)" }, initials: "NB" },
    drills: [{ word: "mad, wasn't it?", say: "MÉD, UÓ-zânt it", note: { en: "= foi loucura, né?", "pt-BR": "= foi loucura, né?" } }],
    dialogueSteps: [ { text: "Back to normal already. Mad yesterday, wasn't it?", tr: { en: "Yesterday was crazy, right?", "pt-BR": "Ontem foi loucura, né?" }, ear: { en: "<b>“méd”</b> = loucura", "pt-BR": "<b>“méd”</b> = loucura" }, audioPrompt: "Neighbour, grinning at the bus stop in the slush: “Back to normal already. Mad yesterday, wasn't it?”", basic: "Mad! But brilliant.", fluent: "Absolutely mad — but honestly, brilliant." } ] },

  /* 7.5 — RESILIENCE & RESOLVE */
  { sequence: 171, blockId: 7, indexInBlock: 21, phase: 2, subBlock: "7.5", threshold: 80,
    sceneTitle: { en: "Hitting the Wall", "pt-BR": "Batendo no Limite" },
    contextDescription: { en: "It all catches up: the crash, the theft, the cold, the constant effort of a second language. A friend sees you're not okay and asks, gently, what's really going on.", "pt-BR": "Tudo te alcança: a batida, o furto, o frio, o esforço constante de um segundo idioma. Um amigo percebe que você não está bem e pergunta, com cuidado, o que está acontecendo de verdade." },
    objective: { en: "Admit you're struggling, honestly.", "pt-BR": "Admitir que está difícil, com honestidade." },
    environment: { mood: "neutral", baseNoise: 26 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "I'm exhausted", say: "aim ig-ZÓS-tid", note: { en: "= estou exausto.", "pt-BR": "= estou exausto." } }],
    dialogueSteps: [ { text: "You don't seem yourself. What's really going on?", tr: { en: "They sense you're struggling.", "pt-BR": "Eles sentem que você está mal." }, ear: { en: "<b>“ig-ZÓS-tid”</b>", "pt-BR": "<b>“ig-ZÓS-tid”</b>" }, audioPrompt: "Friend, gentle and quiet: “You don't seem yourself. What's really going on?”", basic: "I'm exhausted, honestly.", fluent: "Honestly? I'm exhausted — it's all been a lot." } ] },
  { sequence: 172, blockId: 7, indexInBlock: 22, phase: 2, subBlock: "7.5", threshold: 80,
    sceneTitle: { en: "The Call Home", "pt-BR": "A Ligação para Casa" },
    contextDescription: { en: "Late at night, you call home. A familiar voice in your mother tongue — then the ache of explaining, in their language, a life they can't quite picture. You reassure them you're okay.", "pt-BR": "Tarde da noite, você liga para casa. Uma voz familiar no seu idioma — e então a dor de explicar uma vida que eles mal conseguem imaginar. Você os tranquiliza de que está bem." },
    objective: { en: "Reassure family that you're managing.", "pt-BR": "Tranquilizar a família de que está se virando." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Family", "pt-BR": "Família" }, initials: "FA" },
    drills: [{ word: "I'm doing okay", say: "aim DÚ-in ô-KÊI", note: { en: "Reassure them.", "pt-BR": "Tranquilize-os." } }],
    dialogueSteps: [ { text: "We worry about you out there all alone.", tr: { en: "They worry about you.", "pt-BR": "Eles se preocupam com você." }, ear: { en: "<b>“ô-LÔUN”</b>", "pt-BR": "<b>“ô-LÔUN”</b>" }, audioPrompt: "Family member, loving, down a long-distance line: “We worry about you out there all alone.”", basic: "I'm doing okay, really.", fluent: "I'm doing okay, really — I've got good friends here now." } ] },
  { sequence: 173, blockId: 7, indexInBlock: 23, phase: 2, subBlock: "7.5", threshold: 80,
    sceneTitle: { en: "The Decision to Stay", "pt-BR": "A Decisão de Ficar" },
    contextDescription: { en: "A crossroads. You could go home, where it's easy. But something in you has changed. A friend asks the question that decides everything: are you staying?", "pt-BR": "Uma encruzilhada. Você poderia voltar, onde é fácil. Mas algo em você mudou. Um amigo faz a pergunta que decide tudo: você vai ficar?" },
    objective: { en: "Declare your decision to stay and commit.", "pt-BR": "Declarar a decisão de ficar e se comprometer." },
    environment: { mood: "pleased", baseNoise: 28 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "I'm staying", say: "aim STÊI-in", note: { en: "= eu vou ficar.", "pt-BR": "= eu vou ficar." } }],
    dialogueSteps: [ { text: "So... are you staying, or going home?", tr: { en: "Stay or leave?", "pt-BR": "Ficar ou voltar?" }, ear: { en: "<b>“STÊI-in”</b>", "pt-BR": "<b>“STÊI-in”</b>" }, audioPrompt: "Friend, sincere: “So... are you staying, or going home?”", basic: "I'm staying.", fluent: "I'm staying — this is home now." } ] },
  { sequence: 174, blockId: 7, indexInBlock: 24, phase: 3, subBlock: "7.5", threshold: 80,
    sceneTitle: { en: "An Unexpected Kindness", "pt-BR": "Uma Gentileza Inesperada" },
    contextDescription: { en: "A small thing undoes you: the café you go to every day has your order ready before you ask. “The usual, love?” You've become a regular — a face that's known.", "pt-BR": "Uma coisinha te desarma: o café que você frequenta já tem seu pedido pronto antes de você pedir. “The usual, love?” Você virou um cliente fiel — um rosto conhecido." },
    objective: { en: "Receive the warmth of being ‘a regular’.", "pt-BR": "Receber o carinho de ser ‘da casa’." },
    culturalNote: { en: "‘The usual?’ from a café means you belong to a place now.", "pt-BR": "‘The usual?’ de um café significa que você agora pertence a um lugar." },
    environment: { mood: "pleased", baseNoise: 40 },
    npc: { name: { en: "Barista", "pt-BR": "Barista" }, initials: "BA" },
    drills: [{ word: "the usual, please", say: "dâ IÚ-jiu-âl, plíz", note: { en: "= o de sempre.", "pt-BR": "= o de sempre." } }],
    dialogueSteps: [ { text: "Morning! The usual, love?", tr: { en: "Your regular order, right?", "pt-BR": "O seu de sempre, né?" }, ear: { en: "<b>“IÚ-jiu-âl”</b>", "pt-BR": "<b>“IÚ-jiu-âl”</b>" }, audioPrompt: "Barista, warm, already reaching for your cup: “Morning! The usual, love?”", basic: "The usual, please. Cheers!", fluent: "You know me too well — the usual, please. Cheers!" } ] },
  { sequence: 175, blockId: 7, indexInBlock: 25, phase: 3, subBlock: "7.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "Unbreakable", tagline: "Unbreakable — Survived the Storm", shareText: "A crash, a stolen phone, a deposit fight, and a whole city frozen by snow — London threw it all at me and I'm still standing. Unbreakable. 🇬🇧❄️" },
    sceneTitle: { en: "Bonus — Still Standing", "pt-BR": "Bônus — Ainda de Pé" },
    contextDescription: { en: "On a clear, cold morning you stand on a bridge over the Thames, coffee in hand. Hit by a car, robbed, frozen, fought with a landlord — and still here, still standing, stronger. The city couldn't break you.", "pt-BR": "Numa manhã fria e clara você está numa ponte sobre o Tâmisa, café na mão. Atropelado, roubado, congelado, em guerra com o locador — e ainda aqui, ainda de pé, mais forte. A cidade não conseguiu te quebrar." },
    objective: { en: "Own your resilience — you survived it all.", "pt-BR": "Assumir sua resiliência — você sobreviveu a tudo." },
    environment: { mood: "pleased", baseNoise: 42 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "I can handle anything now", say: "ai kén RÉN-dâl É-ni-thing náu", note: { en: "Pure resilience.", "pt-BR": "Pura resiliência." } }],
    dialogueSteps: [
      { text: "After everything this month... how are you still smiling?", tr: { en: "How are you so resilient?", "pt-BR": "Como você está tão resiliente?" }, ear: { en: "<b>“SMÁI-lin”</b>", "pt-BR": "<b>“SMÁI-lin”</b>" }, audioPrompt: "Friend, amazed, by the river: “After everything this month... how are you still smiling?”", basic: "I can handle anything now.", fluent: "Honestly? After all that, I can handle anything now." },
      { text: "You really can. London didn't break you.", tr: { en: "London didn't break you.", "pt-BR": "Londres não te quebrou." }, ear: { en: "<b>“brêik iú”</b>", "pt-BR": "<b>“brêik iú”</b>" }, audioPrompt: "Friend, proud: “You really can. London didn't break you.”", basic: "No. It made me.", fluent: "No — it didn't break me. It made me." },
    ] },
];

export const BLOCK07_BY_SEQUENCE = BLOCK07_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
