/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 04 (Modules 76–100)
 *  "The Professional Game" — 5 sub-blocks:
 *    4.1 Apartment Hunting   (76–80)  viewings, agents, deposits
 *    4.2 Job Search          (81–85)  recruiters, right-to-work, CV
 *    4.3 The Interview       (86–90)  competency Qs, salary, "we'll be in touch"
 *    4.4 Police & Bureaucracy(91–95)  reporting theft, NI number, council tax
 *    4.5 Nightlife / The Door(96–100) bouncer attitude test, rounds, BONUS
 *  Module 100 = "London Professional" milestone selfie.
 * ============================================================ */

export const BLOCK04_MODULES = [
  /* 4.1 — APARTMENT HUNTING */
  { sequence: 76, blockId: 4, indexInBlock: 1, phase: 3, subBlock: "4.1", threshold: 80,
    sceneTitle: { en: "The Viewing", "pt-BR": "A Visita ao Apê" },
    contextDescription: { en: "A damp flat, ten other hopefuls circling. The estate agent talks fast and sells hard. You have five minutes to seem like the ideal tenant.", "pt-BR": "Um apê úmido, dez interessados rondando. O corretor fala rápido e empurra a venda. Você tem cinco minutos para parecer o inquilino ideal." },
    objective: { en: "Express serious interest in a flat.", "pt-BR": "Demonstrar interesse sério num apê." },
    environment: { mood: "neutral", baseNoise: 42 },
    npc: { name: { en: "Estate Agent", "pt-BR": "Corretor(a)" }, initials: "EA" },
    drills: [{ word: "is it still available?", say: "iz it stil a-VÊI-lâ-bâl", note: { en: "Ask if it's taken.", "pt-BR": "Pergunte se já foi alugado." } }],
    dialogueSteps: [ { text: "Lots of interest in this one. Any questions?", tr: { en: "It's popular — any questions?", "pt-BR": "Tem muita procura — alguma pergunta?" }, ear: { en: "<b>“ÍN-trest”</b>", "pt-BR": "<b>“ÍN-trest”</b>" }, audioPrompt: "Agent, slick and rushed: “Lots of interest in this one. Any questions?”", basic: "Is it still available?", fluent: "It's great — is it still available?" } ] },
  { sequence: 77, blockId: 4, indexInBlock: 2, phase: 3, subBlock: "4.1", threshold: 80,
    sceneTitle: { en: "The Catch: Deposit", "pt-BR": "A Pegadinha: O Depósito" },
    contextDescription: { en: "“Six weeks' deposit, one month up front, plus a holding fee.” The numbers stack terrifyingly. You must clarify before committing.", "pt-BR": "“Six weeks' deposit, one month up front, plus a holding fee.” Os números empilham assustadoramente. Você precisa esclarecer antes de se comprometer." },
    objective: { en: "Clarify the upfront costs.", "pt-BR": "Esclarecer os custos iniciais." },
    culturalNote: { en: "UK rentals: deposit (capped at 5 weeks) + first month + referencing. Get it in writing.", "pt-BR": "Aluguel no Reino Unido: depósito (limite 5 semanas) + 1º mês + análise. Peça por escrito." },
    environment: { mood: "neutral", baseNoise: 38 },
    npc: { name: { en: "Estate Agent", "pt-BR": "Corretor(a)" }, initials: "EA" },
    drills: [{ word: "up front", say: "âp FRÂNT", note: { en: "= adiantado.", "pt-BR": "= adiantado." } }],
    dialogueSteps: [ { text: "So that's the deposit and first month up front.", tr: { en: "Pay deposit + first month now.", "pt-BR": "Pague depósito + 1º mês agora." }, ear: { en: "<b>“di-PÓ-zit”</b>", "pt-BR": "<b>“di-PÓ-zit”</b>" }, audioPrompt: "Agent: “So that's the deposit and first month up front.”", basic: "How much in total?", fluent: "And how much is that in total, up front?" } ] },
  { sequence: 78, blockId: 4, indexInBlock: 3, phase: 3, subBlock: "4.1", threshold: 80,
    sceneTitle: { en: "Referencing", "pt-BR": "Análise de Inquilino" },
    contextDescription: { en: "“We'll need references and proof of income.” As a newcomer with no UK history, this is the wall. Negotiate a guarantor or upfront rent.", "pt-BR": "“We'll need references and proof of income.” Como recém-chegado sem histórico no Reino Unido, este é o muro. Negocie um fiador ou aluguel adiantado." },
    objective: { en: "Offer an alternative to UK references.", "pt-BR": "Oferecer alternativa às referências do Reino Unido." },
    environment: { mood: "hostile", baseNoise: 36 },
    npc: { name: { en: "Estate Agent", "pt-BR": "Corretor(a)" }, initials: "EA" },
    drills: [{ word: "pay in advance", say: "pêi in ad-VÁNS", note: { en: "Offer upfront rent.", "pt-BR": "Ofereça aluguel adiantado." } }],
    dialogueSteps: [ { text: "No UK references? That's tricky, I'm afraid.", tr: { en: "No references = a problem.", "pt-BR": "Sem referências = problema." }, ear: { en: "<b>“TRÍ-ki”</b> = difícil", "pt-BR": "<b>“TRÍ-ki”</b> = complicado" }, audioPrompt: "Agent, hesitant: “No UK references? That's tricky, I'm afraid.”", basic: "I can pay in advance.", fluent: "I understand — I can pay a few months in advance." } ] },
  { sequence: 79, blockId: 4, indexInBlock: 4, phase: 3, subBlock: "4.1", threshold: 80,
    sceneTitle: { en: "The Flatshare Interview", "pt-BR": "A Entrevista do Apê Compartilhado" },
    contextDescription: { en: "A cheaper option: a room in a flatshare. But the housemates ‘interview’ you over tea to see if you'd fit. Be likeable, be tidy.", "pt-BR": "Opção mais barata: um quarto compartilhado. Mas os colegas te ‘entrevistam’ tomando chá para ver se você combina. Seja simpático, seja organizado." },
    objective: { en: "Win over potential housemates.", "pt-BR": "Conquistar os possíveis colegas de apê." },
    environment: { mood: "neutral", baseNoise: 34 },
    npc: { name: { en: "Housemate", "pt-BR": "Colega de Apê" }, initials: "HM" },
    drills: [{ word: "easy-going", say: "Í-zi-GÔU-in", note: { en: "= de boa, tranquilo.", "pt-BR": "= de boa, tranquilo." } }],
    dialogueSteps: [ { text: "So... are you tidy? We're pretty chilled here.", tr: { en: "Are you clean/relaxed?", "pt-BR": "Você é organizado/tranquilo?" }, ear: { en: "<b>“TÁI-di”</b> = organizado", "pt-BR": "<b>“TÁI-di”</b> = organizado" }, audioPrompt: "Housemate, casual over tea: “So... are you tidy? We're pretty chilled here.”", basic: "Yeah, tidy and easy-going.", fluent: "Definitely — tidy, easy-going, and respectful." } ] },
  { sequence: 80, blockId: 4, indexInBlock: 5, phase: 3, subBlock: "4.1", threshold: 80,
    sceneTitle: { en: "Signing the Tenancy", "pt-BR": "Assinando o Contrato" },
    contextDescription: { en: "You got it. The contract: a wall of clauses about notice, bills, and the dreaded ‘end of tenancy clean’. Confirm the move-in date.", "pt-BR": "Conseguiu. O contrato: uma parede de cláusulas sobre aviso prévio, contas e a temida ‘limpeza de saída’. Confirme a data de entrada." },
    objective: { en: "Confirm the tenancy start date.", "pt-BR": "Confirmar a data de início do contrato." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Estate Agent", "pt-BR": "Corretor(a)" }, initials: "EA" },
    drills: [{ word: "move-in date", say: "MÚV-in dêit", note: { en: "= data de entrada.", "pt-BR": "= data de entrada." } }],
    dialogueSteps: [ { text: "Sign here and the keys are yours Saturday.", tr: { en: "Sign — keys on Saturday.", "pt-BR": "Assine — chaves no sábado." }, ear: { en: "<b>“tÉ-nân-si”</b> = contrato", "pt-BR": "<b>“tÉ-nân-si”</b> = contrato" }, audioPrompt: "Agent, sliding the contract: “Sign here and the keys are yours Saturday.”", basic: "Saturday? Perfect.", fluent: "Saturday works — where do I sign?" } ] },

  /* 4.2 — JOB SEARCH */
  { sequence: 81, blockId: 4, indexInBlock: 6, phase: 3, subBlock: "4.2", threshold: 80,
    sceneTitle: { en: "The Recruiter Call", "pt-BR": "A Ligação do Recrutador" },
    contextDescription: { en: "An unknown number — a recruiter, talking a mile a minute about a ‘brilliant opportunity’. You must sound keen and competent on the spot.", "pt-BR": "Número desconhecido — um recrutador, falando mil palavras por minuto sobre uma ‘oportunidade brilhante’. Você precisa soar interessado e competente na hora." },
    objective: { en: "Express availability and interest fast.", "pt-BR": "Expressar disponibilidade e interesse rápido." },
    environment: { mood: "neutral", baseNoise: 40 },
    npc: { name: { en: "Recruiter", "pt-BR": "Recrutador(a)" }, initials: "RE" },
    drills: [{ word: "I'm available", say: "aim a-VÊI-lâ-bâl", note: { en: "= estou disponível.", "pt-BR": "= estou disponível." } }],
    dialogueSteps: [ { text: "Are you actively looking? Can you start soon?", tr: { en: "Job hunting? Can you start soon?", "pt-BR": "Procurando emprego? Pode começar logo?" }, ear: { en: "<b>“ÉK-tiv-li”</b>", "pt-BR": "<b>“ÉK-tiv-li”</b>" }, audioPrompt: "Recruiter, rapid-fire: “Are you actively looking? Can you start soon?”", basic: "Yes, I'm available.", fluent: "Yes — actively looking and available immediately." } ] },
  { sequence: 82, blockId: 4, indexInBlock: 7, phase: 3, subBlock: "4.2", threshold: 80,
    sceneTitle: { en: "Right to Work", "pt-BR": "Direito de Trabalhar" },
    contextDescription: { en: "“Do you have the right to work in the UK?” The gatekeeper question. Your honest, confident answer decides if the call continues.", "pt-BR": "“Do you have the right to work in the UK?” A pergunta-filtro. Sua resposta honesta e confiante decide se a ligação continua." },
    objective: { en: "State your right-to-work status clearly.", "pt-BR": "Declarar seu status de direito de trabalho com clareza." },
    culturalNote: { en: "Employers must legally check this. Know your visa/share code.", "pt-BR": "Empregadores são obrigados a checar isso. Saiba seu visto/share code." },
    environment: { mood: "neutral", baseNoise: 38 },
    npc: { name: { en: "Recruiter", "pt-BR": "Recrutador(a)" }, initials: "RE" },
    drills: [{ word: "right to work", say: "ráit tu UÂRK", note: { en: "= direito de trabalhar.", "pt-BR": "= direito de trabalhar." } }],
    dialogueSteps: [ { text: "Do you have the right to work in the UK?", tr: { en: "Can you legally work here?", "pt-BR": "Você pode trabalhar aqui legalmente?" }, ear: { en: "<b>“ráit tu uârk”</b>", "pt-BR": "<b>“ráit tu uârk”</b>" }, audioPrompt: "Recruiter: “Do you have the right to work in the UK?”", basic: "Yes, I do.", fluent: "Yes — I have a valid work visa." } ] },
  { sequence: 83, blockId: 4, indexInBlock: 8, phase: 3, subBlock: "4.2", threshold: 80,
    sceneTitle: { en: "“Sell Yourself”", "pt-BR": "“Se Venda”" },
    contextDescription: { en: "“Tell me about your experience.” Thirty seconds to pitch your whole career — concise, confident, no rambling. The reality-shock of self-promotion.", "pt-BR": "“Tell me about your experience.” Trinta segundos para resumir toda a carreira — conciso, confiante, sem enrolação. O choque de ter que se vender." },
    objective: { en: "Pitch your experience concisely.", "pt-BR": "Resumir sua experiência de forma concisa." },
    environment: { mood: "neutral", baseNoise: 36 },
    npc: { name: { en: "Recruiter", "pt-BR": "Recrutador(a)" }, initials: "RE" },
    drills: [{ word: "I've got experience in", say: "aiv gót iks-PÍ-ri-âns in", note: { en: "Lead your pitch.", "pt-BR": "Comece seu pitch." } }],
    dialogueSteps: [ { text: "Tell me about your experience.", tr: { en: "Summarise your background.", "pt-BR": "Resuma sua experiência." }, ear: { en: "<b>“iks-PÍ-ri-âns”</b>", "pt-BR": "<b>“iks-PÍ-ri-âns”</b>" }, audioPrompt: "Recruiter: “Tell me about your experience.”", basic: "I've got five years in design.", fluent: "I've got five years' experience in product design." } ] },
  { sequence: 84, blockId: 4, indexInBlock: 9, phase: 3, subBlock: "4.2", threshold: 80,
    sceneTitle: { en: "Booking the Interview", "pt-BR": "Marcando a Entrevista" },
    contextDescription: { en: "“They'd like to see you Thursday at 2.” Diaries clash, accents blur the times. Confirm the slot without a costly mix-up.", "pt-BR": "“They'd like to see you Thursday at 2.” Agendas batem, o sotaque embaralha os horários. Confirme o horário sem confusão custosa." },
    objective: { en: "Confirm an interview time precisely.", "pt-BR": "Confirmar o horário da entrevista com precisão." },
    environment: { mood: "neutral", baseNoise: 36 },
    npc: { name: { en: "Recruiter", "pt-BR": "Recrutador(a)" }, initials: "RE" },
    drills: [{ word: "Thursday at two", say: "THÂRZ-dêi at tú", note: { en: "Confirm day + time.", "pt-BR": "Confirme dia + hora." } }],
    dialogueSteps: [ { text: "Thursday at two work for you?", tr: { en: "Can you do Thursday 2pm?", "pt-BR": "Pode quinta às 14h?" }, ear: { en: "<b>“THÂRZ-dêi”</b>", "pt-BR": "<b>“THÂRZ-dêi”</b>" }, audioPrompt: "Recruiter: “Thursday at two work for you?”", basic: "Thursday at two, yes.", fluent: "Thursday at two — perfect, I'll be there." } ] },
  { sequence: 85, blockId: 4, indexInBlock: 10, phase: 3, subBlock: "4.2", threshold: 80,
    sceneTitle: { en: "What's the Salary?", "pt-BR": "Qual o Salário?" },
    contextDescription: { en: "The delicate question. Brits dance around money. You must ask the range without seeming greedy — but knowing your worth.", "pt-BR": "A pergunta delicada. Britânicos rodeiam o assunto dinheiro. Você precisa perguntar a faixa sem parecer ganancioso — mas sabendo seu valor." },
    objective: { en: "Ask about salary tactfully.", "pt-BR": "Perguntar o salário com tato." },
    environment: { mood: "neutral", baseNoise: 34 },
    npc: { name: { en: "Recruiter", "pt-BR": "Recrutador(a)" }, initials: "RE" },
    drills: [{ word: "the salary range", say: "dâ SÉ-lâ-ri rêindj", note: { en: "= a faixa salarial.", "pt-BR": "= a faixa salarial." } }],
    dialogueSteps: [ { text: "Any questions before Thursday?", tr: { en: "Questions before the interview?", "pt-BR": "Perguntas antes de quinta?" }, ear: { en: "<b>“SÉ-lâ-ri”</b>", "pt-BR": "<b>“SÉ-lâ-ri”</b>" }, audioPrompt: "Recruiter, wrapping up: “Any questions before Thursday?”", basic: "What's the salary range?", fluent: "Yes — could you share the salary range?" } ] },

  /* 4.3 — THE INTERVIEW */
  { sequence: 86, blockId: 4, indexInBlock: 11, phase: 2, subBlock: "4.3", threshold: 80,
    sceneTitle: { en: "Tell Me About Yourself", "pt-BR": "Fale Sobre Você" },
    contextDescription: { en: "The glass meeting room. Two interviewers, one fake smile. The dreaded opener: “So, tell me about yourself.” Don't recite your CV — tell a story.", "pt-BR": "A sala de reunião de vidro. Dois entrevistadores, um sorriso falso. A temida abertura: “So, tell me about yourself.” Não recite o currículo — conte uma história." },
    objective: { en: "Open the interview with a strong summary.", "pt-BR": "Abrir a entrevista com um bom resumo." },
    environment: { mood: "hostile", baseNoise: 28 },
    npc: { name: { en: "Interviewer", "pt-BR": "Entrevistador(a)" }, initials: "IV" },
    drills: [{ word: "currently I…", say: "KÂ-rent-li ai", note: { en: "Anchor in the present.", "pt-BR": "Ancore no presente." } }],
    dialogueSteps: [ { text: "So, tell me about yourself.", tr: { en: "Give a short personal summary.", "pt-BR": "Dê um breve resumo pessoal." }, ear: { en: "<b>“a-BÁUT iór-SÉLF”</b>", "pt-BR": "<b>“a-BÁUT iór-SÉLF”</b>" }, audioPrompt: "Interviewer, neutral: “So, tell me about yourself.”", basic: "Currently I'm a designer.", fluent: "Currently I'm a product designer with five years' experience." } ] },
  { sequence: 87, blockId: 4, indexInBlock: 12, phase: 2, subBlock: "4.3", threshold: 80,
    sceneTitle: { en: "Your Greatest Weakness", "pt-BR": "Seu Maior Defeito" },
    contextDescription: { en: "The trap question: “What's your greatest weakness?” Answer honestly enough to be human, smartly enough to still get hired.", "pt-BR": "A pergunta-armadilha: “What's your greatest weakness?” Responda honesto o bastante para ser humano, esperto o bastante para ser contratado." },
    objective: { en: "Turn a weakness into growth.", "pt-BR": "Transformar um defeito em crescimento." },
    environment: { mood: "hostile", baseNoise: 28 },
    npc: { name: { en: "Interviewer", "pt-BR": "Entrevistador(a)" }, initials: "IV" },
    drills: [{ word: "I'm working on", say: "aim UÂR-kin ón", note: { en: "Frame growth.", "pt-BR": "Enquadre como evolução." } }],
    dialogueSteps: [ { text: "And your greatest weakness?", tr: { en: "What's a weakness of yours?", "pt-BR": "Qual seu maior defeito?" }, ear: { en: "<b>“UÍK-nâs”</b>", "pt-BR": "<b>“UÍK-nâs”</b>" }, audioPrompt: "Interviewer, leaning in: “And your greatest weakness?”", basic: "I'm working on delegating.", fluent: "I take on too much — but I'm working on delegating." } ] },
  { sequence: 88, blockId: 4, indexInBlock: 13, phase: 2, subBlock: "4.3", threshold: 80,
    sceneTitle: { en: "Why This Company?", "pt-BR": "Por Que Esta Empresa?" },
    contextDescription: { en: "“Why do you want to work here?” They want flattery dressed as research. Show you know them — and mean it.", "pt-BR": "“Why do you want to work here?” Eles querem bajulação disfarçada de pesquisa. Mostre que conhece a empresa — e seja sincero." },
    objective: { en: "Give a researched reason for wanting the role.", "pt-BR": "Dar um motivo bem fundamentado para querer a vaga." },
    environment: { mood: "neutral", baseNoise: 28 },
    npc: { name: { en: "Interviewer", "pt-BR": "Entrevistador(a)" }, initials: "IV" },
    drills: [{ word: "I admire your", say: "ai ad-MÁIR iór", note: { en: "Open with praise.", "pt-BR": "Comece com elogio." } }],
    dialogueSteps: [ { text: "Why do you want to work here?", tr: { en: "Why this company?", "pt-BR": "Por que esta empresa?" }, ear: { en: "<b>“ad-MÁIR”</b>", "pt-BR": "<b>“ad-MÁIR”</b>" }, audioPrompt: "Interviewer: “Why do you want to work here?”", basic: "I admire your work.", fluent: "I admire your design work and your mission." } ] },
  { sequence: 89, blockId: 4, indexInBlock: 14, phase: 2, subBlock: "4.3", threshold: 80,
    sceneTitle: { en: "Negotiating the Offer", "pt-BR": "Negociando a Proposta" },
    contextDescription: { en: "They want you — but the first number is low. The hardest sentence in a second language: asking for more, calmly, without flinching.", "pt-BR": "Eles te querem — mas o primeiro número é baixo. A frase mais difícil num segundo idioma: pedir mais, com calma, sem hesitar." },
    objective: { en: "Counter-offer professionally.", "pt-BR": "Fazer uma contraproposta profissional." },
    environment: { mood: "hostile", baseNoise: 28 },
    npc: { name: { en: "Hiring Manager", "pt-BR": "Gestor(a)" }, initials: "HM" },
    drills: [{ word: "I was hoping for", say: "ai uâz RÔU-pin for", note: { en: "Soften a counter-offer.", "pt-BR": "Suavize a contraproposta." } }],
    dialogueSteps: [ { text: "We can offer forty thousand.", tr: { en: "The offer is £40k.", "pt-BR": "A proposta é £40 mil." }, ear: { en: "<b>“FÓR-ti THÁU-zând”</b>", "pt-BR": "<b>“FÓR-ti THÁU-zând”</b>" }, audioPrompt: "Manager: “We can offer forty thousand.”", basic: "I was hoping for more.", fluent: "Thank you — I was hoping for closer to forty-five." } ] },
  { sequence: 90, blockId: 4, indexInBlock: 15, phase: 2, subBlock: "4.3", threshold: 80,
    sceneTitle: { en: "“We'll Be In Touch”", "pt-BR": "“A Gente Entra em Contato”" },
    contextDescription: { en: "The interview ends with the ambiguous British farewell: “We'll be in touch.” Could mean yes, could mean never. Close warmly and confidently.", "pt-BR": "A entrevista acaba com o ambíguo adeus britânico: “We'll be in touch.” Pode ser sim, pode ser nunca. Encerre com calor e confiança." },
    objective: { en: "Close the interview gracefully.", "pt-BR": "Encerrar a entrevista com elegância." },
    environment: { mood: "neutral", baseNoise: 28 },
    npc: { name: { en: "Interviewer", "pt-BR": "Entrevistador(a)" }, initials: "IV" },
    drills: [{ word: "thanks for your time", say: "TÉNKS for iór táim", note: { en: "Professional close.", "pt-BR": "Encerramento profissional." } }],
    dialogueSteps: [ { text: "Great. We'll be in touch.", tr: { en: "We'll contact you (maybe).", "pt-BR": "A gente entra em contato (talvez)." }, ear: { en: "<b>“in TÂTCH”</b>", "pt-BR": "<b>“in TÂTCH”</b>" }, audioPrompt: "Interviewer, standing, polite: “Great. We'll be in touch.”", basic: "Thanks for your time.", fluent: "Thank you for your time — I look forward to hearing from you." } ] },

  /* 4.4 — POLICE & BUREAUCRACY */
  { sequence: 91, blockId: 4, indexInBlock: 16, phase: 2, subBlock: "4.4", threshold: 80,
    sceneTitle: { en: "Reporting a Theft", "pt-BR": "Registrando um Roubo" },
    contextDescription: { en: "Your phone's been nicked on the bus. At the police station, a weary officer slides a form across. You must report it clearly for insurance.", "pt-BR": "Seu celular foi roubado no ônibus. Na delegacia, um policial cansado empurra um formulário. Você precisa relatar com clareza para o seguro." },
    objective: { en: "Report a stolen item.", "pt-BR": "Relatar um item roubado." },
    culturalNote: { en: "‘Nicked’ = stolen. You need a crime reference number for insurance.", "pt-BR": "‘Nicked’ = roubado. Você precisa de um número de ocorrência para o seguro." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "Police Officer", "pt-BR": "Policial" }, initials: "PO" },
    drills: [{ word: "it was stolen", say: "it uâz STÔU-lân", note: { en: "= foi roubado.", "pt-BR": "= foi roubado." } }],
    dialogueSteps: [ { text: "What would you like to report?", tr: { en: "What's the incident?", "pt-BR": "O que deseja relatar?" }, ear: { en: "<b>“ri-PÓRT”</b>", "pt-BR": "<b>“ri-PÓRT”</b>" }, audioPrompt: "Officer, flat: “What would you like to report?”", basic: "My phone was stolen.", fluent: "My phone was stolen on the bus this morning." } ] },
  { sequence: 92, blockId: 4, indexInBlock: 17, phase: 2, subBlock: "4.4", threshold: 80,
    sceneTitle: { en: "The Statement", "pt-BR": "O Depoimento" },
    contextDescription: { en: "“Talk me through exactly what happened.” You must narrate events in order, in past tense, under a sceptical gaze. Precision matters.", "pt-BR": "“Talk me through exactly what happened.” Você precisa narrar os fatos em ordem, no passado, sob um olhar cético. A precisão importa." },
    objective: { en: "Narrate events in the past tense.", "pt-BR": "Narrar os fatos no passado." },
    environment: { mood: "neutral", baseNoise: 28 },
    npc: { name: { en: "Police Officer", "pt-BR": "Policial" }, initials: "PO" },
    drills: [{ word: "someone took it", say: "SÂM-uân tuk it", note: { en: "Past tense of take.", "pt-BR": "Passado de take." } }],
    dialogueSteps: [ { text: "Talk me through what happened.", tr: { en: "Describe the events.", "pt-BR": "Descreva o que houve." }, ear: { en: "<b>“RÉ-pând”</b>", "pt-BR": "<b>“RÉ-pând”</b>" }, audioPrompt: "Officer, pen poised: “Talk me through what happened.”", basic: "Someone took it on the bus.", fluent: "Someone took it from my bag while I was on the bus." } ] },
  { sequence: 93, blockId: 4, indexInBlock: 18, phase: 2, subBlock: "4.4", threshold: 80,
    sceneTitle: { en: "The NI Number", "pt-BR": "O Número de Seguridade" },
    contextDescription: { en: "To get paid legally you need a National Insurance number. A government phone line, hold music, and a maze of menus. Request an application.", "pt-BR": "Para receber salário legalmente você precisa de um National Insurance number. Linha do governo, música de espera e um labirinto de menus. Solicite a aplicação." },
    objective: { en: "Request a National Insurance number.", "pt-BR": "Solicitar um número de seguridade social." },
    culturalNote: { en: "‘NI number’ = like a tax/social-security ID. No NI = taxed at emergency rate.", "pt-BR": "‘NI number’ = espécie de CPF/INSS. Sem NI = tributado na alíquota de emergência." },
    environment: { mood: "neutral", baseNoise: 32 },
    npc: { name: { en: "Gov Helpline", "pt-BR": "Linha do Governo" }, initials: "GH" },
    drills: [{ word: "apply for", say: "a-PLÁI for", note: { en: "= solicitar.", "pt-BR": "= solicitar." } }],
    dialogueSteps: [ { text: "How can I help you today?", tr: { en: "How can I help?", "pt-BR": "Como posso ajudar?" }, ear: { en: "<b>“a-PLÁI for”</b>", "pt-BR": "<b>“a-PLÁI for”</b>" }, audioPrompt: "Helpline, after hold music: “How can I help you today?”", basic: "I want to apply for an NI number.", fluent: "I'd like to apply for a National Insurance number." } ] },
  { sequence: 94, blockId: 4, indexInBlock: 19, phase: 3, subBlock: "4.4", threshold: 80,
    sceneTitle: { en: "Registering with a GP", "pt-BR": "Cadastro no Posto (GP)" },
    contextDescription: { en: "To access the NHS you must register with a local GP surgery. A guarded receptionist demands proof of address — the recurring newcomer wall.", "pt-BR": "Para usar o NHS você precisa se cadastrar num posto (GP). Uma recepcionista arredia exige comprovante de endereço — o muro recorrente do recém-chegado." },
    objective: { en: "Register as a new NHS patient.", "pt-BR": "Cadastrar-se como novo paciente do NHS." },
    environment: { mood: "neutral", baseNoise: 34 },
    npc: { name: { en: "GP Receptionist", "pt-BR": "Recepcionista do Posto" }, initials: "GR" },
    drills: [{ word: "register as a patient", say: "RÉ-djis-târ az a PÊI-shânt", note: { en: "= cadastrar-se como paciente.", "pt-BR": "= cadastrar-se como paciente." } }],
    dialogueSteps: [ { text: "Are you registering as a new patient?", tr: { en: "New patient registration?", "pt-BR": "Cadastro de novo paciente?" }, ear: { en: "<b>“RÉ-djis-târ”</b>", "pt-BR": "<b>“RÉ-djis-târ”</b>" }, audioPrompt: "Receptionist: “Are you registering as a new patient?”", basic: "Yes, please.", fluent: "Yes — I'd like to register as a new patient." } ] },
  { sequence: 95, blockId: 4, indexInBlock: 20, phase: 3, subBlock: "4.4", threshold: 80,
    sceneTitle: { en: "Council Tax", "pt-BR": "Imposto Municipal" },
    contextDescription: { en: "A brown envelope: council tax. A bill you didn't expect, in jargon you don't know. You call the council to set it up and ask about discounts.", "pt-BR": "Um envelope pardo: council tax. Uma conta inesperada, em jargão desconhecido. Você liga para a prefeitura para regularizar e perguntar sobre descontos." },
    objective: { en: "Set up council tax and ask about discounts.", "pt-BR": "Regularizar o imposto e perguntar por descontos." },
    culturalNote: { en: "Council tax funds local services. Single occupants get 25% off — ask!", "pt-BR": "O council tax custeia serviços locais. Quem mora sozinho tem 25% de desconto — pergunte!" },
    environment: { mood: "neutral", baseNoise: 32 },
    npc: { name: { en: "Council Office", "pt-BR": "Prefeitura" }, initials: "CT" },
    drills: [{ word: "a discount", say: "a DÍS-kaunt", note: { en: "= desconto.", "pt-BR": "= desconto." } }],
    dialogueSteps: [ { text: "You're setting up council tax for the flat?", tr: { en: "Registering council tax?", "pt-BR": "Regularizando o imposto?" }, ear: { en: "<b>“KÁUN-sâl téks”</b>", "pt-BR": "<b>“KÁUN-sâl téks”</b>" }, audioPrompt: "Council office: “You're setting up council tax for the flat?”", basic: "Yes. Any discount alone?", fluent: "Yes — and is there a single-person discount?" } ] },

  /* 4.5 — NIGHTLIFE / THE DOOR */
  { sequence: 96, blockId: 4, indexInBlock: 21, phase: 3, subBlock: "4.5", threshold: 80,
    sceneTitle: { en: "The Door Selector", "pt-BR": "O Seletor da Porta" },
    contextDescription: { en: "A techno club, bass thudding through the pavement, a long cold queue. The bouncer judges your VIBE more than your words. Sound relaxed, not desperate.", "pt-BR": "Um clube de techno, o grave martelando a calçada, uma fila fria e longa. O segurança julga sua ATITUDE mais que suas palavras. Soe tranquilo, não desesperado." },
    objective: { en: "Project relaxed confidence to the bouncer.", "pt-BR": "Projetar confiança tranquila ao segurança." },
    culturalNote: { en: "Door policy = attitude. Over-eager = rejected. Cool and brief = in.", "pt-BR": "Política da porta = atitude. Afobado = barrado. Tranquilo e breve = entra." },
    environment: { mood: "hostile", baseNoise: 66 },
    npc: { name: { en: "Bouncer", "pt-BR": "Segurança" }, initials: "BX" },
    drills: [{ word: "just the two of us", say: "djâst dâ tú âv âs", note: { en: "State your group size, calm.", "pt-BR": "Diga o tamanho do grupo, calmo." } }],
    dialogueSteps: [ { text: "How many? You been here before?", tr: { en: "Group size? Been here before?", "pt-BR": "Quantos? Já veio aqui?" }, ear: { en: "<b>“rau MÉ-ni”</b>", "pt-BR": "<b>“rau MÉ-ni”</b>" }, audioPrompt: "Bouncer, flat, over heavy bass: “How many? You been here before?”", basic: "Just the two of us.", fluent: "Just the two of us — heard great things." } ] },
  { sequence: 97, blockId: 4, indexInBlock: 22, phase: 3, subBlock: "4.5", threshold: 80,
    sceneTitle: { en: "Ordering Over the Noise", "pt-BR": "Pedindo no Barulho" },
    contextDescription: { en: "Inside, the music is a physical force. At the bar you must order a round by shouting clearly and holding up fingers — words alone won't survive the noise.", "pt-BR": "Lá dentro, a música é uma força física. No bar você precisa pedir uma rodada gritando claro e mostrando os dedos — só palavras não sobrevivem ao barulho." },
    objective: { en: "Order drinks over deafening music.", "pt-BR": "Pedir bebidas sobre a música ensurdecedora." },
    environment: { mood: "hostile", baseNoise: 70 },
    npc: { name: { en: "Bartender", "pt-BR": "Bartender" }, initials: "BT" },
    drills: [{ word: "two beers!", say: "tú BÍRZ", note: { en: "Short + loud.", "pt-BR": "Curto + alto." } }],
    dialogueSteps: [ { text: "WHAT CAN I GET YA?", tr: { en: "What do you want? (shouted)", "pt-BR": "O que você quer? (gritado)" }, ear: { en: "<b>“guét ia”</b>", "pt-BR": "<b>“guét ia”</b>" }, audioPrompt: "Bartender, screaming over the music: “WHAT CAN I GET YA?”", basic: "Two beers!", fluent: "Two beers, please!" } ] },
  { sequence: 98, blockId: 4, indexInBlock: 23, phase: 3, subBlock: "4.5", threshold: 80,
    sceneTitle: { en: "Last Orders", "pt-BR": "Últimos Pedidos" },
    contextDescription: { en: "A bell rings, lights flicker: “Last orders!” The peculiar British closing ritual. You have seconds to get one final round before the bar shuts.", "pt-BR": "Um sino toca, as luzes piscam: “Last orders!” O peculiar ritual de fechamento britânico. Você tem segundos para o último pedido antes do bar fechar." },
    objective: { en: "Get a final order in before closing.", "pt-BR": "Fazer o último pedido antes de fechar." },
    culturalNote: { en: "‘Last orders’ + ‘time at the bar’ = the pub is closing now. Move fast.", "pt-BR": "‘Last orders’ + ‘time at the bar’ = o bar está fechando. Corra." },
    environment: { mood: "hostile", baseNoise: 62 },
    npc: { name: { en: "Bartender", "pt-BR": "Bartender" }, initials: "BT" },
    drills: [{ word: "last orders", say: "lást ÓR-dârz", note: { en: "= últimos pedidos.", "pt-BR": "= últimos pedidos." } }],
    dialogueSteps: [ { text: "Last orders! Anything else?", tr: { en: "Bar's closing — want more?", "pt-BR": "Vai fechar — quer mais?" }, ear: { en: "<b>“lást ÓR-dârz”</b>", "pt-BR": "<b>“lást ÓR-dârz”</b>" }, audioPrompt: "Bartender, ringing the bell: “Last orders! Anything else?”", basic: "Two more, please!", fluent: "Two more of the same, please!" } ] },
  { sequence: 99, blockId: 4, indexInBlock: 24, phase: 3, subBlock: "4.5", threshold: 80,
    sceneTitle: { en: "Getting Home Safe", "pt-BR": "Voltando em Segurança" },
    contextDescription: { en: "3am, ears ringing, no trains. You order a cab and must give your address clearly to a driver who's heard every drunk slur tonight.", "pt-BR": "3h da manhã, ouvidos zunindo, sem trens. Você pede um táxi e precisa dar seu endereço claramente a um motorista que já ouviu toda gíria de bêbado hoje." },
    objective: { en: "Give your home address clearly, late and tired.", "pt-BR": "Dar seu endereço com clareza, tarde e cansado." },
    environment: { mood: "neutral", baseNoise: 44 },
    npc: { name: { en: "Cab Driver", "pt-BR": "Motorista" }, initials: "CB" },
    drills: [{ word: "take me to", say: "têik mi tu", note: { en: "= me leve para.", "pt-BR": "= me leve para." } }],
    dialogueSteps: [ { text: "Right, where are we off to?", tr: { en: "Where to?", "pt-BR": "Para onde vamos?" }, ear: { en: "<b>“óf tu”</b>", "pt-BR": "<b>“óf tu”</b>" }, audioPrompt: "Cab driver, late-night calm: “Right, where are we off to?”", basic: "Take me to Camden.", fluent: "Take me to Camden, please — Inverness Street." } ] },
  { sequence: 100, blockId: 4, indexInBlock: 25, phase: 3, subBlock: "4.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "London Professional", tagline: "London Professional — Hired & Housed", shareText: "Flat secured, job landed, past the bouncer and home safe — I'm a London Professional now! 🇬🇧💼" },
    sceneTitle: { en: "Bonus — The Offer Call", "pt-BR": "Bônus — A Ligação da Proposta" },
    contextDescription: { en: "Your phone lights up. The hiring manager: “We'd love to offer you the job.” Flat sorted, job won — you've cracked the professional game. Savour it.", "pt-BR": "Seu celular acende. O gestor: “We'd love to offer you the job.” Apê resolvido, emprego conquistado — você decifrou o jogo profissional. Saboreie." },
    objective: { en: "Accept the job offer with grace.", "pt-BR": "Aceitar a proposta de emprego com elegância." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Hiring Manager", "pt-BR": "Gestor(a)" }, initials: "HM" },
    drills: [{ word: "I accept", say: "ai ak-SÉPT", note: { en: "= eu aceito.", "pt-BR": "= eu aceito." } }],
    dialogueSteps: [
      { text: "We'd love to offer you the job. Can you start the first?", tr: { en: "You got the job — start on the 1st?", "pt-BR": "Você conseguiu — começa dia 1º?" }, ear: { en: "<b>“â-fâr iú dâ djób”</b>", "pt-BR": "<b>“â-fâr iú dâ djób”</b>" }, audioPrompt: "Hiring manager, warm: “We'd love to offer you the job. Can you start the first?”", basic: "Yes! I accept.", fluent: "Yes — I accept, I can start on the first!" },
      { text: "Brilliant. Welcome to the team!", tr: { en: "Welcome aboard!", "pt-BR": "Bem-vindo ao time!" }, ear: { en: "<b>“BRÍ-li-ânt”</b>", "pt-BR": "<b>“BRÍ-li-ânt”</b>" }, audioPrompt: "Manager, delighted: “Brilliant. Welcome to the team!”", basic: "Thank you so much!", fluent: "Thank you — I can't wait to start!" },
    ] },
];

export const BLOCK04_BY_SEQUENCE = BLOCK04_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
