/* ============================================================
 *  LinguoBound — City 01: London · BLOCK 12 (Modules 276–300)
 *  "Deepening Community" — 5 sub-blocks:
 *    12.1 Giving Back        (276–280) charity / food bank / street collection
 *    12.2 Building Something  (281–285) organizing a community street fair
 *    12.3 A Changing Manor    (286–290) the area shifts — loss, arrivals, balance
 *    12.4 The Inner Circle    (291–295) friendships deepen under real weight
 *    12.5 Pillar of the Manor (296–300) leadership — BONUS milestone (300)
 *  Module 300 = "Pillar of the Community" milestone selfie.
 * ============================================================ */

export const BLOCK12_MODULES = [
  /* 12.1 — GIVING BACK */
  { sequence: 276, blockId: 12, indexInBlock: 1, phase: 2, subBlock: "12.1", threshold: 80,
    sceneTitle: { en: "Signing Up at the Food Bank", "pt-BR": "Inscrição no Banco de Alimentos" },
    contextDescription: { en: "A draughty church hall in your borough. You've decided to give back to the city that took you in. The volunteer coordinator, brisk but kind, hands you a hi-vis vest and a clipboard.", "pt-BR": "Um salão paroquial cheio de correntes de ar no seu bairro. Você decidiu retribuir à cidade que te acolheu. A coordenadora de voluntários, ágil mas gentil, te entrega um colete refletivo e uma prancheta." },
    objective: { en: "Volunteer yourself and ask how to help.", "pt-BR": "Oferecer-se como voluntário e perguntar como ajudar." },
    culturalNote: { en: "‘Hi-vis’ (high-visibility vest) is everywhere in UK volunteering and work. Putting one on signals ‘I'm here to graft’.", "pt-BR": "‘Hi-vis’ (colete refletivo) é onipresente no voluntariado e trabalho no Reino Unido. Vestir um sinaliza ‘vim pra trabalhar’." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Volunteer Coordinator", "pt-BR": "Coordenadora de Voluntários" }, initials: "VC" },
    drills: [{ word: "I'd like to help out", say: "aid láik tu RÉLP áut", note: { en: "= eu gostaria de ajudar.", "pt-BR": "= eu gostaria de ajudar." } }, { word: "where do you need me?", say: "uér du iú NÍD mi", note: { en: "Offer to be useful anywhere.", "pt-BR": "Ofereça-se para ser útil em qualquer função." } }],
    dialogueSteps: [ { text: "New face! Lovely. Have you volunteered with us before?", tr: { en: "She welcomes you in.", "pt-BR": "Ela te dá as boas-vindas." }, ear: { en: "<b>“RÉLP áut”</b>", "pt-BR": "<b>“RÉLP áut”</b>" }, audioPrompt: "Coordinator, brisk and warm in a busy hall: “New face! Lovely. Have you volunteered with us before?”", basic: "No, but I'd like to help out.", fluent: "First time — I'd really like to help out. Where do you need me?" } ] },
  { sequence: 277, blockId: 12, indexInBlock: 2, phase: 2, subBlock: "12.1", threshold: 80,
    sceneTitle: { en: "Sorting the Donations", "pt-BR": "Separando as Doações" },
    contextDescription: { en: "Shoulder to shoulder with a chatty retiree named Pam, you sort tins into crates. She tests you with rapid-fire banter — the British way of deciding if she likes you.", "pt-BR": "Ombro a ombro com a aposentada tagarela Pam, você separa latas em caixotes. Ela te testa com uma zoeira rápida — o jeito britânico de decidir se gosta de você." },
    objective: { en: "Hold your own in friendly British banter.", "pt-BR": "Manter o jogo na zoeira amistosa britânica." },
    environment: { mood: "pleased", baseNoise: 38 },
    npc: { name: { en: "Pam (Volunteer)", "pt-BR": "Pam (Voluntária)" }, initials: "Pa" },
    drills: [{ word: "you're keeping me on my toes", say: "iór KÍ-pin mi on mai TÔUZ", note: { en: "= você me mantém esperto/alerta.", "pt-BR": "= você me mantém esperto/alerta." } }],
    dialogueSteps: [ { text: "Beans with beans, love — not with the soup! Where you been all my life?", tr: { en: "Pam teases as you work.", "pt-BR": "Pam te zoa enquanto trabalham." }, ear: { en: "<b>“on mai TÔUZ”</b>", "pt-BR": "<b>“on mai TÔUZ”</b>" }, audioPrompt: "Pam, cackling over crates of tins: “Beans with beans, love — not with the soup! Where you been all my life?”", basic: "Sorry, Pam! You're keeping me on my toes.", fluent: "Beans with beans, got it — blimey, Pam, you're keeping me on my toes!" } ] },
  { sequence: 278, blockId: 12, indexInBlock: 3, phase: 2, subBlock: "12.1", threshold: 80,
    sceneTitle: { en: "Serving with Dignity", "pt-BR": "Servir com Dignidade" },
    contextDescription: { en: "At the hot-food counter, a quietly proud man your own age comes through the line, ashamed to be there. You learned this lesson the hard way once. You serve him as an equal, not a case.", "pt-BR": "No balcão de comida quente, um homem da sua idade, de orgulho calado, passa pela fila, envergonhado de estar ali. Você aprendeu essa lição do jeito difícil um dia. Você o serve como um igual, não como um ‘caso’." },
    objective: { en: "Offer help warmly, preserving someone's dignity.", "pt-BR": "Oferecer ajuda com calor, preservando a dignidade do outro." },
    environment: { mood: "neutral", baseNoise: 34 },
    npc: { name: { en: "Guest", "pt-BR": "Visitante" }, initials: "Gu" },
    drills: [{ word: "good to see you", say: "gúd tu SÍ iú", note: { en: "Greet him like any friend.", "pt-BR": "Cumprimente-o como um amigo qualquer." } }, { word: "there's plenty", say: "dérs PLÉN-ti", note: { en: "= tem de sobra.", "pt-BR": "= tem de sobra." } }],
    dialogueSteps: [ { text: "I, uh... I don't usually do this. First time.", tr: { en: "He's ashamed — put him at ease.", "pt-BR": "Ele está envergonhado — deixe-o à vontade." }, ear: { en: "<b>“PLÉN-ti”</b>", "pt-BR": "<b>“PLÉN-ti”</b>" }, audioPrompt: "Guest, eyes down, almost whispering at the counter: “I, uh... I don't usually do this. First time.”", basic: "Good to see you. There's plenty.", fluent: "Hey, good to see you — sit wherever, there's plenty, take your time." } ] },
  { sequence: 279, blockId: 12, indexInBlock: 4, phase: 3, subBlock: "12.1", threshold: 80,
    sceneTitle: { en: "The Street Collection", "pt-BR": "A Coleta na Rua" },
    contextDescription: { en: "Rattling a collection tin outside the Tube in the cold, you must catch the eye of hurried Londoners and ask for change — through a wall of polite British avoidance and the odd flat ‘no’.", "pt-BR": "Chacoalhando uma latinha de doações na saída do metrô no frio, você precisa captar o olhar de londrinos apressados e pedir trocado — através de uma parede de evasão educada britânica e de um ‘não’ seco aqui e ali." },
    objective: { en: "Make a warm, quick pitch to passing strangers.", "pt-BR": "Fazer um apelo caloroso e rápido a desconhecidos que passam." },
    environment: { mood: "neutral", baseNoise: 64 },
    npc: { name: { en: "Passer-by", "pt-BR": "Transeunte" }, initials: "Pb" },
    drills: [{ word: "spare a little for the food bank?", say: "spér a LÍ-tâl fôr dâ FÚD-benk", note: { en: "= um trocado para o banco de alimentos?", "pt-BR": "= um trocado para o banco de alimentos?" } }],
    dialogueSteps: [ { text: "(hurrying past, not making eye contact)", tr: { en: "Catch them with warmth, not guilt.", "pt-BR": "Capte-os com calor, não com culpa." }, ear: { en: "<b>“spér a LÍ-tâl”</b>", "pt-BR": "<b>“spér a LÍ-tâl”</b>" }, audioPrompt: "Street ambience: rumbling Tube exit, footsteps, a busker far off. A commuter hurries past.", basic: "Spare a little for the food bank?", fluent: "Morning! Could you spare a little for the local food bank? Every bit helps." } ] },
  { sequence: 280, blockId: 12, indexInBlock: 5, phase: 2, subBlock: "12.1", threshold: 80,
    sceneTitle: { en: "“We Could Use Someone Like You”", "pt-BR": "“Precisamos de Alguém Como Você”" },
    contextDescription: { en: "End of the shift, exhausted and warmed through. The coordinator pulls you aside: they need a reliable hand to help run things. The city is asking you to step up.", "pt-BR": "Fim do turno, exausto e aquecido por dentro. A coordenadora te chama de lado: precisam de uma pessoa confiável para ajudar a tocar as coisas. A cidade está te pedindo para assumir." },
    objective: { en: "Accept more responsibility graciously.", "pt-BR": "Aceitar mais responsabilidade com elegância." },
    environment: { mood: "pleased", baseNoise: 26 },
    npc: { name: { en: "Volunteer Coordinator", "pt-BR": "Coordenadora de Voluntários" }, initials: "VC" },
    drills: [{ word: "I'd be honoured", say: "aid bi Ó-nârd", note: { en: "= eu ficaria honrado. (o ‘h’ é mudo)", "pt-BR": "= eu ficaria honrado. (o ‘h’ é mudo)" } }],
    dialogueSteps: [ { text: "You've got a good way with people. Fancy taking on a bit more?", tr: { en: "She offers you a bigger role.", "pt-BR": "Ela te oferece um papel maior." }, ear: { en: "<b>“Ó-nârd”</b> (h mudo)", "pt-BR": "<b>“Ó-nârd”</b> (h mudo)" }, audioPrompt: "Coordinator, sincere, packing up the hall: “You've got a good way with people. Fancy taking on a bit more?”", basic: "I'd be honoured. Count me in.", fluent: "I'd be honoured, honestly — count me in for whatever you need." } ] },

  /* 12.2 — BUILDING SOMETHING */
  { sequence: 281, blockId: 12, indexInBlock: 6, phase: 2, subBlock: "12.2", threshold: 80,
    sceneTitle: { en: "Pitching the Street Fair", "pt-BR": "Propondo a Feira de Rua" },
    contextDescription: { en: "At the residents' association meeting, you stand up and pitch a community street fair to bring a fraying neighbourhood back together. Folded arms and sceptical faces await.", "pt-BR": "Na reunião da associação de moradores, você se levanta e propõe uma feira de rua comunitária para reunir um bairro que está se desfazendo. Braços cruzados e caras céticas te aguardam." },
    objective: { en: "Pitch an idea persuasively to a sceptical room.", "pt-BR": "Defender uma ideia de forma persuasiva para uma plateia cética." },
    environment: { mood: "neutral", baseNoise: 36 },
    npc: { name: { en: "Association Chair", "pt-BR": "Presidente da Associação" }, initials: "AC" },
    drills: [{ word: "bring everyone together", say: "bring ÉV-ri-uân tu-GÉ-dâr", note: { en: "= reunir todo mundo.", "pt-BR": "= reunir todo mundo." } }, { word: "hear me out", say: "RÍR mi áut", note: { en: "= me deixem terminar / me escutem.", "pt-BR": "= me deixem terminar / me escutem." } }],
    dialogueSteps: [ { text: "A street fair? We tried that years ago. Waste of time.", tr: { en: "They're sceptical — win them over.", "pt-BR": "Estão céticos — conquiste-os." }, ear: { en: "<b>“RÍR mi áut”</b>", "pt-BR": "<b>“RÍR mi áut”</b>" }, audioPrompt: "Association chair, arms crossed, doubtful: “A street fair? We tried that years ago. Waste of time.”", basic: "Hear me out — it'll bring everyone together.", fluent: "Just hear me out — done right, it'll bring the whole street together again." } ] },
  { sequence: 282, blockId: 12, indexInBlock: 7, phase: 2, subBlock: "12.2", threshold: 80,
    sceneTitle: { en: "The Council Permit", "pt-BR": "A Licença da Prefeitura" },
    contextDescription: { en: "A grey council office. To close the road for the fair you must navigate a bored officer, road-closure forms, and public-liability insurance jargon — without losing patience.", "pt-BR": "Um repartição cinzenta da prefeitura. Para fechar a rua para a feira você precisa lidar com um funcionário entediado, formulários de interdição e o jargão de seguro de responsabilidade civil — sem perder a paciência." },
    objective: { en: "Request a road-closure permit through bureaucracy.", "pt-BR": "Solicitar licença de interdição de rua na burocracia." },
    environment: { mood: "neutral", baseNoise: 30 },
    npc: { name: { en: "Council Officer", "pt-BR": "Funcionário da Prefeitura" }, initials: "CO" },
    drills: [{ word: "a road-closure permit", say: "a RÔUD-clôu-jâr PÂR-mit", note: { en: "= uma licença de interdição de rua.", "pt-BR": "= uma licença de interdição de rua." } }],
    dialogueSteps: [ { text: "You'll need public liability cover before I can even look at this.", tr: { en: "Bureaucracy — stay patient.", "pt-BR": "Burocracia — mantenha a paciência." }, ear: { en: "<b>“PÂR-mit”</b>", "pt-BR": "<b>“PÂR-mit”</b>" }, audioPrompt: "Council officer, flat and bureaucratic behind glass: “You'll need public liability cover before I can even look at this.”", basic: "Understood. How do I arrange that?", fluent: "Right, public liability — how do I sort that out, and what else do you need?" } ] },
  { sequence: 283, blockId: 12, indexInBlock: 8, phase: 3, subBlock: "12.2", threshold: 80,
    sceneTitle: { en: "Rallying the Neighbours", "pt-BR": "Mobilizando os Vizinhos" },
    contextDescription: { en: "Door to door on your street, you must recruit help and delegate tasks — gazebos, a bake sale, a sound system — turning a vague idea into a roster of real jobs people will own.", "pt-BR": "De porta em porta na sua rua, você precisa recrutar ajuda e delegar tarefas — tendas, uma feira de bolos, um som — transformando uma ideia vaga numa lista de tarefas reais que as pessoas vão abraçar." },
    objective: { en: "Delegate tasks and rally volunteers door to door.", "pt-BR": "Delegar tarefas e mobilizar voluntários de porta em porta." },
    environment: { mood: "pleased", baseNoise: 44 },
    npc: { name: { en: "Neighbour", "pt-BR": "Vizinho(a)" }, initials: "Ne" },
    drills: [{ word: "could you take charge of", say: "cud iú têik TCHÁRDJ âv", note: { en: "= você poderia ficar responsável por…", "pt-BR": "= você poderia ficar responsável por…" } }],
    dialogueSteps: [ { text: "Sounds great, but what would you actually need from me?", tr: { en: "Give them a clear job.", "pt-BR": "Dê a eles uma tarefa clara." }, ear: { en: "<b>“têik TCHÁRDJ”</b>", "pt-BR": "<b>“têik TCHÁRDJ”</b>" }, audioPrompt: "Neighbour, friendly on the doorstep, kids shouting behind: “Sounds great, but what would you actually need from me?”", basic: "Could you take charge of the bake sale?", fluent: "Honestly? Could you take charge of the bake sale — you'd be brilliant at it." } ] },
  { sequence: 284, blockId: 12, indexInBlock: 9, phase: 3, subBlock: "12.2", threshold: 80,
    sceneTitle: { en: "When It Starts to Rain", "pt-BR": "Quando Começa a Chover" },
    contextDescription: { en: "Fair day — and of course, this being London, the heavens open at noon. Stalls scramble for cover. As organiser, you must keep spirits up and improvise on the spot.", "pt-BR": "Dia da feira — e claro, como é Londres, o céu desaba ao meio-dia. As barracas correm para se abrigar. Como organizador, você precisa manter o ânimo e improvisar na hora." },
    objective: { en: "Keep morale up and improvise in a crisis.", "pt-BR": "Manter a moral e improvisar numa crise." },
    culturalNote: { en: "Brits bond over weather disasters. ‘Typical British summer!’ said with a grin turns a soaking into a shared joke.", "pt-BR": "Britânicos se unem em desastres climáticos. ‘Típico verão britânico!’ dito com um sorriso transforma um banho de chuva numa piada coletiva." },
    environment: { mood: "neutral", baseNoise: 58, rain: true },
    npc: { name: { en: "Stallholder", "pt-BR": "Barraqueiro(a)" }, initials: "St" },
    drills: [{ word: "we'll make the best of it", say: "uíl mêik dâ BÉST âv it", note: { en: "= a gente dá um jeito / tira o melhor disso.", "pt-BR": "= a gente dá um jeito / tira o melhor disso." } }],
    dialogueSteps: [ { text: "It's chucking it down! Should we just call it off?", tr: { en: "Don't quit — improvise.", "pt-BR": "Não desista — improvise." }, ear: { en: "<b>“tchâ-kin it DÁUN”</b> = chovendo muito", "pt-BR": "<b>“tchâ-kin it DÁUN”</b> = chovendo muito" }, audioPrompt: "Stallholder, panicking under hammering rain on a gazebo: “It's chucking it down! Should we just call it off?”", basic: "No way — we'll make the best of it!", fluent: "Not a chance — get under the gazebos, we'll make the best of it! Typical British summer, eh?" } ] },
  { sequence: 285, blockId: 12, indexInBlock: 10, phase: 3, subBlock: "12.2", threshold: 80,
    sceneTitle: { en: "“You Did This”", "pt-BR": "“Você Fez Isso Acontecer”" },
    contextDescription: { en: "Sun back out, the street alive with music, kids, and the smell of jerk chicken and samosas. An elderly neighbour who never speaks to anyone takes your hand, tears in her eyes.", "pt-BR": "Sol de volta, a rua viva com música, crianças e cheiro de frango jerk e samosas. Uma vizinha idosa que nunca fala com ninguém segura sua mão, com lágrimas nos olhos." },
    objective: { en: "Receive heartfelt thanks with humility.", "pt-BR": "Receber um agradecimento sincero com humildade." },
    environment: { mood: "pleased", baseNoise: 56 },
    npc: { name: { en: "Elderly Neighbour", "pt-BR": "Vizinha Idosa" }, initials: "EN" },
    drills: [{ word: "it was all of us", say: "it uâz ÓL âv âs", note: { en: "= foi todo mundo / fomos todos nós.", "pt-BR": "= foi todo mundo / fomos todos nós." } }],
    dialogueSteps: [ { text: "I haven't seen this street smile in twenty years. You did this.", tr: { en: "Share the credit.", "pt-BR": "Divida o mérito." }, ear: { en: "<b>“ÓL âv âs”</b>", "pt-BR": "<b>“ÓL âv âs”</b>" }, audioPrompt: "Elderly neighbour, voice trembling amid the festivities: “I haven't seen this street smile in twenty years. You did this.”", basic: "It wasn't just me — it was all of us.", fluent: "That wasn't me — it was all of us. This is your street too." } ] },

  /* 12.3 — A CHANGING MANOR */
  { sequence: 286, blockId: 12, indexInBlock: 11, phase: 2, subBlock: "12.3", threshold: 80,
    sceneTitle: { en: "The Corner Shop Closes", "pt-BR": "A Lojinha da Esquina Fecha" },
    contextDescription: { en: "Mr Patel, who's run the corner shop for 30 years and knew your order before you did, is retiring. The shutters come down for good. You go in to say a proper goodbye.", "pt-BR": "O Sr. Patel, que tocou a lojinha da esquina por 30 anos e sabia seu pedido antes de você, vai se aposentar. As grades descem de vez. Você entra para se despedir de verdade." },
    objective: { en: "Say a meaningful goodbye to a local fixture.", "pt-BR": "Despedir-se de forma significativa de uma figura do bairro." },
    environment: { mood: "pleased", baseNoise: 24 },
    npc: { name: { en: "Mr Patel", "pt-BR": "Sr. Patel" }, initials: "MP" },
    drills: [{ word: "it won't be the same", say: "it uôunt bi dâ SÊIM", note: { en: "= não vai ser a mesma coisa.", "pt-BR": "= não vai ser a mesma coisa." } }, { word: "enjoy your retirement", say: "in-DJÓI iór ri-TÁIA-mânt", note: { en: "= aproveite a aposentadoria.", "pt-BR": "= aproveite a aposentadoria." } }],
    dialogueSteps: [ { text: "Last day, my friend. You were one of the good ones, you know.", tr: { en: "He's closing for good.", "pt-BR": "Ele está fechando de vez." }, ear: { en: "<b>“dâ SÊIM”</b>", "pt-BR": "<b>“dâ SÊIM”</b>" }, audioPrompt: "Mr Patel, emotional behind the till on his last day: “Last day, my friend. You were one of the good ones, you know.”", basic: "It won't be the same. Enjoy your retirement.", fluent: "This place won't be the same without you — enjoy your retirement, you've earned it." } ] },
  { sequence: 287, blockId: 12, indexInBlock: 12, phase: 3, subBlock: "12.3", threshold: 80,
    sceneTitle: { en: "Gentrification Talk", "pt-BR": "Conversa Sobre Gentrificação" },
    contextDescription: { en: "Where the launderette was, a £6-flat-white café now glows. On a bench, an old-timer who's lived here all his life grumbles about the changes. You navigate a loaded conversation.", "pt-BR": "Onde era a lavanderia, agora brilha um café de coado a £6. Num banco, um velho morador que viveu aqui a vida toda resmunga das mudanças. Você navega uma conversa delicada." },
    objective: { en: "Discuss neighbourhood change with nuance.", "pt-BR": "Conversar sobre a mudança do bairro com nuance." },
    culturalNote: { en: "‘Gentrification’ is a charged word in London — about rising rents pushing out long-time, often working-class and immigrant, residents.", "pt-BR": "‘Gentrificação’ é uma palavra carregada em Londres — sobre aluguéis em alta expulsando moradores antigos, muitas vezes da classe trabalhadora e imigrantes." },
    environment: { mood: "neutral", baseNoise: 46 },
    npc: { name: { en: "Old-Timer", "pt-BR": "Morador Antigo" }, initials: "OT" },
    drills: [{ word: "priced out", say: "práist ÁUT", note: { en: "= expulso pelos preços altos.", "pt-BR": "= expulso pelos preços altos." } }],
    dialogueSteps: [ { text: "Six quid for a coffee. My kids can't afford to live here anymore.", tr: { en: "He mourns the change.", "pt-BR": "Ele lamenta a mudança." }, ear: { en: "<b>“práist áut”</b>", "pt-BR": "<b>“práist áut”</b>" }, audioPrompt: "Old-timer, bitter on a bench by traffic noise: “Six quid for a coffee. My kids can't afford to live here anymore.”", basic: "It's hard. So many get priced out.", fluent: "I hear you — too many families are getting priced out of the place they built." } ] },
  { sequence: 288, blockId: 12, indexInBlock: 13, phase: 3, subBlock: "12.3", threshold: 80,
    sceneTitle: { en: "Welcoming the New Family", "pt-BR": "Recebendo a Família Nova" },
    contextDescription: { en: "A newly-arrived immigrant family is moving in two doors down, overwhelmed and wide-eyed — exactly as you once were. Full circle. You knock with a small welcome gift.", "pt-BR": "Uma família imigrante recém-chegada está se mudando dois portões adiante, perdida e de olhos arregalados — exatamente como você um dia foi. O ciclo se fecha. Você bate à porta com um pequeno presente de boas-vindas." },
    objective: { en: "Welcome a newcomer the way you once needed.", "pt-BR": "Acolher um recém-chegado como você um dia precisou." },
    environment: { mood: "pleased", baseNoise: 34 },
    npc: { name: { en: "New Neighbour", "pt-BR": "Vizinho Novo" }, initials: "NN" },
    drills: [{ word: "welcome to the neighbourhood", say: "UÉL-câm tu dâ NÊI-bâr-rud", note: { en: "= bem-vindo ao bairro.", "pt-BR": "= bem-vindo ao bairro." } }, { word: "if you ever need anything", say: "if iú ÉV-âr níd É-ni-thing", note: { en: "= se precisar de qualquer coisa.", "pt-BR": "= se precisar de qualquer coisa." } }],
    dialogueSteps: [ { text: "Oh — hello. Sorry, my English is... still not very good.", tr: { en: "They're nervous, like you were.", "pt-BR": "Estão nervosos, como você esteve." }, ear: { en: "<b>“UÉL-câm”</b>", "pt-BR": "<b>“UÉL-câm”</b>" }, audioPrompt: "New neighbour, anxious and apologetic amid moving boxes: “Oh — hello. Sorry, my English is... still not very good.”", basic: "Welcome! If you ever need anything, just knock.", fluent: "Welcome to the neighbourhood — and don't worry about the English, it comes. If you ever need anything, just knock." } ] },
  { sequence: 289, blockId: 12, indexInBlock: 14, phase: 2, subBlock: "12.3", threshold: 80,
    sceneTitle: { en: "The Residents' Dispute", "pt-BR": "A Disputa dos Moradores" },
    contextDescription: { en: "The association meeting turns heated: a new block of flats wants permission to build, splitting the street into furious camps. As a trusted voice, you must speak without inflaming it.", "pt-BR": "A reunião da associação esquenta: um novo prédio quer permissão para construir, dividindo a rua em facções furiosas. Como uma voz respeitada, você precisa falar sem jogar mais lenha na fogueira." },
    objective: { en: "De-escalate a heated community dispute.", "pt-BR": "Acalmar uma disputa comunitária acalorada." },
    environment: { mood: "hostile", baseNoise: 50 },
    npc: { name: { en: "Angry Resident", "pt-BR": "Morador Irritado" }, initials: "AR" },
    drills: [{ word: "let's hear both sides", say: "léts rír bôuth SÁIDZ", note: { en: "= vamos ouvir os dois lados.", "pt-BR": "= vamos ouvir os dois lados." } }],
    dialogueSteps: [ { text: "They'll ruin this street! Anyone who disagrees is a traitor!", tr: { en: "Cool the room down.", "pt-BR": "Esfrie os ânimos." }, ear: { en: "<b>“bôuth SÁIDZ”</b>", "pt-BR": "<b>“bôuth SÁIDZ”</b>" }, audioPrompt: "Angry resident, shouting over a chaotic meeting: “They'll ruin this street! Anyone who disagrees is a traitor!”", basic: "Please — let's hear both sides calmly.", fluent: "I get the anger, truly — but let's hear both sides calmly, or we'll lose each other over this." } ] },
  { sequence: 290, blockId: 12, indexInBlock: 15, phase: 3, subBlock: "12.3", threshold: 80,
    sceneTitle: { en: "Change and Continuity", "pt-BR": "Mudança e Permanência" },
    contextDescription: { en: "Walking your manor at dusk, you reflect with a long-time friend: the city always changes, and the trick isn't to stop it but to keep its soul alive through it. You put that into words.", "pt-BR": "Caminhando pelo seu pedaço da cidade ao entardecer, você reflete com um amigo de longa data: a cidade sempre muda, e o segredo não é impedir isso, mas manter a alma dela viva através disso. Você coloca isso em palavras." },
    objective: { en: "Express acceptance of change while honouring roots.", "pt-BR": "Expressar aceitação da mudança honrando as raízes." },
    environment: { mood: "pleased", baseNoise: 38 },
    npc: { name: { en: "Old Friend", "pt-BR": "Amigo Antigo" }, initials: "OF" },
    drills: [{ word: "keep its soul", say: "kíp its SÔUL", note: { en: "= manter a alma dela.", "pt-BR": "= manter a alma dela." } }],
    dialogueSteps: [ { text: "Doesn't it make you sad, how much it's all changed?", tr: { en: "Offer a wiser view.", "pt-BR": "Ofereça uma visão mais sábia." }, ear: { en: "<b>“kíp its SÔUL”</b>", "pt-BR": "<b>“kíp its SÔUL”</b>" }, audioPrompt: "Old friend, wistful, walking at dusk with distant traffic: “Doesn't it make you sad, how much it's all changed?”", basic: "Cities change. We keep its soul.", fluent: "A little — but cities always change. Our job is to keep its soul alive through it." } ] },

  /* 12.4 — THE INNER CIRCLE */
  { sequence: 291, blockId: 12, indexInBlock: 16, phase: 2, subBlock: "12.4", threshold: 80,
    sceneTitle: { en: "A Friend in Crisis", "pt-BR": "Um Amigo em Crise" },
    contextDescription: { en: "Your closest London friend turns up at midnight, falling apart — their marriage is ending. They don't need advice, just you. You must hold space and comfort, in English, under real weight.", "pt-BR": "Seu amigo mais próximo de Londres aparece à meia-noite, desmoronando — o casamento dele está acabando. Ele não precisa de conselho, só de você. Você precisa acolher e confortar, em inglês, sob um peso real." },
    objective: { en: "Comfort a friend in genuine crisis.", "pt-BR": "Confortar um amigo numa crise real." },
    environment: { mood: "neutral", baseNoise: 20 },
    npc: { name: { en: "Best Friend", "pt-BR": "Melhor Amigo" }, initials: "BF" },
    drills: [{ word: "I'm here for you", say: "aim RÍR fôr iú", note: { en: "= estou aqui por você.", "pt-BR": "= estou aqui por você." } }, { word: "take your time", say: "têik iór TÁIM", note: { en: "= sem pressa.", "pt-BR": "= sem pressa." } }],
    dialogueSteps: [ { text: "I'm sorry to come so late. I just... I didn't know where else to go.", tr: { en: "Just be present for them.", "pt-BR": "Apenas esteja presente para ele." }, ear: { en: "<b>“RÍR fôr iú”</b>", "pt-BR": "<b>“RÍR fôr iú”</b>" }, audioPrompt: "Best friend, voice cracking at your door at midnight: “I'm sorry to come so late. I just... I didn't know where else to go.”", basic: "Come in. I'm here for you.", fluent: "Hey — come in, sit down. You don't have to explain anything. I'm here for you." } ] },
  { sequence: 292, blockId: 12, indexInBlock: 17, phase: 2, subBlock: "12.4", threshold: 80,
    sceneTitle: { en: "The Falling-Out", "pt-BR": "O Desentendimento" },
    contextDescription: { en: "A stupid argument has festered into weeks of silence with a good friend. You swallow your pride and reach out first — the harder, braver thing — to mend it honestly.", "pt-BR": "Uma briga boba apodreceu em semanas de silêncio com um bom amigo. Você engole o orgulho e dá o primeiro passo — o mais difícil e corajoso — para consertar com honestidade." },
    objective: { en: "Apologise first and repair a friendship.", "pt-BR": "Pedir desculpas primeiro e reparar uma amizade." },
    environment: { mood: "hostile", baseNoise: 24 },
    npc: { name: { en: "Estranged Friend", "pt-BR": "Amigo Afastado" }, initials: "EF" },
    drills: [{ word: "I've missed you", say: "aiv MÍST iú", note: { en: "= senti sua falta.", "pt-BR": "= senti sua falta." } }, { word: "I was out of line", say: "ai uâz áut âv LÁIN", note: { en: "= eu passei do ponto / errei.", "pt-BR": "= eu passei do ponto / errei." } }],
    dialogueSteps: [ { text: "I wasn't sure you'd ever call. What do you want?", tr: { en: "They're guarded — be sincere.", "pt-BR": "Estão na defensiva — seja sincero." }, ear: { en: "<b>“áut âv LÁIN”</b>", "pt-BR": "<b>“áut âv LÁIN”</b>" }, audioPrompt: "Estranged friend, cold and cautious on the phone: “I wasn't sure you'd ever call. What do you want?”", basic: "I was out of line. I've missed you.", fluent: "I was out of line, and I've missed you — can we please talk this through?" } ] },
  { sequence: 293, blockId: 12, indexInBlock: 18, phase: 2, subBlock: "12.4", threshold: 80,
    sceneTitle: { en: "The Wedding Toast", "pt-BR": "O Brinde de Casamento" },
    contextDescription: { en: "A friend has asked you — the foreigner who once couldn't order a coffee — to give a toast at their wedding. A room full of guests, glasses raised, waiting on your every English word.", "pt-BR": "Um amigo pediu a você — o estrangeiro que um dia não conseguia pedir um café — para fazer um brinde no casamento dele. Uma sala cheia de convidados, taças erguidas, na expectativa de cada palavra sua em inglês." },
    objective: { en: "Deliver a warm, confident wedding toast.", "pt-BR": "Fazer um brinde de casamento caloroso e confiante." },
    environment: { mood: "pleased", baseNoise: 42 },
    npc: { name: { en: "Wedding Guests", "pt-BR": "Convidados" }, initials: "WG" },
    drills: [{ word: "raise your glasses", say: "rêiz iór GLÁ-siz", note: { en: "= ergam suas taças.", "pt-BR": "= ergam suas taças." } }, { word: "to the happy couple", say: "tu dâ RÉ-pi CÂ-pâl", note: { en: "= ao casal feliz.", "pt-BR": "= ao casal feliz." } }],
    dialogueSteps: [ { text: "(the room hushes, all eyes turn to you, glass in hand)", tr: { en: "Own the moment.", "pt-BR": "Domine o momento." }, ear: { en: "<b>“RÉ-pi CÂ-pâl”</b>", "pt-BR": "<b>“RÉ-pi CÂ-pâl”</b>" }, audioPrompt: "Wedding reception ambience: cutlery, soft chatter dying down, a chair scrapes as the room goes quiet for you.", basic: "Please raise your glasses to the happy couple!", fluent: "When I first arrived, I could barely say hello — and now I get to say this: please, raise your glasses to the happy couple!" } ] },
  { sequence: 294, blockId: 12, indexInBlock: 19, phase: 2, subBlock: "12.4", threshold: 80,
    sceneTitle: { en: "An Act of Deep Trust", "pt-BR": "Um Ato de Profunda Confiança" },
    contextDescription: { en: "Over dinner, a friend asks you to be their child's godparent — and their emergency contact. In a city where you arrived alone, someone is now naming you as family. You answer from the heart.", "pt-BR": "Durante o jantar, um amigo te pede para ser padrinho do filho dele — e seu contato de emergência. Numa cidade onde você chegou sozinho, alguém agora te nomeia como família. Você responde do coração." },
    objective: { en: "Accept a profound role with sincerity.", "pt-BR": "Aceitar um papel profundo com sinceridade." },
    environment: { mood: "pleased", baseNoise: 22 },
    npc: { name: { en: "Friend", "pt-BR": "Amigo(a)" }, initials: "FR" },
    drills: [{ word: "I'd be there in a heartbeat", say: "aid bi dér in a RÁRT-bit", note: { en: "= eu estaria lá num piscar de olhos.", "pt-BR": "= eu estaria lá num piscar de olhos." } }],
    dialogueSteps: [ { text: "There's no one we trust more. Would you be his godparent?", tr: { en: "They're making you family.", "pt-BR": "Estão te tornando família." }, ear: { en: "<b>“RÁRT-bit”</b>", "pt-BR": "<b>“RÁRT-bit”</b>" }, audioPrompt: "Friend, emotional over a quiet dinner: “There's no one we trust more. Would you be his godparent?”", basic: "Yes — I'd be there in a heartbeat.", fluent: "I'd be honoured — I'd be there for him in a heartbeat, always." } ] },
  { sequence: 295, blockId: 12, indexInBlock: 20, phase: 3, subBlock: "12.4", threshold: 80,
    sceneTitle: { en: "The 2am Conversation", "pt-BR": "A Conversa das 2h" },
    contextDescription: { en: "On a rooftop after a party, just you and a true friend and the city lights. The kind of raw, honest, 2am conversation about life, fear, and meaning that only happens between real friends.", "pt-BR": "Num terraço depois de uma festa, só você e um amigo de verdade e as luzes da cidade. O tipo de conversa crua, honesta, das 2h sobre vida, medo e sentido que só acontece entre amigos de verdade." },
    objective: { en: "Have an honest, vulnerable late-night talk.", "pt-BR": "Ter uma conversa noturna honesta e vulnerável." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "True Friend", "pt-BR": "Amigo de Verdade" }, initials: "TF" },
    drills: [{ word: "do you ever wonder if", say: "du iú ÉV-âr UÂN-dâr if", note: { en: "= você já se pergunta se…", "pt-BR": "= você já se pergunta se…" } }],
    dialogueSteps: [ { text: "Be honest — are you actually happy? Like, really?", tr: { en: "Answer with full honesty.", "pt-BR": "Responda com total honestidade." }, ear: { en: "<b>“É-ktchu-â-li RÉ-pi”</b>", "pt-BR": "<b>“É-ktchu-â-li RÉ-pi”</b>" }, audioPrompt: "True friend, quiet on a rooftop, distant city hum: “Be honest — are you actually happy? Like, really?”", basic: "I think I finally am.", fluent: "You know what? I think, for the first time, I actually am." } ] },

  /* 12.5 — PILLAR OF THE MANOR (milestone 300) */
  { sequence: 296, blockId: 12, indexInBlock: 21, phase: 2, subBlock: "12.5", threshold: 80,
    sceneTitle: { en: "Asked to Lead", "pt-BR": "Convidado a Liderar" },
    contextDescription: { en: "The residents' association wants you as their new chair — the foreigner, now the trusted heart of the street. You must accept the responsibility with grace and a clear vision.", "pt-BR": "A associação de moradores quer você como novo presidente — o estrangeiro, agora o coração de confiança da rua. Você precisa aceitar a responsabilidade com elegância e uma visão clara." },
    objective: { en: "Accept a leadership role with a clear vision.", "pt-BR": "Aceitar um papel de liderança com uma visão clara." },
    environment: { mood: "pleased", baseNoise: 32 },
    npc: { name: { en: "Outgoing Chair", "pt-BR": "Presidente que Sai" }, initials: "OC" },
    drills: [{ word: "I won't let you down", say: "ai uôunt lét iú DÁUN", note: { en: "= não vou decepcionar vocês.", "pt-BR": "= não vou decepcionar vocês." } }],
    dialogueSteps: [ { text: "It was unanimous. The street wants you as chair. Will you?", tr: { en: "They elect you to lead.", "pt-BR": "Eles te elegem para liderar." }, ear: { en: "<b>“lét iú DÁUN”</b>", "pt-BR": "<b>“lét iú DÁUN”</b>" }, audioPrompt: "Outgoing chair, proud, handing over a folder: “It was unanimous. The street wants you as chair. Will you?”", basic: "I will. I won't let you down.", fluent: "I will — and I promise you, I won't let this street down." } ] },
  { sequence: 297, blockId: 12, indexInBlock: 22, phase: 2, subBlock: "12.5", threshold: 80,
    sceneTitle: { en: "Mediating the Feud", "pt-BR": "Mediando a Rixa" },
    contextDescription: { en: "Two neighbours have feuded for years over a boundary fence. As the trusted chair, you sit them both down to broker a peace neither could reach alone — calmly, fairly, firmly.", "pt-BR": "Dois vizinhos brigam há anos por causa de uma cerca divisória. Como presidente de confiança, você senta os dois para costurar uma paz que nenhum alcançaria sozinho — com calma, justiça e firmeza." },
    objective: { en: "Mediate fairly between two angry parties.", "pt-BR": "Mediar com justiça entre duas partes irritadas." },
    environment: { mood: "hostile", baseNoise: 28 },
    npc: { name: { en: "Feuding Neighbour", "pt-BR": "Vizinho em Rixa" }, initials: "FN" },
    drills: [{ word: "let's find common ground", say: "léts fáind CÓ-mân GRÁUND", note: { en: "= vamos achar um ponto em comum.", "pt-BR": "= vamos achar um ponto em comum." } }],
    dialogueSteps: [ { text: "I'm not apologising to him! He started it years ago!", tr: { en: "Guide them to a truce.", "pt-BR": "Guie-os a uma trégua." }, ear: { en: "<b>“CÓ-mân GRÁUND”</b>", "pt-BR": "<b>“CÓ-mân GRÁUND”</b>" }, audioPrompt: "Feuding neighbour, arms folded, glaring across the table: “I'm not apologising to him! He started it years ago!”", basic: "No blame today. Let's find common ground.", fluent: "Nobody's assigning blame today — let's just find some common ground, for both your sakes." } ] },
  { sequence: 298, blockId: 12, indexInBlock: 23, phase: 2, subBlock: "12.5", threshold: 80,
    sceneTitle: { en: "The Local Paper", "pt-BR": "O Jornal Local" },
    contextDescription: { en: "A reporter from the local paper wants to interview you for a feature on the community revival — ‘the immigrant who brought the street back to life’. You speak about it humbly, on the record.", "pt-BR": "Um repórter do jornal local quer te entrevistar para uma matéria sobre a renovação da comunidade — ‘o imigrante que trouxe a rua de volta à vida’. Você fala sobre isso com humildade, e fica registrado." },
    objective: { en: "Give a humble, articulate interview.", "pt-BR": "Dar uma entrevista humilde e articulada." },
    environment: { mood: "pleased", baseNoise: 30 },
    npc: { name: { en: "Local Reporter", "pt-BR": "Repórter Local" }, initials: "LR" },
    drills: [{ word: "it takes a village", say: "it têiks a VÍ-lidj", note: { en: "= é preciso uma aldeia/comunidade inteira.", "pt-BR": "= é preciso uma aldeia/comunidade inteira." } }],
    dialogueSteps: [ { text: "So how does it feel to be the person who turned this street around?", tr: { en: "Deflect the praise gracefully.", "pt-BR": "Desvie o elogio com elegância." }, ear: { en: "<b>“VÍ-lidj”</b>", "pt-BR": "<b>“VÍ-lidj”</b>" }, audioPrompt: "Local reporter, friendly, recorder running: “So how does it feel to be the person who turned this street around?”", basic: "It wasn't me alone. It takes a village.", fluent: "Honestly, I just lit a spark — the street did the rest. It takes a village." } ] },
  { sequence: 299, blockId: 12, indexInBlock: 24, phase: 3, subBlock: "12.5", threshold: 80,
    sceneTitle: { en: "The Speech of Thanks", "pt-BR": "O Discurso de Agradecimento" },
    contextDescription: { en: "At a community celebration thrown partly in your honour, you're handed the microphone. You must thank the city and the people who turned a stranger into one of their own — in fluent, heartfelt English.", "pt-BR": "Numa celebração comunitária organizada em parte em sua homenagem, te passam o microfone. Você precisa agradecer à cidade e às pessoas que transformaram um estranho em um dos seus — num inglês fluente e sentido." },
    objective: { en: "Give a heartfelt public thank-you speech.", "pt-BR": "Fazer um discurso público de agradecimento sentido." },
    environment: { mood: "pleased", baseNoise: 48 },
    npc: { name: { en: "The Community", "pt-BR": "A Comunidade" }, initials: "TC" },
    drills: [{ word: "you made me one of your own", say: "iú mêid mi uân âv iór ÔUN", note: { en: "= vocês me fizeram um dos seus.", "pt-BR": "= vocês me fizeram um dos seus." } }],
    dialogueSteps: [ { text: "(the crowd quietens, faces beaming, waiting for your words)", tr: { en: "Speak from the heart.", "pt-BR": "Fale do coração." }, ear: { en: "<b>“uân âv iór ÔUN”</b>", "pt-BR": "<b>“uân âv iór ÔUN”</b>" }, audioPrompt: "A warm crowd in a community hall hushes, the mic crackles, someone whoops your name.", basic: "Thank you. You made me one of your own.", fluent: "I came here a stranger who couldn't speak a word — and you made me one of your own. Thank you, from the bottom of my heart." } ] },
  { sequence: 300, blockId: 12, indexInBlock: 25, phase: 3, subBlock: "12.5", threshold: 75,
    kind: "bonus", triggerSelfieShare: true,
    selfieOverlay: { eyebrow: "Pillar of the Community", tagline: "Pillar of the Community — They Call This Manor Mine", shareText: "I arrived a stranger who couldn't order a coffee. Today my neighbours elected me, threw a street party, and called me one of their own. From outsider to pillar of the community. 🇬🇧🤝 #LinguoBound" },
    sceneTitle: { en: "Bonus — One of Our Own", "pt-BR": "Bônus — Um dos Nossos" },
    contextDescription: { en: "Golden bunting strung between lampposts, the whole street out in the sun, a banner with your name on it. Children you've watched grow, neighbours who were once strangers, an old-timer wiping his eyes. The city that once felt like a wall is now, unmistakably, home — and it's claiming you as its own. Step up beside them. Take the picture.", "pt-BR": "Bandeirinhas douradas penduradas entre os postes, a rua inteira ao sol, uma faixa com o seu nome. Crianças que você viu crescer, vizinhos que um dia foram estranhos, um morador antigo enxugando os olhos. A cidade que um dia parecia uma parede agora é, inconfundivelmente, um lar — e está te reivindicando como um dos seus. Suba ao lado deles. Tire a foto." },
    objective: { en: "Celebrate becoming a true pillar of the community.", "pt-BR": "Celebrar tornar-se um verdadeiro pilar da comunidade." },
    environment: { mood: "pleased", baseNoise: 54 },
    npc: { name: { en: "The Whole Street", "pt-BR": "A Rua Inteira" }, initials: "WS" },
    drills: [{ word: "this is home now", say: "dis iz RÔUM náu", note: { en: "The truth of the journey so far.", "pt-BR": "A verdade da jornada até aqui." }, }],
    dialogueSteps: [
      { text: "Three cheers for the heart of this street! Hip hip—", tr: { en: "They're celebrating you.", "pt-BR": "Eles estão celebrando você." }, ear: { en: "<b>“hip hip hu-RÊI”</b>", "pt-BR": "<b>“hip hip hu-RÊI”</b>" }, audioPrompt: "The whole street cheering in the sun, party music, a child laughing: “Three cheers for the heart of this street! Hip hip—”", basic: "This is home now. Thank you, all of you.", fluent: "I never dreamed I'd belong anywhere like this — this is home now. Thank you, all of you." },
      { text: "You're not a guest here anymore. You're family.", tr: { en: "You belong, completely.", "pt-BR": "Você pertence, completamente." }, ear: { en: "<b>“iór FÉ-mi-li”</b>", "pt-BR": "<b>“iór FÉ-mi-li”</b>" }, audioPrompt: "An old neighbour, arm around you amid the celebration: “You're not a guest here anymore. You're family.”", basic: "Family. Both of my worlds.", fluent: "Family — that means everything. I've got two homes now, and you're one of them." },
    ] },
];

export const BLOCK12_BY_SEQUENCE = BLOCK12_MODULES.reduce((a, m) => { a[m.sequence] = m; return a; }, {});
